### PR TITLE
Fixes missing mag icons for nodular AK

### PR DESCRIPTION
**Pull request by Evie7056**
## About The Pull Request

I feel freaking annoyed when I get empty sprite whenever I craft shotgun mags. Now this dark time has gone.

Fixes this. https://discord.com/channels/255035529085583360/375588651599396866/1123693295030259755
and this https://discord.com/channels/255035529085583360/375588651599396866/1147283593744351324
And this! https://discord.com/channels/255035529085583360/375588651599396866/1119185953618141225

https://discord.com/channels/255035529085583360/375588651599396866/1117616407404884079
And... yeah there were really that many reports.

UPD
Also this expanded quite a bit, so there also new coder sprites for .20 drum and extended mag. .20 Drum is the copy of .30 drum because I have no idea how to make a proper drum. Extended mag sprites are actually made by me, lol

## Why It's Good For The Game

Bugfixes are good.

## Testing

image
image
image

## Changelog
:cl: Evie7056
fix: missing shotgun mag icon.
fix: missing mag sprites on AK-Shotguns.
fix: missing mag sprites on .20 AK
/:cl:

### CODE REVIEW

**Comment by Evie7056** [comment]
Actually... hold on it. I forgot that this bug also includes lack of sprites on AK. Might need to squish one more bug with one slap.

**Comment by Evie7056** [comment]
Nvm, it works now.
image

**Comment by Humonitarian** [comment]
Modular gun's DevDel here, PR approved

**Comment by Humonitarian** [comment]
Actually, hold on. Are those mags not fitting correctly? There seems to be a hole in the AK where the mag should go.

It is possible the mags need to be raised by a pixel.

**Comment by Evie7056** [comment]
> Actually, hold on. Are those mags not fitting correctly? There seems to be a hole in the AK where the mag should go.
> 
> It is possible the mags need to be raised by a pixel.

I'll try to figure out how to do this myself, I don't really wanna open sprite editor

**Comment by Humonitarian** [comment]
> I'll try to figure out how to do this myself, I don't really wanna open sprite editor
> 
> Hope there is a var to shift mags.

You should be able to just select and drag the mag up by a pixel within the Dream Maker DMI editor, same place where you renamed the state.

**Comment by Evie7056** [comment]
fixed. 
screenshorts updated

**Comment by Evie7056** [comment]
missing sprites for .20 are added. screenies updooted

**Review by TheShown911 — APPROVED** [review]

**Pull request merged**
