### PR TITLE
NSA Rewrite (COMPLETE) 

### PR DESCRIPTION
**Pull request by Jackofashepard**
This is the half finished version of the NSA Rewrite, currently i moved almost all NSA code to metabolism.dm and it now adds NSA values paired with id (reagent ID) and metabolism_class (CHEM_INGEST, CHEM_INJECT, ect) combo. The result is NSA stacking for the same chemical over the 3 different holders. Now the reason why this is a draft is because while i have been able to make it add NSA in this way with A LOT of help from ACCount and others it still doesn't remove NSA from the list correctly (namely it still searches for a normal id to remove instead of the new combo). Any help appreciated and have a good Eris weekend!

### CODE REVIEW

**Comment by Jackofashepard** [comment]
I fixed the issue, it now removes NSA as reagents leave their individual holders. This is possible thanks to nestors advice and MANY MANY MANY hours spent figuring out lists

**Comment by ACCount12** [comment]
Can you test if Haloperidol still works? The whole thing is still kinda sketchy, but it does seem to work otherwise.

**Comment by Jackofashepard** [comment]
Yes i'll test it right now

**Comment by Jackofashepard** [comment]
Sedates but doesnt lower NSA, it in fact adds 5 NSA

**Comment by Jackofashepard** [comment]
Well it sounds like nestor wants to rework chem entirely so this NSA rework will need to be reworked again

**Comment by Jackofashepard** [comment]
Okay this sorts it, PR ready

**Pull request merged**
