### PR TITLE
languages tweak

### PR DESCRIPTION
**Pull request by SirRichardFrancis**
## About The Pull Request

Last Shelter disciples speak Latin.
Faction language guaranteed to be known by faction member, at expense of a chance of additionally knowing russian/serbian/whatever.
So it's English common, faction language (Neohongo/Latin/Russian/Jive), maybe random language (when faction language isn't given), language from perks/background and language that player chose on character creation.

## Why It's Good For The Game

Sacrificing extra language to make sure your character speak faction language doesn't feel good.
Very often someone in the faction doesn't speak faction language, that makes communication somewhat annoying.

## Changelog
:cl:
tweak: faction language guaranteed to be known by faction member
tweak: people spawned via Last Shelter speak Latin
/:cl:

### CODE REVIEW

**Comment by Humonitarian** [comment]
It might be a CBT idea, but Last Shelter only knowing Latin?

I disagree with Jive being named a faction language, though. Guild does have use for knowing multiple languages.
Same goes for Inspector and Preacher, they should retain their chances.

If anything, Jive should be guaranteed to Club Manager, not miners and artists.

**Comment by Sparrowbird611** [comment]
I prefer serbian for guildsmen rather than Jive. Idk it just feels more fitting to me. Everything else seems fine to me.

**Comment by FortuneMaster** [comment]
> I prefer serbian for guildsmen rather than Jive. Idk it just feels more fitting to me. Everything else seems fine to me.

serbians hate asters

**Comment by Sparrowbird611** [comment]
> > I prefer serbian for guildsmen rather than Jive. Idk it just feels more fitting to me. Everything else seems fine to me.
> 
> serbians hate asters

All the better to give them the language, so they can mutually insult each other :)

**Comment by SirRichardFrancis** [comment]
> It might be a CBT idea, but Last Shelter only knowing Latin?

Еhey speak Latin in addition to English Common.

> I disagree with Jive being named a faction language, though. Guild does have use for knowing multiple languages.
> Same goes for Inspector and Preacher, they should retain their chances.

Jive assigned to guild because it was already there, guildies had 80% chance of knowing it.
Guild still have a perk that may give extra language, and you always can pick one secondary language. Also there is origin that gives you yet another language.

> If anything, Jive should be guaranteed to Club Manager, not miners and artists.

Maybe. But what guildies get then?

> I prefer serbian for guildsmen rather than Jive. Idk it just feels more fitting to me. Everything else seems fine to me.

Serbian is language of an antagonist faction, half the ship hates them, and other half no more than a raiding target.

> All the better to give them the language, so they can mutually insult each other :)

That doesn't look like a valid argument for me, if you want to discuss their mothers IC - you can pick Serbian as second language no problem.

**Comment by Humonitarian** [comment]
> They speak Latin in addition to English Common.
That's what I propose to be changed, so they only speak Latin, for the authentic shelter experience

**Comment by Sparrowbird611** [comment]
I don't recommend doing the above. Being unable to communicate with most of the playerbase is not a fun experience.

**Comment by SirRichardFrancis** [comment]
> That's what I propose to be changed, so they only speak Latin, for the authentic shelter experience

That's somewhat radical change, since there is no IC way of learning a language.
Imo that bounds Last Shelter disciples to NT and preventing them from communication with most players.
Also having most of your radio feed scrambled is annoying. But if you get approval from a maintainer - no problem.

**Review by Firefox13 — COMMENTED** [review]
I do not like the whole idea of "faction languages" overall because it's just another way to fuck over people eavesdropping on radio channels.
The "factional language" concept should only applied sparingly(technomancers) and unfortunately currently everyone's a damn polyglot.

**Comment by SirRichardFrancis** [comment]
> I do not like the whole idea of "faction languages" overall because it's just another way to fuck over people eavesdropping on radio channels.
> The "factional language" concept should only applied sparingly(technomancers) and unfortunately currently everyone's a damn polyglot.

So are codespeak. Yet languages is a nice thing to have, and anyone can chose a language they want to understand, so if John Contractor pick Neohongo instead of Latin - that's his bad. Adds flavor to the game.
If we have those anyway, might as well get rid of annoying RNG and communication problems it causing.

**Comment by TheShown911** [comment]
You don't choose languages after becoming an antagonist

**Comment by SirRichardFrancis** [comment]
> You don't choose languages after becoming an antagonist

You choose languages on character creation, meaning before you join the round.

**Review by drexample — APPROVED** [review]

**Pull request merged**
