### PR TITLE
Solidification

### PR DESCRIPTION
**Pull request by TGCMbetcher**
## About The Pull Request

Adds the same solidification of plasma to gold and uranium

## Why It's Good For The Game

Allows science, after like 20-30 minutes of work, to get the materials they need

## Changelog
:cl:
add: Added recipes that allow the solidification of gold an uranium
/:cl:

### CODE REVIEW

**Comment by Voldirs** [comment]
Why not adding the same for silver?

**Comment by TGCMbetcher** [comment]
> Why not adding the same for silver?

Because there is no way to get liquid silver in the wild. Its not in circuit boards or anything an autolathes give it to you naturally. This is mostly for botany to make the plant gold/uranium you make have a way to turn into solid matter. If you have liquid silver chances are you were making drinks an used enough of it that you cant resolidify.

**Comment by glaciusinfinity** [comment]
> > Why not adding the same for silver?
> 
> Because there is no way to get liquid silver in the wild. Its not in circuit boards or anything an autolathes give it to you naturally. This is mostly for botany to make the plant gold/uranium you make have a way to turn into solid matter. If you have liquid silver chances are you were making drinks an used enough of it that you cant resolidify.

If nothing else you should add it for consistency's sake, maybe at some later point, a way to get liquid silver will be added and being able to solidify it would be convenient to have

**Comment by TGCMbetcher** [comment]
alright Ill add silver in as well as a carbon iron way of making steel. Frankly frost oil was way more valuable then steel so if thats how they want to do it whatever. Id rather spend paltry amounts at the guild for 480 sheets then spen forever slaving on a chem dispensor

**Pull request closed without merging**
