### PR TITLE
TGUI backend [Ready for check]

### PR DESCRIPTION
**Pull request by LetterN**
## About The Pull Request
Ports the **backend** of the tgui, ~~does not include new uis~~ only includes gps ui

## Changelog
:cl:
add: All of tgui backend
add: Asset cache
add: GPS component & ui
code: prefixes old nanoui procs equally named to tgui ones with `nanoui_`
code: Reverts GC changes, syncs with tg instead.
code: Adds rustg, logging will use rustg now (it's faster and safer)
code: Updates the MC, including stack end detector (infinite loops) and weakrefs (less gc tomfoolery)
code: Updates globals (managed ones)
code: Updates weakref, it's a datum instead of a "blank" type (default is `/atom/movable`, this is **more expensive**)
code: CLIENTS ARE A SUBTYTPE OF DATUM NOW
/:cl:

# NOTICE: BECAUSE OF POPULAR DEMAND, YOU HAVE TO BUILD THE TGUI EVERY TIME YOU CHANGE IT. (SERVER DOES NOT COMPILE IT)

### CODE REVIEW

**Comment by TheObserver-sys** [comment]
Oh god it's happening! It's happening! Fast UI, my beloved

**Review by GrayRachnid — APPROVED** [review]

**Review by TheShown911 — APPROVED** [review]
cover3

**Comment by drexample** [comment]
Remove NodeJS from this

**Comment by LetterN** [comment]
> Remove NodeJS from this

# I cant.

**Comment by Kegdo** [comment]
Why is this still here

**Comment by Arturlang** [comment]
This'd be great to add tguichat with, if it's still happening

**Comment by LetterN** [comment]
splitting this pr again :joy:

**Pull request closed without merging**
