### PR TITLE
[BOUNTY?] Update prosthetic sprites, again

### PR DESCRIPTION
**Pull request by Firefox13**
## About The Pull Request

This PR fixes offsets of the sprites. Also it removes red fleshy mass from limb stumps because they look awful.
~~and four female clothing sprites were fixes~~

## Why It's Good For The Game

~~offset sprites are the only reason I don't use them~~ They look bad and wrong. With this PR they will look better.

## Changelog
:cl:
fix: Prosthetic offsets fixed finally(I hope) for this time.
del: Sprites of red fleshy mass on limb stumps is no more.
/:cl:

### CODE REVIEW

**Comment by TorinoFermic** [comment]
One red pixel in chest_m at icons/mob/human_races/r_human.dmi

**Comment by Firefox13** [comment]
> 
> 
> One red pixel in chest_m at icons/mob/human_races/r_human.dmi

Removed it.

**Comment by basedcringe** [comment]
YES

**Review by TheShown911 — APPROVED** [review]

**Review by genessee596 — APPROVED** [review]
Delegate stamp of approval.

Generally, it's considered good to have sprites where you want them and have things not trigger a player's OCD.

Has maintainer approval, so merging now.

**Pull request merged**
