### PR TITLE
Deletes the prob(66) from excel implant

### PR DESCRIPTION
**Pull request by infraredbaron**
## About The Pull Request

 If you want to deconvert someone - you should be able to.

## Changelog
:cl:
balance: excel implants now don't explode anymore
/:cl:

### CODE REVIEW

**Comment by zoktiik** [comment]
Why yes, I should just let IH deconvert me and compel me to snitch without any inherent risk whatsoever.

**Comment by Medcar** [comment]
> Why yes, I should just let IH deconvert me and compel me to snitch without any inherent risk whatsoever.
> Oh, and that one-hour timer? Haha suck it excels, you lost 8 minutes for nothing.

Maybe add a message saying that you don't remember anything, to prevent this

**Comment by FortuneMaster** [comment]
no

**Comment by Firefox13** [comment]
I agree with most of the commentators above, if you don't want be an Excelsior operative you can jump into a teleporterm instead of surrendering and possibly frame all the other excelsiors. This also makes those who do not want just to leave actually fight for their life and not surrender at the first Takeshi appearance and continue life as normal.

**Pull request closed without merging**
