### PR TITLE
Deckard's gun Sound

### PR DESCRIPTION
**Pull request by ValoTheValo**
## About The Pull Request
I was always annoyed that the pulse rifle made its cool ass sound yet the Deckard got a generic revolver sound. its time to change this. also I don't think the sound is copyrighted so we should be good

## Why It's Good For The Game
Cool sound good.

## Changelog
:cl:
soundadd: the Deckard now makes its iconic sound from Bladerunner
/:cl:

### CODE REVIEW

**Review by SirRichardFrancis — APPROVED** [review]

**Comment by SirRichardFrancis** [comment]
> are you sure about that?

What could go wrong, anyway? :thonkercat:

**Comment by Firefox13** [comment]
> What could go wrong, anyway? :thonkercat:

Entire Eris getting deleted and its legal owners getting into problems

**Comment by SirRichardFrancis** [comment]
> Entire Eris getting deleted and its legal owners getting into problems

image

**Comment by SirRichardFrancis** [comment]
image

**Comment by ValoTheValo** [comment]
> > also I don't think the sound is copyrighted so we should be good
> 
> are you sure about that?

i did a search and found nothing about the sound being copyrighted. iirc either sojurn or eclipse also has this sound on thier codebase

**Comment by TheShown911** [comment]
🤨

**Pull request merged**
