### PR TITLE
Guild Hangar Crate Chute, "New" Disk Cloner, Misc. Map Fixes.

### PR DESCRIPTION
**Pull request by Mycah142**
## About The Pull Request
First and foremost this was a map edit/fix for some shit that either bugged me, or were a glaring issue because SOMEONE forgot to REPLACE SOME REINFORCED WALLS TO SPACE. HHMMMMMMMMMMMMMMM. It steadily became something a little more.

I moved some walls on the west side of the Guild Hangar over one (Near the smelter room), moved a rack and two tables towards the console, to make room for a conveyor belt to a chute specifically for crates to be disposed of.
StrongDMM_tURSkzp1HG

Next, I added a honey extractor circuit to the Bee Crate in the NT agricultural area. There's only one way to get it otherwise and it's through the Guild. I felt it odd as hell that the crate has everything EXCEPT the honey extractor. Made beekeeping fairly lame. Let the mead flow.
StrongDMM_7OkF1JVobI

Then I fixed the FUKKEN HOLE IN THE WALLS TO SPACE BELOW THE CLUB.
StrongDMM_gKe6lemYp4

~~And lastly, I created a sub of the disk cloner, the Aster's Jailbreaker. The only difference between it and a regular disk cloner is that it starts 'hacked' without the upgraded parts. It's slow as sin, but it does the job. It's where the disk cloner was previously located in the Guild.~~ **Atomized for further discussion.**

## Why It's Good For The Game
1. Faster/Easier cleanup of crates in the hangar. Once spent 45 minutes trying to clean the mess a shit captain made brute forcing trade stations dragging or wrenching the crates.
2. Allows actual full use of the bees, maybe people will use them more now since they can actually harvest the honey.
3. NO MORE DEPRESSURIZED MAINT AREA DUE TO NEGLIGENT MAPPING.
~~4. Guild gains a niche, able to jailbreak disks without waiting 20 minutes for Moebius to answer the door, but still benefits heavily from buying upgraded parts from Moebius.~~ **Atomized for further discussion.**

## Testing
[dreamseeker_yAEis47uyX.webm](https://github.com/discordia-space/CEV-Eris/assets/11076040/b7871eb5-7145-421b-88ac-621051331b9b)
~~[dreamseeker_S8Tua0gOGS.webm](https://github.com/discordia-space/CEV-Eris/assets/11076040/c63fed48-e9b7-40c8-9b71-cbbab6836091)~~ **Atomized for further discussion.**

## Changelog
:cl:
add: Honey Extractor Circuit to NT Bee Crate
add: Crate Disposal Chute
fix: Humon's god damn gaping club hole
/:cl:

### CODE REVIEW

**Comment by Mycah142** [comment]
I'd personally like to thank Daget24 for banning me for this weekend so I had time to learn a bit about StrongDMM. Thank you, based Daget.

**Review by Firefox13 — COMMENTED** [review]
Amazing job on tungling useful fixes with a balance change as well as blaming people. I don't like the guild cloner being upgraded from the start as it trivializes printing shitton Dallases. Before they had to get Moebius help for it, even if it was just buying parts.

**Comment by Mycah142** [comment]
You knew I was doing this. At least maybe the disk cloner will actually be used, and the guild will hack disks instead of hanging out in the hangar bay brute forcing traders all fukken day.

The goal was to help the guild manufacture. With Miner, they get mats. Through Vagabonds, disks.

With the (not upgraded, just hack flag flipped) cloner, those oldified disks can be broken and made useful.

Saying this'll cause endless dallases like it'll be every round is some fukken doomsday preaching. Let the guild manufacture.

**Comment by Mycah142** [comment]
I have reverted the Jailbreaker. I will remove mentions of it in the post as well.

**Review by TheShown911 — APPROVED** [review]

**Pull request merged**
