### PR TITLE
[needs head-staff approval] Cruciforms now inform you of your loyalty to NT

### PR DESCRIPTION
**Pull request by MLGTASTICa**
## About The Pull Request
Having a cruciform implanted into you now informs you of your affinity with NT, and that you will usually side with them in times of conflict

## Why It's Good For The Game
NT is supposed to be cult-like , isn't it. This also helps with the forcefull conversion objectives , since the converted would not slander their own church.

## Changelog
:cl:
admin: Added a warning to anyone which gets a cruciform activated.
/:cl:

### CODE REVIEW

**Comment by Humonitarian** [comment]
It should be implied, not pointed out.

Consider describing how their immortality depends on NT, instead

**Comment by MLGTASTICa** [comment]
> It should be implied, not pointed out.
> 
> Consider describing how their immortality depends on NT, instead

Most people don't follow this logic by default.

**Comment by garrulousTeamotei** [comment]
Well, if the main point of this is making inquisitor conversion missions possible without having to kill the target after conversion, why not just implement the cruciform control cruciform upgrade, have it be a purchasable item from the inquisitor. Since inquisitors can't obtain more telecrystals by completing contracts, it would prevent such a cruciform upgrade from being bought en mass
Giving all cruciforms the additional ability of general mind control by means of a loyalty implant seems excessive.

**Comment by Humonitarian** [comment]
Agreed with gar.

Also, "You feel something surge through you, your doubts of the Church melting away. The Machine is within you. Your previous experiences and bonds are unharmed, yet you feel a sense of belonging to Him. Welcome to NeoTheology."

Something like this?

**Comment by MLGTASTICa** [comment]
> Agreed with gar.
> 
> Also, "You feel something surge through you, your doubts of the Church melting away. The Machine is within you. Your previous experiences and bonds are unharmed, yet you feel a sense of belonging to Him. Welcome to NeoTheology."
> 
> Something like this?

Thats good , ill wait on approval from Gray to see if its fitting.

**Comment by Humonitarian** [comment]
Consulted loreman,

"You feel the Grace of God's light, your doubts of the Church melting away. Your previous experiences and bonds are unharmed, yet you feel a sense of belonging to Him. Welcome to NeoTheology."

**Comment by MLGTASTICa** [comment]
> Consulted loreman,
> 
> "You feel the Grace of God's light, your doubts of the Church melting away. Your previous experiences and bonds are unharmed, yet you feel a sense of belonging to Him. Welcome to NeoTheology."

changed it , hopefully you did not lie.

**Comment by Firefox13** [comment]
изображение
It isn't a mind control device.

**Comment by Humonitarian** [comment]
> изображение It isn't a mind control device.

That should be implied by the new message

**Comment by MLGTASTICa** [comment]
No point for any alert messaging , since cruci ain't mind-control at all.

**Pull request closed without merging**
