### PR TITLE
Gun changes

### PR DESCRIPTION
**Pull request by Tea-Primoris**
## About The Pull Request
Recoil will decrease after second from last shot, so single fire is not pinpoint death laser.
Full auto and bursts have slightly less damage than single fire.
Maximum recoil offset is 90 degrees.
Some click handler optimization to reduce lags when firing continuously.
Projectile penetration is increased based on vig stat.
Maximum overcharge of energy weapons splitted in half.
All weapons got damage and recoil tweaks.

## Why It's Good For The Game
Reere requested changes

## Changelog
:cl:
:balance: Recoil will decrease after second from last shot, so single fire is not pinpoint death laser. Also maximum recoil offset is 90 degrees now.
:balance: Full auto and bursts have slightly less damage than single fire. All guns got damage and recoil changes. Projectiles got more penetration the more vig stat you have. Maximum overcharge cutted in half.
/:cl:

### CODE REVIEW

**Review by TorinoFermic — APPROVED** [review]

**Comment by AMM101902** [comment]
I tried testing this and it seems totally busted when I tested it. _(I'm new to using git so I might have fucked something up, but I talked to someone who knows what they are doing and it seems I did everything right)_ Guns don't seem to respect me changing their fire-mode properly, including laser weapons. It seems using a gun in the auto fire-mode results in me attempting to use the gun regardless of if it is still in my hands, allowing me to shoot it while it is on the ground. Full auto also seems to only fire at the max speed semi auto could. A similar issue occurs with lasers and charge mode still trying to fire despite no longer being in hand.



On a separate note, I fear this change will just result in people skipping over projectile weapons entirely for energy weapons with low recoil, or using shotguns even more for the high damage per shot allowing them to kill someone before recoils builds up too much.

**Comment by Tea-Primoris** [comment]
> 
> 
> It seems using a gun in the auto fire-mode results in me attempting to use the gun regardless of if it is still in my hands, allowing me to shoot it while it is on the ground. A similar issue occurs with lasers and charge mode still trying to fire despite no longer being in hand.

Should be fixed. Further testing needed.

**Comment by AMM101902** [comment]
Upon switching fire-modes, automatic fire-modes now fire at semi auto speed.

**Comment by Tea-Primoris** [comment]
> 
> 
> Upon switching fire-modes, automatic fire-modes now fire at semi auto speed.

That's intended, for now.

**Comment by Tea-Primoris** [comment]
> 
> 
> > Upon switching fire-modes, automatic fire-modes now fire at semi auto speed.
> 
> That's intended, for now.

Or full-auto fires faster than before you switch to it again?

**Comment by AMM101902** [comment]
The gun works normally when I first pick it up, but if I ever change the fire mode, then full auto will now shoot noticably slower. It's at about the speed of semi auto.

**Comment by AMM101902** [comment]
The gun works normally when I first pick it up, but if I ever change the fire mode, then full auto will now shoot noticably slower. It's at about the speed of semi auto.

**Comment by Hopekz** [comment]
Are you still working on this PR?
It has been in draft mode for quite a while.

**Review by TorinoFermic — APPROVED** [review]

**Review by genessee596 — APPROVED** [review]

**Review by drexample — APPROVED** [review]

**Pull request merged**
