### PR TITLE
Kraftwerks meat now contains dead nanites

### LINKED ISSUE #4176: [BUG] kraftwerk roaches don’t give nanomachines

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request
4 units of dead nanites can be gotten via the Kraftwerks meat

## Details
closes  #4176

### CODE REVIEW

**Comment by SpadesSlick** [comment]
Is this a type of nanites that used in creation of nanite chems?

**Comment by Trilbyspaceclone** [comment]
No, purely for toxin damage if people want to eat metal and toxic roach. I can switch them if you like to the base type for chem mixing.

**Comment by SpadesSlick** [comment]
Yeah, we need a base type here for people to be able to farm nanites from them.

**Comment by Trilbyspaceclone** [comment]
Corrected, they are now the useable type in crafting

**Pull request merged**
