### PR TITLE
Making PR template more fancy

### PR DESCRIPTION
**Pull request by AlexMorgan3817**
Preview:<hr>

## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by Kurgis** [comment]
This just places additional click time onto what should be immediately seen at a glance, -1 from me.

**Comment by TorinoFermic** [comment]
Preview of this


## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>



<hr>
</details>

## Why It's Good For The Game
<details>
<summary>
	Why It's Good For The Game
</summary>
<hr>




<hr>
</details>

## Changelog
:cl:

**Comment by AlexMorgan3817** [comment]
Waiting for merge

**Comment by ITCups** [comment]
actually no, i think this change is bad, we dont need spoilers for those
Spoilers are probably only needed in image section for people with low internet bandwidth but i cant see it being an issue
Instead i suggest remove section **Why It's Good For The Game** altogether and as i said before move changelog tags into commented out section so people wouldn't have to delete excess tags every time

**Comment by AlexMorgan3817** [comment]
r4r

**Pull request merged**
