### PR TITLE
Add hi-tech handcuffs

### PR DESCRIPTION
**Pull request by SirRichardFrancis**
## About The Pull Request

Counters freedom implant and excel communication, shocking the user(10 burn damage, up to 100 total) on activation.
Falls off when hit by EMP. IH sergeant spawn with one.
image

## Why It's Good For The Game

Ask Presidente.

## Changelog
:cl:
add: new type of handcuffs that block freedom implant
/:cl:

### CODE REVIEW

**Comment by Humonitarian** [comment]
I do not like the idea of just immediately making freedom implant useless.

Making it stun the user when forcibly removed (either through resist, or through freedom implant) would be a better route.

**Comment by TheShown911** [comment]
Why?

**Comment by SirRichardFrancis** [comment]
> Why?

El presidente asked me to make it.
¯\\\_(ツ)\_/¯

**Comment by thedarkcrusader** [comment]
> > Why?
> 
> El presidente asked me to make it. ¯\_(ツ)_/¯

I have now just received several death threats please excuse me for a moment

**Comment by ValoTheValo** [comment]
> > Why?
> 
> El presidente asked me to make it. ¯\_(ツ)_/¯

Cumshoe is salty he got robusted

**Comment by thedarkcrusader** [comment]
> > > Why?
> > 
> > 
> > El presidente asked me to make it. ¯_(ツ)_/¯
> 
> Cumshoe is salty he got robusted

Yes this is the exact specific reason why this is here not because I don't like moebius or anything

**Comment by ValoTheValo** [comment]
> > > > Why?
> > > 
> > > 
> > > El presidente asked me to make it. ¯_(ツ)_/¯
> > 
> > 
> > Cumshoe is salty he got robusted
> 
> Yes this is the exact specific reason why this is here not because I don't like moebius or anything

Diagnosis: Skill Issue

**Comment by UltraNumeron** [comment]
you are extremely geared ironhammer operatives you really should be  able to deal with this instead of adding a roundstart item that makes freedom implants worthless. In general this just looks really unnecesarry.

**Comment by thedarkcrusader** [comment]
> you are extremely geared ironhammer operatives you really should be able to deal with this instead of adding a roundstart item that makes freedom implants worthless. In general this just looks really unnecesarry.

by dealing with it you mean knocking them out over and over breaking there legs or just straight up killing them?

**Comment by Autisem** [comment]
This does kinda invalidated freedom implants, because you can simply only use these types of cuffs

**Comment by SirRichardFrancis** [comment]
> This does kinda invalidated freedom implants

So does breaking a leg, smh.

>because you can simply only use these types of cuffs

There is no way of obtaining those other than spawn with them. Maximum of one pair can exist at the same time.

> Also why block excel comms???

Entire point of those things is to counter augmented criminals. There is not a lot of augments to counter atm, so just freedom implant and excel comms.

**Comment by ValoTheValo** [comment]
> There is no way of obtaining those other than spawn with them. Maximum of one pair can exist at the same time.

Well there is two pairs since the gunnery sarge and IHC get them not just ihc.

**Comment by ValoTheValo** [comment]
Also you can easily counter freedom implants currently. Knock the person out and strip thier guns and armor off. Once they wake up hopefully they will be in the brig. You act like freedom implants are a massive problem for IH and need a dedicated counter that not only makes them worthless but also deals shock damage

Same deal with excelsior. You cant use implants while your knocked out. And if he does manage to call his buddies just fight them. You have alot better gear most of the time anyway

**Comment by SirRichardFrancis** [comment]
> Well there is two pairs since the gunnery sarge and IHC get them not just ihc.

A pair is two things. Two cuffs - one pair.

> Also you can easily counter freedom implants currently...

I know, right.

> You act like freedom implants are a massive problem for IH and need a dedicated counter that not only makes them worthless but also deals shock damage
> Same deal with excelsior. You cant use implants while your knocked out. And if he does manage to call his buddies just fight them. You have alot better gear most of the time anyway

I do not act like there is massive balance problems(you do tho), Presidente wanted his sprite added into the game, and here it is - like regular cuffs, but with a fancy sprite and hi-tech functionality on top, both advantage and disadvantage.

**Comment by thedarkcrusader** [comment]
> Also you can easily counter freedom implants currently. Knock the person out and strip thier guns and armor off. Once they wake up hopefully they will be in the brig. You act like freedom implants are a massive problem for IH and need a dedicated counter that not only makes them worthless but also deals shock damage
> 
> Same deal with excelsior. You cant use implants while your knocked out. And if he does manage to call his buddies just fight them. You have alot better gear most of the time anyway

Having to constantly knock a person out over and over again just to restrain and hold them for a bit is just blatantly annoying  for both parties involved,

**Comment by UltraNumeron** [comment]
just let them use the implant  they paid tc for instead of actively trying to work around it to make it useless? no need to knock em out even, if they use it just let em and fight em to get em back. the shocks just insult to injury and emps are very rare nowadays. The sprite looks cool but the functionality is very shit.

**Comment by Firefox13** [comment]
This invalidates freedom implants and I *really* do not like this since they were made in order to counter handcuff and this is just a counter for a counter while still being the thing that is supposed to be countered
(I know you can't understand me)

**Pull request closed without merging**
