### PR TITLE
Sorter Room Disposal Chute Fix, Shipping Supplies (General Map PR)

### PR DESCRIPTION
**Pull request by Mycah142**
## About The Pull Request
Started as just a quick PR to fix the SOMEHOW STILL WORKING disposal chute in the sorter room (it was missing the trunk connection, I believe it worked all this time because things ejected from just a pipe spawn on the tile it's facing, which was on top of the disposal chute, and so 99% of items just yeeted past) and turned into a general map adjustment to accommodate some things.

First, a trunk was added under the disposal chute in the sorter room between the guild and church. I found it investigating why that room constantly drained of air. No idea if this'll fix that.

While I was playing around in SDMM, I realized that with the destination tagger fix, each department head should get a destination tagger and package wrap, to encourage communication and trade. So Destination Taggers/Package Wrap were added to each Department Lead's office that contained an EFTPOS, on the same table as the EFTPOS. As an additional bit of encouragement, any location that had an EFTPOS, now has shipping supplies (Guild cargo bay, as an example.) If you really want a picture of each of these, I can do so, but I didn't want to make this the PR equivalent of a CVS receipt.
StrongDMM_jRtRFtmmK6

While locating and shipifying EFTPOS, I noticed the Church never had one. Added two EFTPOS, one in the preacher's office, another in the church stall. Shipping supplies as well.

Noticed that the only "public" Destination Tagger and Package Wrap publicly available were in the Guild lobby, so I added another set to the Library. Diversity is the spice of life.

Since this PR was still up, I also corrected the access to the default Windoors to the Neotheology Store Stall, and the Agrocultural room so they're no longer All Access.

Also was informed that the Pulsar Power Bridge circuit wasn't printable, and only available as Maint Loot (for some reason), so I mapped in a spare to Secured Technical Storage.
StrongDMM_gXgmd256tl

## Why It's Good For The Game
Map Fix Good.
Readily available shipping supplies could encourage trade, now that the Destination Tagger works.

## Testing
Disposal worked (Didn't keep the game up long enough to see if air was draining). Nyoomed around to make sure the shipping supplies were where I placed them.

## Changelog
:cl:
add: Added Destination Taggers and Package Wrap anywhere an EFTPOS spawns.
add: Another camera to the gym shower room.
add: Added 2 EFTPOS for Church of Neotheology (Preacher office, selling stall).
add: Shipping Supplies to Library
add: Spare Pulsar Power Bridge Circuit to Secured Technical Storage
fix: Fixed disposal chute in sorter room to have a trunk
fix: NT Shop and Agro windoor access
/:cl:

### CODE REVIEW

**Comment by Holvr0** [comment]
I have indeed asked Mycah for that club-gym staircase (even with a convenient shortcut to now-public NT hallway).

And yes, despite what it looks like, it's probably the sanest possibly place where those stairs can go.

**Comment by SirRichardFrancis** [comment]
My brother in Christ, this is the ugliest staircase I've ever seen! No offence meant.
Staircases on Eris follow a pattern of being surrounded by reinforced walls. That makes them less prone to damage from random fights, and, more importantly, makes them look good.
These, on the contrary, do not look good at all.

Please reconsider and find a better way of doing the thing.

**Comment by Holvr0** [comment]
club2

Alternative staircase, @SirRichardFrancis

**Comment by SirRichardFrancis** [comment]
So much better. Now make it look good on the top.

Remember that stuff inside of the gym could be moved around.

**Comment by Holvr0** [comment]
gym2

@SirRichardFrancis kek

**Comment by SirRichardFrancis** [comment]
Somewhat cramped, but works.

Things (including walls, doors, areas) could be moved around on a larger scale, to make it look even better.

**Comment by Mycah142** [comment]
I hate how disruptive walls would be in the gym. They disrupt line of sight, everything.

Moving anything on the holobar would disrupt existing presets and so those would have to be rebuilt too.

**Comment by SirRichardFrancis** [comment]
Do whatever about it, as long as there is no wall-less staircases.

**Comment by Holvr0** [comment]
clubnew
gymnew

If we want a private entrance for club staff (and only staff, not a public one) it could be like this, but it's a half measure...

**Comment by Holvr0** [comment]
clubkek
gymkek

At this point why not ;D

**Comment by Mycah142** [comment]
I gotchu fam

StrongDMM_jpZrGoT8ev

**Comment by SirRichardFrancis** [comment]
Teleport has to be powered and setup correctly, instead make a stable wormhole straight to the gym.
image

**Comment by SirRichardFrancis** [comment]
Because players _**must**_ have a route to the gym that does not involve going outside and spending 10 seconds to go trough primary hallway.

**Comment by Holvr0** [comment]
@SirRichardFrancis Quickly code a whole system for elevator tubes that near-instantly transport players between z-lvls, just for this shortcut alone.

[And disregard that it's functionally identical to a ladder]

**Comment by SirRichardFrancis** [comment]
I'll call it a hyper Z-level teleportation pod and it'll cost 5 million credits to build. (it will be a resprited ladder)

image

**Comment by Mycah142** [comment]
Six million pesos ladder.

**Review by Firefox13 — CHANGES_REQUESTED** [review]
All stairs must be wrapped with reinforced walls - this isn't a code requirement but simply a mapping standard (all of the stairs are like this).

Double-check the way you put stairs - they must "align", this one needs to be turned around.
изображение

> If you really want a picture of each of these, I can do so, but I didn't want to make this the PR equivalent of a CVS receipt.

Use spoilers then.

**Comment by Mycah142** [comment]
Didn't know spoilers were a thing for GitHub.

I'm likely going to remove the staircase, as it'll be more of a chore than what this PR was intended to be. Maybe I'll work on more bar presets as well as a staircase.

As another question, why not just make stairs unbreakable? We already can't repair or replace them.

**Comment by Mycah142** [comment]
This PR has had a couple additions related to mapping, primarily fixed access for NT windoors, added the Pulsar Power Bridge to Secured Technical Storage, and removed the stairs to the gym attempt.

**Comment by Kurgis** [comment]
LGTM :heart_decoration:

**Pull request merged**
