### PR TITLE
Aberrant Organs: Minor rework and fixes

### PR DESCRIPTION
**Pull request by Pink-Chink**
### Organ Mod Changes
- Improved capillaries - Reduces organ requirements by 50%, multiplicative.
- Durable membrane - Increases organ size by 20%, multiplicative.
- Visceral symbiont - Increases organ size by 20%, multiplicative.
- Bypass tubules - Reduces organ size by 20%, multiplicative.
- Biostructure gel - Increases base organ size by 20%.
- Masked membrane - Reduces organ size by 10%, multiplicative.

### Disgorger Rework
- Research and production are now separately tracked and impacted by the organ components.
- For an organ to count towards research, it must have been inside of a live human at some point.
- There is an invisible throughput value controlled by heart and blood vessel organ efficiencies. Essentially, an organ with at least 80 heart efficiency is necessary for it to function in a playable capacity.
- Increased required organ component count from 4 to 6.
- Formula for research/production rates (capped at 2 or 200%): `value produced = 1 / (2 - (throughput * rate))`

### Other Gameplay Changes
- Added 75 BIO armor to latex and nitrile gloves to allow for safe handling of symbiotic organoids.
- Removed all organoids related to multiple inputs or outputs.
- Removed most deep maint aberrant organs.
- Added symbiotic organoids. These can serve as traps or will allow a bio-engineer to implant an organ without needing surgery at the cost of making the organ larger.
- Added ovarian organoids. When triggered, the player will produce the specified object.
- Added eructal organoid. When triggered, the player will spew a cloud of gas from their mouth. Requires a reagent permeability value >= 0.10 on the player's face (don't wear a mask).
- Added mandibular organoid. Triggers an aberrant organ by consuming an object held in the active hand. Uses the same text as the carrion organ consumption to give them some excuse for being weird.
- Added circadian organoid. Process organoid that modifies cooldown time.
- Added enzymal organoid. Process organoid that modifies output strength.
- Added type 3 hormones.
- Reworked aberrant organ size by making it tied to the organoids.

### Code Changes
- Added protractile organoids. Allows an organ to function as an implant akin to the arm blade. Not present in-game.
- Added a somatic feature for organ mods. This allows an organ mod to add a verb, which opens up a lot more possibilities for future content. Currently, it's used to trigger the mandibular organoid.
- Reworked the way organ mod values are applied. Overall, it functions similarly to how tool mods are applied with the added functionality of using base, multiplicative, and flat modifiers. Flat values are unaffected by multiplicative increases.
- General code cleanup. Shuffled some files around, too. Exciting.

### Bug Fixes
- Fixes an issue preventing aberrant organs from triggering more than once a round.
- Fixes an issue where certain organoids couldn't be modified.

## Why It's Good For The Game

Adds a bit more content and lays the foundation for future organ modding (assisted and robotic). The multi-input/-output organoids were just bloat and can be functionally replicated by using multiple organs.

## Testing

- Researched all disgorger designs.
- Assembled aberrant organs using all of the new organoids alongside older ones.
- Modified all organoids to check for bugs or other weirdness.
- Triggered aberrant organs multiple times to check for the previously mentioned bug.

## Changelog
:cl:
add: Added symbiotic, ovarian, eructal, mandibular, circadian, enzymal, and protractile organoids.
add: Added type 3 hormones.
del: Removed all organoids related to multiple inputs or outputs.
del: Removed most deep maint aberrant organs.
tweak: Improved capillaries - Reduces organ requirements by 50%, multiplicative.
tweak: Durable membrane - Increases organ size by 20%, multiplicative.
tweak: Visceral symbiont - Increases organ size by 20%, multiplicative.
tweak: Bypass tubules - Reduces organ size by 20%, multiplicative.
tweak: Biostructure gel - Increases base organ size by 20%.
tweak: Masked membrane - Reduces organ size by 10%, multiplicative.
tweak: Added 75 BIO armor to latex and nitrile gloves.
tweak: Reworked the disgorger.
tweak: Reworked the way organ mod values are applied.
tweak: Reworked how aberrant organ size is determined.
fix: Fixes an issue preventing aberrant organs from triggering more than once a round.
fix: Fixes an issue where certain organoids couldn't be modified.
code: Cleaned up organoid code.
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
We are so back.

**Comment by Pink-Chink** [comment]
Thanks for the feedback. I noticed there were some changes related to the latest merge that aren't playing well with examining organs and organ verbs. So, that might be affecting the mandibular organoid and other verb-using organoids.

> Making research possible ONLY with organs that were, at some point, in a living human, is pretty restrictive.

I wanted to move away from using standard organs as the primary source of points since it's kinda weird to be able to get research points by feeding the disgorger printed organs. I'll look into why it's only taking the starter ones, though. That being said, I saw two things in the changes that weren't in my notes: organs were contributing half as much as they should have been and reagent modifiers weren't being applied to research points. Gonna see how it goes with those fixed.

**Comment by Pink-Chink** [comment]
`points = (regeant volume * reagent modifier) / production denominator`

If the disgorger was constructed with a total liver efficiency of 100, it will accept objects with diplopterum with a modifier of 1.25. That means you'll be able to feed it roach meat or any container with diplopterum in it. Other reagents require different efficiencies and the modifier isn't something you can see without code diving. The reagents themselves show up when you examine the disgorger.

For gameplay, the research system is still placeholder and I doubt I'll expand it to be much more. The future vision was to add organ loot to hivemind, roach, and spider mobs to give players incentive to sell those to the bio-engineer. They wouldn't be safe to handle for most people and the bio-engineer would be able to feed them to the disgorger to unlock their designs for the mods and scaffolds. I have some early versions of those organs, but things are slow moving on my end.

**Review by TheShown911 — APPROVED** [review]

**Comment by TheShown911** [comment]
Test mergin this one to live

**Pull request merged**
