### PR TITLE
Pulsar Relay

### PR DESCRIPTION
**Pull request by Mycah142**
## About The Pull Request
The Pulsar Sat is fun and all, but a critical component it is missing is the ability to actually communicate to the Eris. This thing isn't Deep Maint. This is a step towards making it a hodge-podge lookin' structure with makeshift telecom, atmospherics, and jury rigged power.

I did attempt to fix the airlock that wasn't working, but after finding out that even the piping connecting the air tank to the vent don't even initialize correctly (they start disconnected), and two days of pulling my hair out on what should've been a simple map fix, I gave up. I did correct the vent's master_tag, and made sure frequencies/id/tags all lined up.

I did attempt to remap everything. If you want to see the last few marbles I have slowly drip out my ear, just tune into the coding-tent channel on the discord of me screaming into the abyss and it laughed back.

## Why It's Good For The Game
Being able to ask your fellow technomancers "What are sat shields for? They seem like a waste of power" while piloting the Icarus straight into the god damn sun is a good thing, as it alerts them to come to the sat and kick you out an airlock.

## Testing
Exhaustive, believe me. The relay, sure as shit, works on the Pulsar, links to the HUB on the Eris appropriately, and is as expected.

## Changelog
:cl:
add: Added Relay to the Pulsar Sat
/:cl:

### CODE REVIEW

**Review by hyperioo — APPROVED** [review]

**Comment by Evie7056** [comment]
No receiver and broadcaster hence it's not working.

**Comment by Mycah142** [comment]
> 

In my defense I tested it both with an AIO HUB and without, and it did link during testing without them.

**Comment by Mycah142** [comment]
> > > 
> > 
> > 
> > In my defense I tested it both with an AIO HUB and without, and it did link during testing without them.
> 
> okay it's weird then

Even with an All In One linked to the Eris network it doesn't work. Something changed because all I 'had' to do was close out the telecom/lateinitialize() with a return INITIALIZE_HINT_LATELOAD and it was fine.

**Comment by Evie7056** [comment]
Byond shittery my friend that it is :(

Good job either way

**Comment by Evie7056** [comment]
Okay, I tested it again, this is not an issue on EN. /shrug

**Comment by Mycah142** [comment]
> Okay, I tested it again, this is not an issue on EN. /shrug

If you mean the current round right this minute, it's because it was linked inworld. I'm testing local and it isn't linking again either, so it is a problem and somehow I didn't actually solve it.

**Comment by Evie7056** [comment]
> > Okay, I tested it again, this is not an issue on EN. /shrug
> 
> If you mean the current round right this minute, it's because it was linked inworld. I'm testing local and it isn't linking again either, so it is a problem and somehow I didn't actually solve it.

Well, consider my info nullified

**Comment by Firefox13** [comment]
Receiver and broadcaster isn't needed.

**Pull request merged**
