### PR TITLE
Rework E-armblade

### PR DESCRIPTION
**Pull request by Mycah142**
## About The Pull Request
Directly removes Double Tact from the Energy Armblade cybernetic without sacrificing it's BULKY size, which has defensive capabilities while using the BLOCK hotkey.

## Why It's Good For The Game
Why should a quick e-shank require two clicks? It does 6 more damage than the wrist shank (a makeshift item) but has zero modifiability. The wrist shank does more damage with a single mod, without double tact. At the very least, such an item that isn't modifiable should have more advantages than something assembled from actual junk.

## Testing
Compiled, launched, swung my energy armblade into floor tiles without double tact.

## Changelog
:cl:
balance: Removed Double Tact from the Energy Armblade cybernetic.
/:cl:

### CODE REVIEW

**Comment by Mycah142** [comment]
brave_zsl9hNRHFa
No idea how this is my problem.

**Comment by SirRichardFrancis** [comment]
> No idea how this is my problem.

It really isn't.

**Comment by SirRichardFrancis** [comment]
Forgot to clarify, integration tests fail due to these roundstart runtimes:
image
image
Basically mice running all over maintenance are setting off traps before all necessary stuff is initialized.

**Review by Firefox13 — CHANGES_REQUESTED** [review]
Use `no_double_tact` or however it is called variable to remove double tact when it is specifically required to remove double tact from an item that shouldn't or when it doesn't have sense for it to have double tact.
Double tact.

**Comment by Mycah142** [comment]
> Use `no_double_tact` or however it is called variable to remove double tact when it is specifically required to remove double tact from an item that shouldn't or when it doesn't have sense for it to have double tact. Double tact.

So you still want it to have the blocking ability of other Bulky items?

**Comment by Firefox13** [comment]
I mean, it's an armBLADE

**Review by Firefox13 — APPROVED** [review]

**Pull request merged**
