### PR TITLE
Disposal mail delivery

### PR DESCRIPTION
**Pull request by TheLeopold**
## About The Pull Request
Cleaned and fixed disposal mail delivery. Did slight repiping in the church and engineering. Added Club, Tool storage and Dormitories as mail destination. Each department has 2 destinations: Head office and general area. Exception is medbay - they have third one, Chemistry. And IH, they have only one mailbox which is security lobby, since almost whole 1st section is separated from the rest of the disposal system.

tagger
guild
chapel
preacher
изображение
lower
atmos1
atmos2

## Why It's Good For The Game
Fix

## Testing
Disposaled myself to every possible destination as a droid.

## Changelog
:cl:
add: Added Club, Tool storage and Dormitories to the list of possible mail recipients. Added trash bin to the Preacher Office.
fix: fixed disposal mail delivery
/:cl:

### CODE REVIEW

**Comment by Firefox13** [comment]
> Disposaled myself to every possible destination as a droid.

Did you disposal *out* of those places though? You may not get stuck coming in, but may or may not get stuck coming *out*.

**Comment by TheLeopold** [comment]
> Did you disposal _out_ of those places though?

Yes, that too.

**Comment by Holvr0** [comment]
For a funny, consider making it so that Technomancers with Exotic Inspiration active (so, drunk) take no damage from disposals, so they can deliver themselves, too 😁

**Comment by Mycah142** [comment]
> For a funny, consider making it so that Technomancers with Exotic Inspiration active (so, drunk) take no damage from disposals, so they can deliver themselves, too 😁

Already a perk, to not be damaged by disposals. I forget the name of it though.

**Comment by null-Aurelian** [comment]
> Already a perk, to not be damaged by disposals. I forget the name of it though.

Space asshole I think, thought it only reduces the damage

**Review by hyperioo — APPROVED** [review]

**Pull request merged**
