### PR TITLE
Gun Smithing update 1: The Bancroft .60

### PR DESCRIPTION
**Pull request by maikilangiolo**
## About The Pull Request
Adds a new makeshift gun, the Bancroft. A fancy name for a scrap gun, but rest assured this baby will not disappoint you. A cross between an elephant gun and old 45-70 lever action rifles, this hefty cannon will help you hunt big game and dangerous mega roaches with style. And when ammo runs out, there is always the bayonet....
Sprited by bobob9000, god bless him. He even animated the reload!
image

## Why It's Good For The Game
We expand the makeshift gun list with new exciting content. If you think it will be OP, the shotguns do more damage than the new nerfed .60 with #7547, and have less recoil. The niche of this gun is a short scope and really fast, though not hitscan, bullets. also needs #7546 to work since refactor

## Changelog
:cl:
add: Added a new handmade gun, the Bancroft
/:cl:

### CODE REVIEW

**Comment by maikilangiolo** [comment]
oops, bath path in the frame lol will fix

**Comment by TheShown911** [comment]
Wasn't there a gun ban or something?

**Comment by maikilangiolo** [comment]
> Wasn't there a gun ban or something?

What Firefox says about the gun ban:"Gun ban is just "hey can I add X"'. I didn't add a gun for the sake of it, and I also didn't add a gun that doesn't respect the current gun "requirements": frame crafting. It works with the new system, it's got a niche and a purpose, it's not stronger than the makeshif shotgun with a shotgun barrel, or even with the AMR barrel.

**Comment by Firefox13** [comment]
> What Firefox says about the gun ban:"Gun ban is just "hey can I add X"

did you ask delegate/me that though

**Comment by maikilangiolo** [comment]
> > What Firefox says about the gun ban:"Gun ban is just "hey can I add X"
> 
> did you ask delegate/me that though

I talked with humon about the Bancroft gun, and I asked you about the Hornet. If you want to close this, sure. I didn't want to do everything in DMs/discord but hoped people saw this PR and discussed "good/bad/useless".

**Comment by HanSolo1519** [comment]
Incredibly sexy, I'm biased as fuck towards things that actually use .60 but this seems to be pretty unique. Glad to see something fitting the civilian aesthetic that's not just the serbian rifle.

**Comment by hyperioo** [comment]
@maikilangiolo 

image

**Comment by maikilangiolo** [comment]
Firefox word is his word.

**Pull request closed without merging**
