### PR TITLE
Updates Bio-generator to be better!

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request
Makes bio-generators be able to be upgraded and deconned better*
Makes bio-generator upgraded bins affect how much can be stored with current max being 16 but with sci's level 3 being normally if upgraded 13 crops - Lucky number

Adds a load of commits and fixes bad else ifs that prevent you from upgrading and deconning the bio-gen I think

## Why It's Good For The Game

Gives more of a reason to try and upgrade the bio genertor

## Changelog
:cl:
tweak: Upgrading the bio-generators matter bins will now let you store even more crops! 
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Any suggestions on how to make it work?

**Comment by SpadesSlick** [comment]
image
Why are you making commits with something you don't sure works?

**Comment by Trilbyspaceclone** [comment]
This is the only one that isnt following the line by line reading, maybe if-else will make it go `Oh! I should use this!`

**Comment by SpadesSlick** [comment]
I mean, why don't you test to to make sure it works?

**Comment by drexample** [comment]
Bio-generator is a deprecated feature that will never be used.

**Pull request closed without merging**
