### PR TITLE
Lethal injection fix

### PR DESCRIPTION
**Pull request by Iglpigl**
## About The Pull Request

Lethal injection now uses chlorine and choral hydrate.

## Why It's Good For The Game

It works now.

## Testing

After some time we get something like this: 
Screenshot_1

## Changelog
:cl:
fix: lethal injection is lethal now
/:cl:

### CODE REVIEW

**Review by Firefox13 — CHANGES_REQUESTED** [review]
Lethal injection should be a mix of something that puts the prisoner to sleep and something that kills them with either toxin or suffocation damage for humanism reasons. No pure acid syringes pls

**Comment by maikilangiolo** [comment]
> humanism reasons

I'll just stick to using the electric chair which now takes multiple uses to kill and makes the prisoner die in extreme and slow agony.

**Comment by Firefox13** [comment]
electricchair.dm nor part in the living.dm answering for burn_skin damage weren't touched for ages though.

**Comment by maikilangiolo** [comment]
Someone changed it to take multiple goes because ghosts could trigger electric chairs and instant kill people.

**Comment by Firefox13** [comment]
See for yourself
https://github.com/discordia-space/CEV-Eris/blob/master/code/game/objects/structures/electricchair.dm
https://github.com/discordia-space/CEV-Eris/commits/master/code/game/objects/structures/electricchair.dm

**Review by Firefox13 — APPROVED** [review]

**Comment by tristain01** [comment]
Simple, Turn iron hammers firing range into a firing.sqaud.room

**Pull request merged**
