### PR TITLE
Gym fixening

### PR DESCRIPTION
**Pull request by ErisMeleeEnjoyer**
#7630 with fixes
also fixed finish_rest a bit so that the menu won't pop up in an instant in case you are in danger(which is a skill issue tbh)

### CODE REVIEW

**Comment by ErisMeleeEnjoyer** [comment]
I did check this on local(i fucking hate testing sanity code), and it seems to be working; however, since this touches sanity, I recommend putting this on test, just to be sure that I didn't miss anything.

**Comment by SirRichardFrancis** [comment]
Wanna note that #7630 was reverted because it was suspected in making server lag.
Server continued to lag like crazy after this revert, however.

**Comment by ErisMeleeEnjoyer** [comment]
> Wanna note that #7630 was reverted because it was suspected in making server lag. Server continued to lag like crazy after this revert, however.

it was reverted because it had runtimes and critical bugs, not lags. Machinery is responsible for most of unnedeed processing and therefore lag

**Comment by ErisMeleeEnjoyer** [comment]
Applied fixes to bugs that were found during testing

**Review by TheShown911 — APPROVED** [review]
Should be good if there weren't problems on the test server.

**Pull request merged**
