### PR TITLE
Adds boltgun sprite to suit storage (tested) 

### PR DESCRIPTION
**Pull request by Jackofashepard**
Title

### CODE REVIEW

**Comment by ACCount12** [comment]
Merge conflict.

**Comment by Jackofashepard** [comment]
Not sure whats causing it, i literally copy pasted the back sprite and renamed it to onsuit, no ones touched this file in ages either

**Comment by mattroks101** [comment]
Big wielding update dude. I touched that file just last week.

**Comment by Jackofashepard** [comment]
F

**Pull request closed without merging**
