### PR TITLE
Loadout part 1

### PR DESCRIPTION
**Pull request by AgentMA1**
## About The Pull Request

Adds green turtleneck to loadout,removes bay shit, now green can spawn too.

## Why It's Good For The Game

People asked for the green turtleneck, so i provided with it. I still want to maybe add and delete other things, but this is the first step, i still need to add the black turtleneck anyways.

## Changelog
:cl:
add: Added green turtleneck to loadout
del: Removed a shit ton of useless bay leftover that only makes issues
/:cl:

### CODE REVIEW

**Comment by AgentMA1** [comment]
if travis failed i would shot myself

**Comment by Firefox13** [comment]
Aren't green/black turtlenecks are serb-only? I believe they're like /tg/ turtlenecks where the only way to get them is to fuck nukies first. Or use a cheap tacti~cool turtleneck.

**Comment by AgentMA1** [comment]
> Aren't green/black turtlenecks are serb-only? I believe they're like /tg/ turtlenecks where the only way to get them is to fuck nukies first. Or use a cheap tacti~cool turtleneck.

Actually, sometimes they spawn in maint alredy, and the /tg/ ones pretty much spawn either in maint, or in some tg Codes in loadout can be choosen. 
They offer no defenses, are style only then. And compared to other clothes have no sensors, what can be bad sometimes

**Comment by Firefox13** [comment]
> 
> 
> > Aren't green/black turtlenecks are serb-only? I believe they're like /tg/ turtlenecks where the only way to get them is to fuck nukies first. Or use a cheap tacti~cool turtleneck.
> 
> Actually, sometimes they spawn in maint alredy, and the /tg/ ones pretty much spawn either in maint, or in some tg Codes in loadout can be choosen.

Because of our fucky loot system.  They weren't supposed to appear there.

**Comment by AgentMA1** [comment]
> > > Aren't green/black turtlenecks are serb-only? I believe they're like /tg/ turtlenecks where the only way to get them is to fuck nukies first. Or use a cheap tacti~cool turtleneck.
> > 
> > 
> > Actually, sometimes they spawn in maint alredy, and the /tg/ ones pretty much spawn either in maint, or in some tg Codes in loadout can be choosen.
> 
> Because of our fucky loot system. They weren't supposed to appear there.

I mean, they are only clothes, they have Nothing in special or something that should make them, serbian only

**Comment by AgentMA1** [comment]
Closing becouse im not working on this

**Pull request closed without merging**
