### PR TITLE
Spawning Redesign: Backups and Immersion

### LINKED ISSUE #2717: Spawning in space is back
This time it only occurs when Cryo is damaged.

### PR DESCRIPTION
**Pull request by NanakoAC**
This PR reworks spawnpoints to be more modular, more reliable, and more interesting. Immersiveness is improved to encourage roleplay

People spawning in cryo will now actually start INSIDE a cryobed, and asleep for a short time (15 seconds). They must wake up and climb out, or be autoejected after a minute.

Added the Dormitory as a new alternate spawnpoint. Anyone spawning there will start off in a bed, asleep.

Fixed tons of bugs in spawning code, so that it now properly uses fallback behaviour. If your chosen spawnpoint is bombed/vented/unavailable, the game will try to spawn you at another randomly selected spawn area. Currently there are only two, but this will prove more useful in future.
fixes #2717

Fixes tons of bugs with beds and sheets, this feature should now work flawlessly, no more getting stuck in a bed

Improves the Paralyse proc a bit, so that the victim's hud is instantly updated. This is generally useful, but was done specifically for immersion in the above cases where you start off asleep. This ensures you don't see the world around you for a second after spawning

Lastly, fixes a lot of proc names to be snake_case instead of the oldAnnoyingCamelCase

### CODE REVIEW

**Comment by mattroks101** [comment]
20 seconds seems like a long time to have to wait to play after you've spawned. Goon spawns people in a cryo chamber as well on certain maps but it ejects them immediately.

**Comment by NanakoAC** [comment]
goon is low RP chaos though. This is intended for being atmospheric. 20 seconds is hardly a long time

**Comment by SpadesSlick** [comment]
Indeed, 20 seconds is too much. Make it 10.

**Comment by NanakoAC** [comment]
eh lets compromise on 15 secs. change pushed
its still not that much, for a brief stint at the start of a multi hour round x

**Comment by NanakoAC** [comment]
Testing by the QA team has uncovered several blocking bugs in this PR. DNM for now until i fix them

**Comment by RandomColonist** [comment]
From testing:
1 - Naming error causing spawning to break if you don't set your spawnpoint to "Aft Cryogenic Storage" instead of "Cryogenic Storage" which is nonexistant anymore (you can choose any other existing spawnpoint).
2 - Weird bug appears. If you will try to spawn as human choosing the Cyborg Storage spawn point, you will randomly spawn in other available spawnpoint (as intended), but after this, if you try to change your spawnpoin in character setup you will be unable to choose any spawnpoint exept one random that will appear in list. If you do this cyborg storage gimmick spawn one-two more times, you will be unable to choose spawnpoint from character setup at all. List simply won't appear. It resets upon server restart, so it will not break the game completely.
3 - Upon spawning in cryostorage, cryofreezer that you spawned in will have name "cryogenic freezer ()". Parentheses should contain your name in them, but they obviously don't.

**Comment by RandomColonist** [comment]
As an addition, after tests i think this can use some additional sounds and bold blue message about you regaining your consciousness. Nanako said that "Immersiveness is improved to encourage roleplay", but in person i don't felt any immersion, just 5-10 secs of sleep where you can see cryofreezer, then silent woking up and ejecting from cryofreezer without any notice. Again, in my opinion, few sounds and message can fix that.

**Comment by TorinoFermic** [comment]
### My testing 

1. All everyone spawn at the game start without his backpack.

**Comment by NanakoAC** [comment]
updated, everything fixed

**Comment by GrayRachnid** [comment]
15 seconds :-1:

**Comment by mattroks101** [comment]
Three people now disapprove of 15 seconds.

**Comment by RandomColonist** [comment]
I say 15 and even 20. Because i tested it and it was good. You won't even understand what's going on. I bet that those "three people" compiled build with this fork and tried themselves. Please consider to test it out yourself before make assumptions like "20 is too much, 15 too long".

**Comment by mattroks101** [comment]
Alright I'll take your word for it.

**Comment by NanakoAC** [comment]
fixed map, reduced timer to 12 secs

**Comment by NanakoAC** [comment]
ok this is totally 4 reals fixed now, and the timer is lowered to 12 seconds

**Pull request merged**
