### PR TITLE
Medbay Remap Remap and Map Fixes and Tweaks

### PR DESCRIPTION
**Pull request by ValoTheValo**
## About The Pull Request
This PR restores some of the areas from Medbay before the remap while keeping the new additions. old surgery maint is back plus the lounge has been somewhat shrunk. 
20-Sep-22 18-15-31
the locker room has been moved up a floor to behind chemistry. 
Chemistry had its desk moved down abit and was slightly shrunk
20-Sep-22 17-45-37
there is now a very tiny maint passage into silk road where the two old chem windows were. and there is now doors into maint in that area between MBO and Chem. chemists locker was moved up to chem storage
i also fixed that one tile in disposals 
also fixed some roofing in IH maint so it wont be vented when shields go down due to lack of roof
20-Sep-22 18-35-53

This PR also adds more posters and holoposters around the inhabited areas of the ship while removing two holoplants that looked bad in maint (sorry about that)

## Why It's Good For The Game
I felt that Medbay after the remap was too large and open and lost some of its charm. the wide and open design didn't mesh well with the cramped feel the rest of medbay backrooms was going for. the added posters and holoposters are just some slight extra decoration and lighting and should mark areas slightly more like asters guild signs in guild ETC

## Changelog
:cl:
add: more posters around the ship
tweak: remapped medbay
/:cl:

### CODE REVIEW

**Comment by SaltyOldBull** [comment]
fucking terrible, no.

**Comment by Firefox13** [comment]
Make sure to check for roofs and test all the areas in-game.
I dunno if it's a good idea to separate chemistry and MBO's office (since you can get into it through maint, but not like it had much security before)

**Comment by Mycah142** [comment]
> Can we please make sure biomechanical engineers don't get constantly nerfed by the fucking obelisks in the church due to the proximity of their workspace?

Feel the love of Jesus, heathen.

**Comment by maikilangiolo** [comment]
> Can we please make sure biomechanical engineers don't get constantly nerfed by the fucking obelisks in the church due to the proximity of their workspace? In that tiny space you're almost always sitting somewhere that gets you less of a von-krabin boost, which is dumb, because you're in medical and not the fucking church.

Reminds me club can't farm roaches except in extremely specific locations because they get gibbed by the obelisks. Annoying as well

**Comment by DiaFRAME444** [comment]
Maybe Obelisk should require Line of Sight after all.

**Comment by ValoTheValo** [comment]
> Maybe Obelisks should require Line of Sight after all.

Dear lord why do obelisks go through walls

**Comment by ValoTheValo** [comment]
> Make sure to check for roofs and test all the areas in-game. I dunno if it's a good idea to separate chemistry and MBO's office (since you can get into it through maint, but not like it had much security before)

I put some openable shutters in the mbos and chems office on the doors. To keep tiders from smashing them in. Should be abit more secure now

**Comment by ValoTheValo** [comment]
21-Sep-22 13-44-15

**Comment by ValoTheValo** [comment]
21-Sep-22 13-48-33
Obelisk has been reloacated

**Review by hyperioo — CHANGES_REQUESTED** [review]
You have left the noticeboard in maints (it's not on MBO office side).

Ps: I think the goal was to reduce obelisks performance impact by just checking distance instead of line of sight.

**Comment by ValoTheValo** [comment]
> You have left the noticeboard in maints (it's not on MBO office side).
> 
> Ps: I think the goal was to reduce obelisks performance impact by just checking distance instead of line of sight.

allright just fixed it. havent changed obelisks in this PR. lack code skill to do so.

**Comment by hyperioo** [comment]
Obelisk seems far enough now so some concerns have been adressed. Might need some fine tuning if problems arise during testing.

**Pull request merged**
