### PR TITLE
loot rework optimization.

### PR DESCRIPTION
**Pull request by Evankhell561**
## About The Pull Request

1. Including price in the spawn value calculations made selecting an item to be spawned slower, slowing down the atom subsystem. This pr optimizes the loot rework code to avoid this slowdown.

2. Additionally, it removes a lot of unsorted items from the spawn tables, preventing debug items from appearing unexpectedly.

## Changelog
:cl:
fix: slowdown of the atom subsystem.
tweak: items without any specific tag can no longer be spawned in maint.
tweak: scraps piles no longer guarantee a rare item, instead they guarantee a no junk item.
/:cl:

### CODE REVIEW

**Review by TorinoFermic — APPROVED** [review]

**Review by mattroks101 — APPROVED** [review]

**Comment by Evankhell561** [comment]
update:

_tweak: scraps piles no longer guarantee a rare item, instead they guarantee a no junk item._

**Comment by mattroks101** [comment]
Good to merge yet?

**Comment by Evankhell561** [comment]
> Good to merge yet?

Yes

**Comment by MadmanMartian** [comment]
There's antimatter sections that appear as maint loot. Could you add those to the blacklist?

**Comment by Evankhell561** [comment]
> There's antimatter sections that appear as maint loot. Could you add those to the blacklist?

done

**Comment by Evankhell561** [comment]
:cry:

**Review by TorinoFermic — APPROVED** [review]

**Pull request merged**
