### PR TITLE
Unnerfing stungloves.

### PR DESCRIPTION
**Pull request by SpadesSlick**
Looks like this last nerf was too much.

### CODE REVIEW

**Comment by Pariah919** [comment]
There's a good reason I'd argue why they were nerfed to being 30. The fact they dealt 50 agony is quite hilarious considering they STACK with pulled punches and intents like grab. Having batons deal more agony makes sense and gives them a purpose while considering that I've had times playing where IH literally ignored my laser/gunshots and fucking stungloved me in the face with 90 agony (or 60 if they don't know to aim for head) has been quite a few times. Though negativity bias.
I'd say 35 or 40 is a better number than 50.

**Comment by SpadesSlick** [comment]
Then stacking should be removed.

I have no intentions of giving batons any purpose, they just there for the sake of filling up the armoury. What IH need is a melee weapon that can give them any reason to go to melee combat, because of how much ranged options they have.

**Comment by Stealthkibbler** [comment]
Batons are also able to crack airlocks open pretty quickly, so their use extends past actual combat, not to mention because of the agony they do, when used as a harmbaton against roaches they kill them extremely fast.

**Comment by TorinoFermic** [comment]
It turns out the stunbaton's stun var is too high and might be removed while keeping the agony intact.

**Pull request merged**
