### PR TITLE
Cleans up body organ scan code

### PR DESCRIPTION
**Pull request by vode-code**
## About The Pull Request
This PR makes the external and internal organ parts of body scans use an other_wounds list instead of a lot of variables, set a variable for unknown body instead of add to it since it's only used in a boolean format, and do nothing on the infection switch if there is no significant infection instead of going through all of it.

## Why It's Good For The Game
It looked bad previously, and this should decrease lag a tiny bit, although I haven't tested.

## Changelog
:cl: Chickenish
refactor: refactored some body scanner code, this should also make it look cleaner.
/:cl:

### CODE REVIEW

**Comment by Firefox13** [comment]
> although I haven't tested.

Did you just admit that you didn't test your own code? изображение

**Comment by drexample** [comment]
> although I haven't tested.

Then go and test it.

**Comment by GrayRachnid** [comment]
I think he means the lag part

**Comment by vode-code** [comment]
I did in fact mean the lag part, I have gameplay tested all my code, I did not bother to use the profiler however.

**Review by Firefox13 — APPROVED** [review]

**Pull request merged**
