### PR TITLE
Music for spawning Serbs

### PR DESCRIPTION
**Pull request by SirRichardFrancis**
## About The Pull Request

Added previously unused sound from assets_storage, it plays for Serb antagonist at spawn.
Link to storage - https://discord.com/channels/255035529085583360/501814371081650176/863040172219826197

## Why It's Good For The Game

looks like a nice addition
## Changelog
:cl:
soundadd: Serbs now going to hear some music at spawn
/:cl:

### CODE REVIEW

**Comment by TheShown911** [comment]
What's the license on this music?

**Comment by SirRichardFrancis** [comment]
> What's the license on this music?

That's derivative work made by one of Eris players, based on Just Cause 2 (11 years old game) soundtrack, on which I found no license information, looks like there is none. 
Soundtrack itself was distributed for free on developers website, and track used 
was changed beyond recognition.
Here is the original, if you want to compare: https://youtu.be/K6RVTOYgdK4

**Comment by drexample** [comment]
I ain't sure it's good for fair use

**Comment by SirRichardFrancis** [comment]
> I ain't sure it's good for fair use

You gotta be kidding me

**Comment by SirRichardFrancis** [comment]
Okay, here's the thing. Those tracks (source material and final work) is distinct, just listen to them. If not for author mentioning what inspired him - nobody would recognize the similarity, ever.
Furthermore - we use music that is copyrighted for sure, look at the jukebox

**Comment by drexample** [comment]
> Okay, here's the thing. Those tracks (source material and final work) is distinct, just listen to them. If not for author mentioning what inspired him - nobody would recognize the similarity, ever.
> Furthermore - we use music that is copyrighted for sure, look at the jukebox

Jukebox uses links from a third party server to stream music directly to your client. We do not store any copyrighter material on our machine or in the repository, not causing any violations. This puts a file of possibly copyrighted material onto our official repo, making us possible eligible for takedown notice.

**Comment by SirRichardFrancis** [comment]
> Jukebox uses links from a third party server to stream music directly to your client. We do not store any copyrighter material on our machine or in the repository, not causing any violations. This puts a file of possibly copyrighted material onto our official repo, making us possibly eligible for takedown notice.

Takedown notice by who exactly? I say it's original work of Kegdo, who even would came and look for it? As for that song mentioned before, similarity is too elusive

**Comment by drexample** [comment]
My dude, SS13 is a boiling pot of unnecessary drama and github (alongside with most modern age companies) have almost knee-jerk level of treatment towards even remote copyright infringements. People can report us and github will have to take a look. I'd rather be safe than spend a week recovering our repo. Either prove this is legally fine or find something original. You yourself said it's based on a game OST.

**Comment by SirRichardFrancis** [comment]
Prove how? "Derivative work" is a thing, and that is clearly our case. What you expect me to do? Hire a lawyer?

**Comment by drexample** [comment]
If you integrate it into jukebox system, I'll gladly accept it, otherwise I'd like to hear what Firefox thinks

**Comment by Firefox13** [comment]
Better safe than sorry. While deriative work is a thing we cannot guarantee we won't get an e-mail for a copyright takedown(as you couldn't find what license it uses).

**Comment by SirRichardFrancis** [comment]
Because there's hardly any info about it, maybe I'm just looking wrong, dunno.
I understand your point, but it's really paranoid, that not even _the_ soundtrack from a game, just a very remote derivative. No way an algorithm would recognize it.
Is there any possibility of putting this in the game in some safe way?
I only care because this tune really belongs here, but realization via jukebox is above my capabilities right now, took me 2 hours staring at the code to figure out how to make this PR.
And I have no idea how it's all function server-side with jukebox.

**Comment by drexample** [comment]
> Because there's hardly any info about it, maybe I'm just looking wrong, dunno.
> I understand your point, but it's really paranoid, that not even _the_ soundtrack from a game, just a very remote derivative. No way an algorithm would recognize it.
> Is there any possibility of putting this in the game in some safe way?
> I only care because this tune really belongs here, but realization via jukebox is above my capabilities right now, took me 2 hours staring at the code to figure out how to put together this PR.
> And I have no idea how it's all function server-side with jukebox.

Alright, let's do it this way. I'll integrate it into the jukebox and credit everyone involved. The sound will be used, but it won't be on our repo. Is that fine?

**Pull request closed without merging**
