### PR TITLE
IronHammer Job Scaling courtesy of /tg/

### PR DESCRIPTION
**Pull request by Kurgis**
Effectively ports code which was moved in: tgstation/tgstation/pull/6706

## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>
Ironhammer job now scales based on a set config number, so you can control how many Operatives you want in a round based upon the amount of players in lobby, based off the minimum amount set in their job file.

	
<hr>
</details>

### CODE REVIEW

**Comment by Kurgis** [comment]
SahQO YOLOS
> @Kurgis please don't use magical numbers, i mean e.g. number 6 in your cycle and few places in if(), use defines at least, remove one left //jobDebug, don,t be Nanako
and if you fucked up default numbers why do you write "set 0 to use defaults" if they are nerfed in half  without mentioning
imo 4 1 1 operatibes are not enough  to defend Eris from crew and critters, but actually who cares

**Comment by Kurgis** [comment]
Ready for review.

**Comment by Kurgis** [comment]
Do not merge, holding for a map change in case there's conflicts.

**Comment by Kurgis** [comment]
Actually this didn't use mapmerge, so it will without a doubt cause conflicts, will fix after #4013 is reviewed.

**Comment by Kurgis** [comment]
Travis flip.

**Comment by Kurgis** [comment]
This appears to of merged successfully without conflicts after viewing the map file. Ready for review.

**Comment by SpadesSlick** [comment]
Eris can have a rather long rounds. A short round based /tg/ system will not fit our codebase.

**Pull request closed without merging**
