### PR TITLE
Booze is now much stronger. Liver might go on strike for this...

### LINKED ISSUE #3278: Alcohol is broken
I need to drink more than 10 bottles of tunguska+beer to get fog effect, before it my screen will shake as mad. To lose consciousness i need MORE than all of that.

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request
Almost all boozes have been made **much** stronger

## Details
closes #3278

### CODE REVIEW

**Comment by mattroks101** [comment]
These aren't strong enough to kill you are they?

**Comment by Trilbyspaceclone** [comment]
TGH stat factors in a lot so if your cant hold your booze then just go trash diving for the bobbles to get it up really

**Comment by FrownTown** [comment]
You can’t actually raise toughness that way anymore with the introduction of insight and proper progression mechanics. Also, human bodies don’t vary enough for a threshold dose for one person to be lethal to another barring allergies, so really I’m not sure toughness should have more than a small impact.

**Comment by Stealthkibblers** [comment]
Sometimes your inspiration food/drinks is entirely alcohol so this could be a problem, it feels a bit eh too since alcohol outside of speeding up the process of your inspiration (sometimes) doesn't really have any inherent gameplay bonuses.

**Comment by Stealthkibblers** [comment]
nevermind, a captain did something hilarious by drinking down the entirety of the booze vendor and he only got put unconscious for 2 minutes before getting up to drink more.

[https://cdn.discordapp.com/attachments/277556025039650816/654218474993877002/dreamseeker_yTcQYoMXvf.png](url)

**Comment by FrownTown** [comment]
> nevermind, a captain did something hilarious by drinking down the entirety of the booze vendor and he only got put unconscious for 2 minutes before getting up to drink more.
> 
> dreamseeker_yTcQYoMXvf

Keep in mind that toughness impacts the degree to which alcohol affects you.

**Comment by SpadesSlick** [comment]
Seems fine, the gameplay test will tell us if this needs to be fixed more.

**Pull request merged**
