### PR TITLE
Fixing excelsior left arm sprite

### PR DESCRIPTION
**Pull request by MatejaTadic03**
## About The Pull Request

The excelsior left arm had no sprite. I have added it.

## Why It's Good For The Game

bug bad.

## Changelog
:cl:
fix: left excelsior arm sprite now exists
/:cl:

### CODE REVIEW

**Comment by Firefox13** [comment]
You're converting four-directional sprite into one-directional instead of adding a missing state for the sprite. This isn't going to work...

**Comment by MatejaTadic03** [comment]
> You're converting four-directional sprite into one-directional instead of adding a missing state for the sprite. This isn't going to work...

I tested it, it works.

**Comment by MatejaTadic03** [comment]
> You're converting four-directional sprite into one-directional instead of adding a missing state for the sprite. This isn't going to work...

Fixed it, its 4 directional now.

**Review by TheShown911 — COMMENTED** [review]
What about the female sprite?

**Comment by MatejaTadic03** [comment]
> What about the female sprite?

It's good.

**Review by hyperioo — CHANGES_REQUESTED** [review]
I think it's missing one state for female version

image

**Comment by MatejaTadic03** [comment]
> I think it's missing one state for female version
> 
> image

I fixed it. I noticed that the directions on all excelsior arms sprites were messed up so I fixed them up too. Tested it and it looks good.

**Review by hyperioo — APPROVED** [review]

**Pull request merged**
