### PR TITLE
Neotheology uniform resprite (+ minor OneStar uniform fix)

### PR DESCRIPTION
**Pull request by CeUvi**
## About The Pull Request

Updated Neotheo uniform to fit eris.
nt uniforms

## Why It's Good For The Game

Old sprites looked buff as hell for some reason, also didn't fit with the rest of uniforms such as IH or MoeMed/

## Testing

image

## Changelog
:cl: CeUvi & Valo
imageadd: nt uniforms resprite
imageadd: onestar female uniform fix
/:cl:

### CODE REVIEW

**Comment by CeUvi** [comment]
valo asked me to put his small fix of the onestar female uniform, so our PRs won't conflict
image

**Comment by Firefox13** [comment]
Update the changelog

**Comment by CeUvi** [comment]
done

**Comment by Firefox13** [comment]
OK
Did you test One Star uniform?

**Comment by ValoTheValo** [comment]
> OK Did you test One Star uniform?

I tested it when I did it on my PR and nothing went wrong. Same sprite

**Comment by CeUvi** [comment]
how can i fix failed integration tests

**Review by TheShown911 — APPROVED** [review]

**Pull request merged**
