### PR TITLE
Adds additional icon states to Makarov and Clarissa, removes WT-550.

### PR DESCRIPTION
**Pull request by Kurgis**
Mag, and slide icon states. Makarov sprites taken from Watler's Sprite Dump, Clarissa icon by Jeff, I quickly made the Clarissa mag state in Dream Maker.

clarissa_mag
makarov_mag

Removes the defunct WT-550, replaces what little instances of it there were with the Idaho. Re-named the "saber" icon state to "idaho", and deleted the wt550 icons. Not only is the WT-550 not fit the sprite theme, its role as a gun is covered already by the Idaho, and is redundant. WT also stands for "Ward-Takahashi" as I've learned, a Baylore tidbit.

### CODE REVIEW

**Comment by Kurgis** [comment]
It was better to add the removal alongside this PR for time. Merge the PR primarily with the removal of the WT-550 in mind, if it's closed I can get a new PR up in 2 minutes with just the Makarov and Clarissa sprites.

**Comment by Trilbyspaceclone** [comment]
Top mounted ammo also fits in SMG class pistols. Such as the Molly, and Staylight IH Gun thing that fires 9mms. And do to being around 20 shots per mag made them rather useful for reloading do to small space it took/fitting in more guns. Maybe keep them around?

**Comment by Kurgis** [comment]
If top loaders were to be kept within the game, I'd change it to a separate mag well class, which means that you'd still be unable to use it. While the behavior is certainly useful, it's not intended.

**Comment by Kurgis** [comment]
This is ready for review.

**Pull request merged**
