### PR TITLE
Combat Hardsuit Sprite Update

### PR DESCRIPTION
**Pull request by assortedbeads**
## About The Pull Request
Updates the sprite of the combat hardsuit.

Module Back
Module Ground
Sealed Back
Sealed Front
Sealed Hud
Sealed Side
Unsealed Back
Unsealed Front
Unsealed Hud
Unsealed Side

Spider Rig Side Core
Spider Unsealed Back
Spider Unsealed Front
Spider Unsealed Side
Spider Rig Back Core
Spider Rig Front Edit

## Why It's Good For The Game
Remove the old outdated sprite with a better (?) one

## Testing

Launched the game
Spawned the rig
Put it on
Activated it
Turned around and took pictures of sealed and unsealed states

## Changelog
:cl:
imageadd: replaces all the sprites of the old combat hardsuit
/:cl:

### CODE REVIEW

**Comment by TheShown911** [comment]
Looks kinda weird...

**Comment by SirRichardFrancis** [comment]
> Looks kinda weird...

You prefer the old one? Either way elaborate.

**Comment by TheShown911** [comment]
> > Looks kinda weird...
> 
> You prefer the old one? Either way elaborate.

No, it's just that I think this one looks a bit weird. I can't elaborate as it looks weird, the same way something would taste weird, it's just personal preference.

**Review by Firefox13 — APPROVED** [review]
изображение

**Pull request merged**
