### PR TITLE
Shutter & firelock resprite by CeUVI

### PR DESCRIPTION
**Pull request by githubuser4141**
## About The Pull Request

Changes the icons of emergency firelocks and shutters, also adds a transparent shutter.

## Why It's Good For The Game

Better sprites, more variety.

## Testing

Yes

## Changelog
:cl: Credit to CeUVI
add: Adds a transparent shutter, a shutter that blocks movement but allows air, light and gun flow
imageadd: New shutters
imagedel: Old shutters
/:cl:

### CODE REVIEW

**Comment by Holvr0** [comment]
Add screenshots, please.

**Comment by thevandie** [comment]
Gib image

**Comment by Evie7056** [comment]
icon bot my beloved 
image

**Comment by ValoTheValo** [comment]
image in game plz

**Comment by CeUvi** [comment]
DoorHazard
rapid_pdoor

**Comment by githubuser4141** [comment]
Update, I'm trying to have someone else PR this hopefully it happens soon

**Comment by githubuser4141** [comment]
Okay, this should be moved to https://github.com/discordia-space/CEV-Eris/pull/8355, going to close this

**Pull request closed without merging**
