### PR TITLE
Removes Malfunctioning AI from Roleset

### PR DESCRIPTION
**Pull request by Kurgis**
## About The Pull Request
Removes Malfunctioning AI from the storyteller event pool.

The hardest part of this PR is perhaps this description. To describe to you, in detail, how this roleset is frankly not fun for either the player playing it or the many receiving it. There is no endgame for any AI playing it, besides just waiting for the siege to occur, some even try hiding, but I ask, "for what?" Why do they even attempt to delay? They aren't delaying so they can accomplish their goal or objective, just to remain alive. With this in mind recently the player base for AIs in general has taken a new meta regarding in how to play Malfunctioning AI, and it instead incorporates losing _as the goal._ Realizing that instead they can achieve gratification by killing as many players as possible by self-destructing once they're inevitably overwhelmed. This roleset has remained for years, not even functional, which I believe shows a general disinterest to support it.

## Why It's Good For The Game
We no longer must interrupt our rounds for this fossilized relic to go full Jurassic Park on us _consistently_. If you have Malf AI enabled, and the roleset is called you are essentially guaranteed to be called for roleset. Many players have even, if unintentionally, memorized names and know OOCly that they are going to roll Malf within a specific timeframe of activating.

## Changelog
:cl:
del: Malfunctioning AI has been removed from the storyteller event pool.
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
based PR

**Comment by Humonitarian** [comment]
Super good

Now remove the AI role too

**Comment by pexel5** [comment]
baza

**Comment by Alliostra** [comment]
basado

**Comment by githubuser4141** [comment]
Why not just remove the AI's overly-destructive and nonsensical abilities, e.g. it's 'nuke' ability that force-restarts the round (why an antag would have a OOC ability, what even), and it's ability to magically cause inert machinery (computers, machines, etc..) to explode in a super-blast grenade radius. Without those two abilities it'd be limited to shocking/bolting/depowering doors and causing atmos fires.

**Comment by Iglpigl** [comment]
> Could removing the AI's overly-destructive and nonsensical abilities, e.g. it's 'nuke' ability that force-restarts the round (why an antag would have a OOC ability, what even), and it's ability to magically cause inert machinery (computers, machines, etc..) to explode in a super-blast grenade radius.
> 
> Without those two abilities it'd be limited to shocking/bolting/depowering doors and causing atmos fires. I've never played an AI in any server, but it's fairly enteraining to be on the receiving side (excluding the above-mentioned abilities)

Let me fix that for you:
"Why not just remove AI"

**Comment by MLGTASTICa** [comment]
remove borer when?

**Comment by ValoTheValo** [comment]
based PR

**Review by SirRichardFrancis — APPROVED** [review]
Might as well remove all of the related code, instead of leaving it in limbo.

> head admin approved

Muh N.A.P.

https://user-images.githubusercontent.com/65828539/202062713-79c76843-6bb8-41be-9cdb-5537ba1c81ea.mp4

**Comment by TheShown911** [comment]
Now remove the AI, and borgs too.

**Comment by Kurgis** [comment]
#7809 should of closed this when merged, forgot to put the keywords in to the descriptions.

**Pull request closed without merging**
