### PR TITLE
Add TGS4 Code Support

### PR DESCRIPTION
**Pull request by BASIC-BIT**

### CODE REVIEW

**Comment by SpadesSlick** [comment]
But... Why?

**Comment by ACCount12** [comment]
fucking why

**Comment by Kmc2000** [comment]
DON'T DO IT TGS4 IS A TRAP
https://www.youtube.com/watch?v=I0AxrOUJ62E

**Comment by ACCount12** [comment]
This would not be merged without further discussion. Contact me on Discord and explain the "why" of it.

**Comment by BASIC-BIT** [comment]
My mistake, this was intended to be a PR to my personal branch!  Whoops!

**Pull request closed without merging**
