### PR TITLE
Armour adjustments, additions, fixes and general slowdown reduction 

### PR DESCRIPTION
**Pull request by Jackofashepard**
In summary SCAF and BP vest protection was reduced, armours had their slowdowns lowered universally. In other words if it was slow, it is still slow compared to everything else unless it does not have the armour to make it worth it or sensible.

### CODE REVIEW

**Comment by ACCount12** [comment]
You are doing the same thing Clock explictly told you not to do, again. You cut all those numbers by about 3 times, which is way too much.

**Comment by Jackofashepard** [comment]
In summary SCAF and BP vest protection was reduced, armours had their slowdowns lowered universally. In other words if it was slow, it is still slow compared to everything else unless it does not have the armour to make it worth it or sensible.

**Comment by Jackofashepard** [comment]
Few more armour values adjusted

**Comment by Kurgis** [comment]
You're going to need a better editor to do this, you're missing a lot of values.

**Comment by Pariah919** [comment]
SCAF is fine where it is honestly in my opinion. It's a tank suit. It should stay that way until further notice because as serbs otherwise you'll almost never get the ability to recover anyway.

**Comment by Jackofashepard** [comment]
- All voidsuits have flash protection now

- Antag armour (excel and antag) buffed, uplink price also adjusted

- Added the heavy armour helmet to the uplink 

- Armours with silly large armour values have had it reduced 

- Slowdown on voidsuits and armours has been reduced overall (if it was slow its still slow by the new standards except for armours that have armour/lack of armour to justify a speedup/slowdown)

**Pull request merged**
