### PR TITLE
Vagabonds now can change "name" of his "job"

### PR DESCRIPTION
**Pull request by AlexMorgan3817**
## About The Pull Request
<details><summary>Vagabonds now can change "name" of his "job"</summary>
<hr>Just a syndiscum card for vagabonds<hr></details>

## Changelog
:cl:
tweak: Vagabonds now can change "name" of his "job"
/:cl:

### CODE REVIEW

**Comment by AlexMorgan3817** [comment]
R4R

**Comment by ACCount12** [comment]
Those tabs - why, just why? We normally only tab out the defines and the comments.

**Comment by AlexMorgan3817** [comment]
> Those tabs - why, just why? We normally only tab out the defines and the comments.

Cuz it fancy and have autoleveling

**Comment by SpadesSlick** [comment]
image
image

**Pull request merged**
