### PR TITLE
Sprite change for Himan

### PR DESCRIPTION
**Pull request by Wouju**
## About The Pull Request
Epic sprite change electric boogalo Eris med part 5 not clickbait
(I woke up at 2am in cold sweat to realize I could have done this months ago instead of the gnome)

Changes himan dead sprite from this: 
image
image
image
image
(in descending order, South, West, North, East)

To this obviously much better sprite:
image
image
image
image

## Why It's Good For The Game

Old sprite looks like a dumbass gnome and I hate myself for making it, this looks way better

## Changelog
:cl:
imageadd: replaced old himan dead sprite with a new one (more horizontal, less gnomey)
/:cl:

### CODE REVIEW

**Comment by TheShown911** [comment]
Who are you?

**Comment by Wouju** [comment]
> Who are you?

I dont know

**Comment by Fatherperhaps** [comment]
very cool

**Comment by Wouju** [comment]
4 successful and 1 failing checks my beloved

**Comment by Humonitarian** [comment]
Someone stole the Fourth Section Deck 1 Port Maintenance APC

Can't have shit on Erks

**Comment by hyperioo** [comment]
See #6020 for PR that introduced the gnome

**Review by hyperioo — APPROVED** [review]
If you're not satisfied with your sprite, this will free you

**Pull request merged**
