### PR TITLE
Wielding Update

### PR DESCRIPTION
**Pull request by mattroks101**
## About The Pull Request

**Wielding is here!** All items can now be wielded. You have to wield them manually, either by using the UI button, or the hotkey (currently SHIFT+X). The item is unwielded when you: drop it, equip it, click on the wield HUD icon, or use the wield hotkey again.

Items wielded can do 30% more damage when wielded in both hands, at the cost of not being able to use your other hand. Items that do no damage will still do no damage wielded though. This number can be changed to whatever you guys thing is the most balanced.

Guns are treated specially. If the `one_hand_penalty` var is set, then the amount of recoil you have will be increased by the var every time the gun is shot without being wielded. See the combat shotgun as an example.

This also adds the item flag `ABSTRACT`. You cannot attack things or otherwise interact anything using an item that has this flag.

**TODO:**
- ~~While not necessary, inhands for wielded rifles and shotguns would look really nice.~~
- ~~One hand penalties need to be decided for automatic weapons. Five is a good baseline but we should figure out if we want to increase it or decrease it.~~
- A new sprite is needed for the HUD icon. The one I have is something I made in two seconds as a placeholder.

## Screenshots

<details>
  <summary>Expand</summary>
Holding a shotgun in both hands using the sprite of another gun that looks like it was already held in both hands. Please god we need a better HUD button.

dreamseeker_8D0HvtQUnt

If you're wielding something in both hands it will say you're holding it in your hands.
dreamseeker_Dur00ZmUaX
</details>

### CODE REVIEW

**Comment by mattroks101** [comment]
Reere wants me to do one more thing but other than that this is done.

**Comment by mattroks101** [comment]
Reere's request has too much that isn't related to this base wielding system. This is ready for review now.

**Comment by TorinoFermic** [comment]
Dual wield seems to be working but also causes boxes to be dual wielded and is impossible to be stored in backpacks or place on a table except when thrown.

This screenshot shows the captain dual wielding the box of spare ids.
dreamseeker_2020-01-05_13-09-46

**Comment by mattroks101** [comment]
Storage items are now fixed.

**Comment by mattroks101** [comment]
Also in case anyone stumbles upon this PR,

`The wintermute does not have the dual wield icon, I had to dual wield via SHIFT+X`
This is not a bug, this is how the system works. Wielding weapons manually is how it's supposed to work.

**Comment by TorinoFermic** [comment]
Actually, I couldn't find the dual wield icon at the start of testing but I know where is.
Should we redefine the sprite for this button ?

**Comment by mattroks101** [comment]
It really needs a professional sprite. The button I have is a coder sprite I made.

**Pull request merged**
