### PR TITLE
[Paid code] TGUI port (includes refactoriong half the coderbase)

### PR DESCRIPTION
**Pull request by LetterN**
## About The Pull Request
ports tgui + tools for frictionless devving

## Why It's Good For The Game
mmm yes fast ui 🐒 

## Changelog
:cl:
add: TGUI
del: Half? Of nanoui
code: Updated the MC and it's friends
code: Asset cache, now with 50% less lag** (**not guaranteed)
code: Better map merge! Now everyone can edit the map at the same time
code: rust-g suite! Now you can have procedural lavaland, and faster file io
/:cl:

~~# THIS REMOVES TRAVIS, TURN IT OFF AND USE GITHUB WORKERS~~
# ON HOLD UNTIL https://github.com/discordia-space/CEV-Eris/pull/6366 GETS MERGED

### CODE REVIEW

**Comment by drexample** [comment]
>


<div class="TimelineItem pt-0 js-comment-container js-socket-channel js-updatable-content" data-gid="MDExOlB1bGxSZXF1ZXN0NjU3NTY5ODY3" data-url="/_render_node/MDExOlB1bGxSZXF1ZXN0NjU3NTY5ODY3/pull_requests/body?variables%5BdeferredCommentActions%5D=false" data-channel="eyJjIjoicHVsbF9yZXF1ZXN0OjY1NzU2OTg2NyIsInQiOjE2MjIzMzk2MDR9--f3d9f680f56387a6a6b15f5e59b8411c3c3ea9f493ba160dbf3bdf5a42b8b5be" style="box-sizing: border-box; padding: 16px 0px; position: relative; display: flex; margin-left: 16px; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class=" timeline-comment-group js-minimizable-comment-group js-targetable-element TimelineItem-body my-0 " id="issue-657569867" style="box-sizing: border-box; margin-top: 4px; margin-bottom: 0px !important; min-width: 0px; max-width: 100%; color: var(--color-timeline-text); flex: 1 1 auto;"><div class="ml-n3 timeline-comment unminimized-comment comment previewable-edit js-task-list-container editable-comment js-comment timeline-comment--caret reorderable-task-lists" data-body-version="15fc37a2a9e08bf30f2ffead99ad5ccbb414d7087478607689325c14a765c9ea" data-unfurl-hide-url="/content_reference_attachments/hide" style="box-sizing: border-box; margin-left: -16px !important; position: relative; color: var(--color-text-primary); background-color: var(--color-bg-primary); border: 1px solid var(--color-border-primary); border-radius: 6px;"><div class="edit-comment-hide" style="box-sizing: border-box;"><task-lists sortable="" style="box-sizing: border-box;">THIS REMOVES TRAVIS, TURN IT OFF AND USE GITHUB WORKERS</task-lists></div><form class="js-comment-update" id="issue-657569867-edit-form" action="https://github.com/discordia-space/CEV-Eris/issues/6277" accept-charset="UTF-8" method="post" style="box-sizing: border-box;"></form></div></div></div><div id="js-timeline-progressive-loader" data-timeline-item-src="discordia-space/CEV-Eris/timeline?id=MDExOlB1bGxSZXF1ZXN0NjU3NTY5ODY3&amp;variables%5Bafter%5D=Y3Vyc29yOnYyOpPPAAABebr1jEgBqjQ4MTY2MDk0MjA%3D&amp;variables%5Bfirst%5D=60" style="box-sizing: border-box; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></div><div class="js-timeline-item js-timeline-progressive-focus-container" data-gid="MDE3OlB1bGxSZXF1ZXN0Q29tbWl0NjU3NTY5ODY3OmQxNGE3OTM2MDExMmZkZDJhZGU4ZDkzYzc3NWZkZDc1YzExMWRkZGU=" style="box-sizing: border-box; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="js-commit-group" style="box-sizing: border-box;"><div class="js-commit-group-commits" style="box-sizing: border-box;"><div class="TimelineItem TimelineItem--condensed js-commit py-3" style="box-sizing: border-box; padding: 4px 0px 16px; position: relative; display: flex; margin-left: 16px;"><div class="TimelineItem-badge" style="box-sizing: border-box; position: relative; z-index: 1; display: flex; width: 32px; height: 16px; margin: 8px 8px 8px -15px; color: var(--color-icon-secondary); align-items: center; background-color: var(--color-bg-canvas); border: 0px; border-radius: 50%; justify-content: center; flex-shrink: 0;"><svg aria-hidden="true" viewBox="0 0 16 16" version="1.1" data-view-component="true" height="16" width="16" class="octicon octicon-git-commit"><path fill-rule="evenodd" d="M10.5 7.75a2.5 2.5 0 11-5 0 2.5 2.5 0 015 0zm1.43.75a4.002 4.002 0 01-7.86 0H.75a.75.75 0 110-1.5h3.32a4.001 4.001 0 017.86 0h3.32a.75.75 0 110 1.5h-3.32z"></path></svg></div><div class="TimelineItem-body" style="box-sizing: border-box; min-width: 0px; max-width: 100%; margin-top: 4px; color: var(--color-timeline-text); flex: 1 1 auto;"><div class="js-details-container Details js-socket-channel js-updatable-content" data-channel="eyJjIjoicmVwbzo1MTc1MTYxNTpjb21taXQ6ZDE0YTc5MzYwMTEyZmRkMmFkZThkOTNjNzc1ZmRkNzVjMTExZGRkZSIsInQiOjE2MjIzMzk2MzN9--22e81453868e3a9838ce0dd511eb9b8b8d9922d9b2a1ac77a045dec27840379b" data-url="/discordia-space/CEV-Eris/pull/6277/commits/d14a79360112fdd2ade8d93c775fdd75c111ddde/_render_node/commit/pull_condensed" style="box-sizing: border-box;"><div class="d-flex " style="box-sizing: border-box; display: flex !important;"><div class="AvatarStack flex-self-start " style="box-sizing: border-box; align-self: flex-start !important; position: relative; min-width: 26px; height: 20px;"><div class="AvatarStack-body" aria-label="LetterN" style="box-sizing: border-box; display: flex; background-image: ; background-position-x: ; background-position-y: ; background-size: ; background-repeat-x: ; background-repeat-y: ; background-attachment: ; background-origin: ; background-clip: ; background-color: initial; position: absolute;"><a class="avatar avatar-user" data-skip-pjax="true" data-hovercard-type="user" data-hovercard-url="/users/LetterN/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/LetterN" style="box-sizing: initial; background-color: var(--color-bg-canvas); color: var(--color-text-link); text-decoration: none; display: flex; overflow: hidden; line-height: 1; vertical-align: middle; border-radius: 4px; flex-shrink: 0; box-shadow: 0 0 0 1px var(--color-avatar-border); position: relative; z-index: 1; width: 20px; height: 20px; margin-right: -11px; border-right: 0px; transition: margin 0.1s ease-in-out 0s;"></a></div></div></div></div></div></div></div></div></div><br class="Apple-interchange-newline">

based

**Comment by Hatterhat** [comment]
deranged

**Comment by TheShown911** [comment]
Is this ready for review? Also got *a few* conflicts.

**Comment by mattroks101** [comment]
Any update on this? Any chance of fixing the conflicts?

**Comment by ChungusGamer666** [comment]
this is one of the PRs of all time

**Comment by mattroks101** [comment]
> Any update on this? Any chance of fixing the conflicts?

**Comment by Doster-d** [comment]
Please add last optimization commit that disable force auto update windows, thanks.

**Comment by LetterN** [comment]
moved to https://github.com/discordia-space/CEV-Eris/pull/6464 (part 1)

**Pull request closed without merging**
