### PR TITLE
Grenade launchers

### PR DESCRIPTION
**Pull request by SirRichardFrancis**
## About The Pull Request

This PR makes all grenade launchers use special grenades, instead of hand grenades.

image

Added grenade boxes, each containing 6 grenades.
Rubber rounds - cost 6 TC in uplink, 3 boxes in the armory
EMP grenades - cost 12 TC in uplink
Frag grenades - cost 12 TC in uplink, 1 box in the armory
Blast grenades - cost 18 TC in uplink

## Why It's Good For The Game

Using hand grenades in grenade launcher makes no sense.

## Changelog
:cl:
add: grenade launcher ammunition to uplink
add: basic grenade launcher ammunition in the armory
tweak: grenade launchers use specialized ammo instead of hand grenades
/:cl:

### CODE REVIEW

**Comment by thedarkcrusader** [comment]
Hey hold on

**Comment by thedarkcrusader** [comment]
Nevermind merge please

**Comment by drexample** [comment]
That's fair, but we should probably have a version that works with normal grenades in the futuer.

**Review by drexample — APPROVED** [review]

**Comment by Jan-Blasiak** [comment]
Fucking finally, I've been promoting that idea for over a year, good work.

**Pull request merged**
