### PR TITLE
Adds IH AK to IH

### PR DESCRIPTION
**Pull request by Jackofashepard**
## About The Pull Request

Adds 4 IH AKs to IH and 9 mags (2 for each gun and one extra). Moved slugs to crate and the mags are in there too.
image

## Why It's Good For The Game

Surprise surprise its me with yet another IH PR, i know i know my bias is showing! Just adds another gun thats a nice middle between sol and takeshi. Besides this gun quite literally has IH print on it, its destiny.

## Changelog
:cl:
add: Added IH AK and mags to IH.
tweak: Moved slugs to crate in armoury.
/:cl:

### CODE REVIEW

**Comment by CeUvi** [comment]
why
ih already has sols, wintermutes and takeshis
why do they need even more guns

**Comment by TheShown911** [comment]
No

**Comment by Jackofashepard** [comment]
Understandable, have a good day

**Comment by Jackofashepard** [comment]
Making a new one for armoury as a whole

**Pull request closed without merging**
