### PR TITLE
Remove spiders toxin addiction chance

### PR DESCRIPTION
**Pull request by Firefox13**
## About The Pull Request

This PR sets `addiction_chance` to 0 for Pararein and Aranecolmin. It also fixed a lowercase.

## Why It's Good For The Game

These toxins already destroy your sanity and getting *addicted* to spider bites is something really stupid.

## Changelog
:cl:
balance: You cannot get addicted to spider toxins (Pararein and Aranecolmin) anymore.
/:cl:

### CODE REVIEW

**Review by SirRichardFrancis — APPROVED** [review]

**Comment by SirRichardFrancis** [comment]
Until local punks are able to suck pararein directly from spiders, that argument is mute.

**Comment by SirRichardFrancis** [comment]
Not to mention that for maintaining pararein addiction one should have bidon of anti-toxin on hand.

**Comment by garrulousTeamotei** [comment]
You can buy full bottles of spider chems from the Guild, in the least.

**Comment by TheShown911** [comment]
Soulless.

**Review by hyperioo — APPROVED** [review]

**Comment by hyperioo** [comment]
I guess if the Great Leader wants it.

**Pull request merged**
