### PR TITLE
glasses again (and bottles)

### PR DESCRIPTION
**Pull request by CeUvi**
## About The Pull Request
updates glasses sprites and reagentfillings (which kirov was too lazy to add)

## Why It's Good For The Game
new sprets good
also drinks would not look so "melted plastic"-y anymore.

## Changelog
:cl: CeUvi, WalterJe
imageadd: updated some glasses and reagent filling states
/:cl:

### CODE REVIEW

**Comment by CeUvi** [comment]
> This PR only removes filling states, not adds.

image
ok?


> Drinks looked like molten plastic with changes you proposed, and that's why I didn't add it.

they look like molten plastic now, and they'll look less like molten plastic after this PR is merged.

**Comment by SirRichardFrancis** [comment]
> ok?

image
Not ok.

> they look like molten plastic now, and they'll look less like molten plastic after this PR is merged.

Bring proofs.

**Comment by CeUvi** [comment]
> Not ok.

it didn't look like the mug is half full so i deleted it.


> Bring proofs.

new:
image
old:
image

**Comment by SirRichardFrancis** [comment]
> it didn't look like the mug is half full so i deleted it.

It did. There isn't many ways to make filling states for 7x12 pixel non-transparent mug.

> new:
> old:

How it that proving "they look like molten plastic now, and they'll look less like molten plastic after this PR is merged." statement?
Bring screenshots from the game, before and after.

**Comment by MLGTASTICa** [comment]
> > it didn't look like the mug is half full so i deleted it.
> 
> It did. There isn't many ways to make filling states for 7x12 pixel non-transparent mug.
> 
> > new:
> > old:
> 
> How it that proving "they look like molten plastic now, and they'll look less like molten plastic after this PR is merged." statement?
> Bring screenshots from the game, before and after.

you can actually see the bottom of the glass , just like how you can see through most drinks

**Comment by CeUvi** [comment]
> It did. There isn't many ways to make filling states for 7x12 pixel non-transparent mug.

let me post it again
image



> Bring screenshots from the game, before and after.

can't, it's too much cbt

**Comment by SirRichardFrancis** [comment]
> you can actually see the bottom of the glass , just like how you can see through most drinks

You can already. Changes in this PR only makes glass bottom to stand out a lot.
Imo that makes otherwise good sprites to look silly.
image

> can't, it's too much cbt

CeUvi be like:
>lies in PR description and changelog to make his shit merged
>no screenshots for sprite changing PR
nepravda

**Comment by CeUvi** [comment]
> You can already. Changes in this PR only makes glass bottom to stand out a lot.
> Imo that makes otherwise good sprites to look silly.

you fool, it's a wrong sprite


> lies in PR description and changelog to get his shit merged
ну и в каком месте я врал бля

**Comment by SirRichardFrancis** [comment]
> ну и в каком месте я врал бля

Ну давай разберем по частям тобою написанное


> updates glasses sprites and reagentfillings (that kirov forgot to add)

Я тебе прямо сказал что не менял спрайты оверлеев из-за того что они говно, хули ты пиздишь-то блять

> also drinks would not look so "melted plastic"-y anymore.

Для напитков не изменилось ничего, они не выглядят пластиковыми потому что я им всем альфу задал, а ты блять дно стакана рисуешь поверх напитка

> imageadd: added some glasses and reagent filling states

Нихуя ты не добавил, наоборот удалил

**Comment by CeUvi** [comment]
> Я тебе прямо сказал что не менял спрайты оверлеев из-за того что они говно, хули ты пиздишь-то блять

ладно, сейчас исправлю на "СПРАЙТЫ, КОТОРЫЕ КИРОВ ПОЛЕНИЛСЯ ДОБАВИТЬ", думаю станет лучше


> дно стакана рисуешь поверх напитка

конкретно кринжанул так


> Нихуя ты не добавил, наоборот удалил

плачь об этом

**Comment by SirRichardFrancis** [comment]
> ладно, сейчас исправлю на "СПРАЙТЫ, КОТОРЫЕ КИРОВ ПОЛЕНИЛСЯ ДОБАВИТЬ", думаю станет лучше

Не поленился, а не хотел быть причастным к добавлению этой шляпы.

> конкретно кринжанул так

Это я от твоих изменений кринжанул, нормально же получились спрайты в первый раз

> плачь об этом

Здравая реакция на критику, снежиночка ты наша особенная.

> тут я в общем могу сказать только то, что кирова очень расстроило удаление ЧЕТЫРЁХ пикселей и небольшое несоответствие в описании пра

_Небольшое несоответствие?_ Единственная строчка без пиздежа это "new sprets good", и то криво написано.

**Comment by CeUvi** [comment]
> Это я от твоих изменений кринжанул, нормально же получились спрайты в первый раз

игроков опрашивал, я полагаю?


> Здравая реакция на критику, снежиночка ты наша особенная.

бро ты до меня доебался снихуя, че мне ещё тебе отвечать


> криво написано

фича

**Comment by SirRichardFrancis** [comment]
image

**Comment by Alliostra** [comment]
shut up kirov (not Ceuvis alt)

**Comment by CeUvi** [comment]
image
new bottles pogchamp

**Comment by Omni44** [comment]
I don't know what you guys are having in your local stores, but I don't think vodka is supposed to be navy blue it is now, and overall these colors we have now are all over the place, can you fix it up a bit, k, thx.

**Comment by CeUvi** [comment]
> vodka is supposed to be navy blue

we're russians, we know better

**Comment by Omni44** [comment]
> we're russians, we know better
Fancy you say that, having neither made it first (according to written sources), and certainly not the best (according to everyone).

**Comment by CeUvi** [comment]
we drink more

**Comment by Humonitarian** [comment]
ZUBROWKA_BIALA_700ml 1
A beautifully navy blue vodka

**Comment by TheShown911** [comment]
I don't know Russian, nor am I an alcoholic so I won't be reviewing this.

**Comment by CeUvi** [comment]
блять

**Review by hyperioo — APPROVED** [review]
Code looks good. Trusting you that the dmis are well made.

**Pull request merged**
