### PR TITLE
Funeral ejector

### PR DESCRIPTION
**Pull request by SingingSpock**
Adds a disposal for NT to commit bodies to space. Also adds a basic air system to the NT disposal sorting area

## About The Pull Request

Adds a disposal to space for NT to use to commit coffins to the depths of space, which then allows the players inside to get the high tier respawn buff.
image

## Why It's Good For The Game

This is in the Preacher job description and all the code to support this still exists, there just wasn't a mapped space to actually do it. (I was told it got overlooked in a NT remap) This allows NT to perform another service for nonbelievers and enables the RP of a funeral and burial in space (which most will probably ignore in favor of the meager biomatter from putting a body in there, but oh well).

## Testing

Went into the room, checked the APC and Air Alarm are functioning properly, checked the conveyor is working properly, spaced myself to make sure I got ejected into the depths properly.

## Changelog
:cl: SingingSpock
add: funeral disposal for NT to use.
/:cl:

### CODE REVIEW

**Comment by DiaFRAME444** [comment]
Spacing a body instead of melting it for biomatter? Not in a thousand years.

**Comment by tristain01** [comment]
It would be nice to give RP funerals instead of just toss someone in a slab and fucking off

**Comment by garrulousTeamotei** [comment]
The thing is already in maintenance, so it's not like it's designed for a public ceremony, more like for the after-ceremony. At that point, if it's a problem of body disposal, there is the wonderful Bioreactor

**Comment by SingingSpock** [comment]
> The thing is already in maintenance, so it's not like it's designed for a public ceremony, more like for the after-ceremony. At that point, if it's a problem of body disposal, there is the wonderful Bioreactor

It's for the final sending-off, after you do something in the main church yes. But sending someone to space gives them a better reduction on their respawn time than sending them to the biomatter/morgue. It may be necessary to do something that motivates NT to actually do this for nonbelievers (maybe Eye energy), but that's outside the scope of this PR. This is to make it possible for the people like myself and a couple others who *will* do the RP and burial in space the actual mechanical opportunity to do so.

**Comment by DiaFRAME444** [comment]
I would prefer if melted bodies got a respawn time reduction.

**Comment by thevandie** [comment]
> I would prefer if melted bodies got a respawn time reduction.

That just sounds lazy? If anything the biogen should give LESS than the morgue, because you're just chucking a body into the trash machine, as opposed to the morgue which is dedicated for that purpose.

**Comment by DiaFRAME444** [comment]
I would prefer to not set someone's respawn timer 10 minutes longer because I decide to melt them and not destroy them to get 500 biomass per corpse.

I'm gonna go for the 500 biomass per corpse deal regardless of course, but I'll feel some distant, vague sadness on the back of my head over the respawn time.

> you're just chucking a body into the trash machine, as opposed to the morgue which is dedicated for that purpose.

What? Melting corpses is one of the biogenerator's main purposes.

**Comment by SingingSpock** [comment]
Again, this isn't adding anything new regarding respawn timers. You can put a body in a coffin and space it through an airlock and it'll give the bonus. This just gives NT a room to do it in.

**Comment by Alliostra** [comment]
Just make the ejected coffin fly right back to the other side of the ship, through a secret network of chutes and pipes and into the bioreactor. The "space burial" is just for Public relations, no biomatter is lost.

**Comment by Mycah142** [comment]
> Just make the ejected coffin fly right back to the other side of the ship, through a secret network of chutes and pipes and into the bioreactor. The "space burial" is just for Public relations, no biomatter is lost.

This is straight up the funniest shit I've read in a long time. The imagery is akin to the Complaints Department fax machine feeding right into a paper shredder. Peak NeoTheology.

**Comment by Pink-Chink** [comment]
image

**Review by hyperioo — CHANGES_REQUESTED** [review]
Fix duplicate APC

**Comment by SingingSpock** [comment]
> Fix duplicate APC

Should be fixed, but I have no clue how to get the proper CI suite to run again

**Comment by Pink-Chink** [comment]
image
Looks like your latest commit took away the catwalk. Otherwise, looks good to go. I'll merge it when it's ready.

**Comment by SingingSpock** [comment]
I also added a basic air system to the disposal room and made it its own area.
image

**Review by hyperioo — APPROVED** [review]

**Pull request merged**
