### PR TITLE
Recooked Silencer Icon

### PR DESCRIPTION
**Pull request by Kurgis**
Replaces & deletes old icon.

Silencers
Left to right: Old sprite, Watler's sprite, and a recook of the old one.

### CODE REVIEW

**Comment by drexample** [comment]
New icon looks far worse than the old one. 
It's either replacing it with something better or closing the PR.

**Comment by Kurgis** [comment]
@drexample Is the "recook" sprite of the old silencer icon acceptable?

**Comment by drexample** [comment]
@Kurgis yes, it does seem to be more fitting, than the old one

**Comment by Kurgis** [comment]
This is ready.

**Pull request merged**
