### PR TITLE
Makes roach taming less shit

### PR DESCRIPTION
**Pull request by Kmc2000**
~~https://gyazo.com/da8060432166ec68940873e0119ab573~~

~~The less we talk about the code, the better~~

NOW WITH 100% LESS SHITCODE!!!!
https://streamable.com/v9l6d

To tame a roach:
Grow ambrosia vulgaris, or something sugary, drug laden, or vodka filled.
Grow at least 2, if not more!
Make wired rod
Click wired rod with your plant
Go find roach in maint
Hold your plant in ACTIVE HAND
Once you see it hesitate, BUCKLE INTO IT
If successful, the roach will look stoned
To move your new roach, simply hold your plant on a stick out and click where you want the roach to go. WATCH OUT! If you click too much, the roach might eat the plant on a stick.

### CODE REVIEW

**Comment by optimumtact** [comment]
Readd stungloves

**Comment by crossedfall** [comment]
This needs to be speed merged. For the betterment of Eris... No... For the betterment of SS13 this needs immediate implementation.

**Comment by Pariah919** [comment]
Now this is some toptier SHITCODE

**Comment by SpadesSlick** [comment]
it_has_to_die
Do it all properly, or we discarding all roach taming code until proper rework will come up.

**Pull request closed without merging**
