### PR TITLE
Recoil and Armor QoL

### PR DESCRIPTION
**Pull request by Humonitarian**
## About The Pull Request

What it says on the tin. Makes recoil feel better, makes aiming feel better, makes offset less punishing for those with stats. Also a stealth armor buff.

Merging should wait until I had time to test the values with recoil disarms. Anyone is free to test this on local as well.

## Why It's Good For The Game

People complained, I deliver.

## Changelog
:cl:
balance: recoil recovery and recoil from running adjusted
del: removed extra penetration from vigilance
add: vigilance increases accuracy
/:cl:

### CODE REVIEW

**Comment by drexample** [comment]
image

👀

**Comment by Humonitarian** [comment]
> image
> 
> 👀

I already halved them once. This is the final strike.

Stiffness live long!

**Comment by TheShown911** [comment]
Atomize your PRs

**Comment by drexample** [comment]
Atomize your PRs

**Review by drexample — CHANGES_REQUESTED** [review]
Either remove unrelated commit or remake the PR

**Comment by Humonitarian** [comment]
> Either remove unrelated commit or remake the PR

You mean change description?

**Comment by Kegdo** [comment]
eheheheheh atomize your prs

**Comment by hyperioo** [comment]
Merging since I think the commits drexample was talking about with "Either remove unrelated commit or remake the PR" disappeared with your merge commit

**Pull request merged**
