### PR TITLE
solidifier no longer crashes the server.

### PR DESCRIPTION
**Pull request by Evankhell561**
## About The Pull Request

what the title says.

## Why It's Good For The Game
because reasons 

## Changelog
:cl:
fix: solidifier no longer crashes the server.
/:cl:

### CODE REVIEW

**Review by TorinoFermic — APPROVED** [review]

**Comment by TorinoFermic** [comment]
Speedmerge

**Comment by MadmanMartian** [comment]
Going to need you to explain how this fixes the infinite recursion bug before I can trust the PR to speedmerge it.

**Comment by Evankhell561** [comment]
> Going to need you to explain how this fixes the infinite recursion bug before I can trust the PR to speedmerge it.

image

**Comment by Evankhell561** [comment]
> > Going to need you to explain how this fixes the infinite recursion bug before I can trust the PR to speedmerge it.
> 
> image

"diff" can be zero.

**Comment by MadmanMartian** [comment]
So, the issue is it trying to add to a maxed-out stack?

How does this fix that?

**Comment by Evankhell561** [comment]
> So, the issue is it trying to add to a maxed-out stack?
> 
> How does this fix that?

if the biomatter stack is full, then the code will not try to add more biomatter but will create a new stack.

**Comment by MadmanMartian** [comment]
Lovely

**Review by MadmanMartian — APPROVED** [review]

**Pull request merged**
