### PR TITLE
Bots no longer use TTS

### PR DESCRIPTION
**Pull request by Kurgis**
## About The Pull Request
Removes the tts_seed from bots, so they no longer speak.

## Why It's Good For The Game
Removes the tts_seed from bots, so they no longer speak.

## Changelog
:cl:
del: Bots no longer speak using TTS.
/:cl:

### CODE REVIEW

**Review by SirRichardFrancis — COMMENTED** [review]
This PR is:
1) Soulless
2) Removes intended feature
3) Absolutely soulless

**Comment by Holvr0** [comment]
Why remove? Just tank their volume to like 15% of what they currently have, and they won't be as invasive.

**Comment by GrayRachnid** [comment]
i'm like 99.9% sure this will just default them to a human seed

**Comment by Kurgis** [comment]
> i'm like 99.9% sure this will just default them to a human seed

The 0.1% margin is correct, they don't use any seed.

**Comment by Alliostra** [comment]
SOVLLESS

**Comment by SirRichardFrancis** [comment]
> i'm like 99.9% sure this will just default them to a human seed

Can confirm that this is the correct way of removing mob TTS, only humans default to human seeds if they don't have one.

**Comment by TheShown911** [comment]
Soulless x2

**Review by SirRichardFrancis — APPROVED** [review]

**Comment by DiaFRAME444** [comment]
Why not just make bots scream less often

**Comment by Firefox13** [comment]
Closing because #7824 was merged (10% chance to speak)

**Pull request closed without merging**
