### PR TITLE
Make devices have cell support as inherent behavior

### PR DESCRIPTION
**Pull request by Evankhell561**
## Changelog
:cl:
tweak: The projector chameleon now turns off automatically when the battery runs out.
/:cl:

### CODE REVIEW

**Review by genessee596 — CHANGES_REQUESTED** [review]
make changelonge pleez

a better one so people actually know what we added if they can't see devblog

**Comment by Garen7** [comment]
ngl cell behavior should be a component, though this is probably fine

**Comment by Evankhell561** [comment]
> make changelonge pleez
> 
> a better one so people actually know what we added if they can't see devblog

it shouldn't really change anything visible to gamers ... except I think the chameleon projector now automatically shuts off when the battery runs out.

**Comment by genessee596** [comment]
> > make changelonge pleez
> > a better one so people actually know what we added if they can't see devblog
> 
> it shouldn't really change anything visible to gamers ... except I think the chameleon projector now automatically shuts off when the battery runs out.

Can you still please make a changelog? Shouldn't take more than a minute or two tops

**Review by genessee596 — APPROVED** [review]

**Comment by FrownTown** [comment]
This gets rid of cargo cult code. That means it is good. Bless.

**Review by TorinoFermic — APPROVED** [review]

**Comment by genessee596** [comment]
merging since has maint+dele approval

**Pull request merged**
