### PR TITLE
PAYDAY masks and suits to Bill Trustworthy's Discount Guns and Enterprising Detritus

### PR DESCRIPTION
**Pull request by CeUvi**
## About The Pull Request
read the title
payday
(haven't added a suit yet, as this may cause conflicts)
## Why It's Good For The Game
now you can cosplay PAYDAY gang

## Changelog
:cl: CeUvi, WalterJe
imageadd: payday masks
imageadd: payday tuxedo
add: tuxedo to loadout
/:cl:

### CODE REVIEW

**Comment by LagushkaKiller** [comment]
ok and

**Comment by Sparrowbird611** [comment]
You don't think this is a tad expensive for meme clothes? Why not lower the masks a fair bit, to at least slaught-o-matic prices (100), and maybe the suit to 200 at most.

**Comment by CeUvi** [comment]
> You don't think this is a tad expensive for meme clothes? Why not lower the masks a fair bit, to at least slaught-o-matic prices (100), and maybe the suit to 200 at most.
> 
> Also damn we need a clothing vendor.

i think the prices are totally fine

**Comment by Sparrowbird611** [comment]
> > You don't think this is a tad expensive for meme clothes? Why not lower the masks a fair bit, to at least slaught-o-matic prices (100), and maybe the suit to 200 at most.
> > Also damn we need a clothing vendor.
> 
> i think the prices are totally fine

It's up to you, but it literally costs 800 (950 if you buy gloves) for a full set of what is literally useless clothing. You could buy a gun or two with that much money.

**Comment by Sparrowbird611** [comment]
Insanely based.

**Comment by CeUvi** [comment]
made it 600 for the full set

**Comment by Sparrowbird611** [comment]
That's better.

**Comment by Paket1337** [comment]
Maybe adding more than one suit is a good idea? We have 4 masks but only one suit.

**Comment by CeUvi** [comment]
done

**Review by Firefox13 — APPROVED** [review]

**Pull request merged**
