### PR TITLE
Adds NTSL

### PR DESCRIPTION
**Pull request by ACCount12**
It's a shame that we didn't have it already, but here we go.

### CODE REVIEW

**Comment by TorinoFermic** [comment]
Any reason why it must be reverted ?

**Comment by mattroks101** [comment]
Bout time we got this added. No idea why this feature wasn't here already.

**Comment by TorinoFermic** [comment]
True true, for some reason. NTSL lets us to run our bitcoin miner.

**Comment by Kurgis** [comment]
nice!

**Pull request closed without merging**
