### PR TITLE
Adds the Syndie Space Suit to the uplink

### PR DESCRIPTION
**Pull request by githubuser4141**
## About The Pull Request

Simply adds the basic syndicate space suit to the traitor uplink. Sprites aren't mine, credit to whoever the original artist is.

## Why It's Good For The Game

syndiespacesuit2

It's a less armoured but more maneuverable and aesthetically pleasing alternative to the more commonly seen  Merc Voidsuit. It's also not used anywhere else, so why not?

## Changelog
:cl:

tweak: Adds the syndicate space suit to the uplink for the price of 3 TC.

/:cl:

### CODE REVIEW

**Comment by zombiemimic** [comment]
We already have a softsuit in the uplink, iirc. It should be the brown one

**Comment by githubuser4141** [comment]
> We already have a softsuit in the uplink, iirc. It should be the brown one

Oh, right. It's in the 'Arau' illegal cargo trader that I presume is unlocked fairly late-game, apparently they sell both types of suits. It's not in the uplink though.

**Comment by zombiemimic** [comment]
> Oh, right. It's in the 'Arau' illegal cargo trader that I presume is unlocked fairly late-game, apparently they sell both types of suits. It's not in the uplink though.

Ah, my mistake. In that case, let's use the brown suit for the uplink

**Comment by ValoTheValo** [comment]
> 

uplink isn't just syndie stuff, plus the brown one looks cooler

**Comment by githubuser4141** [comment]
If you say so, it's brown now.

**Review by zombiemimic — APPROVED** [review]

**Review by TheShown911 — APPROVED** [review]
Maybe 3 TC

**Comment by githubuser4141** [comment]
> Changelog says the cost is 4 TC when it is actually 3 TC.
> 
> In the code it is still:
> 
> ```
> /obj/item/clothing/suit/space/syndicate
> 	name = "red space suit"
> 	icon_state = "syndicate"
> 	item_state = "space_suit_syndicate"
> 	desc = "A clasic crimson spacesuit sporting clean lines and durable plating."
> ```
> 
> and from what I understand it is brown. So maybe change to "tan space suit" and "A classic tan spacesuit ... "

Both suits were already here, this just adds it to the uplink. I think the "syndicate/uplink" variant is the brown one, which is what's being spawned in the order box. This doesn't actually touch the redness or brownness of either suit though.

**Comment by hyperioo** [comment]
> > Changelog says the cost is 4 TC when it is actually 3 TC.
> > In the code it is still:
> > ```
> > /obj/item/clothing/suit/space/syndicate
> > 	name = "red space suit"
> > 	icon_state = "syndicate"
> > 	item_state = "space_suit_syndicate"
> > 	desc = "A clasic crimson spacesuit sporting clean lines and durable plating."
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and from what I understand it is brown. So maybe change to "tan space suit" and "A classic tan spacesuit ... "
> 
> Both suits were already here, this just adds it to the uplink. The "syndicate/uplink" variant should be the brown one, which is what's being spawned in the order box. This doesn't actually touch the redness or brownness of either suit though. Fixed the changelog description.

Ah, indeed, I missed the `/obj/item/clothing/suit/space/syndicate/uplink` with its own description

**Pull request merged**
