### PR TITLE
Plasmacutterfix

### PR DESCRIPTION
**Pull request by Rexdyer1**
## About The Pull Request

WIP DO NOT MERGE, This requests borrows some Aurora code to add the functionality of a multi tile passthrough for ores. this will allow the plasma cutter to be actually useful in mass cutting lots of ores at the same time instead of just being one shot at a time for each tile. 

## Why It's Good For The Game

It will make mining more efficient and make it more worth it to trade with moebius for better parts. 
## Testing

No tests as of yet. I'm still trying to get the code to work, honestly could use some help reviewing it and working things out
## Changelog
:cl:
add: New function to plasma cutter. cuts through multiple rock tiles. pending further updates to ore clamp functionality and autopickup of ores to allow the cutter to be more useful. maybe rebalance to plasma cutter energy cost. 
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
do we even have a plasma cutter for mining?

**Comment by Mycah142** [comment]
> do we even have a plasma cutter for mining?

Mecha.

**Comment by Rexdyer1** [comment]
> do we even have a plasma cutter for mining?

Yeah. its very bad at the moment, it can only hit one tile at a time and currently mechs can't autopickup ores they walk over. So I'm trying to fix both those issues. I can't seem to figure out the issue with why it isn't working how I want it.

**Comment by benj8560** [comment]
hate to say it but it's likely not worth doing unless you rework mining mechs to allow for skill/tool effects for yields. At the moment you yield significantly less materials using one. It does depend on the ore type but you'll usually see around 5-10 ore with a mech drill. Where as you can peak at 20-35 per vein with greyson drills. Mechs are pretty much useless for mining until that's no longer a issue.

**Comment by Holvr0** [comment]
@Rexdyer1 You still alive? Could use that change to pair well with the other mining changes ⛏️

**Comment by Rexdyer1** [comment]
sorry can't get to it, gonna close it up.

**Pull request closed without merging**
