### PR TITLE
Loot rework part 3

### PR DESCRIPTION
**Pull request by Evankhell561**
## About The Pull Request
1. implements the third part of the loot rework.
2. Balance the spawn values ​​of the guns.

sprites for:
- [x] gun assembly.
- [x] armor assembly.
- [x] Handmade bolt action rifle
- [x] Handmade revolver.
- [x] Slide barrel shotgun.
- [x] Makeshift laser carbine
- [x] Makeshift grenade launcher
- [x] gun and armor parts.
- [x]  Makeshift armored void suit.
- [x]  Scavenger armor.​
- [x]  gun parts
- [x] electronics pouch.

## Why It's Good For The Game

this is part of the development document.

## Changelog
:cl:
add: gun assembly.
add: gun assembly.
add: Handmade bolt action rifle
add: Handmade revolver
tweak: Handmade Pistol now uses .40 caliber and requires different materials to craft it.
add: Slide barrel shotgun
add: Makeshift laser carbine
add: Makeshift grenade launcher
add: gun and armor parts
tweak: now there are fewer guns in maint, instead some gun parts spawners have been added.
fix: gun spawn values
add: Makeshift armored void suit
add: Scavenger armor.​
add: gun parts and electronics pouch
/:cl:

### CODE REVIEW

**Comment by ArmolitskiyCarpoeb** [comment]
omg

**Review by Iglpigl — CHANGES_REQUESTED** [review]
Insanely huge amount of conflicts.

**Comment by TorinoFermic** [comment]
Please resolve merge conflicts

**Comment by Evankhell561** [comment]
I'm going to draft this because of the amount of conflict.

**Comment by Evankhell561** [comment]
This pr also applies changes to the craft system so that part-based crafting can work.

**Pull request merged**
