### PR TITLE
Captain resprite, sheath tweaks, officer's saber

### PR DESCRIPTION
**Pull request by CeUvi**
## About The Pull Request
added officer's saber to Captain's and FO's lockers
saber

resprited captain, added fancy-looking coat
cockptain

also made sheath a belt subtype, so you can use "switch belt layer" verb on it

## Why It's Good For The Game
yes.

## Changelog
:cl: CeUvi
add: Officer's saber to Captain's and FO's lockers
add: New coat for captain
tweak: Made sheath a belt subtype, so you can use "switch belt layer" verb on it
tweak: made captain spawn with his new coat and jackboots
imageadd: New sprites for captain
imagedel: Old sprites for captain
/:cl:

### CODE REVIEW

**Comment by CeUvi** [comment]
have succesfully fucked up branches, so there is le saber now

**Comment by CeUvi** [comment]
have succesfully fucked up branches, so there is le saber now

**Comment by Sparrowbird611** [comment]
Man has freaking drip.

**Comment by Firefox13** [comment]
That makes him look more like military admiral than a captain

**Comment by CeUvi** [comment]
> That makes him look more like military admiral than a captain

epic i'd say

**Comment by Sparrowbird611** [comment]
He's the military dictator of the Eris, let him look the part :)

**Comment by FortuneMaster** [comment]
have mixed feelings about new costume

**Comment by ValoTheValo** [comment]
i love this new outfit. infinitely better than the old outfit

**Comment by AgentMA1** [comment]
Let the old sprite of captain clothes be maint loot/stash loot

**Comment by CeUvi** [comment]
> Let the old sprite of captain clothes be maint loot/stash loot

i accidentally deleted those

**Comment by CeUvi** [comment]
old sprites back
didnt put them in maints or anywhere else because i dont know how and also Firstly there is absolutely no reason for this to be made, secondly it will screw up loot and make all these items more common, thirdly, one and possibly more items price changes are direct violation to contributing guidelines, you should try reading them.
https://wiki.cev-eris.com/Content_GuidelinesEn

**Review by TheShown911 — APPROVED** [review]
I like it.

**Pull request merged**
