### PR TITLE
Resprites: Cow , Bear, Fish, Generator & Power Bank

### PR DESCRIPTION
**Pull request by githubuser4141**
## About The Pull Request

Resprites the ancient bay/TG sprites for cow, space fish, space bear, PACMAN and the power bank/cabinet.

## Why It's Good For The Game

Better sprites.
image

Power rack sprites are partly WIP - cover interaction doesn't exist as of yet.

## Testing

See comments.

## Changelog
:cl: Credit to Près de l'oiseau#2625
imageadd: New sprites for cow, space carps, space bear, PACMAN and power bank/cabinet.
imagedel: Old sprites of  cow, space carps, space bear, PACMAN and power bank/cabinet.

/:cl:

### CODE REVIEW

**Comment by Kurgis** [comment]
Seeing some odd things in the icondiff check, as if the file's image was accidentally off-set. This another issue with the bot?

**Comment by githubuser4141** [comment]
Okaaaay taking away the cat sprites for now because WIP.

**Comment by hyperioo** [comment]
> Okaaaay taking away the cat sprites for now because WIP.

I'm still seeing cat sprites in the sprite diff, is that normal?

**Comment by hyperioo** [comment]
Alright, I pulled the branch to check, cat is fine

image

**Pull request merged**
