### PR TITLE
Revert "Replace current laser sprites with new ones"

### PR DESCRIPTION
**Pull request by Alliostra**
Reverts discordia-space/CEV-Eris#6670

Long overdue, new laser sprites aren't even visible half the time. Unless they can be fixed, it is better to have functioning old laser sprites.

### CODE REVIEW

**Comment by Alliostra** [comment]
https://discord.com/channels/255035529085583360/375588651599396866/913281840054423632

**Review by SirRichardFrancis — APPROVED** [review]
We're going full TG this week :mitosis:

**Comment by ValoTheValo** [comment]
> We're going full TG this week :mitosis:

Remove dont repair clearly

**Comment by TheShown911** [comment]
This is probably an issue of how the gifs of the sprites are looped, could be fixed by either making these one frame sprites or cutting the gif animations so they don't fully disappear.

**Comment by ValoTheValo** [comment]
> This is probably an issue of how the gifs of the sprites are looped, could be fixed by either making these one frame sprites or cutting the gif animations so they don't fully disappear.

should be easy enough. imma try that

**Comment by Alliostra** [comment]
what the fuck is a "compare screenshot test" and how do I remove it from the github

**Comment by Alliostra** [comment]
Closing this in favor of https://github.com/discordia-space/CEV-Eris/pull/7877

**Pull request closed without merging**
