### PR TITLE
Captain armor resprite

### PR DESCRIPTION
**Pull request by Kegdo**
## About The Pull Request

when the
image

## Why It's Good For The Game

old sprite bad
## Changelog
:cl:
imageadd: added new(good) captain armor sprite(by Près de l'oiseau)
imagedel: deleted old(bad) captain armor sprite
/:cl:

### CODE REVIEW

**Comment by Kegdo** [comment]
i forgor to edit the FUCKING title

**Comment by TheShown911** [comment]
Credit the spriters

**Comment by Kegdo** [comment]
> Credit the spriters

issue adressed

**Review by hyperioo — APPROVED** [review]
Sprite guru said the sprite was ok

**Pull request merged**
