### PR TITLE
Port benzin roach

### PR DESCRIPTION
**Pull request by SirRichardFrancis**
## About The Pull Request

Ports benzin roach from Eclipse / NEV "Northern Light".

benzin

They explode when shot, which could be either extra danger or used to player advantage.
Rarity between seuche and panzer roaches.

## Why It's Good For The Game

New roach type is cool.

## Changelog
:cl:
add: benzin roach
/:cl:

### CODE REVIEW

**Comment by assortedbeads** [comment]
Finally, suicide roach

**Comment by Humonitarian** [comment]
Put blattedin in the meat (it's their blood), and increase rarity are my two suggestions

Question: do they chainexplode?

**Comment by SirRichardFrancis** [comment]
> Put blattedin in the meat (it's their blood)

~Their blood is welding fuel.~ Ok.

> increase rarity are my two suggestions

Not yet, let players ~suffer~ enjoy the new feature first.

> Question: do they chainexplode?

No.

**Comment by pexel5** [comment]
Is it possible, tammed this cockroach, to use it as a welder tank and refuel the welder from it?

**Comment by pexel5** [comment]
And also, does it explode if you kill it with a melee weapon?

**Comment by SirRichardFrancis** [comment]
> Is it possible, tammed this cockroach, to use it as a welder tank and refuel the welder from it?

...no?

> And also, does it explode if you kill it with a melee weapon?

No.

**Comment by pexel5** [comment]
> Why not do the first one? As for me, the perfect solution to all problems with fuel. best for technomancer life - WALKING WELDER TANK!

**Comment by ValoTheValo** [comment]
should probably be on the rarer side considering its a walking welderbomb and we already have enough landmines in maint blowing holes in the ship

**Comment by assortedbeads** [comment]
> > And also, does it explode if you kill it with a melee weapon?
> 
> No.

Basically a melee buff maintainers please speed merge

**Comment by SirRichardFrancis** [comment]
image
image
@pexel5

**Comment by MLGTASTICa** [comment]
> image image @pexel5

immersion to the next level.

**Comment by pexel5** [comment]
> *blush jesus christ, I didn't think you'd do that. This was awsome

**Review by zombiemimic — APPROVED** [review]
time to milk them for welding fuel

**Comment by pexel5** [comment]
> time to milk them for welding fuel

++++

**Review by TheShown911 — APPROVED** [review]

**Review by hyperioo — APPROVED** [review]

**Pull request merged**
