### PR TITLE
Increase resuscitator timer

### PR DESCRIPTION
**Pull request by SirRichardFrancis**
## About The Pull Request

Increased time when player character could be revived from 5 to 15 minutes.

## Why It's Good For The Game

Being brought back from the dead feels good, staying permanently dead is not so much.
Shocking, but nerfing resuscitator didn't force people to "just play NT lol".

## Changelog
:cl:
tweak: resuscitator could be used 15 minutes after person's death
/:cl:

### CODE REVIEW

**Comment by pexel5** [comment]
Thank you, as a doctor player, I really like this PR.

**Review by TheShown911 — COMMENTED** [review]
Absolute cope PR.

**Comment by SirRichardFrancis** [comment]
> Absolute cope PR.

I want to have easier time reviving people with skill issues, so they don't leave that much, because it's a real problem right now, and even one or two people that leave the round make a visible impact.
By the time body placed in a cryo bag, 5 minutes often pass already, and player is unlikely to wait respawn for half an hour.
As for NT main that disliked this PR, well, a lot of people can't be NT due to job restrictions, others for RP reasons.

**Comment by Alliostra** [comment]
grafik

**Pull request merged**
