### PR TITLE
Engineering icons

### PR DESCRIPTION
**Pull request by Kurgis**
## About The Pull Request

New hardhat icons, new workboot icon, and hazard vests.

## Why It's Good For The Game

Hardhats are popping, hazard vests are no longer Baysprites. Deleted unused OldEris Preacher icon, adjusts the handmade armor to remove clipping.

## Changelog
:cl: Kurgis, WatlerJe
imageadd: New sprites for hard hats, their objects will take up a greater presence now.
imageadd: Workboots and hazard vests touched-up to NewStyle.
/:cl:

### CODE REVIEW

**Comment by SpadesSlick** [comment]
image
Uniforms should not be bloated for non existing jobs, since we have a relayering project coming soon.

Also technomancer uniforms will be reworked rather soon and we already have spriter on it, so you better just remove any uniform related changes.

Everything else is fine, however.

**Comment by SpadesSlick** [comment]
Also here is PR qith uniforms I talked about: #4974

**Comment by SpadesSlick** [comment]
This PR will be closed in 7 days.

**Comment by Kurgis** [comment]
Made requested changes.

**Pull request merged**
