### PR TITLE
Translates famous Russian quote from the recycling vendor

### PR DESCRIPTION
**Pull request by Iglpigl**
## About The Pull Request

Apparently according to some Russian dudes it roughly translates to this, alternative was deleting it outright but this is probably smarter.
Translates famous Russian quote that Sidor from popular video game stalker says to you when you bring him shit from the recycling vendor.

## Why It's Good For The Game

People were being confused.

## Changelog
:cl:
spellcheck: recycling vendor no longer knows Russian
/:cl:

### CODE REVIEW

**Comment by Alliostra** [comment]
soulless

**Comment by TheShown911** [comment]
soulless

**Comment by hyperioo** [comment]
That wakes up memories 👀 

image

**Comment by SirRichardFrancis** [comment]
image

**Pull request closed without merging**
