### PR TITLE
Reduces the recoil of pistols/revolvers by a lot

### PR DESCRIPTION
**Pull request by MLGTASTICa**
## About The Pull Request
Cuts down a lot of recoil from most of the pistols to make them viable.
## Why It's Good For The Game
3 Shots and the rest can't be aimed , even with very high stats. A pistol shouldn't have a lot of recoil , especially one that is rare ,  obtainable through stashes or the traitor uplink  , and that already has a low mag capacity.
Pistols also in general use barely powerfull calibers most of the time and lack the ability for full auto.

## Changelog
:cl:
balance: Reduced recoil of the mandella from 19 to 2
balance: Reduced recoil of the avarsala from  33 to 5
balance: Reduced recoil of the lamia from 21 to 5
balance: Reduced recoil from the paco from 10 to 3
balance: Reduced recoil from clarrisa from 19 to 2
balance: Reduced recoil from the makarov from 21 to 3
balance: Reduced recoil fron the consul from 35 to 6
balance: Reduced recoil from the deckard from 40 to 6
balance: Reduced recoil of the handmade revolver from 60 to 7
balance: Reduced recoil from the havelock from 18 to 8
balance: Reduced recoil from the mateba from 38 to 6
balance: Reduced recoil from miller from 50 to 8
balance: Reduced recoil from the skydriver from 50 to 6
/:cl:

### CODE REVIEW

**Comment by Omni44** [comment]
This has been general issue of pistols all over the board, kind of pointless to do such thing with just Mandela.

**Comment by MLGTASTICa** [comment]
> This has been general issue of pistols all over the board, kind of pointless to do such thing with just Mandela.

if maintainers agree with that i can lower it for all of them.

**Comment by zoktiik** [comment]
I don't believe pistols should generally have these very low recoil values,  though only a slight increase across the board should do the job.
While pistols shouldn't have ridiculously high recoil, I believe that they should still have at least a substantial amount of kick, because there's nothing like a stock to help absorb recoil, nor is there a lot of weight to counterbalance it. 
Game-wise, I think pistols having relatively high recoil values is also balanced due to the fact that they are easily carried/concealed, and that a high-ish recoil stat would encourage the shooter to move into close-quarters, which is what these guns were meant for.
However, I do believe the old recoil stats for these guns is a bit ridiculous. Good PR.

**Comment by MLGTASTICa** [comment]
> I don't believe pistols should generally have these very low recoil values, though only a slight increase across the board should do the job.
> While pistols shouldn't have ridiculously high recoil, I believe that they should still have at least a substantial amount of kick, because there's nothing like a stock to help absorb recoil, nor is there a lot of weight to counterbalance it.
> Game-wise, I think pistols having relatively high recoil values is also balanced due to the fact that they are easily carried/concealed, and that a high-ish recoil stat would encourage the shooter to move into close-quarters, which is what these guns were meant for.
> However, I do believe the old recoil stats for these guns is a bit ridiculous. Good PR.

You can easily conceal a drozd .40 smg in a medium general pouch. I personally believe all pistols should have very low values as they are weapons that are not very capable both in terms of damage and fire rate.

**Comment by zoktiik** [comment]
> > I don't believe pistols should generally have these very low recoil values, though only a slight increase across the board should do the job.
> > While pistols shouldn't have ridiculously high recoil, I believe that they should still have at least a substantial amount of kick, because there's nothing like a stock to help absorb recoil, nor is there a lot of weight to counterbalance it.
> > Game-wise, I think pistols having relatively high recoil values is also balanced due to the fact that they are easily carried/concealed, and that a high-ish recoil stat would encourage the shooter to move into close-quarters, which is what these guns were meant for.
> > However, I do believe the old recoil stats for these guns is a bit ridiculous. Good PR.
> 
> You can easily conceal a drozd .40 smg in a medium general pouch. I personally believe all pistols should have very low values as they are weapons that are not very capable both in terms of damage and fire rate.

I'll test your PR and give more detailed feedback soonish.

**Review by Firefox13 — APPROVED** [review]

**Pull request merged**
