### PR TITLE
Drops the summary dropdown in pull requests.

### PR DESCRIPTION
**Pull request by Kurgis**
## About The Pull Request
It will look as shown in this summary.

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by TorinoFermic** [comment]
Here's the good example before this PR where hiding big text actually helps.
image

**Comment by SpadesSlick** [comment]
I don't think that's good idea.

**Comment by LethalGhost** [comment]
They barely use as intended - to hide large amount of text. Usually they hide all the description.
If we remove them from template advanced users can add them by hands when needed.
Or we should better describe functionailyty withing template.

**Comment by drexample** [comment]
This doesn't look good or useful.

**Pull request closed without merging**
