### PR TITLE
Revert "Comments out benzin"

### PR DESCRIPTION
**Pull request by Mycah142**
## About The Pull Request
Reverts discordia-space/CEV-Eris#7555

## Why It's Good For The Game
Funni roach.
Also, with explosions and fire being reworked, these babies might be feasible again. Vagabonds should be reminded why they should fear maint.

### CODE REVIEW

**Comment by SirRichardFrancis** [comment]
# Benzin roaches have returned. Billions will die.

image

**Comment by SirRichardFrancis** [comment]
It still needs testing though.

**Comment by SirRichardFrancis** [comment]
Also you're missing a changelog.

**Review by Firefox13 — COMMENTED** [review]
Cancer feature will still be a cancer feature even if the code it used was changed.

Besides, this will literally won't work.

**Comment by SirRichardFrancis** [comment]
Feature isn't cancer, players need to git good is all.

**Comment by Firefox13** [comment]
No. Maints are supposed to be dangerous, but not mindbreaking killing rooms.

**Comment by SirRichardFrancis** [comment]
> Besides, this will literally won't work.

Actually correct. Romch explosion does no damage, even if you stand on top of it when it explodes.

image

**Comment by SirRichardFrancis** [comment]
> No. Maints are supposed to be dangerous, but not mindbreaking killing rooms.

Could "not mindbreaking killing rooms", if explosion is mild enough.
Still a skill issue, explosions could be easily avoided, and so are fires.

**Comment by Firefox13** [comment]
> Actually correct. Romch explosion does no damage, even if you stand on top of it when it explodes.

Because uncommented code is still old system code. Hence it doesn't work.

I'm also concerned about possible infrastructure (pipes or cables) damage. Which is actually hell.

**Comment by SirRichardFrancis** [comment]
Cables and pipes could be adjusted to survive small explosions, if that's the core issue.
Fuel fires will remain a thing, but a _good_ thing at that, because it's both adds some dynamic to maintenance tunnels, and almost superstitious "don't smoke in maintenance" rule.

**Comment by null-Aurelian** [comment]
How much fuel is in the fuel puddle?

**Comment by SirRichardFrancis** [comment]
> How much fuel is in the fuel puddle?

40 units.

**Comment by Humonitarian** [comment]
Fire rework is still drafted

**Comment by Twomoon-Github** [comment]
finally, the return of the maint king

**Comment by thevandie** [comment]
> Cables and pipes could be adjusted to survive small explosions, if that's the core issue. Fuel fires will remain a thing, but a _good_ thing at that, because it's both adds some dynamic to maintenance tunnels, and almost superstitious "don't smoke in maintenance" rule.

With SPCR's EXTREME amounts of salt towards welding fuel explosions, yeah 40 welding fuel is gonna do jack shit to everything around, re-add the funny romch (I've never seen it, I wasn't here before it was removed)

**Comment by Humonitarian** [comment]
Do not readd unless spilled welding fuel no longer generated heat. That was the main issue, not explosions. Not even spaceproof armor protects you from the oven that maints became every round.

**Comment by null-Aurelian** [comment]
I thought the heat was counteracted by running on internals

**Comment by SirRichardFrancis** [comment]
I don't actually recall fires being an issue, only explosions breaking wires all the time.

**Comment by thevandie** [comment]
> Do not readd unless spilled welding fuel no longer generates heat. That was the main issue, not explosions. Not even spaceproof armor protects you from the oven that maints became every round.

them being ignited, or them on their own generating heat?

**Comment by SirRichardFrancis** [comment]
It's about fuel they leak being ignited by smoking vagabonds. And apparently it heats up the air without any limit...
Not a roach issue per se, but related one.

**Comment by Mycah142** [comment]
I am going to make benzins great again.

**Comment by SirRichardFrancis** [comment]
F

**Pull request closed without merging**
