### PR TITLE
You've been gnomed!

### PR DESCRIPTION
**Pull request by DarkLevelSS13**
You have been gnomed!

## About The Pull Request
Adding gnome costume for artist (Also you can find parts of this costume in trash).
Added by request of INFRARED_BARON.
Sprites made by Watler'Je.
image
image

## Why It's Good For The Game
image

## Changelog
:cl: DarkLevel - code, Watler'Je - Sprites.
add: Gnome costume set.
/:cl:

### CODE REVIEW

**Review by TorinoFermic — APPROVED** [review]

**Review by TheShown911 — APPROVED** [review]
Yes.

**Review by genessee596 — APPROVED** [review]
i absolutely fucking hate this with every ounce - every fiber - of my mind, body, and soul

lets add it

**Comment by TorinoFermic** [comment]
Time to merge it

**Comment by MadmanMartian** [comment]
I look away for 5 minutes, and look what happens

**Pull request merged**
