### PR TITLE
Chameleon clothing update

### PR DESCRIPTION
**Pull request by Alliostra**
## About The Pull Request

~~I'm deeply sorry~~

Wearing the chameleon jumpsuit will now allow you to quickly switch between one of 4 loadouts, which you can customize yourself (the default loadouts are a vagabond, an IH op, a scientist and a NT acolyte)

Also adds a chameleon satchel, so you are no longer bound to using a backpack if you want to go full chameleon clothes.
Chameleon clothes will now properly respect what the item they are mimicking is supposed to block from view. (Previously, having a chameleon mask with the appearance of a cigarette would not display glasses)
Chameleon clothes no longer contain biomatter, but plastic instead, so moebius can now actually print the chameleon kit.

Hex helped with the nanoUI stuff. Others who I forgot about probably helped, too.

this is the result of a copy-paste coder writing original code. has mining gone too far?

grafik
## Why It's Good For The Game

Chameleon clothes OP, plz nerf!
(makes chameleon clothes actually usable)

## Changelog
:cl:
add: added the ability to quickly switch between different loadouts for chameleon clothes if the chameleon jumpsuit is worn.
add: Added the chameleon satchel
fix: chameleon items will no longer block other clothing sprites from appearing when they weren't supposed to
tweak: chameleon clothes are now made of plastic instead of bioatter
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
can you make it so chameleon clothing don't use biomatter, as currently moesci cant actually print thier cham kits due to them costing biomatter due to not having resource values assigned

**Comment by FortuneMaster** [comment]
Would you kindly attach screenshot or two of chameleon loadout screen

**Comment by Alliostra** [comment]
grafik
click on a button to set a new item to the slot.

**Comment by FortuneMaster** [comment]
> grafik click on a button to set a new item to the slot.

attach it to PR description itself(for convenience of rosa who'll be making devlog too)

**Review by Firefox13 — APPROVED** [review]

**Pull request merged**
