### PR TITLE
resprited slimes

### PR DESCRIPTION
**Pull request by CeUvi**
## About The Pull Request
image
image
image
image

## Why It's Good For The Game
new sprets good

## Changelog
:cl: WalterJe
imageadd: slems
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
awesome sprites , now imagine if slime people had them too.

**Comment by CeUvi** [comment]
> awesome sprites , now imagine if slime people had them too.

fuck slimepople

**Comment by Iglpigl** [comment]
> awesome sprites , now imagine if slime people had them too.

What about golems though, if their sprite works correctly which is pretty rare they are still ugly.

**Comment by CeUvi** [comment]
> > awesome sprites , now imagine if slime people had them too.
> 
> What about golems though, if their sprite works correctly which is pretty rare they are still ugly.

fuck golems

**Comment by Iglpigl** [comment]
> > > awesome sprites , now imagine if slime people had them too.
> > 
> > 
> > What about golems though, if their sprite works correctly which is pretty rare they are still ugly.
> 
> fuck golems

No really does any server have cool golem sprites(if possible made by Walter if not not a problem) if no then it's fine no need to sprite for an obscure feature, could be a future PR when you have some time.

**Comment by Alliostra** [comment]
> 
> 
> > > > awesome sprites , now imagine if slime people had them too.
> > > 
> > > 
> > > What about golems though, if their sprite works correctly which is pretty rare they are still ugly.
> > 
> > 
> > fuck golems
> 
> No really does any server have cool golem sprites(if possible made by Walter if not not a problem) if no then it's fine no need to sprite for an obscure feature, could be a future PR when you have some time.

you could check out vorestation for sprites

**Comment by Kurgis** [comment]
Please keep out the suggestions not related to the PR.

**Review by mattroks101 — APPROVED** [review]

**Comment by TheShown911** [comment]
Where are these sprites from? If from another server you should credit the PR where they were introduced in.

**Comment by CeUvi** [comment]
> Where are these sprites from? If from another server you should credit the PR where they were introduced in.

it's Walter's and i already credited him

**Pull request merged**
