### PR TITLE
Adds 3 Cell Crates!

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Adds three new crates each dealing with cells! - For when Sci is to lazy or such!
Atomic Cell Crate -
Has one of each Cell in it costing 7500 for free* endless power!
Random Cheap Cell Crate  - Only 1250 with 5 cells!
These are basic low end to high for max, with Rng to be able to give ether a good deal or being highway robbery! The price of power!
A better Cell rng Crate costing 3000(Maybe 5k if it is abused?) -  were it can have hyper and supers 
Of all sizes  - Also only 5 cells subject to Rng

### CODE REVIEW

**Comment by AncientV25** [comment]
Oh christ, no. "let's just buy atomcells guys!!!"

You do know that the Captain has 2 million in the bank and that making enough money to spew out atomcells isn't difficult? This would 100% invalidate sci's efforts regardless of whether or not they're present.

**Comment by Pariah919** [comment]
if you want atomcells just fucking buy cassads and sell them to moebius OR GO MINING

**Comment by ACCount12** [comment]
If we want to make getting R&D shit more trivial, we should just make raw materials order-able in cargo, with exorbitant markup.

**Comment by Trilbyspaceclone** [comment]
@AncientV25 Is the problem just the Atomic cells?

**Pull request closed without merging**
