### PR TITLE
Makes Plasma rifles fire in bursts

### PR DESCRIPTION
**Pull request by zombiemimic**
## About The Pull Request
redoes #6702 without the merge conflict, with NT dominion

## Why It's Good For The Game
gives a reason to use plasma

## Changelog
:cl:
add: Added burst fire mode to Dominion and Cassad plasma rifles
/:cl:

### CODE REVIEW

**Comment by zombiemimic** [comment]
> How does this interact with the overdrive chip?

Overdrive merely adds a new firemode, so it works fine

**Comment by TheShown911** [comment]
Why only the cassad?

**Comment by CeUvi** [comment]
bcus cassad is an assault rifle, and others aren't.

**Comment by TheShown911** [comment]
All the other rifles are supposed to be stronger then the cassad

**Comment by Iglpigl** [comment]
> bcus cassad is an assault rifle, and others aren't.

Silence IH main.

**Comment by zombiemimic** [comment]
> All the other rifles are supposed to be stronger then the cassad

are they?

**Comment by TheShown911** [comment]
Yes.

**Comment by ValoTheValo** [comment]
Cassad is Turbo shit and isnt even useable as an assault rifle. Based change

**Comment by Omni44** [comment]
This is completely pointless. Either figure out way to make plasma in general as a whole not dogshit, or don't touch it.

**Comment by Kegdo** [comment]
~~the plasma gun fires in spurts~~

**Review by drexample — APPROVED** [review]

**Pull request merged**
