### PR TITLE
Cyborgs can no longer be hard-stunned by flashes. Security cyborgs are immune to flashes. Adds framework for modular traits.

### PR DESCRIPTION
**Pull request by MLGTASTICa**
## About The Pull Request
Cyborgs no longer get hard-stunned by flashes
Sec cyborgs are now immune to flashes
Adds in framework for robot_Traits

## Why It's Good For The Game
Stuns are cringe , even so on extremly slow robots. You should bother with the effort for an ion gun atleast if you wish for a insta-win
## Changelog
:cl:
balance: Cyborgs no longer get hard-stunned by flashes , instead they get a speed debuff and the flash overlay.
balance: Security cyborgs are now flash immune
code: Added framework for module-based and component-based  robot traits , which provide functionality
code: "Floor Cleaning" trait added for the janitor cyborg module , "Flash resistant" added for security , "Deflective armor" trait added for admin fun.
/:cl:

### CODE REVIEW

**Comment by SirRichardFrancis** [comment]
Cyborg immune to flashes? Can you not?

**Comment by MLGTASTICa** [comment]
> 

No longer hardstunned , not immune , bruh.

**Comment by SirRichardFrancis** [comment]
> No longer hardstunned , not immune , bruh.

"Sec cyborgs are now immune to flashes"
"balance: Security cyborgs are now flash immune"

**Comment by MLGTASTICa** [comment]
> > No longer hardstunned , not immune , bruh.
> 
> "Sec cyborgs are now immune to flashes" "balance: Security cyborgs are now flash immune"

Problem?

**Comment by SirRichardFrancis** [comment]
> Problem?

Yes.

**Comment by MLGTASTICa** [comment]
> > Problem?
> 
> Yes.

Cope. Cyborgs suck in their current state and they desperately need this. Also remember that one of the driving principles of eris development is no easy hardstuns in combat.

**Comment by Firefox13** [comment]
> immune to flashes

lol no.
seriously

**Comment by TheShown911** [comment]
bruh secborgs are the strongest mobs on the station what the hell are you on about

**Comment by Shadow-Quill** [comment]
You need to keep in mind that station-bound synthetics aren't limited by pain or damage (except for losing modules in the case of the latter)

Off the top of my head, the top three ways to deal with a cyborg is: flash, emp, or robotics console

**Comment by FortuneMaster** [comment]
Remove the immunity thing and the PR is fine by me. Hardstuns aren't fun, but OP borgs aren't too

**Comment by ValoTheValo** [comment]
The AI main massivly buffing cyborgs. Shocker. 
(Salt PR)

**Comment by ValoTheValo** [comment]
> You need to keep in mind that station-bound synthetics aren't limited by pain or damage (except for losing modules in the case of the latter)
> 
> Off the top of my head, the top three ways to deal with a cyborg is: flash, emp, or robotics console

Dont forget bullets or lazers.

**Comment by Omni44** [comment]
I think SPCR understands something about fighting the borgs everyone else seems to be missing here:
When dealing with unstoppable freight train with taser turret on you that's largely unmoved by pain or for the most part getting damaged you're not supposed to actually engage its bullshit, let alone in as smoothbrained way as flashing. Proper way to do it is to do astral projection and murder the person on the other side of the screen. In minecraft ofc.
It's that simple folks!

**Comment by Kegdo** [comment]
hmmm yes, let's make stuff that is already hard to kill and is pain-resistant even hard to kill. AI main detected, to Brazil you go

**Comment by Sparrowbird611** [comment]
How bout you make borgs play similar to normal people, like FBPs, instead of doing whatever this insanity is. Especially given a flash will still hardstun a normal human anyway.

**Comment by MLGTASTICa** [comment]
> Referenc


> How bout you make borgs play similar to normal people, like FBPs, instead of doing whatever this insanity is. Especially given a flash will still hardstun a normal human anyway.

flash doesnț hardstun humans.

**Comment by Sparrowbird611** [comment]
> 

Weaken my bad, though that is still a status effect that condemns you to painfully slow movement and, unless recently changed, prevents attacking at all. Though probably doesn't cause you to drop weapons anymore. Terrible effects abound either way.

**Comment by MLGTASTICa** [comment]
> > 
> 
> Weaken my bad, though that is still a status effect that condemns you to painfully slow movement and, unless recently changed, prevents attacking at all. Though probably doesn't cause you to drop weapons anymore. Terrible effects abound either way.

Yes and cyborgs get slowdown .  The cyborg flash however canț keep a human chain stunned for long enough , since the human life tick is faster than its recharge rate , on the other hand the cyborg life tick is very long , causing one flash to be doom.

**Comment by Jan-Blasiak** [comment]
Balanced like Yugoslavian economy.

**Review by Firefox13 — CHANGES_REQUESTED** [review]
Borgs hardstuns should remain since, citing, `borgs have more HP, can't be knocked out or slipped, they suffer no slowdown, they win every melee fight due to their high HP and every ranged fight due to almost limitless ammo`.
Besides, you can't emag one and don't blow your cover during it if they can't be hardstuneed.

**Comment by MLGTASTICa** [comment]
> Borgs hardstuns should remain since, citing, `borgs have more HP, can't be knocked out or slipped, they suffer no slowdown, they win every melee fight due to their high HP and every ranged fight due to almost limitless ammo`. Besides, you can't emag one and don't blow your cover during it if they can't be hardstuneed.

borgs have less health than humans , humans can go in 200 to -200 , effectively 400 HP and even further if they wear armor, while cyborgs have 200 health and are stuck with this. The cyborg health is really RNG because it depends on what components you hit , but most of the time they will die quite fast. Ontop of this , cyborgs all have extremly slow walk-speed. Their ammo is not limited and recharges slowly. Also they can still get hardstunned by EMPs , and even a EMP gadget could be added for contractors for this very scope.

**Comment by Shadow-Quill** [comment]
> borgs have less health than humans , humans can go in 200 to -200 , effectively 400 HP and even further if they wear armor,

You forgot that pain exists.

**Comment by drexample** [comment]
buff them in a better way

**Comment by drexample** [comment]
AND STOP PUTTING FRAMEWORK SHIT WITH UNRELATED CODE CHANGES GODDAMIT

**Pull request closed without merging**
