### PR TITLE
OD FIXES and Trico od. OHH YEAH

### PR DESCRIPTION
**Pull request by fernandos13**
## About The Pull Request
FIXES the LACK of od in ALL the chems
adds OD to tricord

## Why It's Good For The Game
well you know so people don't chug a bottle of everything and..survive with 300 of every fucking chem

## Changelog
:cl:
add: OD tricord at 60
fix: OD in every other chem now works again
/:cl:

### CODE REVIEW

**Comment by fernandos13** [comment]
how do i close this
dang it went wrong somewhere again

**Comment by fernandos13** [comment]
nice it was working with trico. somehow addint it to every chem went wrong somewhere need to check it double now. NOT WORKING DO NOT MERGE

**Comment by fernandos13** [comment]
FROM THE SLUMBER I AWAKE WITH THE SOLUTION

**Comment by Kurgis** [comment]
I was working on a different project awhile back, for EU4, a Vanilla-Oriented Total Conversion (if that makes sense), and I saw within the files unset cultures. Starting up GitKraken I got to work to learning how to scenario edit, how to edit idea sets, and the huge amount of localizations required for everything. After the many hours of work, I pull requested my changes, where it was promptly closed by the Project Lead. Though, closed with great confusion at the effort put into something which was agreed upon beforehand to be removed, if only I had simply discussed this with other developers this waste would not of occurred.

I bring that up, for now I feel as though I'm responding with the same confusion as that Project Lead, before a PR of effort is closed, because it does not abide by what is needed or wanted. After checking Discord the only place where you've mentioned these changes is in #en_docks, a place which many other developers do not check or browse. You seem to be attempting to fix overdose since "NOTHING is calling the OD to kick in". You're likely experiencing an unrelated issue with with "Tri-Metabolism", and `dose` amount. There are three different metabolisms working in tandem with each other (an unwanted feature which is slated for removal), and they each function differently. You likely ingested reagent which failed to acquire required dosage for an overdose, overdose does have proper proc calls.

**Comment by fernandos13** [comment]
thanks for the words. truly makes me feel dumb (you know how it is)
but helps me keep up coding in the future new pr for trico coming up soon

**Comment by TheShown911** [comment]
As Kurgis said, it feels bad to deny a PR with a lot of effort put in, but you should use this as lesson to discuss changes so they don't get denied, and your work wasted. There have been a few PR-s rebalancing tricord so be wary of changing it.

**Pull request closed without merging**
