### PR TITLE
Blitzshell uplink rework

### PR DESCRIPTION
**Pull request by Humonitarian**
## About The Pull Request

Blitzshell was given quite a few new toys to play with, and uplink was tweaked significantly.

Weapon changes:
The default plasma weapon no longer possesses all 3 firemodes. Instead, the default firemode now fires standard plasma shots,  while the burst and AP shots can be purchased as upgrades.
The laser weapon now has two upgrades: STUN and burst mode. To make up for the pricy upgrades, the base laser's price was reduced to 10 TC from 20. Erismed 4 should help avoid Blitz becoming as strong as it used to be.

Consumables:
Smoke charges only cost 1 TC (they aren't all that strong anyways), and nanites cost 3 TC instead of 5 to help recoveries. Again, humans received Erismed 4 as extra resilience, so this should be fair.

Tools:
Flash Reflective implant that makes them immune to flashes (just use an EMP!)
Parkour perk via a Climbing implant. This perk gives a 25% decrease to ladder climbing time, as well as the ability to scale walls over empty space. Very cool.
Cell aluminum plating, which halves the amount of energy lost from EMP when purchased. They still stun and damage, however.

Harpoon was broken, so it was commented out to avoid newbies wasting TC.

BSDM no longer purchasable, Blitz starts with it.

General:
Uplink mechanics reworked to allow upgrades to disappear once purchased, and new upgrades to appear in their place.

Uplink prices were decreased generally to make up for the weaker starting weapon.

## Why It's Good For The Game

Makes Blitz have a few more tools in their arsenal, which helps against hard counters. Reworks their weapons systems to give players more freedom. Tweaks uplink prices, and improves uplink mechanics to feel less clunky. Blitzshells generally desired all these.

## Testing

Tested on local, I could scale walls and upgrade my guns. Items disappeared from uplink as expected.

## Changelog
:cl:
add: New Blitzshell items
balance: Reworked blitzshell uplink
balance: Blitzshell starts with basic plasma firemode, can purchase new ones
fix: Blitz can no longer order the broken BS harpoon and BSDMs
/:cl:

### CODE REVIEW

**Comment by Humonitarian** [comment]
I'm considering redoing all the blitz uplink prices to make fun things more affordable

**Comment by MLGTASTICa** [comment]
omg giving the robot flash protection ? Op and gamebreaking. Salt PR one might even say.

**Comment by Humonitarian** [comment]
> omg giving the robot flash protection ? Op and gamebreaking. Salt PR one might even say.

I mean it literally is a salt PR, I have no shame here.

Any suggestions on what else to add or change? You're the robo expert.

**Comment by MLGTASTICa** [comment]
> > omg giving the robot flash protection ? Op and gamebreaking. Salt PR one might even say.
> 
> I mean it literally is a salt PR, I have no shame here.
> 
> Any suggestions on what else to add or change? You're the robo expert.

 make EMPs less of a eat-shit hard counter and  let flashes always blind but never hardstun

**Comment by ValoTheValo** [comment]
> omg giving the robot flash protection ? Op and gamebreaking. Salt PR one might even say.

the difference is one is a solo antag and the other is a normal ass borg

**Comment by radarseas** [comment]
a cham projector would be a funny upgrade for a blitzshell and tie into their ambush capability and design as well as letting them escape/evade from things like people with thermals. _(or dumb gimmics like pretending to be the spare ID to lure victims into places to be shot at.)_

a TC costing single-use module like repairs that synthises beartraps or maybe drone-immune landmines would be good for assassinations, probably a bit too good (considering unlike most antags they can ventcrawl, run and gun) but handy for trapping/knocking out people ready for a kill/implant. _they can still call for help and fire at you._ or just... not step in/on it. Blitz already suffers from being a glass cannon and slow against people on nuka cola/hyperzine, having some way to defeat or escape it at the very least. even at a hefty cost like 20TC-25TC per one would be nice.

blitzshells have no need for buying BSDM units from their uplinks (they can't actually use them and have an in-built module for it which is compatable with their own syringe module for blood sample contract speedrunning.) _might be worth commenting out from uplink as well as the harpoon?_

blitz's biggest weakness and what's most painful about is absolutely zero way to do anything about EMP hardstuns honestly, they uhh, usually get obliterated by a frye for 80 credits from guild or literally every single uplink antag that bothers to buy EMPs. or a single cassad pulse shot which most smart IH will carry plus get roundstart (not including the halicons) and moesci can print brigdors which also EMP. failing all of that there's stashes which can have specialised EMP equipment stuff. the timer is very short so ventcrawling won't save you usually. _its basically over if you even happen to get hit_.

flashes should still blind or have some detriment, regardless of upgrades. you already made the effort of reaching the drone, clicking on its sprite and not having it block it with a table _while probably being shot at the entire time by it plus the crew_ and having your flash not EMP'd by other crew. plus having the flash to begin with.

(also remember blitzshell can buy a shotgun module that throws _people back and gives them shrap making chasing harder - plus its also funny watching people go flying from it_).

**Review by TheShown911 — APPROVED** [review]
I haven't read any of this, but no one plays beepshell so it probably won't be noticed.

**Pull request merged**
