### PR TITLE
this should allow NT converts to have access

### PR DESCRIPTION
**Pull request by fernandos13**
NT converts access

## About The Pull Request
  should allow NT convert to acces the church

## Why It's Good For The Game
 fixes NON nt workers. 
but NT belivers to have some acces in the church "and morgue"

## Changelog
:cl: Fernandos33
fix:  NT believers can now. walk around churchs
/:cl:

### CODE REVIEW

**Comment by fernandos13** [comment]
also don't worry i tested. non implanted works don't have access

**Comment by SpadesSlick** [comment]
I think it should provide access upon cruciform generation, not in every job datum.

Also it reminds me how much outdated our assess structure for church is.

**Comment by fernandos13** [comment]
i tried that at the begining. "would be easier and better as you said"
but couldn't manage it in any way.

i even tried giving ANY cruci "inquisitor stats" to see if it worked. but no. only thing I PERSONALY could manage is this one

now. if you can show me some documents to read about how the access is handled, or anything that would teach me more about this code. i could try again after reading/studying that

but as it is. i have no idea how to make that happen.

**Comment by SpadesSlick** [comment]
There isn't that much on access as it is, it's a collection of flags that is used in doors and consoles. Current ones were made before NT get their own department, and it was never properly changed, so it's a core of our problems.

So please make another PR when you handle it properly.

**Pull request closed without merging**
