### PR TITLE
tool radials

### PR DESCRIPTION
**Pull request by nichlas0010**
Adds radials for the get_tool_type proc

### CODE REVIEW

**Comment by nichlas0010** [comment]
oh wait, the radial goes transparent with the object. I'll fix that later.

**Comment by NanakoAC** [comment]
slick feature, 80+ files though oh dear, ill look through this. Any comment on the sheer quantity?

Please fix that transparency thing asap

**Comment by nichlas0010** [comment]
The quantity is just because I needed to add an extra argument to get_tool_type, for the atom the radial should appear on. The 80 or so files changes is just every place get_tool_type exists

**Comment by nichlas0010** [comment]
@NanakoAC transparency issue fixed 👌

**Comment by nichlas0010** [comment]
image

**Pull request merged**
