### PR TITLE
Remove platting trip chance

### PR DESCRIPTION
**Pull request by SirRichardFrancis**
## About The Pull Request

What it says on the tin.

https://user-images.githubusercontent.com/65828539/172070009-f1632748-8cf7-4e8a-933b-037fc8a2233b.mp4

## Why It's Good For The Game

Everyone hates it.

## Changelog
:cl:
del: platting trip chance
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
based PR

**Comment by koghs** [comment]
allowing people to make pipeline parts of maint into highways with 0 effort is bad idea, can say it as one who did it myself 
also 
ultimate salt PR 
also 
it's not Eris if you didn't die to roach because of tripping

**Comment by ValoTheValo** [comment]
just revert this to pre SPCR tripping. so its not aids and constant

**Comment by pexel5** [comment]
YES PLEASE

**Comment by tristain01** [comment]
I approve of this, another step in the right direction.

**Review by TheShown911 — APPROVED** [review]
I like this.

**Pull request closed without merging**
