### PR TITLE
Tell player if they face dir, change face dir hotkey from ALT+DIR to ALT+CTRL+DIR

### PR DESCRIPTION
**Pull request by Kegdo**
## About The Pull Request
yea
## Why It's Good For The Game

now it's foolproof
## Changelog
:cl:
tweak: Tell player if they face dir, change face dir hotkey from ALT+DIR to ALT+CTRL+DIR
/:cl:

### CODE REVIEW

**Comment by Omni44** [comment]
Literally only two reasons to have dir lock in the first place are to use shield under current system, and shoot using scope while moving. If you want to do that, we're far better off just liquidating this absolute meme of a feature alltogether (as we should). Especially since people _will_ dir lock by accident like it happens all the time and this will fuck them over.

**Comment by Kegdo** [comment]
> Literally only two reasons to have dir lock in the first place are to use shield under current system, and shoot using scope while moving. If you want to do that, we're far better off just liquidating this absolute meme of a feature alltogether (as we should). Especially since people _will_ dir lock by accident like it happens all the time and this will fuck them over.

I unironically need this feature to (brace for cringe) ROLEPLAY, so not gonna kill this feature. Will tryna make it more obvious that you locked your dir(which is already hard to do, SHIFT+ALT + arrow key, how can one be so dumb)

**Comment by Omni44** [comment]
It's alt+arrow key by default, and yes, people ask about how to undo it ooc all the time already.
This "feature" serves absolutely no good purpose, except for scope

**Comment by ValoTheValo** [comment]
Salt PR. Just remove the shield giving you protection while on back. This will just lead to frustrating scenarios

**Comment by Kegdo** [comment]
>remove shield protection

hmm yes, I put a huge chunk of steel on me back, sacrificing my backpack slot, just to gain nothing in return. Seems legit.

**Comment by Kegdo** [comment]
image
also

**Comment by ValoTheValo** [comment]
Facedir has uses like using a flashlight while in combat or taking a hostage and not getting shot in the back. The shield giving you protection while on your back is the problem in this.

**Comment by ValoTheValo** [comment]
> > remove shield protection
> 
> hmm yes, I put a huge chunk of steel on me back, sacrificing my backpack slot, just to gain nothing in return. Seems legit.

You can still use the sheild by taking it off. You just dont need to carry the thing everywhere in your hand. Thats the benifit.

**Comment by CeUvi** [comment]
epic shield nerf
can't even use shields as, *you know*, shields, since you need to face-dir and also shoot.

also alt+shift is a standart hotkey for changing language

**Comment by vode-code** [comment]
> epic shield nerf
can't even use shields as, you know, shields, since you need to face-dir and also shoot.

some of us can win without using guns, and shields can help with that either way.

**Comment by CeUvi** [comment]
only faction that get shields are IH (gun based) and NT (melee based)
i guess you can freely remove shields from IH now.

**Comment by Kegdo** [comment]
when the spriter boy is salty!
just, you know, don't use facedir, you still face a direction, you just aren't locked to it, so you can't cheese the LMG+Shield tactic

**Comment by CeUvi** [comment]
bro, I don't want to cheese LMGs, I want to look at one direction with a shield, using my sidearm (shooting the same direction) and also moving without constantly rotating myself and getting hit 1000 times, you dumbass.

**Comment by Kegdo** [comment]
clearly a skill issue. Get better.

**Comment by CeUvi** [comment]
your skills are questionable too, since you couldn't find a proper solution to the issue.

**Comment by glaciusinfinity** [comment]
Isn't the more logical solution to limit the angle of where you are able to shoot your gun? This just seems like a bizarre way to balance this because you are making less viable by making it more annoying to use.

**Comment by CeUvi** [comment]
> more logical solution

definitely there is a more logical solution but
damn!
kegdo can't code!

**Comment by Kegdo** [comment]
You know, I was planning to do a better solution later, or let humon do that
But
Now
I don't want to
Just to see you seethe

**Comment by CeUvi** [comment]
reverting this pr instantly after it's merge
cry about it

**Comment by Kegdo** [comment]
image
image
image

the person who coded them shields approves this pr, silence now, powergamers

**Comment by Kegdo** [comment]
#6826 makes a different solution, so I'll just tweak facedir a bit

**Comment by Humonitarian** [comment]
> 

I referred to shooting backwards specifically, I thought you meant that and not this. Oh well.

**Review by zombiemimic — APPROVED** [review]
Kegdo has de-salted the PR. Thank you

**Comment by CeUvi** [comment]
thanks kegdo, very cool

**Comment by Humonitarian** [comment]
Alt+control is a little complicated, no? I feel like it would be hard to do with one hand only

**Comment by Kegdo** [comment]
Isn't that hard, and it's better than """accidentally""" locking yourself.

**Comment by ValoTheValo** [comment]
> Literally only two reasons to have dir lock in the first place are to use shield under current system, and shoot using scope while moving. If you want to do that, we're far better off just liquidating this absolute meme of a feature alltogether (as we should). Especially since people _will_ dir lock by accident like it happens all the time and this will fuck them over.

There is also using flashlight when fighting in maint or taking a hostage and not getting shot in the back.

**Review by hyperioo — APPROVED** [review]
Looks good now. I have no idea why caused such a heated discussion but currently it's a just a better notification for the player and a hotkey change

**Pull request merged**
