### PR TITLE
new technomancer helmet and armor sprotes

### PR DESCRIPTION
**Pull request by CeUvi**
## About The Pull Request
Made Techbro's technomancer armor sprites cooler
image
image
image

## Why It's Good For The Game
more cool sprotes

## Changelog
:cl:
imageadd: "new" technomancer armor sprite
imageadd: "new" technomancer helmet sprite and the second helmet sprite
add: Randomizer to spawn with one or the other helmet
/:cl:

### CODE REVIEW

**Comment by 1glitchycent** [comment]
Based. Speedmerge.

**Review by TorinoFermic — APPROVED** [review]

**Comment by Medcar** [comment]
the armor literally got resprited a couple days ago

**Comment by CeUvi** [comment]
> the armor literally got resprited a couple days ago

yes and

**Comment by Wouju** [comment]
> the armor literally got resprited a couple days ago

From what I know people didn't like the first one.
This re-sprite of a re-sprite looks better anyways.

**Review by Wouju — APPROVED** [review]

**Review by genessee596 — APPROVED** [review]
I like how both helmet types can spawn to give the 'weird science' vibe of technomancy

good job

**Comment by genessee596** [comment]
Got maintainer and delegate approval, merging now

**Comment by Garen7** [comment]
new helmet better old armor better

**Pull request merged**
