### PR TITLE
Stiffness and obscuration removal try 2

### PR DESCRIPTION
**Pull request by Iglpigl**
## About The Pull Request

Same as #7983.

## Why It's Good For The Game

Same as #7983.

## Testing

Same as #7983.

## Changelog
:cl:
del: Removed stiffness and obscuration
/:cl:

### CODE REVIEW

**Comment by Pink-Chink** [comment]
Remove the variables and defines you commented out, too.

**Comment by ValoTheValo** [comment]
Based PR

**Comment by thevandie** [comment]
Immaculately based

**Comment by TheShown911** [comment]
If you want to remove it, remove it, don't just comment it out.

**Review by hyperioo — CHANGES_REQUESTED** [review]
Delete the lines instead of commenting.

**Comment by Iglpigl** [comment]
> Delete the lines instead of commenting.

Done.

**Review by hyperioo — APPROVED** [review]

**Pull request merged**
