### PR TITLE
kitchen storage again

### PR DESCRIPTION
**Pull request by zombiemimic**
## About The Pull Request
kitchen storage and club worker maint access

image

## Why It's Good For The Game
club is bad, this will make it less bad

## Changelog
:cl:
add: balls crushed hard enough to map kitchen storage again
add: club worker has maint access
/:cl:

### CODE REVIEW

**Comment by Wouju** [comment]
is there underplating beneath the catwalks?

**Comment by zombiemimic** [comment]
> is there underplating beneath the catwalks?

yes

**Comment by Wouju** [comment]
> > is there underplating beneath the catwalks?
> 
> yes

image

**Comment by TheShown911** [comment]
Don't know how this should be handled due to the mapping contest.

**Comment by Firefox13** [comment]
@TheShown911 This PR was made before mapping contest was organized, so it isn't part of it.

**Review by Firefox13 — APPROVED** [review]

**Pull request merged**
