### PR TITLE
Buff respawn timer reduction

### PR DESCRIPTION
**Pull request by SirRichardFrancis**
## About The Pull Request

Drone respawn timer - 5 minutes.

Human respawn timer reduction:

Went in cryo healthy - 25 minutes.
Went in cryo wounded - 20 minutes.
Put in the morgue - 15 minutes.
Dissolved in bioreactor - 15 minutes.
Stolen by commies - 15 minutes.
Spaced in a coffin - 25 minutes.

## Why It's Good For The Game

Keeping players out of the game benefits literally nobody, currently players are unlikely to stick around and wait for long respawn timer.

## Changelog
:cl:
tweak: increased respawn timer reduction from most sources
/:cl:

### CODE REVIEW

**Comment by SirRichardFrancis** [comment]
Bruh.
image

**Review by TheShown911 — COMMENTED** [review]
I mean sure, but i think people don't respawn because they loose all their loot and stats, not because they have to wait.

**Comment by FortuneMaster** [comment]
What shown and others have said multiple times - second part of the problem is you losing all your round progress and having to restart, which isn't fun. As for reducing timer, first two are basically useless(unless you're going to metagame by stashing your loot somewhere), because people who go to cryo are doing it with the intention of leaving the game, morgue and coffin face the problem of having any initiative or any sort of award for putting dead ones in them. Excel and biogenerator are fair(maybe we should be considering reducing timer to 10-15 minutes in general though)

**Comment by SirRichardFrancis** [comment]
> I mean sure, but i think people don't respawn because they loose all their loot and stats, not because they have to wait.

> What shown and others have said multiple times - second part of the problem is you losing all your round progress and having to restart, which isn't fun.


Can't find that conversation in discord now, but I wanted to address that issue before, by giving people that join late in the round, better stats and starting loadout, (to catch up with players who've been junking/leveling/received paychecks/whatever for hours, or to compensate for their own lost progress) but been told that it's absolutely haram.
So if we can't have better solution, let's have none at all, riiiight.

> As for reducing timer, first two are basically useless(unless you're going to metagame by stashing your loot somewhere), because people who go to cryo are doing it with the intention of leaving the game, morgue and coffin face the problem of having any initiative or any sort of award for putting dead ones in them.

What about joining as a technomancer, who is required to start, and rejoin later to play character and job you initially wanted?
I personally have done that many times, tho it might be odd for someone who doesn't play the game.

Tbh, starting "loot" is not worth abusing, aside of maybe tau cross necklace, but pulling that off with head roles is already bannable.

> Excel and biogenerator are fair(maybe we should be considering reducing timer to 10-15 minutes in general though)

That's out of my reach, iirc server config is involved.

**Comment by SirRichardFrancis** [comment]
Found it.

image

image

**Comment by assortedbeads** [comment]
> Can't find that conversation in discord now, but I wanted to address that issue before, by giving people that join late in the round, better stats and starting loadout, (to catch up with players who've been junking/leveling/received paychecks/whatever for hours, or to compensate for their own lost progress) but been told that it's absolutely haram.
> So if we can't have better solution, let's have none at all, riiiight.

Personally I find it odd that people are against letting late joiners catch up.

Eris is combat focused and has stats unlike tg/bee/goon. In these servers you can late join and not need a balancing act because everyone is baseline, at most people have gotten augs or loot or something.

Here in every area of character creation stats are important, and simply by being active in round you level quickly, even more so with oddities.

It feels like giving late joiners set incremental stat boosts should be easy to agree on. 
They wont be as strong as someone who has been leaning hard into stats, but they wont be so far being the curve simply because they joined one hour in, or even thirty minutes in.

**Comment by FortuneMaster** [comment]
> > As for reducing timer, first two are basically useless(unless you're going to metagame by stashing your loot somewhere), because people who go to cryo are doing it with the intention of leaving the game, morgue and coffin face the problem of having any initiative or any sort of award for putting dead ones in them.
> 
> What about joining as a technomancer, who is required to start, and rejoin later to play character and job you initially wanted? I personally have done that many times, tho it might be odd for someone who doesn't play the game.
> 
Then why have that requirement in the first place?

**Comment by SirRichardFrancis** [comment]
> Then why have job requirement in the first place?

Because absence of energy and shields is bad for the ship, also someone have to fix broken stuff later in the round.

**Comment by FortuneMaster** [comment]
> > Then why have job requirement in the first place?
> 
> Because absence of energy and shields is bad for the ship, also someone have to fix broken stuff later in the round.

Why not just make engine set from roundstart? Following the logic of the second part of reply we should make every job required to start the round

**Comment by SirRichardFrancis** [comment]
> Why not just make engine set from roundstart?

Answer is, because it's part of SS13 engineer's routine for over 10 years, replace the engine with dummy prop that makes power and that routine ends on shoving five shovels in the Cube.

> Following the logic of the second part of reply we should make every job required to start the round

Go ahead, make it.

**Review by hyperioo — APPROVED** [review]

**Comment by hyperioo** [comment]
Should not hurt anyone, so why not

**Pull request merged**
