### PR TITLE
Fix poltergeists

### PR DESCRIPTION
**Pull request by SirRichardFrancis**
## About The Pull Request

Prevents ghosts from moving items on tables, racks and low walls.

image

## Why It's Good For The Game

Fixes cool.

## Changelog
:cl:
fix: ghosts moving items on tables, racks and low walls
/:cl:

### CODE REVIEW

**Comment by Omni44** [comment]
Literally souless.

**Comment by Iglpigl** [comment]
This is not a bugfix this is just straight up feature removal, mouse mains already got destroyed when shitty optimization PRs got merged and now ghost gameplay is getting shafted too, I urge you to reconsider, close this PR and actually let all ghost mains enjoy what they do the best, not remove it because one person classified it as a bug.

**Comment by SirRichardFrancis** [comment]
> This is not a bugfix this is just straight up feature removal

That's clearly an oversight, not an intended feature.

> mouse mains already got destroyed when shitty optimization PRs got merged

Mouse mains... lol
image

> and now ghost gameplay is getting shafted too

Ghost gameplay is not a thing,

> let all ghost mains enjoy what they do the best

Ghost mains.
image

**Comment by TheShown911** [comment]
I have noticed a long trend of developers stealthily and consistently removing the heart of eris's's ghost, mouse and lobby gameplay. Ever since the message spam from the character creation about augmentations got removed the lobby gameplay has suffered substantially, as you can't look at the fast colorful messages anymore. I will stand for this no more. Next thing the shadow anti-mouse/ghost/lobby metadev coalition clique will do is "fix" mouse goonchat, destroying the high roleplay mouse gameplay
unknown-151
With a heavy heart I cannot approve this PR in my good consciousness.

**Review by TheShown911 — APPROVED** [review]

**Comment by SirRichardFrancis** [comment]
> Next thing the shadow anti-mouse/ghost/lobby metadev coalition clique will do is "fix" mouse goonchat, destroying the high roleplay mouse gameplay !

Completely untrue!

**Comment by MLGTASTICa** [comment]
> This is not a bugfix this is just straight up feature removal, mouse mains already got destroyed when shitty optimization PRs got merged and now ghost gameplay is getting shafted too, I urge you to reconsider, close this PR and actually let all ghost mains enjoy what they do the best, not remove it because one person classified it as a bug.

Fuck mouse mains

**Comment by Omni44** [comment]
I get that you're ironing out bugs, and it's a good thing, bless you for this, but this is such minor thing that can't even really influence anyone in any way that also plays into the whole "ancient ship with unknown past and strange stuff happening" lore that  I don't even see a point.

**Comment by ValoTheValo** [comment]
literally unplayable. how are us dchat mains gonna get our kicks now?

**Comment by ValoTheValo** [comment]
> I get that you're ironing out bugs, and it's a good thing, bless you for this, but this is such minor thing that can't even really influence anyone in any way that also plays into the whole "ancient ship with unknown past and strange stuff happening" lore that I don't even see a point.

kinda agree with you but sometime it just gets on the nose. if it was somehow tied to sanity that would be extremely based

**Comment by Sparrowbird611** [comment]
We'd be better off tying it to bluespace rapture or whatever area mechanic we have is than sanity.

Also damn this thread is really popular relative to what it does.

**Review by mattroks101 — APPROVED** [review]

**Pull request merged**
