### PR TITLE
roachsign now emits a bit of light

### PR DESCRIPTION
**Pull request by Twomoon-Github**
## About The Pull Request

Makes the roachsign emit a little blue light.

## Why It's Good For The Game

Make it looks cooler, more flavor for the roachdiner that will use it (cave update)

## Testing

all good, as the pic show
roachsignlight

## Changelog
:cl: Twomoon
tweak: tweaked the roachsign code
/:cl:

### CODE REVIEW

**Review by TheShown911 — APPROVED** [review]
Soul

**Comment by SirRichardFrancis** [comment]
This doesn't call the parent proc where initialization magic happens, sign will be marked as uninitialized in atom subsystem's logs and may have issues with it's plane (it's not being calculated) if it's ever mapped in.

@hyperioo @TheShown911 Why did you approve and merge this?

**Comment by Twomoon-Github** [comment]
> This doesn't call the parent proc where initialization magic happens, sign will be marked as uninitialized in atom subsystem's logs and may have issues with it's plane (it's not being calculated) if it's ever mapped in.
> 
> @hyperioo @TheShown911 Why did you approve and merge this?

i dont understand what it is, but i havent seen any problem, both on spawned sign, and on sign premapped (only in a POI not yet in the main game, but will be with the cave update, and it had no problem, its the roachdiner)

anyway if needed i can check more into it later, i will be out for two weeks, and no computer will be available tho

**Comment by SirRichardFrancis** [comment]
What no plane initialization does, for reference:
image

As long as that sign isn't mapped anywhere near open spaces and no one looks into SSatom's logs, it's kind of fine...
But not really.
If you don't understand what something does or, say, why there is funny `..()` and `. = ..()` things all over the code and what they do - just ask in the #coding-tent.

**Comment by TheShown911** [comment]
Yeah, you need to return initialization hints on init, just a .=..() should fix everything.

**Comment by Twomoon-Github** [comment]
thanks, will fix it when im back home, see you in two weeks lol

**Pull request merged**
