### PR TITLE
Crafting PR and Shield Tweaks

### PR DESCRIPTION
**Pull request by assortedbeads**
## About The Pull Request
This PR creates a new craftable riot shield, the (bull)Dozer shield. 
It's the door of a locker that's been weighted down with armor parts and liberal amounts of plasteel, it's strong and a passable melee weapon, but slows you down as long as you hold it.
Wearing it is fine though.
You can bang on it with all swords and hammers.
On the topic of hammers, the non-makeshift mace is craftable now.

This PR also makes shields wearable in your suit storage. Rejoice NT mains, your time is here.

Lastly this PR buffs the integrity of the hardsuit shield, and gives the Dozer shield it's old integrity.

## Why It's Good For The Game
The addition of a craftable riot shield (I will not count the tray shield as such because it is a disgrace) helps diversify playstyles. 
I feel like the addition of making it automatically slow you (humon's suggestion) means you have to think more with it.
Also it apparently was supposed to be in the game anyway.

Shields being wearable in your suit slot is good for inventory management. While shields are useful, they are rarely ever worth giving up for an entire bag.

Sprite Dump (Shout out to Shaz for helping me figure these out)

Dozer Back Left Hand Dozer Front Left Hand
Dozer Left Left Hand Dozer Right Left Hand

Wall Back Wall Front
Wall Left Wall Right

Slung Back Slung Right
Slung Front Slung Left

Lowered Back Lowered Front
Lowered Right Lowered Left

## Changelog
:cl:
add: Added a new riot shield, the Dozer shield and an accompanying crafting recipe 
add: Adds a recipe for the non-makeshift mace
tweak: You can now store your shields in your suit storage
balance: Buffed the Rig hardsuits integrity
fix: fixed a few things
imageadd: added sprites for the new shield
/:cl:

### CODE REVIEW

**Comment by DiaFRAME444** [comment]
Now you can slap multiple Verutum spears in the NT shield and then drop it in your suit storage, effectively meaning that shields went from removing inventory space to giving you more of it.

**Comment by tristain01** [comment]
I, for one like this, more melee options for actual melee gaming.

**Comment by garrulousTeamotei** [comment]
So, I'm assuming the Dozer follows the other riot shields quirk of being useless unless you're walking? So, it's walk speed and slowdown?

**Comment by DiaFRAME444** [comment]
> I, for one like this, more melee options for actual melee gaming.

The shield is not a melee weapon- Its meant to be comboed with throwing spears. This is because of its delibitating walkspeed penalty.
Of course you can get around that by switching it walk on adn off, but the better option for melee is the Buckler.

> So, I'm assuming the Dozer follows the other riot shields quirk of being useless unless you're walking? So, it's walk speed and slowdown?

I believe its meant to make running at full speed with it by switching walk and run unviable.
Not much of a issue, since you can just put it in your suit storage and avoid the slowdown.

**Comment by garrulousTeamotei** [comment]
>Not much of a issue, since you can just put it in your suit storage and avoid the slowdown.
Just like the maxim

And, I'm hoping the sprite for the shield while running is hiding somewhere?

**Comment by assortedbeads** [comment]
> So, I'm assuming the Dozer follows the other riot shields quirk of being useless unless you're walking? So, it's walk speed and slowdown?

Yes, walk speed and slowdown in return for easy crafting and good stats defensively

**Comment by assortedbeads** [comment]
> >Not much of a issue, since you can just put it in your suit storage and avoid the slowdown.
> 
> Just like the maxim
> 
> And, I'm hoping the sprite for the shield while running is hiding somewhere?

Running sprites are in the dmi I just got lazy, Ill toss them up later

**Comment by assortedbeads** [comment]
> > Not much of a issue, since you can just put it in your suit storage and avoid the slowdown.
> 
> Just like the maxim
> 
> And, I'm hoping the sprite for the shield while running is hiding somewhere?

Added running screenshots

**Review by hyperioo — APPROVED** [review]

**Pull request merged**
