### PR TITLE
Alcohol tweaks

### PR DESCRIPTION
**Pull request by Humonitarian**
## About The Pull Request

Increases lethality of alcohol, reduces the rate of annoying effects, improves sanity scaling via strength, makes more complex cocktails scale better and provide more sanity.

Adds the lore-accurate Pan Galactic Gargle Blaster, with lore-accurate effects, leaving the old one as Pan Galactic Gargle Blaster Lite!

## Why It's Good For The Game

I am piss drunk

## Changelog
:cl:
tweak: alcohol gives more sanity
tweak: alcohol more lethal
add: lore-accurate gargleblaster
balance: serb vendor vodka price increased to match increased sanity gain
/:cl:

### CODE REVIEW

**Comment by Holvr0** [comment]
Drink up!

**Comment by TheShown911** [comment]
Fails all checks, suspicious.

**Comment by Humonitarian** [comment]
> Fails all checks, suspicious.

Clearly, there are no issues. I merely got the compiler drunk too!

**Comment by Humonitarian** [comment]
On second hand, the 123 warnings are suspicious.

**Review by Firefox13 — APPROVED** [review]
Looks ok

**Pull request merged**
