### PR TITLE
Rescue Borg: Stop the bleeding.

### PR DESCRIPTION
**Pull request by FennecTheFennec**
### About The Pull Request
---
Adds Bruise Packs and Ointment to Rescue borgs, at current they cannot bandage the wounds of patients they are attempting to rescue.

### Why It's Good For The Game
---

Rescue Borgs can now stop bleeding of patients they are attempting to rescue.

### Changelog
---
🆑
add: Added Bruise and Burn packs to the Borg Rescue Module
/🆑

### CODE REVIEW

**Comment by SpadesSlick** [comment]
Please add the changelog entry.

**Comment by FennecTheFennec** [comment]
When I figure out how, I definitely will.

**Comment by Deon-DF** [comment]
You just need to modify the description of the PR According to the guidelines which you replaced when you wrong your description.

**Comment by FennecTheFennec** [comment]
Done.

**Comment by Deon-DF** [comment]
I am pretty sure Spades meant you would want to edit the description of the pull request and add this:

## About The Pull Request

Adds Bruise Packs and Ointment to Rescue borgs, at current they cannot bandage the wounds of patients they are attempting to rescue.

## Why It's Good For The Game
Quality of life improvement.

## Changelog
:cl:
add: Added Bruise and Burn packs to the Borg Rescue Module
/:cl:

**Comment by FennecTheFennec** [comment]
@Deon-DF What about that?

**Pull request merged**
