### PR TITLE
HICU: Huge Integrated Circuit Update

### PR DESCRIPTION
**Pull request by Doster-d**
## About The Pull Request

This pull request is port from Onyxbay, TG, Baystation circuit code. 

Old circuits code are not removed, but disabled.

Added new systems to optimization circuit stuff, like:
- Circuit Components. Fires do_work proc only if tick have some space for it.
- Circuits. Initialize circuits and generate key for XOR encryption 

Added circuit copy/pasting (cloning).

Added many circuits so descriptions these circuits will be at least like "Война и Мир".

Added/updated related stuff for circuits, like fonts, css files.

Updated interface for assemblies, now it look like interface of Visual Studio Code.

Potentially fixes old bugs with circuits.

## Why It's Good For The Game

The old circuits code are... Outdated.
The PR's circuits are good, contains numerous bug fixes.

## Changelog
:cl:
add: Circuit Component subsystem to optimization circuit do_work proc.
add: Circuit subsystem to optimization initialization stuff.
add: New numerous circuits.
add: circuits cloning ability.
tweak: Updated interface for assemblies, now it look like interface of Visual Studio Code.
del: Disabled old circuit subsystem.
soundadd: added some new sound for circuits, like tripple beep sound.
soundadd: added HEV suit sound from HL2. (Circuits only)
soundadd: added AI sounds from System Shock. (Circuits only)
admin: Added secret to disable/enable circuit proc do_work firing.
config: Added config var to disable circuit cloning
/:cl:

Please check MMI tank, PAI holder and AI holder circuits, I can miss some mistakes.

### CODE REVIEW

**Comment by Doster-d** [comment]
+13.029

**Comment by Doster-d** [comment]
Added AI control circuit

**Comment by Zert0X** [comment]
изображение

**Comment by Doster-d** [comment]
Example of new interface for assemblies:

**Comment by drexample** [comment]
Capital! Dare I say based. 
But we are unsure on circuit cloning being uh... 
Balanced?

**Comment by Doster-d** [comment]
> Capital! Dare I say based. 
> But we are unsure on circuit cloning being uh... 
> Balanced?

You can disable cloning in config.

**Comment by drexample** [comment]
Yeah, fair.

**Review by drexample — APPROVED** [review]
based and circuitpilled

**Pull request merged**
