### PR TITLE
Fix for supermatter monitor gasses

### PR DESCRIPTION
**Pull request by EvenInDeathIStillServe**
Game tracked "phoron" instead of "plasma", meaning the plasma percent was always 0%. Fixed and changed the "PH" for phoron to "PZ" for plasma.
Removed the H2 tracking because we don't have that gas.

### CODE REVIEW

**Comment by GrayRachnid** [comment]
All other consoles use TX for plasma. Might want to use that.

**Comment by EvenInDeathIStillServe** [comment]
Done

**Comment by NanakoAC** [comment]
noo don't use TX, its dumb
PZ is fine

**Comment by GrayRachnid** [comment]
:thonk:

PZ sounds very stupid if I were to be honest.

**Comment by EvenInDeathIStillServe** [comment]
TX, standing for Toxin, makes it sound like Plasma is a BAD thing that you DON'T want interacting with your engine. PZ, however, sounds like an eco-friendly energy source that definitely belongs in a absurdly high pressure & temperature environment.

**Pull request merged**
