### PR TITLE
station bounded radio respite

### PR DESCRIPTION
**Pull request by CeUvi**
## About The Pull Request
read the title
radio

## Why It's Good For The Game
da

## Changelog
:cl: CeUvi
imageadd: new sprites for walkietalkie
/:cl:

### CODE REVIEW

**Comment by thedarkcrusader** [comment]
i want to see it in game on a table post  a picture of it on a table please

**Comment by CeUvi** [comment]
image

**Comment by Firefox13** [comment]
изображение
This might be icondiff issue but are you sure there are no stray pixels?

**Comment by CeUvi** [comment]
> This might be icondiff issue but are you sure there are no stray pixels?

yes, i am.

**Review by Firefox13 — APPROVED** [review]

**Pull request merged**
