### PR TITLE
Fuck it, cyberspace from kotmap

### PR DESCRIPTION
**Pull request by AlexMorgan3817**
## About The Pull Request

Cyberspace

## Why It's Good For The Game

Cyberspace

## Changelog
:cl:
add: Cyberspace
/:cl:

<h1>Cyberspace</h1>

### CODE REVIEW

**Comment by FortuneMaster** [comment]
image

**Comment by SirRichardFrancis** [comment]
Ну чо там?

**Comment by AlexMorgan3817** [comment]
> Ну чо там?

Сессия, так всё кроме интеграции с ИИ и малфом готово.
Если конечно отбросить баланс

**Comment by AlexMorgan3817** [comment]
For awaiting cyberspace: https://soundcloud.com/alexmorgan3817/blyat-traktor

**Comment by drexample** [comment]
Due to general low quality of the code, numerous critical bugs in previous contributions, several set and failed deadlines and hostile reaction to criticism we have decided that this PR is just not worth it.

We'd rather have someone code something decent from ground up and pay for it again than have our maintainers lose brain cells from your subpar code.

In around two months it's gonna be a year since you took money and delivered nothing. I wish we have done this sooner so someone more capable would have been able to take over this feature.

Hope you choke on the money you scammed our previous project leader out of.

**Comment by SirRichardFrancis** [comment]
488a6bc137ce51c4_848xH

**Pull request closed without merging**
