### PR TITLE
FS Guns to FS Vendor Overpriced Edition & Molly Price Reduction

### PR DESCRIPTION
**Pull request by ValoTheValo**
## About The Pull Request
Same as #7231 but without price changes on the majority of guns. only guns with price changes now are Gladstone. returned to its pre Billomat price and location of 2000$ and the Molly from 1800 to 1000 due to it honestly being the worst SMG in the game (0.5 Damage Multiplier on Full Auto) 

## Why It's Good For The Game
Makes sense for FS Vendor to Sell FS Guns. maybe people will buy the molly now

## Changelog
:cl:
tweak: Colt 1911, Molly and Gladstone moved from Billomat to FS Vendor
balance: Molly Item Price reduced by 400$ to 1000 (From 1400)
balance: Molly Vendor Price reduced by 800$ to 1000 (From 1800)
balance: Gladstone returned to original price of 2000$
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
Firstly there is absolutely no reason for this to be made, secondly it will screw up loot and make all these items more common, thirdly, one and possibly more items price changes are direct violation to contributing guidelines, you should try reading them.
https://wiki.cev-eris.com/Content_GuidelinesEn

**Comment by thedarkcrusader** [comment]
> Firstly there is absolutely no reason for this to be made, secondly it will screw up loot and make all these items more common, thirdly, one and possibly more items price changes are direct violation to contributing guidelines, you should try reading them. https://wiki.cev-eris.com/Content_GuidelinesEn

If this has absolutely no reason to be made, then why was it made in the FirstPlace?

**Comment by Firefox13** [comment]
but didn't I said already that those intentionally overpriced guns should stay in an intentionally overpriced vendor?

**Comment by ValoTheValo** [comment]
> but didn't I said already that those intentionally overpriced guns should stay in an intentionally overpriced vendor?

They are still intentionally overpriced???

**Comment by ValoTheValo** [comment]
I can move the AK back if thats really nessicary as its the only ludicrously overpriced gun. And that doesnt fit the """self defense""" theme or whatever.

**Comment by Firefox13** [comment]
> They are still intentionally overpriced??? Just in a different spot.

let the meme vendor remain a meme vendor

**Comment by ValoTheValo** [comment]
> > They are still intentionally overpriced??? Just in a different spot.
> 
> let the meme vendor remain a meme vendor
Wouldnt say the deckard or colt are that overpriced here or really worth of being memes. And i made the molly not a complete waste of money. Not like the vendor still isnt a meme. It still has the Z8, Regulator, Mandella and COG at egregious prices

**Review by TheShown911 — APPROVED** [review]
Fix your commits mate

**Pull request merged**
