### PR TITLE
Adds long enforcer overcoat and brown variant of the serbian overcoat

### PR DESCRIPTION
**Pull request by Smokingsquirrel**
#4000  About The Pull Request

Adds new long enforcer overcoat and brown variant of the serbian overcoat.

## Details

<details>
  <summary>Expand</summary>
Adds long enforcer overcoat to loadout, adds brown serbian overcoat to brown uniform kit from Serbian vendor.
Adds icon states and item states to brown  serbian overcoat and long enforcer coat.
</details>

## Screenshots
See Sprite pit for details.

### CODE REVIEW

**Comment by Nozarati** [comment]
image 1

image 2
Coats look good, both obtainable.

**Comment by mattroks101** [comment]
image
That looks like a codersprite if I've ever seen one.

**Comment by Smokingsquirrel** [comment]
> image
> That looks like a codersprite if I've ever seen one.

Fixed the sprite and made some adjustments, hopefully its not the dreaded word again. 
[https://s12.directupload.net/images/200430/rzkn9whh.png](url)

**Comment by Smokingsquirrel** [comment]
No this is done

**Pull request merged**
