### PR TITLE
Craftable gun parts + Gun frame tweaks

### PR DESCRIPTION
**Pull request by zombiemimic**
## About The Pull Request
For ease of ghetto gunsmithy

## Why It's Good For The Game
to ease up on maintainence gun rushing

## Changelog
:cl:
add: Vagabonds can now ape gun parts they have found
tweak: Vagabonds forgot how to make crazy expensive guns with frames
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
Considering that you can craft a Dallas , Vintorez  , Wintermule , Pulemyot , basically any weapon with the gun assembly , this is not good for balance. If you want to make gun assemblies , get guns and money to buy disks and materials to print more.

**Comment by Omni44** [comment]
1. Aren't gun parts made of 5 plasteel, and shouldn't they therefore costs even more for the purpose of that recipe to factor in material loss and makeshift nature of the whole thing?
2. Shouldn't sawing come before welding?
3. What SPCR said.

**Comment by Sparrowbird611** [comment]
The assembly needs to be reworked, so I agree with MLG in that aspect, but I think this is a good idea for the most part. If you can significantly limit the available guns from the assembly or even better just remove it, this would be good.

Other minor issue is that you should make the actual gun part cost 3 plasteel and 1 steel when deconstructed to line up with this recipe, since idk how you'd make it cost 1.2 plasteel to craft.

**Comment by Sparrowbird611** [comment]
> 1. Aren't gun parts made of 5 plasteel, and shouldn't they therefore costs even more for the purpose of that recipe to factor in material loss and makeshift nature of the whole thing?
> 2. Shouldn't sawing come before welding?
> 3. What SPCR said.

They are 1.2 plasteel for some reason.

**Comment by Omni44** [comment]
>They are 1.2 plasteel for some reason. 
Weird? I swear it was said to be 5.

The whole thing with assembly and being able to craft all weapons, with just power of your own hands and big brainess, including but not limited to supposedly super rare relic gun like valkyrie, or Dallas, and that it's far preferable to actually printing it at lathe is whack as fuck, ngl.

**Comment by vode-code** [comment]
Whenever you nerf crafting gun parts this way via increasing the material cost, you are by necessity also nerfing Artist, who requires creating art, including artistic gun parts, to level.
I would suggest that you lower the plasteel cost to two, and change the list of available guns using the gun assembly based on gun rarity and the user's Mech stat.

**Comment by vode-code** [comment]
oh, never mind, I looked at code for the artist bench and it randomizes the matter.

**Review by TheShown911 — COMMENTED** [review]
Would be too powerful with the current strength of the gun assembly.

**Comment by zombiemimic** [comment]
> Would be too powerful with the current strength of the gun assembly.

Should I change the amount of parts for the assembly?

**Comment by Sparrowbird611** [comment]
> > Would be too powerful with the current strength of the gun assembly.
> 
> Should I change the amount of parts for the assembly?

You should see if you can change how the assembly works, or at least disable it for now. Currently it can make things like valkyries and what not. At least limiting it to far lower level guns.

**Pull request closed without merging**
