### PR TITLE
Aberrant Organs

### PR DESCRIPTION
**Pull request by Pink-Chink**
## About The Pull Request

This introduces aberrant organs, which are modular organs with functions outside of the normal organ efficiencies. They operate on a physiology-themed input/output concept where the input is a stimulus (injected/ingested/touched reagent, injury, etc.) and the output is a response (reagents in the blood/stomach, chemical effects, stat boost, etc.). There is an intermediate processing step where the inputs are mapped to the outputs, if there are multiple of each, or the inputs are amplified. Inputs, processes, and outputs are modular and can be attached or removed as desired with the right tool and stat/perk.

### Basics
To start, this features adds basic organ modifications:
mods

- Improved capillaries - reduces blood, nutriment, and oxygen requirement by 10%
- Durable membrane - increases bruised, broken, and max damage thresholds by 40%
- Stem cell application - increases organ efficiencies by 10% (cannot be removed)
- Visceral symbiont - increases organ efficiencies by 20%, but increases blood, nutriment, and oxygen requirement by 20%
- Bypass tubules - reduces blood, nutriment, and oxygen requirement by 20%, but reduces organ efficiencies by 20%
- Biostructure gel - adds two more upgrade slots, but increases organ size by 0.5
- Masked membrane - hides organ from scanners, but reduces organ efficiencies by 10%

The meat of this feature is the "organoids", which are mods that control the input/output behavior of a new internal organ type called a "scaffold". Scaffolds are functionless organs, but are able to trigger the input, processing, and output functions of the attached organoids, unlike standard organs. Each scaffold can only hold one of each type of organoid.

organoids
organs

In order to determine the exact function of each organoid, players will need to have 50 BIO to obtain full information. To use them, attach an input organoid, a processing organoid, and an output organoid to a scaffold and insert it into a player mob via surgery. Then, the owner of the organ just needs to perform whatever the input asks to generate the output. Most scaffolds will only process the whole thing once every 10 seconds.

image

### Machines

- Regurgitator regurg
  - Processes organs, organ mods, and several reagents into biotic substrate, which is turned into flesh cubes when at 60 or higher. Requires retracting and clamping tools to open and disassamble, respectively. To upgrade, you'll need different organs or organs of higher efficiency. Try using organs related to digestion or filtration.
- Organ Fabricator organ_fab
  - Specialized autolathe for organ printing. Can only recycle flesh cubes back into biotic substrate, which is used in lieu of biomatter as a material resource. Includes a disk piracy feature, but only for Oh My Guts! disks.
- Oh My Guts! vendor organfridge
  - Deep maint vendors with pre-made aberrant organs. The hacking puzzle for the contraband inventory is a little different on these and they take a metal coin to unlock the premium inventory. 
- Medi-sarcophagus sarcophagus
  - Can be found in deep maint or very rarely in the trash as a circuit. Functions as a sleeper, but has a chance to have better chems. Mis-spelled chems are an intended feature. (De)constructable.

### Where to find

The new organ lab is in what used to be maintenance area south of surgery in medbay.

image

### Miscellaneous changes

- Back Alley Organs requires an autolathe with the ORGAN_GROWER tag instead of BIOPRINTER.
- Cruciforms will forcibly remove any mods attached to your organs.
- Added organ-related machinery to deep maint spawns.
- Added a new wire setup for hacking, which is used in deep maint vendors.
- Reduced deep maint trap count by 33% since there are new potential encounters in deep maint corridors.
- Autolathes can selectively recycle items. This feature is only used on the organ fabricator at the moment.
- Crayons end up in your stomach when eaten. Previously, they went to some other holder.

### Credits

Many thanks to vode-code for his modular gadget (input/output) concept and Infrared Baron for the sprites.

## Changelog
:cl:
add: Added aberrant organs
add: Added organ lab to medbay
add: Added medi-sarcophagus, organ vendor, organ fabricator, regurgitator, and organ fridge
add: Added new wiring for the new vendors
add: Added new deep maint spawns
tweak: Cruciforms will rip your guts out
tweak: Back Alley Organs require an autolathe with ORGAN_GROWER
tweak: Created a new spawner for deep maint that includes the aberrant machines
tweak: Organs will be in stasis when inside smartfridges and the regurgitator
tweak: Deep maint cryo room has medi-sarcophagi instead of sleepers
fix: Fixes crayon eating
code: Added some procs to internal organs to handle mods
code: Added selective recycling logic for autolathes (only used for the organ fabricator)
/:cl:

### CODE REVIEW

**Comment by Voldirs** [comment]
Wow, that sounds really cool

**Comment by githubuser4141** [comment]
holy heck yes! Actual content creation, hope this won't get shot down by the TDMheads.

**Comment by Pink-Chink** [comment]
Alrighty, should be good to review.

**Comment by glaciusinfinity** [comment]
https://tenor.com/bDMnW.gif

**Comment by glaciusinfinity** [comment]
based-so-fucking-zased

**Comment by ValoTheValo** [comment]
giga based PR

**Comment by ValoTheValo** [comment]
only thing of note is I think it would be better if they were cybernetic so you could use them with prosthetics and organics. 
still incredibly Pog update

**Comment by Pink-Chink** [comment]
If I were to do cybernetic organs, I’d want them to be mechanically distinct from these.

**Comment by garrulousTeamotei** [comment]
APC is missing from maintenance, section 2, deck 3, port, the cut down on the maintenance. Got an un-powered airlock, now.

**Comment by Pink-Chink** [comment]
Fixed.

Not a bad idea. Makes the room a little more desirable, too.

**Review by TheShown911 — APPROVED** [review]
Now instead of reviewing this I propose a test merge to the live server this launch. What could go wrong?

**Review by hyperioo — COMMENTED** [review]
_What could go wrong live-testing, right?_

**Pull request merged**
