### PR TITLE
Adds an assortment of vests that protect the arms and legs

### PR DESCRIPTION
**Pull request by genessee596**
## About The Pull Request

Adds several 'full body' variants of armor vests that have shoulderpads and kneepads. As such, they protect the legs and arms as well as the chest. They do not protect the head.

You can find this armor wherever their normal variants may be found, albiet more rarely.

They protect the same amount as their normal variant - they just cover the arms and legs as well as the chest. They have the same amount of slowdown as their normal variants.

You can craft a fullbody handmade vest in the crafting menu, under the clothing tab.
The fullbody IH vest spawns on IH operatives roundstart. You can find the basic vest without pads in IH lockers.
You can craft fullbody generic vests, fullbody bulletproof vests, and fullbody operator vests in their respective design disks.
You can buy the fullbody merc vest for 8 TC in the uplink, under 'devices and tools'.
You can find all of these in maintenance.

image
_Above: Local vagabond discovers a stash of fullbody armor._
Credit goes to Shazbot for sprites.

image
_Above: Permission from Shazbot to use his sprites._

image
_Above: Maintainer permission to make this PR._

## Why It's Good For The Game

Right now, there's a total lack of armor that protects the arms and legs except for voidsuits (which we're trying to make more rare / less armor-like) and fullbody suits that have high protection and high slowdown.

This gives players a 'light' alternative that doesn't harm their movement speed, but allows them to protect more than their chest.

Also, more armor. Woo!
## Changelog
:cl:
add: A new assortment of fullbody vests that can be found across the ship
/:cl:

### CODE REVIEW

**Comment by Garen7** [comment]
Why not just remove the armors without shoulder/knee pads these are just strict upgrades so in cases where they're available like IH and through disks the version without shoulder/knee pads will virtually never exist.

Also why make the IH operator full body spawn in their lockers, just make it spawn on them by default.

**Comment by 1glitchycent** [comment]
maybe they could be a sidgrade? Like say, for bulletproof which has 55 bullet, maybe the full armor has 45 bullet?

**Comment by Sparrowbird611** [comment]
I agree with garen personally, on both points.

Also, I recommend replacing the heavy vest you can buy in the traitor PDA with this full variant.

**Comment by TheShown911** [comment]
If players liked the old vests you could add the ability to chop of the extra bits on the new ones and get the old sprite

**Comment by genessee596** [comment]
> If players liked the old vests you could add the ability to chop of the extra bits on the new ones and get the old sprite

You can still find the old vests more commonly than the full kits in maint

**Comment by genessee596** [comment]
> Why not just remove the armors without shoulder/knee pads these are just strict upgrades so in cases where they're available like IH and through disks the version without shoulder/knee pads will virtually never exist.
> 
> Also why make the IH operator full body spawn in their lockers, just make it spawn on them by default.

ok one second

**Comment by genessee596** [comment]
> I agree with garen personally, on both points.
> 
> Also, I recommend replacing the heavy vest you can buy in the traitor PDA with this full variant.

good idea, one sec

**Comment by genessee596** [comment]
the basic vest now spawns in IH lockers, and the full vest spawns on operatives roundstart

you can now buy the fullbody merc vest in the uplink for 8 TC, compared to the basic merc vest for 6 TC

**Review by TorinoFermic — APPROVED** [review]

**Pull request merged**
