### PR TITLE
End of TG UI

### PR DESCRIPTION
**Pull request by ACCount12**
Now tell me: why do we have an entire unused *UI framework* in our codebase?

### CODE REVIEW

**Comment by mattroks101** [comment]
Bout damn time.

**Comment by TorinoFermic** [comment]
Looks good but there's runtime errors with the jukebox

`[11:10:01] Runtime in sound_player.dm,144: type mismatch: 0 - /list (/list)
  proc name: locate listeners (/datum/sound_token/proc/locate_listeners)
  usr: Bluespace Technician (torinofermic) (/mob/living/carbon/human/bst)
  usr.loc: The floor (111,84,3) (/turf/simulated/floor/tiled)`

**Comment by ACCount12** [comment]
Are you sure it's only present in this PR?

**Comment by TorinoFermic** [comment]
I only tested machines where changes was applied in this PR. Jukebox is among of them and the runtime errors and it occurs outside of this PR.

**Pull request merged**
