### PR TITLE
Added roll down shutters and button to lock down the "cash register" area

### PR DESCRIPTION
**Pull request by Z4ph0d42**
## Details
Added a button to the left (outside) of the merchant door, so it should be acessable by any one in the guild.

## Screenshots

image

### CODE REVIEW

**Comment by Z4ph0d42** [comment]
To clarify this is different than total lockdown.

Lockdown covers cargo.
This is more just to close up shop and stop the constant stream of broken glass flowing into cargo

**Comment by Z4ph0d42** [comment]
Also this was my first map PR, I no realize didn't use the mapmerger thing in the read me file.
I think this PR wont conflict with any thing else and can still be made either way.
Next time I'll make my map pulls correctly.

**Comment by Kurgis** [comment]
@Z4ph0d42 https://tgstation13.org/wiki/Map_Merger

**Comment by Z4ph0d42** [comment]
ok, reject it.
Ill re do it correctly.

**Pull request closed without merging**
