### PR TITLE
New gun and grab-fu sounds

### PR DESCRIPTION
**Pull request by Humonitarian**
## About The Pull Request

Guns get a bunch of new sounds based on caliber, plasma Vaporize mode has a new sound, and there are two new grab-fu sounds.

All sounds made by Kegdo. Manual (coding) labour incentivized by Kegdo.

## Why It's Good For The Game

Aural immersion.

## Changelog
:cl:
soundadd: new sounds for all gun calibers
soundadd: new sounds for grab-fu
soundadd: new sounds for all plasma weapons
soundadd: new shield sound
/:cl:

### CODE REVIEW

**Comment by Kegdo** [comment]
yes, now merge it

**Comment by thedarkcrusader** [comment]
> You forgot to mention WHO made them. Shield also gets a block/parry sound. To be specific, all guns but .60 AMR get a new sound; cap gun and gyrojet gun(can not even spawn lmao) use the old pistol sound. Sky driver gets unique sound Grab-fu sounds: joint lock sound pin to ground sound
> 
> > New sounds where can we listen to them?
> 
> [GunsPinJointShield.zip](https://github.com/discordia-space/CEV-Eris/files/7295542/GunsPinJointShield.zip)

joint locking what I thought  you couldn't do that on eris only joint dislocating

**Review by drexample — DISMISSED** [review]
code/modules/clothing/clothing.dm line 502 has wrong type path

**Comment by Kegdo** [comment]
I sure hope this pr will finally get merged this week and I will suffer no more

**Comment by Humonitarian** [comment]
> I sure hope this pr will finally get merged this week and I will suffer no more

Nah

**Comment by Kegdo** [comment]
*fckuign dies*

**Comment by Kegdo** [comment]
> Energy shield sounds were added, but due to inevitable merge conflicts there is no point in implementing them yet.

so is this pr ready to merge now?

**Review by Iglpigl — APPROVED** [review]

**Comment by Kegdo** [comment]
I forgor
[SoundsOverhaul3_GrabMeleeShieldRanged.zip](https://github.com/discordia-space/CEV-Eris/files/7487344/SoundsOverhaul3_GrabMeleeShieldRanged.zip)
fuck I know if these are up-to date, probably not, but there are a lot of sounds and you don't have to code dive to listen to them, yet, maybe some sounds were changed, I am too lazy to check at this point

**Comment by Humonitarian** [comment]
I didn't commit my last change yet, but it isn't vital, a very specific and situational sound was added. I can do that later so kedgo can sleep.

**Review by Firefox13 — APPROVED** [review]

**Pull request merged**
