### PR TITLE
Rifles, Sprites, Icons [DNM]

### PR DESCRIPTION
**Pull request by RandomColonist**
- STS and AK magazines now interchangeable, asked by @SpadesSlick.
- New sprites for 7.62 mags in rifles.
- New (old) sprites for stunbaton by WalterJe.
- New (old) sprites for stunrevolver by WalterJe.
- New sprites for NT GL.
- New sprites for old 5.56 magazine.
- AK magazine was renamed to long magazine.
- Civilian magazine (7.62) was renamed to short magazine.
- Tons of new icons for Giskard, possibilty to attach silencer.

image

### CODE REVIEW

**Comment by TorinoFermic** [comment]
Comments for the PR
STS-35 does not have in-hand sprites
Stunbaton uses old sprite.
Silenced Giskard does not have in-hand sprites

**Comment by shazbot194** [comment]
How did the left-hand sprites go missing?

**Comment by RandomColonist** [comment]
> How did the left-hand sprites go missing?

It was named "arifle" instead of "sts" for some reason. Fixed it, will commit when i get to my PC.

**Comment by shazbot194** [comment]
Ahh, glad to hear it wasn't missing

**Comment by RandomColonist** [comment]
This is a huge mess.

**Pull request closed without merging**
