### PR TITLE
reincarnation and Commitment ritual now be performed by any disciple of nt.

### PR DESCRIPTION
**Pull request by Evankhell561**
## About The Pull Request

this pr is focused on making it possible for any disciple to resurrect other NT members.

## Why It's Good For The Game
because design doc

## Changelog
:cl:
tweak: reincarnation and Commitment can now be performed by any disciple of nt.
tweak: cloning now produces cloning damage depending on who has activated the cloning machine.
/:cl:

### CODE REVIEW

**Comment by Kurgis** [comment]
Would it be possible to add some user input that when a NT disciple clones another person, that the new body received clone damage due to being too low rank? New/existing players also won't know about clone damage, they'll simply see the litany within their list, and assume they should immediately use it instead of getting the Preacher first.

**Comment by Omni44** [comment]
I still think that just changing cloning's itself time absed on who casts it is vastly preferable alternative to cloning damage, which is hard to cure, hard to live with, and they will want to spend that time curing it. 
Also something something, human body purity, something, something.

**Comment by Evankhell561** [comment]
> Would it be possible to add some user input that when a NT disciple clones another person, that the new body received clone damage due to being too low rank? New/existing players also won't know about clone damage, they'll simply see the litany within their list, and assume they should immediately use it instead of getting the Preacher first.

doing that is a little more complicated but it's the best thing to do. i just figured out how to code this.

**Comment by Evankhell561** [comment]
> Would it be possible to add some user input that when a NT disciple clones another person, that the new body received clone damage due to being too low rank? New/existing players also won't know about clone damage, they'll simply see the litany within their list, and assume they should immediately use it instead of getting the Preacher first.

ready

**Review by drexample — APPROVED** [review]

**Pull request merged**
