### PR TITLE
Adds a new coat for MEO, armours up MEO, MBO & Medspec's coats

### PR DESCRIPTION
**Pull request by Anonmare**
## About The Pull Request
Adds a special coat for the MEO (no new sprite as I can't sprite for shit) and makes it somewhat resilient to damage, about 1/2 that of a standard armour vest. The medspec's coat is now notably more resilient to harm, providing med specs a reason to use it for the greater mobility and storage it offers over dedicated combat armour - and making them much cleaner to identify at a glance. Moebius scientists also have some minor RAD protection at a loss of BIO to distinguish them just because I can and it's my PR.
Also fixes the labcoats weird double BIO and BOMB armour that didn't do anything.

## Why It's Good For The Game
Makes the Moebius heads consistent with the rest of command by giving them /some/ armour but explicitly weaker as they are non-combatants (in theory), and for medspec see above. In additiion, the MEO's needed his own coat for some time now, I can't sprite but I'd like to see what people would have in mind for it.

## Changelog
:cl:
add: After significant badgering of the bean counters, the MEO has his own coat now.
balance: Following a shortage of staff due to assassination attempts, Moebius and Ironhammer are now armouring their /key/ personnel's labcoats - MBOs, MEOs and Medspecs rejoice.
fix: Fixed a weird double BIO/BOMB value with the labcoat.
/:cl:

### CODE REVIEW

**Comment by GrayRachnid** [comment]
a coat with different properties but the same sprite is crrrrrringe

**Comment by Anonmare** [comment]
@GrayRachnid I know but I can't sprite and codersprites are fugly.

**Comment by Wouju** [comment]
> @GrayRachnid I know but I can't sprite and codersprites are fugly.

suck a spriter for so long they give in and make a sprite

**Comment by TheShown911** [comment]
Make a very ugly sprite so spriters get offended and resprite it.

**Comment by Anonmare** [comment]
@TheShown911 Done, don't say I didn't warn you.
image

**Comment by Iglpigl** [comment]
Conflicts.

**Comment by Anonmare** [comment]
Going to do what @Alliostra suggested in the mines and re-create the PR to fix the conflicts

**Pull request closed without merging**
