### PR TITLE
Handgun Caliber Re-Balance fix + FS Vendor tweaking

### PR DESCRIPTION
**Pull request by driecg36**
## About The Pull Request

Mostly buffs across the board to make small caliber handguns more usable but still in line with their purpose of being sidearms. Havelock was the most severe change, making it more like a snubnosed revolver than just an NTmk58 with lower capacity (does significantly more damage but has 5 round capacity and high recoil). Colt and Giskard had their materials turned to be steel instead of plasteel and were made cheaper across the board. Colt was nerfed pretty heavily as it was by far the best .35 handgun while costing less than most other ones. Some minor tweaks for other handguns. FS vendor prices across the board were also slashed as they were ludicrously high, especially after the addition of the Novakovic. 

## Why It's Good For The Game

Handguns had been left in a rather terrible state from the caliber rework as many different handguns with different purposes, specialties, and quirks were suddenly all changed to one standard caliber without much consideration for their new roles. This generally rebalances the handguns make more sense in terms of their cost and design (more advanced, newer designs are better than old pieces of junk) which had been left completely skewed before. Slashing many of the prices of the FS vendor also allows these handguns to be desirable to buy instead of outrageously overpriced and never used.  This should introduce more variety in the guns the Eris use by making these more viable as well as allow the FS vendor to operate as generally intended - convenient source of lower-quality guns for those roles that are encouraged against maint-diving.

## Changelog
:cl: driecg36
tweak: Generally lowered FS vendor prices to make it more useful. 
tweak: Giskard and Colt now use steel instead of plasteel, to represent them being low quality guns. 
balance: Buffed most low-caliber handguns to be more in line with their intended purpose and generally more usable. 
/:cl:

EDIT- Ignore some of the wonky merge pulls in the commits list, still kind of new to Github.

### CODE REVIEW

**Comment by SpadesSlick** [comment]
Will this PR be fixed?

**Comment by drexample** [comment]
@driecg36 This PR will be closed in 7 days.

**Comment by driecg36** [comment]
I completely forgot about this PR until now because I have a roach gib brain, will fix it and finish it today.

**Comment by driecg36** [comment]
Going to close this and try again when I have time, also adding a new gun to the vendor when it's complete.

**Pull request closed without merging**
