### PR TITLE
Superior mob optimizations round 2

### PR DESCRIPTION
**Pull request by MLGTASTICa**
## About The Pull Request
Optimizes superior mobs yet again
Tested by calling Life() 500K times
Without  the changes
debugtime1
With the changes
debugtime2

## Why It's Good For The Game
More optimizations

## Changelog
:cl:
code: Optimized roaches again
/:cl:

### CODE REVIEW

**Comment by ArmolitskiyCarpoeb** [comment]
Мегахарош
(Awesome)

**Comment by drexample** [comment]
Does this fix the bug when mobs stand around without noticing there is an enemy nearby?

**Comment by MLGTASTICa** [comment]
> Does this fix the bug when mobs stand around without noticing there is an enemy nearby?

no thats caused by the sanity system not ticking fast enough.

**Comment by drexample** [comment]
> > Does this fix the bug when mobs stand around without noticing there is an enemy nearby?
> 
> no thats caused by the sanity system not ticking fast enough.

Wait, really? Can you link the culprit lines in discord?

**Comment by drexample** [comment]
Well, that didn't kill the test server, so let's see what it does on live.

**Review by drexample — APPROVED** [review]

**Pull request merged**
