### PR TITLE
[Ready] Playtime monitoring and job playtime requirements

### PR DESCRIPTION
**Pull request by MLGTASTICa**
## About The Pull Request
Adds playtime monitoring using player saves
Fully detached from existing files , safe to add and remove at any time
Saves playtimes when round ends normally (not forced, ticker marks it as ended , etc)
Has verbs for whitelisting , admins are automatically whitelisted
To prevent griefing , makes use of SSinactivity features, as thus inactive people don't get any playtime.

## Why It's Good For The Game
We can go off panic bunker and still not get griefed to hell

## Testing
Tested locally, whitelist /unwhitelisting works. Admins are automatically  permitted to use all jobs.
Playtimes get properly saved and loaded when needed.
## Changelog
:cl:
add: Added playtime tracking.
/:cl:

### CODE REVIEW

**Comment by Mycah142** [comment]
> No rounds will be able to start the first time this is run, cause you need command roles to start the round
> 
> Not necessarily a criticism just kinda funny

This is why it's a database that can be modified to artificially inflate playtime for existing players. We probably have a whitelist already, that white list can be given artificial inflated times.

**Comment by MLGTASTICa** [comment]
> No rounds will be able to start the first time this is run, cause you need command roles to start the round
> 
> Not necessarily a criticism just kinda funny

you only need a technomancer

**Comment by thevandie** [comment]
No you need a commanding officer, pretty sure

**Review by Firefox13 — COMMENTED** [review]
Definitely need to:
* Whitelist admins
* Add a "whitelist ckey" button for admins to allow player bypass requirements

**Review by hyperioo — APPROVED** [review]

**Comment by hyperioo** [comment]
Waiting for the file to be creating in config.

**Comment by Firefox13** [comment]
it's time

**Pull request merged**
