### PR TITLE
Remove reerenglish breakdown line

### PR DESCRIPTION
**Pull request by SirRichardFrancis**
## About The Pull Request

image

## Why It's Good For The Game

Less confusing lines - better.
Thought about making and alternative to it, but other lines are more than sufficient.

## Testing

Compiled and run the server.

## Changelog
:cl:
del: Removed silly text line from stun breakdown.
/:cl:

### CODE REVIEW

**Comment by Firefox13** [comment]
Perhaps replace "frenzy" with "sorrow"?

**Comment by DiaFRAME444** [comment]
"The fear sends you into sorrow" doesn't hit as well, though.

**Comment by Mycah142** [comment]
"The fear sends you into woeful agony."

"The fear sends you into a depressive spiral."

"The fear fills you with dread."

**Comment by SirRichardFrancis** [comment]
Came up with many options myself, but they are all meh. Surely, four random lines is a sufficient amount.
Make code suggestions, if you have ideas.

**Comment by Alliostra** [comment]
the fear sends you into a stunlock

**Comment by driecg36** [comment]
"The fear overwhelms you!"

**Pull request merged**
