### PR TITLE
Floor shocker

### PR DESCRIPTION
**Pull request by soslow4u**
As Clockrigger requested: **zapping, sapping floor thing with AoE**
Countered with proper leg insulation. Would zap your fingers on touch
Requires cell or wiring to operate, could be deployed only on powered machinery or tables with conductive materials. Would get more things to attach to, but it works fine for now.
**It needs sprites badly**

Also, added "trajectory" check algorithm based on Bresenham's line pixel drawing, heck why we didn't have it still? 
This `projectile/test/trajectory_check()` is quite too much for such task, imo. Btw, it works only for mobs.

### CODE REVIEW

**Comment by soslow4u** [comment]
Current state:
dont bulli
Sprites needed:
god why you done this

**Comment by Keekenox** [comment]
We have reached peak coder sprite.

**Comment by drexample** [comment]
@soslow4u Are you still working on this?

**Comment by soslow4u** [comment]
@drexample, was waiting for sprites like for eternity

**Comment by Kurgis** [comment]
@drexample The sprites might of actually been made, can this be re-opened while I search for them?

**Comment by Kurgis** [comment]
Actually no, it's unsigned. We don't have anyone working on sprites for the shockers.

**Pull request closed without merging**
