### PR TITLE
Arachno-Syndicalism

### PR DESCRIPTION
**Pull request by Alliostra**
## About The Pull Request

Adds two new carrion spiders: The smoke spider and the holographic spider.

The smoke spider simple is a smoke grenade, nothing special about it. costs 3 genome points to unlock, and 5 chemicals to spawn.

The holographic spider can be used to copy items or mobs, and when activated it looks just like the thing it scanned (TM). This works absolutely perfect 110% of the time and it without any flaws whatsoever.
(particularly the examine texts of items that show special information about their state will not be displayed fully. It works well for humans, though.)

You (realistically Montagu) can use these to deceive people or lure them into dangerous places, or just have your personal little creepy tea party with the heads of staff, who are totally real and not holograms at all. The possibilities are endless!

they can also be worn in all clothing and inventory spaces, for more !fun!

Merges the signal spider and the spark spider into a single one, because they have a thematic overlap and one only works in machines, the other one only when it's not inside of something, anyways.

Also now displays the name of the area a spider is located in in the spider activation menu. Handy!

Please forgive the flood of schizo commits, I created this branch an eternity ago.

Shown, Hyperio, Handyman and other people I forgot about greatly helped me in creating this bloated abomination. Thanks, guys!

## Why It's Good For The Game

You can now lock IH into combat without strapping a corpse to a wheelchair.

grafik

## Changelog
:cl:
add: Adds the carrion smoke spider, which works like a smoke bomb
add: Adds the carrion holographic spider, can be used to imitate scanned objects or mobs
tweak: merges the signal spider with the electric spider
tweak: The carrion spider menu will now show the name of the area that a spider is located in
/:cl:

### CODE REVIEW

**Comment by Humonitarian** [comment]
Poor Ironhammer!

**Comment by Alliostra** [comment]
linters bruh moment, this must have been caused by resolving conflicts.

**Review by TheShown911 — COMMENTED** [review]
Why is there a 5k line diff in the .dme

**Comment by Alliostra** [comment]
Gonna make a new PR with unfucked .dme (hopefully)

**Pull request closed without merging**
