### PR TITLE
Buffs the Tesla overdrive chip

### PR DESCRIPTION
**Pull request by Anonmare**
## About The Pull Request

Overdrived energy weapons will now inflict 66% of their base damage instead of only 20%. Most lasers and plasma weapons deal 30 and 33 damage respectively, with this change, the lasers will now deal 19.8 burn and the plasma weapons will deal 21.78 burn.
In addition, the projectiles will now only cost 50% of their charge cost instead of 15%, recoil increased to 200% and fire delay increased to 33% as a balance
## Why It's Good For The Game
At the current values, 90% of all laser and plasma weapons will inflcit a measly 6-6.6 burn damage - that's barely worse than accidentally burning yourself with the cheap lighter which is 2 burn damage.

## Changelog
:cl:
balance: The Moebius \"Tesla\" overdrive chip will now only reduce energy weapon damage by 33% instead of 80%, charge reduction has been changed from a 85% reduction to only a 50% reduction. In addition, recoil is 200% greater than normal and fire delay has been increased from a 75% reduction to a 66% reduction.
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
viable full auto laser cannon less goo

**Comment by Kegdo** [comment]
> viable full auto laser cannon less goo

I'm 67% sure you haven't read the pr but are already salty, the same thing happened with my pr

**Comment by ValoTheValo** [comment]
> > viable full auto laser cannon less goo
> 
> I'm 67% sure you haven't read the pr but are already salty, the same thing happened with my pr

SPCR moment

**Comment by Anonmare** [comment]
@MLGTASTICa Check your math, the heavy laser projectile has 50 burn at base, this mod will reduce it to 37.5 burn per hit. That might sound like a lot but consider that the regular .35 bullet deals 28 brute and you'll see that it's not that much of a difference.

**Comment by MLGTASTICa** [comment]
> @MLGTASTICa Check your math, the heavy laser projectile has 50 burn at base, this mod will reduce it to 37.5 burn per hit. That might sound like a lot but consider that the regular .35 bullet deals 28 brute and you'll see that it's not that much of a difference.

ah thanks for point it out , i was used to 60 damage laser cannon..

**Comment by Anonmare** [comment]
Changes made:
66% damage
200% recoil
33% fire delay

**Review by TheShown911 — COMMENTED** [review]
I still feel this might be too strong, depending on how big the recoil is in game.

**Review by Firefox13 — APPROVED** [review]
haha machinegun go brrrrrrt

**Pull request merged**
