### PR TITLE
Tweak church jobs.

### PR DESCRIPTION
**Pull request by TheLeopold**
## About The Pull Reques
Acolytes meant to be important soon-to-be-reverend. Having 4 of them dig through garbage is weird. Trying to increase importance through scarcity.
Tweaked acolyte skill to be closer to preacher. Reduced agrolytes because having 3 autistic job slots is too much. Buffed custodian because he's supposed to be church's muscle.

Map changes:
Deleted 2 acolyte lockers, added table and shelf so it won't feel empty. Deleted 2 acolyte marks in bedroom
barracks

Deleted agrolyte locker and mark. Moved mutagen crate. Moved obelisk. Swapped places of genetic machines and watertanks.
botany

Moved the table. Added cystodian locker and mark.
janitor

## Why It's Good For The Game
Makes Acolyte more important by reducing numbers.

## Testing
Joined to fill every church jobs slot. Opened, closed, locked unlocked closets. Looked at map changes.

## Changelog
:cl:
tweak: reduced acolyte slots 4>>2
tweak: reduced agrolyte slots 3>>2
tweak: increased custodian slots 2>>3
tweak: acolyte closet now access-locked
tweak: custodian closet now access-locked
balance: acolyte stats TGH 15>>10, COG 10>>20
balance: custodian stats TGH 10>>15
/:cl:

### CODE REVIEW

**Comment by Firefox13** [comment]
Custodian is our trash-diver though.

**Comment by Mycah142** [comment]
> Custodian is our trash-diver though.

The idea is to reduce the number of acolytes, to increase their importance, without reducing total church population.

I believe custodian will also be increased to 3.

As it stands, custodians actually clean, not maint dive. Most acolytes (see: literally all of them) act like vagabond+ and just dive maint all day.

**Comment by assortedbeads** [comment]
> > Custodian is our trash-diver though.
> 
> The idea is to reduce the number of acolytes, to increase their importance, without reducing total church population.
> 
> I believe custodian will also be increased to 3.
> 
> As it stands, custodians actually clean, not maint dive. Most acolytes (see: literally all of them) act like vagabond+ and just dive maint all day.

That's entirely a player issue though, I regulary see IH roaming maints and searching trash, hell I see the merchant sometimes

**Comment by Mycah142** [comment]
> 
> That's entirely a player issue though, I regulary see IH roaming maints and searching trash, hell I see the merchant sometimes

"Player Issue" is a handwave to problems that people think will somehow... solve itself?

It's an issue. That we can mechanically try to change. Punishing players directly doesn't happen, nor will it. So it's not a Player Issue, and thus warrants something mechanical to adjust.

This is the least intrusive way to try and change behavior.

**Comment by assortedbeads** [comment]
> > 
> > That's entirely a player issue though, I regulary see IH roaming maints and searching trash, hell I see the merchant sometimes
> 
> "Player Issue" is a handwave to problems that people think will somehow... solve itself?
> 
> It's an issue. That we can mechanically try to change. Punishing players directly doesn't happen, nor will it. So it's not a Player Issue, and thus warrants something mechanical to adjust.
> 
> This is the least intrusive way to try and change behavior.

Punishing players directly should happen actually, and if it's an issue it should be handled from the player.

We cant just "low intervention so mechanics should drive player behaviour" to issues. If you want players to act their roles rap their knuckles when they dont.

**Comment by Mycah142** [comment]
> 

Can you imagine ahelping an acolyte who is digging a trash pile? And how well that would go?

Hell I'll ahelp any jobbie digging trash and get banned from submitting ahelps.

**Comment by thevandie** [comment]
> We cant just "low intervention so mechanics should drive player behaviour" to issues. If you want players to act their roles rap their knuckles when they dont.

Excuse me, I think you're on the wrong server. That is exactly how this whole thing is RUN. Low admin intervention, drive people towards doing things via lore, roleplay, and mechanics. That's kind of the fucking point of the server.

**Comment by ValoTheValo** [comment]
> > We cant just "low intervention so mechanics should drive player behaviour" to issues. If you want players to act their roles rap their knuckles when they dont.
> 
> Excuse me, I think you're on the wrong server. That is exactly how this whole thing is RUN. Low admin intervention, drive people towards doing things via lore, roleplay, and mechanics. That's kind of the fucking point of the server.

you are permabanned reason: having fun

**Comment by ValoTheValo** [comment]
but seriously acolyte used to have lower job slots, it was increased as acolyte is sort of the generic role of NT, like Scientist for moe, guild tech for guild, operative for IH etc. and usally make up the bulk of a department

**Comment by Mycah142** [comment]
> but seriously acolyte used to have lower job slots, it was increased as acolyte is sort of the generic role of NT, like Scientist for moe, guild tech for guild, operative for IH etc. and usally make up the bulk of a department

Moe only has what, three types of jobs? And roboticist has no real content? Where as NT has botany and custodial, which both have "content", as well as Acolyte being the only role that has access other than Preacher to certain actual mechanics. It has mechanical importance b ut is treated as the average grunt, so everyone just rolls Acolyte but then doesn't actually Acolyte, they just junk.

**Comment by assortedbeads** [comment]
>  > We cant just "low intervention so mechanics should drive player behaviour" to issues. If you want players to act their roles rap their knuckles when they dont.
> 
> Excuse me, I think you're on the wrong server. That is exactly how this whole thing is RUN. Low admin intervention, drive people towards doing things via lore, roleplay, and mechanics. That's kind of the fucking point of the server.

Ah yes trash digging, the extremely engaging roleplay and mechanically backed task

**Comment by assortedbeads** [comment]
> > > We cant just "low intervention so mechanics should drive player behaviour" to issues. If you want players to act their roles rap their knuckles when they dont.
> > 
> > Excuse me, I think you're on the wrong server. That is exactly how this whole thing is RUN. Low admin intervention, drive people towards doing things via lore, roleplay, and mechanics. That's kind of the fucking point of the server.
> 
> you are permabanned reason: having fun

Act like you're a real person = perma ban apparently

If ya'll want lax rules then dont complain when operative vagabond beater goes trash digging instead of doing their job
You cant have both

**Comment by TheLeopold** [comment]
> Custodian is our trash-diver though.

I've never seen custodian trash-dive. Nor anything in description or wiki implies that.
In other hand Acolyte's wiki page has this line:
>Agrolytes and Custodians can operate the bioreactor and biogenerators leaving both Acolytes the ability to conduct searches for items in maintenance.

**Comment by DiaFRAME444** [comment]
Firefox is correct in this matter. He's the Project Lead.
Also, there are definitely mentions of digging through trash in their job description.

**Comment by TheLeopold** [comment]
_(i hate it when people just confidently say something as if it's true without checking it first)_
No, there's no mentions
изображение

**Comment by thevandie** [comment]
>(i hate it when people just confidently say something as if it's true without checking it first)
Absolute chad, yeah, don't just wave around a title and say "yah, I'm right, I'm big man," always check beforehand.
that kind of thinking is how you get shit situations where everyone assumes something is right just because their idol says it is. It's how you get fucking 1984.

**Comment by DiaFRAME444** [comment]
I stated confidently because I've been in two hour long arguments over the Janitor's job description (Over whether they're supposed to kill roaches in maintenance and over whether they're meant to be NT's main muscle) and two of them definitely agreed that Janitors are supposed to go over trash piles.
At this point just throw this piece of shit job description in the trash, I don't care, its outdated and not comprehensive/wrong.

**Comment by DiaFRAME444** [comment]
>  It's how you get fucking 1984.
Fuck I can't believe I'm engaging in literally 1984

And no Firefox is still right.

**Comment by TheLeopold** [comment]
Let's be honest. Custodians rarely clean the ship as it stands even without trash-diving. Slap maint-looting on them and you'll never see your ship clean again.

**Review by Firefox13 — COMMENTED** [review]
I don't see a point in adding "learning" job slot exclusively for NT. If we want this role in we should have cadets for other departments (which I'm not honestly fan of).
How adding a vaga+ job (which is a bad job idea) going to fix acolytes not being important enough?

**Comment by Firefox13** [comment]
Dedicated maint diving job slot is vagabonds. Other jobs can also do it (guild techs, custodians, who *doesn't* maint-dive?), but they have their responsibilities too (guild techs working for guild mainly and custodians cleaning the ship)

**Comment by Mycah142** [comment]
> How adding a vaga+ job (which is a bad job idea) going to fix acolytes not being important enough?

Scarcity. If they're less common, players might behave differently and stop treating Acolyte as a Vagabond+ job. Acolytes ARE functionally and mechanically important, just not treated as a such by it's players.

Calling it a "player issue, ahelp it" is a waste, as you and I both know that'll never amount to anything.

Do I agree with neophyte? Not really, but the kid is trying and I like the reduction of acolyte at its core.

**Comment by garrulousTeamotei** [comment]
If the purpose is to give NT a vagabond+ type player role, why not just settle on standard vagabonds instead? Swap out a good number of the airlocks in the NT section with the new public crucuiform access silver type airlock. Leave the Acolyte Locker room, Preacher Room, and maybe the biogenerator and bioreactor rooms locked away with their current airlock configuration. 
If you give cruciformed vagabonds a secluded and secured place where they can store their loot, they might just take it, and in the process, create a pool of resources shared with NT proper. And if missing NT artifacts are a problem, those can always be moved about. Maybe one or both of them to the Preacher's private room.

**Comment by TheLeopold** [comment]
I mean yeah. I'm not a fan of neophyte either. But I'm less fan of reducing overall church slots. Or having 5 custodians. Or having 4 acolytes. At least give suggestions what to do instead of this.

**Comment by DiaFRAME444** [comment]
Actually, having less NT jobs but encouraging Cruciformed people to come by the Chapel for stuff seems very NT and would contribute to the setting, down to making other people distrustful of cruciformed people.
It'd be a big PR to pull off something like that since just a few mapping changes wouldn't be enough to encourage people to act that way, but it'd be wonderful if it worked out.

**Comment by TheLeopold** [comment]
Something like that would be the best way, but this is way beyond what I'm capable of. I can't even think about what changes could do it.

**Comment by TheLeopold** [comment]
I think for now I will just cut off neophytes keeping all other changes.

**Comment by TheLeopold** [comment]
Probably overbuffing skills. Open for better suggestions.

**Comment by DiaFRAME444** [comment]
Well not gonna lie, this doesn't seem like a improvement in its current state.

**Comment by TheLeopold** [comment]
> Well not gonna lie, this doesn't seem like a improvement in its current state.

Got any arguments to support that statement?

**Comment by DiaFRAME444** [comment]
It reduces the total amount of NT jobs when NT is already kinda disadvantaged in regards to its max population. Acolyte actually works somewhat well as NT's main "muscle" job like Scientist for Moe, so reducing it is troublesome if you don't have plans to replace it with.
Also, that Janitor stat buff is unjustified.

**Comment by Kurgis** [comment]
> It reduces the total amount of NT jobs when NT is already kinda disadvantaged in regards to its max population. Acolyte actually works somewhat well as NT's main "muscle" job like Scientist for Moe, so reducing it is troublesome if you don't have plans to replace it with. Also, that Janitor stat buff is unjustified.

The majority of NT's population, in my opinion, should not be coming from the department itself. Something should be done to better make core implants more player-facing. I doubt brand new players would be selecting a cruciform for their first instance on Eris, or even open the augmentation screen for that matter. Which is something that should be addressed, you shouldn't need to be in the know to understand those options are there. With that said, the Preacher can always expand their goon squad if there's actual benefit to vagabonds being core implanted.

**Comment by DiaFRAME444** [comment]
> The majority of NT's population, in my opinion, should not be coming from the department itself.

Alas this PR does not add enough support to make NT a open department, so reducing the total amount of open NeoTheology jobs is still a problem.

**Comment by TheLeopold** [comment]
I will break it into multiple small PRs

**Pull request closed without merging**
