### PR TITLE
Improve Readme.md

### PR DESCRIPTION
**Pull request by btwotwo**
Hello pls approve :)

### CODE REVIEW

**Comment by TheShown911** [comment]
Amazing :)

**Comment by btwotwo** [comment]
thx :)

**Comment by comma** [comment]
AMAZING PROJECT

**Comment by TorinoFermic** [comment]
`[Build Status](https://travis-ci.org/Endless-Horizon/CEV-Eris)[Krihelimeter](http://www.krihelinator.xyz)`

Build status is kinda broken and krihelinator is very dead blame github for breaking important statistics

**Comment by Hopekz** [comment]
(:

**Comment by mattroks101** [comment]
Amazing.

**Pull request closed without merging**
