### PR TITLE
Revert "[BOUNTY] GYM"

### PR DESCRIPTION
**Pull request by Firefox13**
Reverts discordia-space/CEV-Eris#7630
CLOCK IS TICKING KEGDO

### CODE REVIEW

**Comment by SirRichardFrancis** [comment]
Don't, I'm putting up a fix.

**Comment by Firefox13** [comment]
> Don't, I'm putting up a fix.

CLOCK IS TICKING KIROV

**Comment by SirRichardFrancis** [comment]
> CLOCK IS TICKING KIROV

image

**Comment by ErisMeleeEnjoyer** [comment]
Due to personal reasons, I cannot make a quick fix on these problems. Thanks to KIROV for doing this instead of me.
You might as well give all the bounty money to him since I cannot recieve payment due to sanctions.
Happy birthday to me.

**Pull request merged**
