### PR TITLE
[DRAFT 2 ELECTRIC BOOGALOO] New Kovacs Sprites and Palette by shazbot

### PR DESCRIPTION
**Pull request by ValoTheValo**
## About The Pull Request
Sprites by Me and Shazbot. Makes the Kovacs .20 again as it was really the only crew and Serb .20 rifle

## Why It's Good For The Game
There was only 5 .20 rifles compared to the 9 .30 Rifles (10 counting the PK) and we definitely didn't need an 11th .30 Rifle and several others rifles .30 did what the new Kovacs did. 
the Kovacs was the only Crew and Serb .20 rifle as the Z8 costs a small fortune and you need to be an excel to get the Vintorez on a regular basis, same for Wintermute and IH. its fine to have minor overlap in purpose if the methods of obtainment and use is different enough. and the Kovacs had its own Niche and is distinct enough from the Vintorez due to the Vintorez's burst, suppressor and faction. 

## Testing
compiled code, it was fine, went in game and shot a few normal and extended magazines into various objects and looked at sprite. 

## Changelog
:cl:
balance: Kovacs is .20 again and regained its AP Boost
imageadd: new Kovacs magazine sprites. and Nicer Palette for the gun
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
having problems with icons not displaying right. will be marked as ready when that bug is resolved

**Comment by ValoTheValo** [comment]
https://cdn.discordapp.com/attachments/299262993617780737/1053084100535275530/image_1.png

**Comment by maikilangiolo** [comment]
> There was only 5 .20 rifles compared to the 9 .30 Rifle

^ Clueless. 3 of the 5 .20 guns are Kovacs clones. 7 of the .30 guns are AK clones. More than half of the .20 guns are the same exact gun, only with +1/-1 inane differences. Crew gets another, better .20 marksman gun with #7898 that actually has a reason to exist. The fact there aren't 500 .20 guns doesn't mean much if they are copy pasted like AKs.

> several others rifles .30 did what the new Kovacs did

Huh, which of the .30 rifles are semi auto only with a medium power scope and strong damage per shot? Do enlighten me, instead of making vague misleading statements.

**Review by Firefox13 — CHANGES_REQUESTED** [review]
Please either remove the caliber changes from this PR completely or atomize it into two different PRs.
I have no issues with sprites because you're changing it to Serbian palette (whic his a good thing) but why are yous tuffing it into balance PR

**Comment by DiaFRAME444** [comment]
This is a balance PR. The sprite changes are because logically, if a rifle is .20, then it should have a .20 magazine shape in its sprite.

**Comment by ValoTheValo** [comment]
> Please either remove the caliber changes from this PR completely or atomize it into two different PRs. I have no issues with sprites because you're changing it to Serbian palette (whic his a good thing) but why are you stuffing it into balance PR

Sure, ill move the balance changes to a 2nd PR

**Comment by ValoTheValo** [comment]
> > There was only 5 .20 rifles compared to the 9 .30 Rifle
> 
> ^ Clueless. 3 of the 5 .20 guns are Kovacs clones. 7 of the .30 guns are AK clones. More than half of the .20 guns are the same exact gun, only with +1/-1 inane differences. Crew gets another, better .20 marksman gun with #7898 that actually has a reason to exist. The fact there aren't 500 .20 guns doesn't mean much if they are copy pasted like AKs.

what .20 guns are Kovacs clones. please enlighten me.

**Comment by SirRichardFrancis** [comment]
> what .20 guns are Kovacs clones. please enlighten me.

All guns are the same and 100% clones (except those made by me, they're unique), you just don't understand!!

[](https://media.tenor.com/4hgLFtGX1lYAAAAd/explain-plan.gif)

**Pull request closed without merging**
