### PR TITLE
Excelsior Jumpsuit cost reduction

### PR DESCRIPTION
**Pull request by ValoTheValo**
## About The Pull Request
i changed the cost of excel uniforms from 100 to 50 in the excelsior teleporter

## Why It's Good For The Game
makes excelsior more likely to wear their own uniforms. (this is a learning PR. im learning to use github and figuring out how to code)

## Changelog
:cl:
tweak: tweaked excelsior jumpsuit cost from 100 to 50
/:cl:

### CODE REVIEW

**Comment by ArmolitskiyCarpoeb** [comment]
>makes excelsior more likely to wear their own uniforms. 

they dont wear their own uniforms because that will reveal them as excelsior

**Comment by ValoTheValo** [comment]
> > makes excelsior more likely to wear their own uniforms.
> 
> they dont wear their own uniforms because that will reveal them as excelsior

war excelsior

**Comment by Garen7** [comment]
this is his first PR so a bikesheding PR that doesn't affect anything should be nonissue and beneficial since its to help him learn

**Review by genessee596 — APPROVED** [review]
i mean, if you ask me the jumpsuit should be nearly-free

but this will do

(still needs code approval)

**Review by Hopekz — APPROVED** [review]
> (still needs code approval)

There is literally no additional code here besides the value change.
The value change is fine.

**Pull request merged**
