### PR TITLE
New sprites for AMR shells

### PR DESCRIPTION
**Pull request by Alliostra**
## About The Pull Request

New colored sprites fro AMR shells

## Why It's Good For The Game

made by shazbot, that's why

## Changelog
:cl:
imageadd: new sprites for the unique AMR shells
/:cl:

### CODE REVIEW

**Comment by Alliostra** [comment]
fock

**Comment by Sparrowbird611** [comment]
Pictures or it didn't happen.

**Comment by Alliostra** [comment]
ebinshells
it's the big ones

**Comment by Alliostra** [comment]
ebinshells

**Review by TheShown911 — APPROVED** [review]
Cool.

**Pull request merged**
