### PR TITLE
Big OneStar Update

### PR DESCRIPTION
**Pull request by ValoTheValo**
## About The Pull Request
Updating basically everything about onestar and adding unused and planned shit from kotmap, and my own ideasguy shit. this will be extremely fun to make and document

Checklist:

Mapping
- [ ] Large OneStar Blacksite
- [ ] Lore and Storytelling
- [ ] OneStar City Ruin
- [ ] Remap The Dungeon
- [ ] Lost OneStar Ship

Items and Objects
- [ ] Fix OS Item Spawning
- [x] OneStar Armor and Clothing
- [ ] OneStar Guns, Magazines and Calibers
- [x] OneStar Toolmods
- [ ] More OneStar Tools
- [ ] OneStar Artifacts
- [ ] OneStar Atomcells
- [ ] OneStar Full Body Prosthetic
- [ ] OneStar Machines
- [ ] Reverse Engineer Sci

Friends and Enemies
- [ ] Improve OneStar Robot Ai
- [ ] More Enemy Variety
- [ ] OneStar Android
- [ ] OneStar Liberators
- [ ] Repaired Onestar Robots

## Why It's Good For The Game
OneStar has like no fucking content currently and what they do have is outdated as shit with no reason to do that. also techno doccument additions good

## Changelog
:cl:
add: Added new things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by maikilangiolo** [comment]
Firstly there is absolutely no reason for this to be made, secondly it will screw up loot and make all these items more common, thirdly, one and possibly more items price changes are direct violation to contributing guidelines, you should try reading them.
https://wiki.cev-eris.com/Content_GuidelinesEn

**Comment by MLGTASTICa** [comment]
Firstly there is absolutely no reason for this to be made, secondly it will screw up loot and make all these items more common, thirdly, one and possibly more items price changes are direct violation to contributing guidelines, you should try reading them.
https://wiki.cev-eris.com/Content_GuidelinesEn

**Comment by ValoTheValo** [comment]
> Firstly there is absolutely no reason for this to be made, secondly it will screw up loot and make all these items more common, thirdly, one and possibly more items price changes are direct violation to contributing guidelines, you should try reading them.
> https://wiki.cev-eris.com/Content_GuidelinesEn

Firstly there is absolutely no reason for this to be made, secondly it will screw up loot and make all these items more common, thirdly, one and possibly more items price changes are direct violation to contributing guidelines, you should try reading them.
https://wiki.cev-eris.com/Content_GuidelinesEn

**Comment by ValoTheValo** [comment]
> Firstly there is absolutely no reason for this to be made, secondly it will screw up loot and make all these items more common, thirdly, one and possibly more items price changes are direct violation to contributing guidelines, you should try reading them. https://wiki.cev-eris.com/Content_GuidelinesEn

I don't make PRs i am the commenter of PRs and you broke the rules buddy, https://wiki.cev-eris.com/Content_GuidelinesEn you should try reading these. This PR is useless and you should be ashamed you ever made it, get out of my sight.

**Comment by glaciusinfinity** [comment]
We are reaching basedness levels that shouldn't be possible

**Comment by ValoTheValo** [comment]
milestone for clothing done

**Comment by ValoTheValo** [comment]
merge conflict on the draft pr. what a suprise

**Comment by GrayRachnid** [comment]
OS Guns disappear when they are wielded, i'm not sure if they have wield sprites but if they don't then at least make them not disappear please.

**Comment by ValoTheValo** [comment]
> OS Guns disappear when they are wielded, i'm not sure if they have wield sprites but if they don't then at least make them not disappear please.

they dont have inhands. im replacing them completely anyway. they use the wrong sprites, sounds and calibres

**Comment by ValoTheValo** [comment]
toolmods milestone done for now. until more sprites are found

**Comment by ValoTheValo** [comment]
so my entire repo shat itself. gonna have to redo this.

**Pull request closed without merging**
