### PR TITLE
Completely delete and obliterate scrapyard

### PR DESCRIPTION
**Pull request by Kegdo**
## About The Pull Request

fucking piece of shit bad annoying location
## Why It's Good For The Game

the shityard takes up processing time, shits into admin log, and you can't even use it - ghosts can't spawn on it and nobody goes there
also every time you code/change something the shityard whines pisses and shits that something is wrong
I hate it so fucking much

## Changelog
:cl:
del: scrapyard forever gone
/:cl:

### CODE REVIEW

**Comment by Kegdo** [comment]
you can't even argue against this, it just takes up the fucking place and does nothing

**Comment by Iglpigl** [comment]
Improve don't remove.

**Comment by Kegdo** [comment]
you can't improve the shityard

**Comment by Iglpigl** [comment]
> you can't improve the shityard

You can if you want, you can make a new map even if you are desperate.

**Comment by Kegdo** [comment]
no.

**Comment by Iglpigl** [comment]
> no.

Absolutely yes, the performance claim is also bullshit, start the server, run the profiler for 10 hours and you will see the real culprits and scrapyard ain't one of them.

**Comment by Kegdo** [comment]
image

**Comment by MLGTASTICa** [comment]
I 100% support this change , scrapyard provides very little in terms of gameplay and only servers to add YET another Z-level ontop of the current Z-level bloat. It only takes up ram , and spawns 100~ mobs that also keep stress on the mob life subsystem. If you want it reimplemented use Hyperio's system that makes it only generate when discovered on the map , its bloat that we don't need always loaded.

**Comment by ValoTheValo** [comment]
Maybe re implement it with how the onestar blacksites are handled so it has no performance impact.

**Review by SirRichardFrancis — APPROVED** [review]
Yes please! Scrapyard have been interesting for like one run, and just for a bit, since it is completely isolated location with awful mapping that makes little sense and tons of broken shit.
image

**Review by TheShown911 — APPROVED** [review]
Ok

**Comment by drexample** [comment]
Bruh

**Comment by drexample** [comment]
Please do not demean contributions of others in your PRs

**Pull request merged**
