### PR TITLE
bluespace entropy improvements

### PR DESCRIPTION
**Pull request by Evankhell561**
## About The Pull Request

This pr is focused on making entropy-related events a little more frequent. As well as increasing the feedback when a cockroach disappears before your eyes. It also provides admins with information on where the Stranger spawned.

## Changelog
:cl:
tweak: Completing the Technomancer's "Disturbance" objective reduces global entropy.
tweak: the narrator's events related to bluespace increase global entropy.
tweak: bluespace cockroach teleports create sparks.
tweak: the Stranger is a bit more powerful as a minor event.
tweak: portals produce a little more entropy.
tweak: destroying the gitf bluespace produces much more entropy.
tweak: creating the bluespace gift produces reduces entropy a bit more.
add: admins are informed about where the Stranger spawned. 
tweak: bluespace roaches now have bluespace crystals instead of roach meat.
tweak: trade beacons generate entropy when used.
/:cl:

### CODE REVIEW

**Review by TheShown911 — APPROVED** [review]
There's an extra `add: Added new things` in the changelog

**Comment by Evankhell561** [comment]
> There's an extra `add: Added new things` in the changelog

👍

**Comment by Evankhell561** [comment]
update:
tweak: bluespace roaches now have bluespace crystals instead of roach meat.

**Comment by Evankhell561** [comment]
update 2:
tweak: trade beacons generate entropy when used.

**Pull request merged**
