### PR TITLE
New Stock Parts Sprites by Baron

### PR DESCRIPTION
**Pull request by githubuser4141**
## About The Pull Request

replaces old stock parts sprites by BEEstation with new ones
Sprites by INFRARED_BARON
image

## Why It's Good For The Game

The old sprites while better  then what they replaced have a cartoon-y style that doesn't fit imo, and were supposed to be a placeholder anyway. New sprites should fit a lot better. Credit to INFRARED_BARON

## Testing

Tested in game can confirm the sprites appear

## Changelog
:cl: INFRARED_BARON
imageadd: Adds new stock part sprites (T1 - Excelsior) - Sprites by INFRARED_BARON
imagedel: Deleted old stock part sprites (T1 - Excelsior, OS & Alien were unchanged.) - Sprites by INFRARED_BARON
/:cl:

### CODE REVIEW

**Comment by thevandie** [comment]
oh hell yeah

**Comment by ValoTheValo** [comment]
Dont Delete the Debug Parts please

**Comment by ValoTheValo** [comment]
never mind im blind and cant read, ignore my previous comment

**Comment by Firefox13** [comment]
изображение
Credit Baron properly please.

What do you mean sprites? Re-read what testing part means. Do they parts show up in-game normally?
изображение

**Comment by githubuser4141** [comment]
> изображение Credit Baron properly please.
> 
> What do you mean sprites? Re-read what testing part means. Do they parts show up in-game normally? изображение

Yes, spawned them in and didn't see anything amiss to be honest I didn't spawn all of them

**Comment by Firefox13** [comment]
Then spawn all of them and check.

**Comment by SirRichardFrancis** [comment]
> Then spawn all of them and check.

image

**Comment by githubuser4141** [comment]
> Then spawn all of them and check.

Checked :)
image

**Comment by thevandie** [comment]
Man. I want technos to be able to print the industrial parts now
From a forge exclusive disk perhaps? Hmm... I might make that

**Comment by thevandie** [comment]
Btw, by "credit baron properly" He meant put it on the actual cl slot, right where he pointed in the image
It shows up more official on the changelog or something 
I think it's on the same line as the cl itself?

**Comment by githubuser4141** [comment]
> Btw, by "credit baron properly" He meant put it on the actual cl slot, right where he pointed in the image It shows up more official on the changelog or something I think it's on the same line as the cl itself?

Oh oops, that might be what he meant, did it.

**Review by hyperioo — APPROVED** [review]

**Pull request merged**
