### PR TITLE
Spinning swords flicks the blood off of them

### PR DESCRIPTION
**Pull request by Kegdo**
## About The Pull Request
image

that's it

## Why It's Good For The Game

weeb stylish shit, the best kind

## Changelog
:cl:
add: spinning swords flicks the blood off of them
/:cl:

### CODE REVIEW

**Comment by Wouju** [comment]
memories broken the truth goes unspoken i've even forgotten my name

**Comment by SaltyOldBull** [comment]
I don’t know the season Or what is the reason I’m standing here holding my blade

**Review by hyperioo — COMMENTED** [review]
Nice branch name.

**Comment by Firefox13** [comment]
So.
(citing)
изображение

besides that, such special interactions should be defined in objects themselves and not in the proc itself because that's just nanako levels of coding

**Comment by Firefox13** [comment]
good night sweet prince

**Pull request closed without merging**
