### PR TITLE
Sprite Overhaul (plus some other stuff)

### PR DESCRIPTION
**Pull request by thevandie**
## About The Pull Request

Updates a load of sprites with both my own handiwork and stuff from the archive Valo has given me (some is Walter's, some is from other random people, I can't find em).
Also adds some minor things, like changing around a few drinks to look better. Basically, anything that had a matte color on its sprite now just uses the liquid's reagent color in the glass. This is because ALL of our drink sprites use the last generation of glass as a basis, so they all look hideously outdated. I also modified most of the drink reagent colors to look less bad, because for some reason 99% of drinks used whiskey's color, and it just... looked like shit. Literal shit. SO, now they look closer to either their IRL counterparts or their old sprite.

## Why It's Good For The Game

All of these sprites were outdated and looked like shit compared to the new artstyle, so I have updated them. Especially the mountain wind and space-up full-sized bottles. Those were... Eugh.

## Testing

I deleted .dmb, reran build.bat, loaded up the game, and made sure the thing I changed worked everytime I modified something. It worked fine each time.

## Changelog
:cl:
add: new sprites for the Generic Robot limbs
add: generic robot torso, groin, and head to the augmentation menu in setup
add: new sprites for the jar, since Handy needed it for his soup pr coming up
add: new sprites for the Space Mountain Wind (Mountain Dew) and Space Up (7-Up) full-sized bottles
add: Space Mt. Wind, Space Cola, and Space-Up full-sized bottles to the soda vending machine for 100 credits (they contain 100 units each)
add: new sprites for the Emeraldine and Miss Blue Caracao bottles, they don't use ancient ss13 sprites anymore
add: the security hud sunglasses to the loadout for IH, since they fit the aesthetics of IH great and it's a shame we don't have access to them without the FO or Cap giving their pair up.
add: new beer sprite! (when in glass) (it looks actually tasty instead of just straight piss)
tweak: tweaked all of the common alcohols have had their colors remapped to something more fitting along with making them no longer use their unique sprites (I explained why earlier)
tweak: the jar now uses a different path so it functions properly. It has a lid n stuff now
fix: fixed a bug with the beaker's reagent-filling sprites, it stuck out a pixel below the actual beaker when completely full
/:cl:

(New beer sprite :D )
image
image
image
image
image

### CODE REVIEW

**Comment by Mycah142** [comment]
I would put the loadout changes (as they're not sprite related) into a different PR.

**Comment by ValoTheValo** [comment]
It would be really great if you posted screenshots of the new sprites so we could judge them

**Comment by thevandie** [comment]
fair enough, gimme a second

**Comment by Firefox13** [comment]
That beer sprite looks really bad to me, like some kind of an overfilled ice cream cup.

**Comment by thevandie** [comment]
Temporarily closing this because I just realized I wanna add a couple more super important things, plus Firefox wants some revisions on the beer sprite, and that's gonna take some time

**Comment by thevandie** [comment]
alright something is bugged, I'm closing this and making a new PR from the same branch

**Pull request closed without merging**
