### PR TITLE
Junk food resprite + junk food minor adjustments

### PR DESCRIPTION
**Pull request by Kegdo**
## About The Pull Request

~~this was such a pain~~
Basically, removes a lot, **A LOT** of bay leftover junk food, or changes their sprites(sprites done by Près de l'oiseau)
removes syndicakes, replaces them with Shimatengoku(can change to One Star, just really not sure if that's a good idea) wok instead
removes semki pack(was only a trash item, not even consumable)
removes pistachios pack for the same reason as semki pack
replaces candy with Shokoloud bar, basically just a chocolate bar. Dark chocolate. Hate it or love it.
replaces a lot of junk food sprites: wok, candy(chocolate), water, milk, soymilk, cheesie honkers, beef jerky, ramen, chips. No, those are not blue doritos, NO
replaces hot coco, coffee and tea sprites from coffee vendor.
some junk foods need to be opened first now: ramen, chips, jerky, cheesie honkers, candy, wok.
**NOTE**: not every sprite was coded in.
image
Beef jerky
image
Ramen
image
other stuff. The left chocolate sprite, green coffee, red and green chips sprites are not coded in.
## Why It's Good For The Game

bay leftover bad

## Changelog
:cl:
add: most of the junk foods now need to be opened first.
add: new junk food, wok. Basically noodles but junk food.
tweak: candy was replaced with Shokoloud chocolate bar.
del: syndicakes deleted.
imageadd: new junk food sprites; sprites done by Près de l'oiseau
imagedel: most of the bay leftover junk food sprites are sent to bay-brazil.
/:cl:

### CODE REVIEW

**Comment by Kegdo** [comment]
image
what the fuck, -35k??

**Comment by ValoTheValo** [comment]
> image what the fuck, -35k??

A little trolling

**Comment by Kegdo** [comment]
image
accidentally deleted a map and I don't even know how nor why

**Comment by Kegdo** [comment]
image
BYOND is haunted

**Comment by Kegdo** [comment]
should be fixed now

**Comment by Kegdo** [comment]
fix

**Review by Firefox13 — APPROVED** [review]

**Pull request merged**
