### PR TITLE
Removes slip hardstun , removes door hardstun.

### PR DESCRIPTION
**Pull request by MLGTASTICa**
## About The Pull Request
Slipping no longer hardstuns , but weakens
door crushing no longer hardstuns , but deals much more damage

## Why It's Good For The Game
Hardstuns are unfun for everyone , after crushing someone for 10 minutes i realised that they fucking suck, boring gameplay and nothing fun for either side.

## Changelog
:cl:
balance: slips no longer hardstun
balance: doors no longer hardstun , but deal much more damage (60 without melle armor)
/:cl:

### CODE REVIEW

**Review by mattroks101 — APPROVED** [review]
Not sure how I feel about doors being more deadly now, but the slip hardstun definitely had to go.

**Comment by githubuser4141** [comment]
Does this nerf carrion slippery spiders? They currently cost 3 DNA points, so maybe the price should be reduced unless they're an exception.

**Comment by MLGTASTICa** [comment]
> Does this nerf carrion slippery spiders? They currently cost 3 DNA points, so maybe the price should be reduced unless they're an exception.

Yes it does , but they're still valuable in combat since they still weaken for the same amount of time.

**Comment by TheShown911** [comment]
For people to understand, Stun() makes you unable to move or act, while you stand in place, and Weaken() makes you drop to the ground and drop all the items you were holding.

**Pull request merged**
