### PR TITLE
Revert "holster code refactor and additions (#7577)"

### PR DESCRIPTION
**Pull request by ValoTheValo**
here goes nothing

## About The Pull Request
this PR reverts the holster rework. nobody really wanted it and it broke a lot of stuff. and with a failing computer, a lot of stuff I need to code and no fix on the horizon this is my last resort. 

## Why It's Good For The Game
nobody really wanted the holster rework. you cant quickdraw from accessory holsters anymore and that was entirely unmentioned on the PR and when i told the coder he said i should "fix some bitches". lost a lot of variety. the new accessory holsters are coded poorly. and the new sprites looks somewhat bad on alot of uniforms. quickdraw on pocket holsters was nice but the drawbacks outweigh the positives in my eye.

## Changelog
:cl:
add: old holsters
del: new holsters
/:cl:

### CODE REVIEW

**Comment by ErisMeleeEnjoyer** [comment]
"Broke a lot of stuff"? "No fix on the horizon"? What are you talking about? Fix for what? Nothing was broken, and the only change that happened was removing quickdraw on accessory holsters; if you are this salty about a change, just say it. And instead of removing the whole PR that adds other various things, like belt holsters, maybe you should try coding the change back yourself, without clicking one button.

**Comment by ValoTheValo** [comment]
> "Broke a lot of stuff"? "No fix on the horizon"? What are you talking about? Fix for what? Nothing was broken, and the only change that happened was removing quickdraw on accessory holsters; if you are this salty about a change, just say it. And instead of removing the whole PR that adds other various things, like belt holsters, maybe you should try coding the change back yourself, without clicking one button.

A change that was never at any point mentioned on the original PR at any point and was esentially a stealth nerf. I thought it was a bug intially as it wasnt mentioned but you and maik said it was deliberate. 
And judging by your response there still is likely not a fix going to happen. And im not a coder so this is really the one way i have in my ability to fix it. I can readd the belt holster too if you want.

**Comment by maikilangiolo** [comment]
Mental insanity. Out of the entire eris discord, only you and diamond were obnoxiously vocal about it. The only complaints you presented was not removing the holsters, which didn't happen, and the loss of quickdraw, which you can add back if you so wish. There's literally a PR to fix the issue of attachment holster not drawing on click but opening the storage interface.

The PR broke nothing, you are just hiding the fact you don't like the change with deceit in order to get the revert approved, because the only thing kegdo refactor changed was the loss of quickdraw, which is a fair trade off to carry a gun or large melee wepaon in your suit while not taking up inventory space.

**Comment by Iglpigl** [comment]
Salt PR.

**Comment by SirRichardFrancis** [comment]
> Mental insanity.

You and Kegdo effectively removed hotkey from classic holsters (hotkey opening a single slot storage is completely useless, let's be frank, you know it is) for no other reason than promoting your own, arguably less useful and convenient, addition.
That's shitty practice, Valo has every right to be upset about it.

**Comment by maikilangiolo** [comment]
I wasn't involved with the PR, and he can he upset sure. But he lied in the description of this PR saying it "broke a lot of stuff" (purposefully vague and avoids adressing the issue) and "no fix on the horizon" (there's a fix PR up for the  past days).

**Comment by SirRichardFrancis** [comment]
Yeah, presentation is dogshit, and full revert looks quite unnecessary. Still, he has a point.

**Comment by maikilangiolo** [comment]
The point we can discuss on, and I recognize it as valid. Throwing this full revert in a hissy fit with misinformation in the description, however, indicates there's no discussion to be had if this is the behavior we can expect.
Valo has a habit of throwing full reverts like candy. Even when I offered to re do myself a PR he made that got screwed by one of mine, he opted to insult and make a revert PR instead

**Comment by assortedbeads** [comment]
I'm doing a single reply to this since honestly I'm not in the mood for more arguements.

Presentation could be better yes, descriptions can be edited.

People are divided on the free storage "issue." I personally believe it's a non issue.

Personally I wouldn't care about the change if you could still quickdraw suit holsters.
Clicking through inventory is not a desired choice, if it was the new holsters wouldn't be taking the quickdraw option.

I see it as a failing on the previous pr's part that instead of finding another way to give new holsters quickdraw, it just shuffled them around.

Is it full of bugs, no. But it could have been handled better than it was.

Personally, I feel like removing a feature for an inferior one because you couldn't fix it -referring to what the original pr did- is rude at best. And telling people to "cope" and "seethe" is a shit way to handle valid critic.

Anyway, this could be done better. But since the original pr was handled just as badly, it seems fair.

But Im not a maintainer so, not my decision.

**Comment by ErisMeleeEnjoyer** [comment]
>nobody really wanted it 

_Two_ people(out of sixty? thirty?) complained about hotkey removal and size reduction. There is no size reduction anymore. 


>and it broke a lot of stuff

Nothing is broken.

>and with a failing computer, a lot of stuff I need to code and no fix on the horizon this is my last resort.

Fix for what? For showing storage instead of grabbing gun? Okay, here it is: #7615; it was created even before your PR.

>lost a lot of variety. 

Your "variety" was three holsters of identical function - store one gun. Now, there are multiple holsters, even in loadout: belt, compact, the very same thing as before, baton, it's everything. There is, in fact, far more variety than before.

>the new accessory holsters are coded poorly 

Yes, sure, of course they are coded far worse than baycode ones that could delete the stored gun before a fix was made. Of course the fact that I asked KIROV to review my PR(and he helped a lot with optimizations of it) should be ignored. Of couse the new holsters cannot be as flexible and easy to code as previous ones, which is shown in #7615 with throwing knives rig.

>and the new sprites looks somewhat bad on alot of uniforms

I specifically asked firefox if it looked good enough, and it was, in fact, fine. Besides, 
image

>quickdraw on pocket holsters was nice but the drawbacks outweigh the positives in my eye.

It was to provide an incentive to use pouch holsters. The fact that you have to click once instead of pressing a button is not enough of a drawback to be reverting the whole PR.

**Comment by ValoTheValo** [comment]
> > nobody really wanted it
> 
> _Two_ people(out of sixty? thirty?) complained about hotkey removal and size reduction. There is no size reduction anymore.
> 
there was a more than two people who had problems with this
> > and it broke a lot of stuff
> 
> Nothing is broken.

you literally told me it was impossible code wise to readd quickdraw to accessory holsters

> > and with a failing computer, a lot of stuff I need to code and no fix on the horizon this is my last resort.
> 
> Fix for what? For showing storage instead of grabbing gun? Okay, here it is: #7615; it was created even before your PR.

fix for accessory holsters loosing ability to quickdraw completely.
> > lost a lot of variety.
> 
> Your "variety" was three holsters of identical function - store one gun. Now, there are multiple holsters, even in loadout: belt, compact, the very same thing as before, baton, it's everything. There is, in fact, far more variety than before.
> 
> > the new accessory holsters are coded poorly
> 
> Yes, sure, of course they are coded far worse than baycode ones that could delete the stored gun before a fix was made. Of course the fact that I asked KIROV to review my PR(and he helped a lot with optimizations of it) should be ignored. Of couse the new holsters cannot be as flexible and easy to code as previous ones, which is shown in #7615 with throwing knives rig.

Again according to you it is impossible to re-add quickdraw
29-Sep-22 14-58-06
> > and the new sprites looks somewhat bad on alot of uniforms
> 
> I specifically asked firefox if it looked good enough, and it was, in fact, fine. Besides, image
> 
> > quickdraw on pocket holsters was nice but the drawbacks outweigh the positives in my eye.
> 
> It was to provide an incentive to use pouch holsters. The fact that you have to click once instead of pressing a button is not enough of a drawback to be reverting the whole PR.

then don't lie about "not nerfing" accessory holsters when you clearly did. its just a shitty thing to do to stealth-nerf something
29-Sep-22 15-02-04

**Comment by ValoTheValo** [comment]
maxresdefault

**Comment by ValoTheValo** [comment]
PR Will likely return as a full refactor of holster code to be not shit.

**Pull request closed without merging**
