### PR TITLE
alien & one star components

### PR DESCRIPTION
**Pull request by Derven**
## About The Pull Request
Alien and one star stock parts.

## Why It's Good For The Game
Adds more lore-related content and lategame components.

## Changelog
Add: Added new stock parts.

### CODE REVIEW

**Comment by drexample** [comment]
@Derven use the PR template

**Comment by Kurgis** [comment]
You created this commit from your master branch, always remember to create a new branch when making any changes, and leave your master unedited. Makes it harder to create multiple PRs if something goes wrong with one of them.

**Comment by drexample** [comment]
Alternative descriptions and names for alien components are being discussed rn, I will relay them to you when we settle on them.

**Comment by AlexMorgan3817** [comment]
@Derven, maybe rename one star components to ultra?

**Comment by SpadesSlick** [comment]
One Star is a faction that produced them in first place.

**Pull request closed without merging**
