### PR TITLE
Makes moebius labcoat be semi buttoned up again

### PR DESCRIPTION
**Pull request by ValoTheValo**
## About The Pull Request
reverts the moebius labcoat to its semi zipped up state prior to #8333 i personally think this looks far nicer, has a unique aesthetic and is consistent with the server artwork

## Why It's Good For The Game
Superior Aesthetics and artistic consistency

## Testing
Compiled, spawned in, buttoned up coat

## Changelog
:cl:
imageadd: Moebius labcoat is now partially zipped up like it used to be
/:cl:

### CODE REVIEW

**Comment by TheShown911** [comment]
This is one of the PRs of all time!

**Review by hyperioo — COMMENTED** [review]
A bit weird that male `labcoat_tox_open` has some sort of apparent pecs mucles when the closed version does not.

**Comment by ValoTheValo** [comment]
> A bit weird that male `labcoat_tox_open` has some sort of apparent pecs mucles when the closed version does not.

i really do not see what you mean by that

**Comment by hyperioo** [comment]
> > A bit weird that male `labcoat_tox_open` has some sort of apparent pecs mucles when the closed version does not.
> 
> i really do not see what you mean by that

image

**Comment by ValoTheValo** [comment]
> > > A bit weird that male `labcoat_tox_open` has some sort of apparent pecs mucles when the closed version does not.
> > 
> > 
> > i really do not see what you mean by that
> 
> image

mightve put the female version on it i think, need to redo this anyway cause of merge conflict

**Pull request closed without merging**
