### PR TITLE
Adds a catgirl vending machine to our beloved codebase

### PR DESCRIPTION
**Pull request by genessee596**
## About The Pull Request

God I wish that title was bait

Adds a catgirl vending machine to this codebase
Really, it does

It has sprites and is completely ready to go

(Admin spawn only)

image
_Above: Me, having wasted 20 minutes of my life coding this shit_
Credit goes to Shazbot#8201 for sprites

Vending machine sells cat ears, schoolgirl uniforms, and fake handcuffs
When hacked, it also sells flashbangs, teargas and bibles because you all need Jesus
## Why It's Good For The Game

It's funny

Guys I promise it's funny

Guys please

## Changelog
:cl: Shazbot and genessee
add: Catgirl vending machine for admins to spawn. Yes, you read that correctly.
/:cl:

### CODE REVIEW

**Comment by genessee596** [comment]
Going to write it here too;

admin spawn only
admin spawn only
admin spawn only
admin spawn only
admin spawn only

**Comment by TheShown911** [comment]
I would suggest that this should de-admin anyone that spawns it in game.

**Review by MadmanMartian — CHANGES_REQUESTED** [review]
No.

**Comment by TorinoFermic** [comment]
Yes on the loss of admin power for the entire round

**Comment by GrayRachnid** [comment]
no

**Comment by MadmanMartian** [comment]
Bury it in the deepest depths of deepmaint, unwrenchable, unhackable, guarded by monsters unknown.

**Comment by GrayRachnid** [comment]
i have github powers i've never used and i will use them to close this

**Comment by genessee596** [comment]
I'm telling you, this PR will increase our codebase tenfold

**Comment by genessee596** [comment]
NOOOOOOOOOO

**Comment by MadmanMartian** [comment]
We are not TG.

**Comment by Hopekz** [comment]
**AdMiN sPaWn OnLy**
R3i4Q5makS-export_deny

**Pull request closed without merging**
