### PR TITLE
Resucitator nerf

### PR DESCRIPTION
**Pull request by Wouju**
## About The Pull Request

Reduces the timer for resurrection from 5 minutes to 1 minute

Doubles the required amount of reagents (instead of 1 resucitator unit per 4 units of nutriment now its 1 res unit per 8 units of nutri)

Makes the enricher reject virus food

fixes a grammar(?) mistake (from drop to drops)

## Why It's Good For The Game

It's not

There is a virus food dispenser in medbay with roughly 1000 units, thats tons of round start resucitator, doesnt seem like a good idea

the required amount of reagents will in theory lower the amount of resucitator
in practice roughly each meat slice produces 8 or more units of animal protein
also you dont need to use just animal protein, you can use nutriment and any child of nutriment (egg yolk, rice, ketchup etc.)

now the big part, the timer reduction

5 minutes is extremely generous, i can understand dying right infront of medbay being an awful bother, so that's one of the reasons why 1 minute, so a chemist can quickly run up to chemistry and make atleast 1 unit and also have time to run back

with 5 minutes it meant you could have died at the other end of the ship, be found by a random vagabond stumbling around, dragged to medbay (while taking a detour) and STILL be revived, which i think is just ridiclous

if you want to be resurrected there's a reason the cruciform exists

## Changelog
:cl:
tweak: Tweaked Resucitator amount produced by the enricher (now you need twice more the amount of nutriment/protein) and reduced the timer for when you can still be revived (from 5 minutes to 3 minutes, pop that hyperzine pill)
/:cl:

### CODE REVIEW

**Comment by SaltyOldBull** [comment]
3 minutes, take it or leave. The working rule of thumb time for restarting someone's circulation without any large sequelae under normal conditions (more so if kept under low temperatures).
1 minute is not nearly enough to make it on the spot as needed, you severely underestimate how little 5 minutes is already. Especially with the necessities of bringing someone back such as cutting out extensively damaged areas or repairing what little tissue there is while also working multiple patients or fending off an attack against medbay, common as they are.

The cruciform and resuscitator mismatch could be easily resolved by doing away with the respawn timer, that way anyone stands a valid chance of getting back in the game via the resuscitator (which already holds restrictive requirements), or by using the assured method that is being cloned via the cruciform.

While I agree with the fixing of virus food as that trivialized the making of resuscitator, I cannot in good conscience agree with a decrease so sharp in the working time of perfectly viable and revivable players just because the one doing the aggression did not go to the length of ensuring that the patient will not be revived; simple hiding of the body for 5 minutes, decapitation or even a trivial damaging of the flesh with some languorous vigor would be enough to invalidate any efforts towards resuscitation (how many people have their cruciforms removed after being murdered on the regular anyway?).

This is to not even mention the degrees or to argue death as a state, seeing as mechanically, the heart-stopping is enough to "kill" a spaceman, a state in which several metabolic functions would still occur up until complete brain death in real-life circumstances. Having to dump out a perfectly viable body because some poor fool got mag dumped or forgot to not smoke a cigarette while hooked on to an air supply that suffocates him to death due to a bug isn't ideal. 

And no I will not be taking "this is a game don't try to bring real-life into it" as an argument if you can clone someone from a particularly mildly tempered parasite you can sure as daylight falls and night creeps in restart a meat pump in the actual working time of degradation in a particular vessel.

**Comment by Wouju** [comment]
for the love of god salt please use words that a retard like me can understand

**Comment by SaltyOldBull** [comment]
3 minutes, not 1.

**Comment by Wouju** [comment]
> 3 minutes, not 1. And play doctor for a few rounds.

I did play doctor ya know
and i still think 3 minutes is too much

hell i would go as far as to remove the resucitator but being able to put someone's head in their groin is funny to me.

**Comment by Wouju** [comment]
> 3 minutes, not 1. And play doctor for a few rounds.

how bout 2 minutes then?

**Comment by SaltyOldBull** [comment]
3.

**Comment by FortuneMaster** [comment]
wuju, do 3, 500% nerf is too much. If 3 turns out to be too generous you'll open another PR with nerf.

**Comment by Wouju** [comment]
> wuju, do 3, 500% nerf is too much. If 3 turns out to be too generous you'll open another PR with nerf.

fair enough, thats a good argument

**Comment by TheShown911** [comment]
Nerf PR? Buff the duration to 6 minutes.
E3ax-smWEAMSK8R

**Comment by Wouju** [comment]
> Nerf PR? Buff the duration to 6 minutes.
> E3ax-smWEAMSK8R

image

**Comment by SirRichardFrancis** [comment]
Who exactly hurt by resuscitator now? 5 minutes is somewhat reasonable time to bring body in medbay and patch it up (ship is big, and people usually dying in hostile environment, have to deal with that too). And even if body delivered in time - it most likely magdumped for 300+ brute, that adv.medkits can't fix, hence no reanimation possible.
If moebius heads not present - there is 90% chance that resus is not prepared, also A LOT of medics just very slow on action, and time is ticking.
If anything, resus should be buffed, not nerfed.

**Comment by drexample** [comment]
> if you want to be resurrected there's a reason the cruciform exists

it's a faction item.

Just make virus food be rejected by the machine, and that's good enough.

**Comment by Wouju** [comment]
> If anything, resus should be buffed, not nerfed.

bro...



> it's a faction item.
And?

While i'm not trying to make the enricher shit (before resucitator it only made blood) i still think resucitator at the moment is bad

**Comment by vode-code** [comment]
> it's a faction item

The faction item in particular is supposed to be the _main draw of the faction_, and resus has one of the benefits and none of the downsides.
Surprising or not, said faction regularly has no converts, with rare exceptions.

**Comment by SirRichardFrancis** [comment]
> The faction item in particular is supposed to be the _main draw of the faction_, and resus has one of the benefits and none of the downsides.
> Surprising or not, said faction regularly has no converts, with rare exceptions.

Not resus to blame. If you nerf molitor - it will just became useless, like that von-krabin thing, and NT won't suddenly became popular after that, it benefits literally no one.
It so happened that Eris medicine know no reanimation methods other than resus. If you removing it (and this PR effectively does that) - introduce some replacement.
As I see it - being saved from death is positive player experience, and saving someone is positive experience as well. Dying or failing to save someone because coder said "don't wanna die - join that faction" is rather frustrating.
That mechanic should have some limitation, of course, shouldn't be too easy. But there is already plenty of limitations as is, 5 minutes to recover body, do surgery and whatnot is hard enough.

**Comment by Jan-Blasiak** [comment]
Really?

1 minute?

Literally NOBODY is going to be using it after that.

You do realize that if you inject it into the person with >100 damage they will just instantly die again and waste the chem?

The long timer is for allowing medics to patch people up enough to rez them, and even 5 mins is not enough usually to bring back people who died in maints surrounding medical if you need to find them.

If you want to nerf resuscitator just double the cost, but don't touch the fucking timer because it's already not long enough in most cases.

**Comment by Alliostra** [comment]
I don't make PRs i am the commenter of PRs and you broke the rules buddy, https://wiki.cev-eris.com/Content_GuidelinesEn you should try reading these. This PR is useless and you should be ashamed you ever made it, get out of my sight.

Either way, I cast my vote in favor.

**Comment by TheShown911** [comment]
I'm neutral on this and won't be reviewing this PR.

**Comment by Wouju** [comment]
> I'm neutral on this and won't be reviewing this PR.

based

**Comment by Jan-Blasiak** [comment]
> Not resus to blame. If you nerf molitor - it will just become useless, like that von-krabin thing, and NT won't suddenly gain popularity after that, this benefits literally no one.
> It so happened that Eris medicine know no reanimation methods other than resus. If you removing it (and this PR effectively does that) - introduce some replacement.
> As I see it - being saved from death is positive player experience, and saving someone is positive experience as well. Dying or failing to save someone because coder said "don't wanna die - join that faction" is rather frustrating.
> **That mechanic should have some limitation, of course, shouldn't be too easy. But there is already plenty of limitations as is, 5 minutes to recover body, do surgery and whatnot is hard enough.**

This.

DON'T TOUCH THE FN TIMER

**Comment by Wouju** [comment]
5 buck bet that no maintainer will touch this PR during the next merge

~~unironically if that happens i will make a new PR with no timer change since its clear that the vocal majority don't want it~~

**Comment by SirRichardFrancis** [comment]
> 5 buck bet that no maintainer will touch this PR during the next merge
> 
> ~unironically if that happens i will make a new PR with no timer change since its clear that the vocal majority don't want it~

Just change this one, duh

**Comment by Wouju** [comment]
> Just change this one, duh

yesn't

I think having the comments cleared will help since majority of them are about the timer

also i realized i forgot to merge a commit

**Comment by SirRichardFrancis** [comment]
> I think having the comments cleared will help since majority of them are about the timer

That's part of the discussion, very important part.

**Comment by Wouju** [comment]
> That's part of the discussion, very important part.

Yes, but majority of the discussion is about the timer

i don't see how making a new PR and closing this one will affect anything

**Comment by SirRichardFrancis** [comment]
> Yes, but majority of the discussion is about the timer
> 
> i don't see how making a new PR and closing this one will affect anything

Yes. Why would you make new one, anyway? Fix this one.

**Comment by Wouju** [comment]
> Yes. Why would you make new one, anyway? Fix this one.

> I think having the comments cleared will help since majority of them are about the timer

fuck why are we having this discussion anyways? its just clogging up the comments

**Comment by SirRichardFrancis** [comment]
> fuck why are we having this discussion anyways? its just clogging up the comments

You have not discarded that change, why complaints about  that should be gone? Leave timer alone, damn it.

**Comment by Wouju** [comment]
> You have not discarded that change, why complaints about that should be gone? Leave timer alone, damn it.

bro... please read clearly next time

**Comment by SirRichardFrancis** [comment]
> bro... please read clearly next time
>
> i will make a new PR with no timer change

Make it happen, then there will be no complaints. Again, you don't have to make new PR when this one exist.

**Comment by drexample** [comment]
Doesn't improve anything.

**Pull request closed without merging**
