### PR TITLE
Fix crossbow bolts not embedding

### PR DESCRIPTION
**Pull request by SirRichardFrancis**
## About The Pull Request

What it says on the tin.

Certain PR with over 2k lines changes broke it. Shocking, I know.

## Why It's Good For The Game

Fixes cool.

## Changelog
:cl:
fix: fixed a few things
/:cl:

### CODE REVIEW

**Comment by Humonitarian** [comment]
Is there no risk on_hit qdels the projectile before damage?

**Comment by SirRichardFrancis** [comment]
> Is there no risk on_hit qdels the projectile before damage?

No, why? Why would on_hit delete a projectile?

**Comment by Humonitarian** [comment]
> > Is there no risk on_hit qdels the projectile before damage?
> 
> No, why? Why would on_hit delete a projectile?

Because rockets exist, lol

On_hit is called after damage because of that

Currently damage through armor returns whether the projectile should continue moving or not, should be fine to save the result as a variable, then return it after on_hit, as a rocket that's qdeleted obviously won't have to worry about continuing its flight.

**Comment by SirRichardFrancis** [comment]
> Because rockets exist, lol

Ah, shit.

I'll test if that's actually an issue.

**Comment by SirRichardFrancis** [comment]
Testing done, no rocket it deleting itself by explosion. Issue isn't there.

image

image

**Review by Pink-Chink — APPROVED** [review]

**Pull request merged**
