### PR TITLE
Adding the katana to ironhammer misc disk

### PR DESCRIPTION
**Pull request by koghs**
## About The Pull Request
Adds the katana to ironhammer misc disk.

### CODE REVIEW

**Comment by Jan-Blasiak** [comment]
Ehh... I'd say katana doesn't feel like it fits in IH at all.

They are private security company after all, not mall ninjas.

**Comment by MadmanMartian** [comment]
Why the hay is ironhammer getting a katana?

**Comment by ACCount12** [comment]
Katanas are more Frozen Star than IHS, because Frozen Star are actually ~weebs~ Japanese. Overall, katana is a solid melee weapon, and adding it to a cheap readily available disk is not the right thing to do.

Making it a separate FS maint loot disk with limited uses would be much better.

**Comment by MadmanMartian** [comment]
I'd rather keep the katana to maintenance loot, or acquired through a different method.

Adding things to disks guarantees it being reproducable on an infinite scale, so that won't do.

**Pull request closed without merging**
