### PR TITLE
Make plasma weapon descriptions obvious

### PR DESCRIPTION
**Pull request by Firefox13**
## About The Pull Request

This PR edits plasma weapon descriptions to state some info about their different modes.

## Why It's Good For The Game

People have zero fucking idea what different plasma weapon modes do unless they codedive.

## Changelog
:cl:
tweak: Plasma weapons are more obvious about their firing modes now, check their descriptions to see the details.
/:cl:

### CODE REVIEW

**Comment by drexample** [comment]
Shouldn't that be in additional tooltip in examine tab instead of item's description?

**Comment by Deon-DF** [comment]
There's a little type, "Melt mode excel" -> "Melt mode excels", otherwise a welcome change.

**Comment by Firefox13** [comment]
> 
> 
> https://github.com/discordia-space/CEV-Eris/blob/d1bd44658433ecd46f8a9c3e257341b33bf3aa26/code/modules/examine/examine.dm
> 
> Put the information you added into description_info.
> Item's normal description is not really a place for such info.

I can't get description_info variable to work. It's only used on shield diffusers, both handheld and hull ones, as well as shield conduits. They are not displayed on them either.

**Comment by drexample** [comment]
@Firefox13 it shows up in the examine tab, as far as I remember.

**Comment by Firefox13** [comment]
I'm blind then

**Pull request merged**
