### PR TITLE
resprites: flashlights, exofab **Updated** & destructive analyzer

### PR DESCRIPTION
**Pull request by githubuser4141**
## About The Pull Request

Replaces the exosuit fabrictor and flashlights with better sprites

## Why It's Good For The Game

Better icons

## Testing

Tested, works
In-game screenshot:

image

## Changelog
:cl:  by INFRARED_BARON

imageadd: New images for flares, small flashlight, large flashlight and the exofab, and destructive analyzer
imagedel: Old images for flares, small/big flashlight and exofab, and destructive analyzer

/:cl:

### CODE REVIEW

**Review by hyperioo — COMMENTED** [review]
Blue one seems a bit to bright for the eye, is it part of our color palette? And the heavy duty is a bit weird, maybe too flat? I asked others for their opinion on the flashlights.

**Comment by githubuser4141** [comment]
Updated with blue flashlights and destructive analyzer sprites.

**Comment by Firefox13** [comment]
изображение
Huh? It scrolls quick through the rest of machinery in the .dmi file.

**Comment by githubuser4141** [comment]
> изображение Huh? It scrolls quick through the rest of machinery in the .dmi file.

it's tuesday I'll test it in game to see if it does that

**Comment by Firefox13** [comment]
Do everyone (maintainers) a favor and test&fix these things *before* Friday's merging time.

**Comment by githubuser4141** [comment]
> Do everyone (maintainers) a favor and test&fix these things _before_ Friday's merging time. I foresee issues with mechfab (building cycle, standby cycle speed, inserting materials alignment) too.

Tested, seems to be working with a 18 second delay on the last frame now.

**Review by hyperioo — APPROVED** [review]

**Pull request merged**
