### PR TITLE
Paramedic Style Fix

### PR DESCRIPTION
**Pull request by budgetcommander**
## About The Pull Request

Changes paramedic armour from having 2 style to -2 style.

## Why It's Good For The Game

I cannot fathom that this wasn't a mistake. Paramedic armour has decent armour and a speed boost. -2 style is a must.

## Changelog
:cl:
tweak: Paramedic armour (both suit and helmet) now have style values of -2 instead of 2.
/:cl:

### CODE REVIEW

**Comment by DiaFRAME444** [comment]
> I cannot fathom that this wasn't a mistake

But you see, Trauma Team.

**Comment by Humonitarian** [comment]
> I cannot fathom that this wasn't a mistake.

It was bad judgement and refusal to follow precedence from the trauma coder, not a mistake.

**Comment by SirRichardFrancis** [comment]
> It was bad judgement and refusal to follow precedence from the trauma coder, not a mistake.

It's a compensation for poor stats on otherwise cool and expensive armor, so paramedics hopefully won't switch it for some junk armor.
Speaking of "refusal to follow precedence", you did the same thing for another armor and refused to discuss it.

**Comment by Humonitarian** [comment]
> > It was bad judgement and refusal to follow precedence from the trauma coder, not a mistake.
> 
> It's a compensation for poor stats on otherwise cool and expensive armor, so paramedics hopefully won't switch it for some junk armor. Speaking of "refusal to follow precedence", you did the same thing for another armor and refused to discuss it.

I never said I was a saint, stiffness exists as well

**Comment by TheShown911** [comment]
This armor wasn't meant to follow any precedence. It was to be very strong to not be changed mid round, and i think it succeeds while still not being the best armor in the game.

**Comment by maikilangiolo** [comment]
yeah I mean, something to make the armor a little more worth it since it should be what you wear would be nice. style mechanically means dodge, so a fast armor that helps you dodge bullets having style makes sense. Unless there is a way to give it a hardcoded slickness without giving it style.

**Comment by DiaFRAME444** [comment]
> style mechanically means dodge, so a fast armor that helps you dodge bullets having style makes sense.

Just a small problem, something with a movement increase and high style can't have 7/10/10 armor.

**Comment by SirRichardFrancis** [comment]
> Just a small problem, something with a movement increase and high style can't have 7/10/10 armor.

Because you said so?

**Comment by DiaFRAME444** [comment]
> Because you said so?

Because the main style coder, Handyman said

> having positive style and armor is only allowed for a few specific stuff, inspector coat is one example.

And Humon said

> Tier 3 is stylish protective clothes, such as the Inspector coat.
Tier 4 is offsite, and would be where you would put stylish armor.

So somehow Paramed, who isn't even on the list of people who are supposed to have Tier 3 protective clothes, almost has full blown Style Armor which is better than the Inspector's Coat.

**Comment by TheShown911** [comment]
I, as a maintainer, put the paramed armor at tier 7 sub section 4.8 part 2. But seriously it's armor could be lowered a bit.

**Comment by maikilangiolo** [comment]
10 armor is already the lowest armor should be, otherwise it becomes just another coat.

**Comment by SirRichardFrancis** [comment]
What exactly makes word of one coder mean more than word of another coder?

**Comment by DiaFRAME444** [comment]
Honestly? Because that coder isn't suggesting clothes that have a speed boost, 7/10/10 armor, and high style.
This is the first case of a metabuddy requesting their favorite job have perfect gear roundstart I've seen. People meme about IH doing that by giving themselves OP armor but I don't think the Voodoo or any of the IH gear is drastically unbalanced. Meanwhile, look at this crap.

**Comment by maikilangiolo** [comment]
personally I think this is a case of "other people/departements" cant have good things. just like when paramedic armor got first introduced, everyone screamed about going paramedic and antag, or breaking into paramed storage to steal the armor. 10 armor is fine, just a rifle will just bring it down to 6.6.

**Comment by assortedbeads** [comment]
Paramed armor is fine cause it's cool and you'll die anyway to someone with half a brain

**Comment by SirRichardFrancis** [comment]
> This is the first case of a metabuddy requesting their favorite job have perfect gear roundstart I've seen.

Do you have anything at all to back up claims like that?

**Comment by TheShown911** [comment]
> What exactly makes word of one coder mean more than word of another coder?

Power.

**Comment by DiaFRAME444** [comment]
> Do you have anything at all to back up claims like that?

The argument immediately preceding this maybe
"Paramed shouldn't have high style and armor at the same time"
"Because you said so?"
"Actually, this is what the main style coder and a maintainer said"
"What exactly makes word of one coder mean more than word of another coder?"
Changing direction drastically like this because you just want people to shut up rather than actually discuss the issue.

**Comment by maikilangiolo** [comment]
yeah, thats not proof. thats just jumping to conclusion. Saying that handy made the armor for a metabuddy to be OP is grasping at straws.

**Comment by DiaFRAME444** [comment]
You're perfectly able to engage in a discussion by going "Its not that overpowered" or "Its better this way because" instead of "That means nothing, that means nothing, please close this PR".
Metabuddy.

**Comment by SirRichardFrancis** [comment]
> The argument immediately preceding this maybe
> Changing direction drastically like this because you just want people to shut up rather than actually discuss the issue.

There is no issue, stats of this armor have been discussed before, and it was buffed due to being on par with cheapest armor protection-wise, while costing a small fortune and research efforts to make. It's still nowhere near as good as it should be in my opinion tho.
Your only arguments is authority of some other coder who made a "list of people who are supposed to have Tier 3 protective clothes" and ridiculous accusations that you can not even in theory substantiate, because that's complete nonsense.

**Comment by Iglpigl** [comment]
KIROV I would recommend just ignoring everything that a miner/dev delegate says it isn't worth getting worked up on, it works wonders for me.

**Comment by Humonitarian** [comment]
> 

I do agree with kirov regarding the paramedic armor being fairly weak in terms of raw protection. It's still not an armor you'll pick over a BP vest, especially due to later nerfs.

The first implementation was funny though. Actual powergame armor with permanent speed buff, style dodge and ok protection.

As for just the style specifically, it goes against the norm, and the helmet offers little to no disadvantages until you observe its flaws from more closely:
Must be lifted up or blocks sight, protection not significantly better than the odd helmet, and worst of all: constant annoying pings about people's wellbeings.

So all in all, the armor has a bit of everything, but that everything includes the downsides.
I mean, I recall this thing has stiffness too, no?

Personally our game also lacks the line of "low negative style", especially for things like vests. Pretty much nothing has that. But that's for another conversation entirely.

**Pull request closed without merging**
