### PR TITLE
Adding in Ghost roles

### PR DESCRIPTION
**Pull request by zombiemimic**
## About The Pull Request
Adds in ghost roles, stolen from TG. these are intended to be stories that run roughly parallel to the main Eris crew, with groups like scavengers, prisoners, and other people working to explore parts of the universe beyond the main ship. Currently adds in the prison hulk
image
TODO: add in ghost role menu

## Changelog
:cl:
add: Added ghost roles
add: Added prison hulk, in which prisoners must escape their prison ship's wreck
/:cl:

### CODE REVIEW

**Comment by Jan-Blasiak** [comment]
Would be great if, through enough effort, people could find their way back to the ship as people on TG can.

**Comment by L74814** [comment]
I mean, what you can do in this one for now? Stare to the floor thinking why you didn't respawned 30 minutes later? There is any objective or...?

**Comment by L74814** [comment]
> I mean, what you can do in this one for now? Stare to the floor thinking why you didn't respawned 30 minutes later? There is any objective or...?

Oh wait, i'm dumb. I didn't saw the teleporter thing.

**Comment by Firefox13** [comment]
This map is a sin against nature

**Pull request merged**
