### PR TITLE
 Fixes victim checking for operating table 

### PR DESCRIPTION
**Pull request by spaceplaceexplorer**
fixes https://github.com/discordia-space/CEV-Eris/issues/2054
fixes https://github.com/discordia-space/CEV-Eris/issues/2058
fixes https://github.com/discordia-space/CEV-Eris/issues/2108

Also fixes attack_by conditions.

### CODE REVIEW

**Comment by LethalGhost** [comment]
Why not use `buckle_mob(..)` and `unbuckle_mob()` overrides for it?

**Comment by spaceplaceexplorer** [comment]
Done

**Comment by LethalGhost** [comment]
Icon will not reset correclty.

**Comment by LethalGhost** [comment]
Actually I mean we can remove `check_vicum` code and processing complitly.
Huh.

**Pull request merged**
