### PR TITLE
Adds a lot of music tapes

### PR DESCRIPTION
**Pull request by drexample**
## About The Pull Request

Adds playlist autogeneration for music tapes, a lot of them added to our internal config file. GLOBalizes juke lists for easier tracking. Roaches have a chance to spit up a tape on death.

## Why It's Good For The Game

Uplifting musique. Lore justifications on as to why roaches have the tapes in the first place - you know how nintendo coated cartridges for Switch with a really bitter tasting liquid that was intended to make toddles reluctant to swallow them? And then everyone FUCKING EVERYONE started licking those stupid cartridges and posting it online? Yeah, they are coated in the same stuff, but roaches like it for some fucking reason.

## Changelog
:cl:
add: Many more tapes and a way to get them from roaches.
/:cl:

### CODE REVIEW

**Comment by vode-code** [comment]
sorry for not noticing this in the boombox PR, but obj/item/weapon is obsolete as of #6357.

**Comment by drexample** [comment]
> sorry for not noticing this in the boombox PR, but obj/item/weapon is obsolete as of #6357.

if I make them use ammo and kill people, does that count?
(joking, let me fix it)

**Review by TheShown911 — APPROVED** [review]
Let me order tapes from the guild.

**Comment by drexample** [comment]
> Let me order tapes from the guild.

no

**Pull request merged**
