### PR TITLE
Don't get desires to smoke/use drugs if you are addicted to them

### PR DESCRIPTION
**Pull request by Kegdo**
## About The Pull Request

no idea what is in the uhhh what is in the title, I may be sleep depriveed

## Why It's Good For The Game

club buff*

* - actually easier insight stacking
## Changelog
:cl:
balance: you don't get desires to smoke/use drugs if you are addicted to them
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
Absolutely the most based and redpilled PR there could ever be,  the biggest nerf to ciggaretes and a massive nerf to drug abusers, thank god for this pr that i myself couldn't think of in time to make myself.

**Comment by TGCMbetcher** [comment]
Hahahaha, huge chemist buff. Time to sell addictol pills for 100 credits ech

**Comment by Kegdo** [comment]
Addictol is kinda hard to make. So good luck and godspeed.

**Comment by Voldirs** [comment]
But there are more drugs than just spess drugs. INCLUD THEM ALL

**Comment by Kegdo** [comment]
You can only increase the rest meter with space drugs, can't you?

**Comment by Kegdo** [comment]
> But there are more drugs than just spess drugs. INCLUD THEM ALL

included, love you

**Comment by Omni44** [comment]
bateman-patrick-bateman

**Review by TheShown911 — APPROVED** [review]
Maybe making it remove only the drug you are addicted to would be better, but that's out of scope for this PR.

**Pull request merged**
