### PR TITLE
Adds Civilian Version of the Kadmin

### PR DESCRIPTION
**Pull request by maikilangiolo**
## About The Pull Request
As approved by some guy. Slightly worse recoil, smaller scope (like the xbow's and some other laser gunz), and purchaseable in Bill's. 
No, the name is not a spelling mistake. Since the gun it is based on was the *Arisaka*, and FS names are sci-fi/cyberpank references, what better play on word than calling it *Arasaka* like the Cyberpunk 1984 RPG? 

## Why It's Good For The Game
Kovacs change to .30 required introducing something else to regular eris crew a .20 battle rifle option

## Testing
I debugged, test reloaded, fired and disassembled the guns. No bugs were found, all worked fine. Forgor pic
image

## Changelog
:cl:
add: added a civilian version of the Kadmin to Bill's vendor
/:cl:

### CODE REVIEW

**Comment by maikilangiolo** [comment]
this was meant as a draft cause I added last minute the vendor stuff, still in progress

**Comment by ValoTheValo** [comment]
Why not just put the regular kadmin in the billomat?

**Review by hyperioo — APPROVED** [review]
> add: new gun

image

There is nothing wrong with the code though.

**Comment by hyperioo** [comment]
Waiting for @Firefox13 approval

**Comment by maikilangiolo** [comment]
> Waiting for @Firefox13 approval
I knew I should have posted the screenshot 
Screenshots_2022-12-09-21-47-41

**Pull request merged**
