### PR TITLE
Removes most guns and armor from spawning, replaces them with makeshift handmade stuff instead; unblacklist OS guns from spawning and adjust their spawn tags

### PR DESCRIPTION
**Pull request by Kegdo**
## About The Pull Request
Unironical hazard don't go into comments
image

my plan has become real
found an issue while trying to make OS guns spawn, apparently they are spawn blacklisted(and one doesn't even have a spawn tag) and the spawners in OS dungeons just add the other guns, like FS guns, sometimes serbian stuff?? I fixed this a bit, but I'm leaving the rest to Valo and his OS unshittify PR.
## Why It's Good For The Game
I was ~~asked~~ forced to do this by the dev team, specifically Rosalimo and FortuneMaster
please god don't meta me for this

## Changelog
:cl:
balance: remove most guns and armor from spawning, replace them with makeshift handmade stuff instead
fix: unblacklist OS guns from spawning and adjust their spawn tags; no effect as of right now
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
epic troll

**Comment by ValoTheValo** [comment]
Firstly there is absolutely no reason for this to be made, secondly it will screw up loot and make all these items more common, thirdly, one and possibly more items price changes are direct violation to contributing guidelines, you should try reading them.
https://wiki.cev-eris.com/Content_GuidelinesEn

**Comment by Kegdo** [comment]
Seethe, cope, cry, mald, sneed, seed, peed, beep, meep,  cock

**Comment by Alanii** [comment]
Why is Rosa violating NAP.

I'm calling the police.

**Comment by MLGTASTICa** [comment]
The most based and redpilled PR ever made , guild finnaly has a reason to defend vagabond rights and vagabonds have a reason to buy from guild.

**Comment by zombiemimic** [comment]
what in the sam fuck

**Comment by garrulousTeamotei** [comment]
Based

**Review by drexample — APPROVED** [review]
Unironically good change.

**Comment by ValoTheValo** [comment]
> Unironically good change.

Welp. Eris is fucked

**Comment by Humonitarian** [comment]
Kegdo died for our sins

**Comment by Jackofashepard** [comment]
Based

**Comment by Kegdo** [comment]
image

**Comment by Wouju** [comment]
image

**Comment by TheShown911** [comment]
https://user-images.githubusercontent.com/61743710/145087238-3ef2315f-d330-472e-89be-2041ff991d94.mp4

**Comment by TheShown911** [comment]
This PR sucks, first up rosa is not a part of the dev team, and fortune master has some very "controversial" opinions on game balance, this hasn't been approved by any maintainers. I will now give you a telepathic message how to make it not suck. All you have to do is take this PR https://github.com/discordia-space/CEV-Eris/pull/6844 and make a good gun drop a random gun part from it when spawned, instead of the gun itself, that is it.

**Comment by Voldirs** [comment]
Not sure if it's good or not, but definitely based.

**Comment by ValoTheValo** [comment]
To paraphrase some points made in discord
This removes most reasons to go to ruins,deepmaint and junk beacon. As its a global blacklist so the quality of guns and armor will be the same even in deepmaint. Joonk needed a nerf or rebalance but this is overkill, nuking an anthill.

**Comment by Kegdo** [comment]
how do I remove a label from my pr

**Comment by Voldirs** [comment]
you cope

**Comment by ValoTheValo** [comment]
> how do I remove a label from my pr

Cope. Seethe. Mald

**Comment by Kegdo** [comment]
shit

**Comment by Wouju** [comment]
> how do I remove a label from my pr

image

**Comment by Kegdo** [comment]
am cryijgn andh shiaking rn hwy have yyouy done thhis

**Comment by garrulousTeamotei** [comment]
> To paraphrase some points made in discord This removes most reasons to go to ruins,deepmaint and junk beacon. 
Just delete the ruins, deepmaint, and junk beacon then. Problem solved.

**Comment by Kegdo** [comment]
^ this. Mostly nobody goes there anyway(except for the junk beacon(and deepmaint))

**Comment by Humonitarian** [comment]
Don't forget voidsuits and RIGs. Many of those give more armour than the stuff you blacklisted.

**Comment by Kegdo** [comment]
oh fuck right

**Comment by Kegdo** [comment]
observe as I make eris players seethe even more

**Comment by Wouju** [comment]
> Don't forget voidsuits and RIGs. Many of those give more armour than the stuff you blacklisted.

Pipebomb delivered

**Comment by ValoTheValo** [comment]
> Don't forget voidsuits and RIGs. Many of those give more armour than the stuff you blacklisted.

I think he blacklisted all suit armor if i read this correctly. Voidsuits would be under that category

**Comment by Kegdo** [comment]
valo you read the code poorly :)

**Comment by ValoTheValo** [comment]
Also to adress the onestar guns they arent in a state that should be added to the game as they are stupidly op, dont use the correct sprites or sounds, dont have thier calibres implemented properly and lack inhands. And im removing and replacing them completely in my PR

**Comment by Kegdo** [comment]
.>a rare gun that can only spawn in a specific dungeon that requires effort, time and group support to beat

.>stupidly op

:)

**Comment by Humonitarian** [comment]
> > Don't forget voidsuits and RIGs. Many of those give more armour than the stuff you blacklisted.
> 
> I think he blacklisted all suit armor if i read this correctly. Voidsuits would be under that category

/obj/item/rig
/obj/item/clothing/suit/space/void

**Comment by ValoTheValo** [comment]
> > > Don't forget voidsuits and RIGs. Many of those give more armour than the stuff you blacklisted.
> > 
> > 
> > I think he blacklisted all suit armor if i read this correctly. Voidsuits would be under that category
> 
> /obj/item/rig /obj/item/clothing/suit/space/void

Aaaaand he just blacklisted rigs and voids. Fucking brilliant

**Comment by Kegdo** [comment]
humon, they also don't know about the /suit/storage, but don't tell anyone about it

**Comment by Kegdo** [comment]
> Aaaaand he just blacklisted rigs and voids. Fucking brilliant

he doesn't know again!

**Comment by Kegdo** [comment]
> Also to adress the onestar guns they arent in a state that should be added to the game as they are stupidly op, dont use the correct sprites or sounds, dont have thier calibres implemented properly and lack inhands. And im removing and replacing them completely in my PR

they aren't added, I just fixed a bit their spawn tags for your PR

**Comment by Humonitarian** [comment]
adjust the outdated techno void to this please

	armor = list(
		melee = 30,
		bullet = 25,
		energy = 25,
		bomb = 30,
		bio = 100,
		rad = 100
	)

**Comment by Omni44** [comment]
This comes in really handy, I needed good proof why universal education is a bad thing, and not everyone should be able to read, let alone, write, and this more than exhausts my thesis.

**Comment by Omni44** [comment]
> The most based and redpilled PR ever made , guild finnaly has a reason to defend vagabond rights and vagabonds have a reason to buy from guild.

Vagabonds on their way to spend 2500 credits they don't have and can't feasibly earn in current without selling duffel bags worth of good stuff for AK/shitty laser rifle.

**Review by drexample — CHANGES_REQUESTED** [review]
Actually, this makes gun spawners spawn guns by themselves, that's no good!
Find a non-crutch way to preserve gun spawners.

**Comment by drexample** [comment]
I'm fine with guns being unavailable in maint trash from the get-go, but what if we want to spawn them on off-site locations and deepmaint?

**Comment by Kurgis** [comment]
From my glancing perspective more effort has been put into the comments I won't bother reading than this PR, this in turn makes this one of my top picks amongst pull requests to pull amusement from on this repository.

**Pull request closed without merging**
