### PR TITLE
fuck poopendarken wood

### PR DESCRIPTION
**Pull request by CeUvi**
## About The Pull Request
return to plastic wood

## Why It's Good For The Game
imagine cummenshitten sprites on eris (it didn't even have broken states wtf who the fuck did this)

## Changelog
:cl:
imageadd: old wood is back
imagedel: shittencummen wood is no more
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
Savior of CEV Eris

**Comment by drexample** [comment]
what the fuck

**Comment by Sparrowbird611** [comment]
Pic or it didn't happen.

**Comment by CeUvi** [comment]
> what the fuck

you tell me, what the fuck is that 
image

**Comment by Sparrowbird611** [comment]
Old sprite picture or it didn't happen.

**Comment by CeUvi** [comment]
> Pic or it didn't happen.

i'm too lazy to downgrade muh byond and compiling eris


> Old sprite picture or it didn't happen.

image

**Comment by Alliostra** [comment]
One day while CeUvi was spriting, Eris got wood.

**Comment by Omni44** [comment]
> > Pic or it didn't happen.
> 
> i'm too lazy to downgrade muh byond and compile eris
> 
> > Old sprite picture or it didn't happen.
> 
> image

Maybe instead of returning to vanilla sprites swap them with dark 2 ones these seem to have a lot less cum on them and fit better?

**Comment by CeUvi** [comment]
> Maybe instead of returning to vanilla sprites swap them with dark 2 ones these seem to have a lot less cum on them and fit better?

no, I'm not doing that.
they're still noisy as fuck and still don't fit the rest of the sprites, so no.

**Comment by Omni44** [comment]
Whatever then I guess. I am fan of neither new ones or old ones, but new ones definitelly do not fit furniture and rest they are usually paired with cotnrary to old ones.

**Review by Firefox13 — APPROVED** [review]

**Comment by Firefox13** [comment]
Wait a second

**Review by Firefox13 — CHANGES_REQUESTED** [review]
> i'm too lazy to downgrade muh byond and compile eris

Test it.

**Comment by CeUvi** [comment]
well, fuck.
bruh has someone not seen the old wood?

**Comment by CeUvi** [comment]
psych
here it is

**Review by TheShown911 — APPROVED** [review]
Soulless

**Pull request merged**
