### PR TITLE
reduces baycode levels WARNING MAP UPDATE

### PR DESCRIPTION
**Pull request by vode-code**
## About The Pull Request
Removes Pathology, Corgize and Monkeyize admin transformations, and a ckey custom item system.
Warning: this removes items from Pathology department, and thus can easily conflict.

## Why It's Good For The Game
Baycode is stagnating the codebase, and I'm getting rid of some of it here.

## Testing
Entered Pathology and saw nothing wrong.
Operated the Centrifuge(due to PlinHost's condensing it was partially pathology) successfully.
Opened the player panel successfully and Corgize and Monkeyize were missing.

## Changelog
:cl:
del: Removed Pathology
admin: Removed some outdated transformations
code: deleted some inaccessible code
code: removed custom items
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
1) Why
2)Transformations are nanako-code , not bay-code
3) Custom items are accesible if we ever wanted and configured it , why should we remove a feature that is not used randomly?

**Comment by Firefox13** [comment]
Virology sucks, we don't need it, noone wants to deal with these viruses
Monkeyize is used by virology and it's literally never used otherwise. There are buttons for it but I've never seen someone press them, we don't have a way to turn monkeys into humans back (monkeyism syndrome fucks you big time). Same goes for corgize.
Custom items require patreon integration for them not to be a HUGE annoyance to deal with.

**Comment by ValoTheValo** [comment]
was the map update just a removal of the viro machines or has something changed in the map? can you post picture?

**Comment by vode-code** [comment]
> was the map update just a removal of the viro machines or has something changed in the map? can you post picture?

it was deletion of Pathology machines but did not remove the room.
virus2room2

**Comment by vode-code** [comment]
> 1)Why

>Why It's Good For The Game
Baycode is stagnating the codebase, and I'm getting rid of some of it here.

read.

> 2)Transformations are nanako-code , not bay-code

this would be true if I was removing transformations as a whole, but the only instance of nanakode is the movement handler attached to it, and specifically monkey/corgi relies on baycode and bayculture.
Monkey because it uses `primitive_form` var, Corgi because bay has an obsession with corgis and eris does not.

**Review by Firefox13 — APPROVED** [review]
Lifte-testing inbound

**Pull request merged**
