### PR TITLE
Tray shield in hands fix

### PR DESCRIPTION
**Pull request by Iglpigl**
## About The Pull Request

Tray shield inhands arent invisable anymore.

## Why It's Good For The Game

Sprites based.

## Changelog
:cl:
fix: tray shield sprites are now visable
/:cl:

### CODE REVIEW

**Review by TheShown911 — COMMENTED** [review]
Should walk and run sprites look the same?

**Comment by Iglpigl** [comment]
> Should walk and run sprites look the same?

Yes considering it doesnt have diffrent protection when walk/running like ballistic one.

**Review by TheShown911 — APPROVED** [review]
Sure...?

**Review by hyperioo — CHANGES_REQUESTED** [review]
There is a difference
```
/obj/item/shield/riot/tray/get_protected_area(mob/user)
	var/list/p_area = list(BP_CHEST, BP_HEAD, BP_L_ARM, BP_R_ARM, BP_GROIN)
	if(MOVING_DELIBERATELY(user) && wielded)
		p_area = BP_ALL_LIMBS
	return p_area
```
when you walk you get BP_ALL_LIMBS

**Comment by Iglpigl** [comment]
Well yes there is a difference but there are no sprites for it and I tried and failed to sprite decent ones.

**Comment by hyperioo** [comment]
@Iglpigl Conflict due to merging #7527

**Pull request closed without merging**
