### PR TITLE
Bluespace technician fix 

### PR DESCRIPTION
**Pull request by infraredbaron**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

maxresdefault

<hr>
</details>

## Changelog
:cl:

add: New immersive clothes 
soundadd: dedicated sound effect for BST
admin: BST now lore friendly

/:cl:

### CODE REVIEW

**Comment by Kurgis** [comment]
You need to add the new bst items to the junk spawner blacklist, otherwise it will spawn in trash piles.

**Comment by MCterra10** [comment]
Ho ho ho ha ha, ho ho ho he ha. Hello there, old chum. I’m gnot an elf. I’m gnot a goblin. I’m a gnome. And you’ve been, GNOMED’

**Comment by SpadesSlick** [comment]
Maybe we should not do THOSE kind of memes? BTS were meant to be something players can ignore while we test/fix shit in game. A fucking GNOME will summon half of the server just to watch it.

**Comment by infraredbaron** [comment]
Think about it as incentive for admins to interfere as minimum as possible, which will further improve actual gameplay with more subtle means of influence.

**Comment by SpadesSlick** [comment]
How a gnome costume reduces admin interference?

**Comment by infraredbaron** [comment]
If there any other way of fixing issues with IC means, it would be favored by design itself.
If bst are needed, admins need something that will indicate them as something that have no reference to current round.

**Comment by SpadesSlick** [comment]
That's what usual BTS clothes do, a Gnome costume will force people to react to it.

**Comment by drexample** [comment]
@SpadesSlick Well, first things first. BST would attract attention no matter how they look. 
It's a man with no markings of any friendly faction, that phases through solid matter and is physically invulnerable, wielding unseen power and tech. For what it's worth, people may take it for an antag.

Gnomes on the other hand are... well, gnomes. Mythical creatures that are rumored to have weird powers. If someone says that there's a gnome near them, people would just shrug it off, because, come on, that's silly. Gnomes aren't real. I wholeheartedly support this PR.

**Comment by SpadesSlick** [comment]
That's not how that will work. This is pure, unrefined meme in the wild, and worst of all, this is meme that have nothing to do with our thematic, it's not sci-fi, cyberpunk or anything like this. Just a little bit of reddit in our codebase.

So it's no from me.

**Pull request closed without merging**
