### PR TITLE
EOTP displays miracle points.dm

### PR DESCRIPTION
**Pull request by TheLeopold**
## About The Pull Request
Adds miracle counter to EOTP description

## Why It's Good For The Game
No more gueswork!

## Testing
Screenshot_1

## Changelog
:cl:
tweak: EOTP displays miracle points
/:cl:

### CODE REVIEW

**Comment by TheLeopold** [comment]
Should I rename it to "Miracle points" or that would be too gamey?

**Comment by Humonitarian** [comment]
What purpose do these serve?

**Comment by TheLeopold** [comment]
Miracle points are spent when group litanies are performed.
When there's no miracle points, group litanies just fail.
And there's zero in-game feedback on why they failed.

**Comment by Humonitarian** [comment]
> Miracle points are spent when group litanies are performed. When there's no miracle points, group litanies just fail. And there's zero in-game feedback on why they failed.

Never knew this was a mechanic

**Review by Humonitarian — APPROVED** [review]

**Pull request merged**
