### PR TITLE
Onestar Guns

### PR DESCRIPTION
**Pull request by zombiemimic**
## About The Pull Request
Have you ever wondered why all these new guns are being found in this ancient ruin? Now there's appropriately old guns in those lockers!
image

Will be blacklisted until loot rework gets done

## Changelog
:cl:
add: Added Onestar Guns
/:cl:

### CODE REVIEW

**Comment by GrayRachnid** [comment]
We all know this is going to be shutdown the moment Firefox or Nestor lays eyes on it so why even try :flatcat:

**Comment by zombiemimic** [comment]
> We all know this is going to be shutdown the moment Firefox or Nestor lays eyes on it so why even try :flatcat:

I believe Firefox requested it explicitly

**Comment by Anonmare** [comment]
The Type 47 is using arabic numerals whilst the other models are using roman numerals, which is inconsistent. I'd vote for using arabic numerals for clarity's sake.

**Comment by zombiemimic** [comment]
> The Type 47 is using arabic numerals whilst the other models are using roman numerals, which is inconsistent. I'd vote for using arabic numerals for clarity's sake.

fixed

**Comment by Anonmare** [comment]
What a heck of a commit name

**Comment by Wouju** [comment]
> What a heck of a commit name

coder moment

**Comment by ValoTheValo** [comment]
finally. this is a really good addition, those guns have been sitting unused for years now at this point

**Comment by FortuneMaster** [comment]
There is one big problem - sprites are outdated as hell

**Comment by Firefox13** [comment]
> 
> 
> We all know this is going to be shutdown the moment Firefox or Nestor lays eyes on it so why even try :flatcat:

I've allowed adding OS guns before

**Review by Firefox13 — APPROVED** [review]

**Comment by TheShown911** [comment]
Sprites are very outdated.

**Pull request merged**
