### PR TITLE
Bundle of Job Fixes, Inspector Access Fix, Neotheo Money Fix and other Misc Fixes

### PR DESCRIPTION
**Pull request by ValoTheValo**
## About The Pull Request
I noticed that for some reason inspector couldn't access brig cells and NeoTheo randomly would stop getting payed due to not actually having a funding source set for them. despite being one of two funders of the expedition lore wise. also for some reason the preacher didn't get a command wage like the rest of command, 

## Why It's Good For The Game
Lorefix and Oversight Fix good?. Neotheo should probably be funding the expedition like they are in lore and i dont really see any reason why they shouldn't have wages and every other department has them. Inspector needs brig access to actually do his job, Preacher is a command staff member and should be payed like one, even if they can roll inquis.

## Changelog
:cl:
fix: Inspector can now access brig cells
fix: Preacher gets a command wage like the rest of command
fix: NeoTheo now actually has a funding source and wont run out of money halfway through the round
fix: IH Jobs now say supervisors correctly
tweak: Inspector spawns with suit sensor monitor for enhanced detectiving
balance: Janitor now has hazard pay instead of professional pay 
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
looking through the PR Change history there appears to have been a small revert war over the NT money thing at one point
#6039 #6050 #6051 still don't really understand why it was done in the first place or why NT and only NT was hit with this. I'm just confused

**Comment by ValoTheValo** [comment]
also this may require a test merge as i am unable to test it on local because it would be annoying to wait like several hours to see if NT still runs out of money randomly. up to maintainers if its required or not

**Comment by MLGTASTICa** [comment]
Big thumbs down on the inspector starting with suit sensor monitor , if he wants one he should either chose it in his loadout or bother moebius.

**Comment by ValoTheValo** [comment]
> Big thumbs down on the inspector starting with suit sensor monitor , if he wants one he should either chose it in his loadout or bother moebius.

he can literally download it on his console within like 20 seconds. this just puts it on his PDA like the medspec has

**Comment by MLGTASTICa** [comment]
> > Big thumbs down on the inspector starting with suit sensor monitor , if he wants one he should either chose it in his loadout or bother moebius.
> 
> he can literally download it on his console within like 20 seconds. this just puts it on his PDA like the medspec has

then let him download it , i dont see any point in them starting instantly with it.

**Comment by ValoTheValo** [comment]
> > > Big thumbs down on the inspector starting with suit sensor monitor , if he wants one he should either chose it in his loadout or bother moebius.
> > 
> > 
> > he can literally download it on his console within like 20 seconds. this just puts it on his PDA like the medspec has
> 
> then let him download it , i dont see any point in them starting instantly with it.

the fucking medspec can download it to his PDA, the Inspector can only do it with a laptop or console, why is this even a thing to complain about?

**Comment by MLGTASTICa** [comment]
> > > > Big thumbs down on the inspector starting with suit sensor monitor , if he wants one he should either chose it in his loadout or bother moebius.
> > > 
> > > 
> > > he can literally download it on his console within like 20 seconds. this just puts it on his PDA like the medspec has
> > 
> > 
> > then let him download it , i dont see any point in them starting instantly with it.
> 
> the fucking medspec can download it to his PDA, the Inspector can only do it with a laptop or console, why is this even a thing to complain about?

because its automating yet another aspect of the early round , and imposes the player to delete the suit monitor if he wants another program installed such as power grid monitor.

**Comment by ValoTheValo** [comment]
> > the fucking medspec can download it to his PDA, the Inspector can only do it with a laptop or console, why is this even a thing to complain about?
> 
> because its automating yet another aspect of the early round , and imposes the player to delete the suit monitor if he wants another program installed such as power grid monitor.

oh no a minor QOL change this game is literally unplayable, i may have to delete the word processor app to download some random bullshit. how does this matter?

**Comment by ValoTheValo** [comment]
https://youtu.be/a8MZBUoQt68

**Comment by garrulousTeamotei** [comment]
> oh no a minor QOL change this game is literally unplayable, i may have to delete the word processor app to download some random bullshit. how does this matter?

You don't understand, the minute download time on the suit sensor monitor is integral to the detective gameplay loop

**Review by SirRichardFrancis — APPROVED** [review]

**Review by TheShown911 — APPROVED** [review]

**Pull request merged**
