### PR TITLE
Reorders all common oddities in oddities.dm to make more sense

### PR DESCRIPTION
**Pull request by DiaFRAME444**
## About The Pull Request
Prepares this document for another PR I'm planning to make later down the line.
General order should be Singular Combat Stat > Singular Work Stat > Dual Combat Stat > Dual Mixed >, and so on.
Also fixes description on the observer book.

## Why It's Good For The Game
I tried to mess with this file earlier, but since everything was out of order and ended up constantly jumping towards different points.
I also believe the reorganized state of this file reveals some things about our current oddity design and layout.

## Changelog
:cl: 
tweak: The oddities.dm file has been reordered.
spellcheck: Observer book description changed.
fix: Bear math oddity is now a subtype of /obj/item/oddity/common/, which allows it to spawn in maintenance.
/ :cl:

### CODE REVIEW

**Comment by Kurgis** [comment]
Looks good.

**Comment by Firefox13** [comment]
If you're actually sorting them then add comments on when certain type of sort starts.

**Comment by Firefox13** [comment]
Even if it does nothing for playerside changelogs are important for bookkeeping.

**Comment by DiaFRAME444** [comment]
> Looks good, though you could argue that oddities can be ordered by alphabet, or ordered by their general palette/description theme as well.

This seems to be the most helpful layout.
Do correct me if I'm wrong.

> If you're actually sorting them then add comments on when certain type of sort starts.

Done

> Even if it does nothing for playerside changelogs are important for bookkeeping.

Fixed

**Review by hyperioo — APPROVED** [review]

**Pull request merged**
