### PR TITLE
fix using spent advanced kits to heal wounds in surgery

### PR DESCRIPTION
**Pull request by ErisMeleeEnjoyer**
## About The Pull Request
NO FUN ALLOWED

## Why It's Good For The Game

quick 1984 fix

## Changelog
:cl:
fix: using spent advanced kits to heal wounds in surgery
/:cl:

### CODE REVIEW

**Comment by pexel5** [comment]
No

**Review by hyperioo — CHANGES_REQUESTED** [review]
```
user.visible_message(
		SPAN_NOTICE("[user] finishes treating damage to [organ.get_surgery_name()] with \the [tool]."),
		SPAN_NOTICE("You finish treating damage to [organ.get_surgery_name()] with \the [tool].")
	)
```
should be put inside the if to have it displayed only if healing is successfull.
And add `to_chat(user, SPAN_WARNING("\The [tool] is used up."))` inside an `else` to warn the user if it's completely used.

**Review by TheShown911 — COMMENTED** [review]
My brother in christ you fail every single check.

**Comment by ErisMeleeEnjoyer** [comment]
I'm built different.

**Comment by ErisMeleeEnjoyer** [comment]
Unbuilted differently

**Review by TheShown911 — APPROVED** [review]

**Review by hyperioo — APPROVED** [review]

**Pull request merged**
