### PR TITLE
Datumizes world/topic & admin/topic

### PR DESCRIPTION
**Pull request by nichlas0010**
Only two mechanic changes have been made to world/Topic, that being the removal of ?players and the changing of ?ping returning 1 more client than there really is.

?players was removed because it wasn't used and was just a clone of ?ping, except without an increment, and ?ping was changed to return the number of clients rather than the number of clients +1, cause that makes sense.

all the admincaster datums have been merged into one, using admincaster as the href

Port of: https://github.com/tgstation/tgstation/pull/31543/files

### CODE REVIEW

**Comment by nichlas0010** [comment]
did about 2/3rds of the admin topic so far 😄

**Comment by ACCount12** [comment]
Nice work. We need to port a lot of refactors to modernize the codebase. Guess I'll start by porting mine too.

**Comment by nichlas0010** [comment]
Ready for review :)

**Comment by NanakoAC** [comment]
This is risky, change the target branch to Development please, we'll try it out on the test server first

**Pull request merged**
