### PR TITLE
[BOUNTY] New type of shutter + shutter respriting

### PR DESCRIPTION
**Pull request by cheesePizza2**
## About The Pull Request

Adds in a new type of shutter - similar to the regular iron shutter, except with holes (think like the ones at malls). You can see through it, of course.
New sprites for the new shutter, as well as replacement sprites (done by Ceuvi) for shutters.

## Why It's Good For The Game

Better sprites + cool new subtype for mappers and players

## Testing

Worked fine

## Changelog
:cl: Cheesepizza2, Ceuvi
add: Added new type of lighter shutters (i.e. ones with holes in them).
imageadd: Replaced shutter sprites.
/:cl:

### CODE REVIEW

**Comment by githubuser4141** [comment]
What it looks like: 
image
image

Yes this is a 100% certified lazy moment

**Comment by Firefox13** [comment]
I would like to see how sprites look in-game

**Comment by Firefox13** [comment]
> Worked fine

I don't believe you.

**Comment by cheesePizza2** [comment]
My guy forgot to give me unwelded/unscrewed/unplated sprites, give me a sec to figure this out

**Comment by thevandie** [comment]
next stop, airlocks

**Comment by cheesePizza2** [comment]
> My guy forgot to give me unwelded/unscrewed/unplated sprites, give me a sec to figure this out

welp, dude wanted me to do them so uhhhhhhh

pro tip: never ask a coder to do spriting work

**Comment by Humonitarian** [comment]
Ingame images/videos please.

**Comment by githubuser4141** [comment]
Image. Sadly the warning lights don't appear to function.

image

**Comment by Humonitarian** [comment]
Doesn't seem to fit our sprite angles.

These doors are top down, and we're.... What's it called again? 3/4s?

Basically, look at walls for how they should look.

**Comment by cheesePizza2** [comment]
Removing hazard door sprites.

**Comment by hyperioo** [comment]
No problem codewise, need a spriter to check...

**Review by hyperioo — APPROVED** [review]
Some feedback on hazard doors from a spriter I asked about:
The yellow on the emergency shutters feels too bright, and I also have a faint inclination that the hues aren't shifted, which might help its aesthetic.
The top part of the bottom half looks like it has no shading because it's so contrasted by that neon yellow that you can't really make it out. Toning the yellow done and expanding shading could help.
The sideways views of the doors also look really noisy/cluttered, but not sure if that's just a byproduct of the angle and/or the difficulty to make door sprites of that variety. Toning down the yellow might help with that.

**Pull request merged**
