### PR TITLE
Fix Jive comms

### PR DESCRIPTION
**Pull request by Firefox13**
## About The Pull Request
Removes NONVERBAL flag from it. As much as I can say, those two flag (NONVERBAL and SIGNLANG) shouldn't be used together and Jive is more of subtle motions rather than moaning slightly and pointing fingers (which is kind of non-verbal)

## Why It's Good For The Game
Fixes people talking on Jive through radio

## Changelog
:cl:
tweak: Removed NONVERBAL flag from Jive, in return it's much more like a sign language and people can't talk on it through comms
/:cl:

### CODE REVIEW

**Comment by Firefox13** [comment]
I'd like to see if it fucks with TTS in any way

**Comment by DiaFRAME444** [comment]
> flags = SIGNLANG | NO_STUTTER

Wait, can this be used to activate the Cruciform rituals while in pain?

**Comment by Humonitarian** [comment]
> > flags = SIGNLANG | NO_STUTTER
> 
> Wait, can this be used to use Cruciform rituals while in pain?

Yeah, totally.

**Review by SirRichardFrancis — COMMENTED** [review]
NONVERBAL flag only indicates that people are using sign language to those who don't know that language, and garbles messages over radio.
This will turn Jive speaker into telepaths, as none of their communication would be narrated with hand gestures, that's it.
I fail to see how it would prevent Jive speakers from using radio. Have you tested this?

**Comment by Firefox13** [comment]
I've fixed Jive appearing on comms (FOR SURE THIS TIME).
About it becoming a pure SIGNLANG - I've also made so if language has either flag (SIGNLANG or NONVERBAL, former in our case) it will emote.

**Review by Pink-Chink — APPROVED** [review]
Seemed to work fine in test.

**Pull request merged**
