### PR TITLE
Uplink boxes with guns

### PR DESCRIPTION
**Pull request by TheReduce**
## Changelog
:cl:

add: Added boxes for guns in uplink. Every box contains gun and one magazine for it (sniper rifle have one bullet instead)

upd:
add: sprite for big box of doom
image

/:cl:

### CODE REVIEW

**Comment by Kurgis** [comment]
Traitors need whatever they can get, this is a nice change.

**Comment by RandomColonist** [comment]
Make AM rifle come with handful of 5 shells instead, you can't kill anyone in a single shot reliably. There is prespawned handful with 5 shells, check code of an ammo box from an uplink.

**Comment by TheReduce** [comment]
> Make AM rifle come with handful of 5 shells instead, you can't kill anyone in a single shot reliably. There is prespawned handful with 5 shells, check code of an ammo box from an uplink.

you can buy ammo for AM rifle if you miss your one shot. I want to rebalance Uplink economy until next launch, because it's succ

**Comment by RandomColonist** [comment]
> you can buy ammo for AM rifle if you miss your one shot. One shot is a feature. I want to rebalance Uplink economy until next launch, because it's succ

Might want to take a look at my attempt then #3559 , maybe you'l find something useful there or incorporate something in your PRs. I am planning to change uplink a bit too.

**Comment by TheReduce** [comment]
> Might want to take a look at my attempt then #3559 , maybe you'l find something useful there or incorporate something in your PRs. I am planning to change uplink a bit too.

i haven't got a big plans for uplink, but now traitors succ i think and want to buff them a bit. i'll look your pr, thx

**Comment by TheReduce** [comment]
Nees to check something, dont approve

**Pull request merged**
