### PR TITLE
water and welder fuel tanks resprite

### PR DESCRIPTION
**Pull request by CeUvi**
## About The Pull Request
speedmerge
now
image

tank sprites by walterje
big tanks by me
## Why It's Good For The Game
bay leftovers 🤮 
## Changelog
:cl: John Wayne (aka WalterJe / WatlerJe)
imageadd: resprut of the watertanks
imageadd: resprut of the fueltanks
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
Does this change the weldertanks on the ruins?

**Comment by CeUvi** [comment]
do they have some special icons?
if no - then yes, this does change them
if yes - then no, this doesn't

**Comment by Kegdo** [comment]
they have, also, close this pr, Ima do the same thing but better.

**Comment by CeUvi** [comment]
ok.

**Pull request closed without merging**
