### PR TITLE
NT BSD "Harpoon

### PR DESCRIPTION
**Pull request by Evankhell561**
## About The Pull Request
del NT BSD "Harpoon" from the map
add NT BSD "Harpoon" to rd closet

## Why It's Good For The Game
Remove stuff from the map

## Changelog
:cl:
del: NT BSD "Harpoon"
add: NT BSD "Harpoon"
/:cl:

### CODE REVIEW

**Comment by Kurgis** [comment]
Remove the RD Locker from the RD's Quarters, or make it spawn with no Harpoon.

**Comment by GrayRachnid** [comment]
The reason it's on the map is because there's 2 RD lockers

**Comment by Evankhell561** [comment]
> Remove the RD Locker from the RD's Quarters, or make it spawn with no Harpoon.

really?
can I at least replace it with a reactive teleport armor?

**Comment by Evankhell561** [comment]
> The reason it's on the map is because there's 2 RD lockers

oh sorry and if I better close this?

**Pull request closed without merging**
