### PR TITLE
Delete loadout.txt

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Deletes the unused loadout.txt file

## Why It's Good For The Game

Has 0 impacts on the game itself so it doesn't really matter

## Changelog
:cl:
del: Removed an old unused file.
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
dude its just a debug file for corrupt  / missing item refs in player loadout saves

**Comment by Trilbyspaceclone** [comment]
It dosnt do anything tho, no point in having it.
Dosnt even update itself its form bay on Dec 16, 2018.
You dont even have most of the items listed in that file.
Why have it?

**Comment by ValoTheValo** [comment]
> It dosnt do anything tho, no point in having it. Dosnt even update itself its form bay on Dec 16, 2018. You dont even have most of the items listed in that file. Why have it?

Then update the fucking file????

**Comment by ValoTheValo** [comment]
There is already issues with player save corruption. I dont think doing this helps

**Comment by Trilbyspaceclone** [comment]
> Then update the fucking file????

Update it to what? *Nothing uses or checks that file*

**Comment by Trilbyspaceclone** [comment]
> There is already issues with player save corruption. I dont think doing this helps

Please show me anyware in the code that uses this file or links to it, I would be shocked if a .txt file with bay code and species somehow corrupts player saves

**Comment by MLGTASTICa** [comment]
> It dosnt do anything tho, no point in having it. Dosnt even update itself its form bay on Dec 16, 2018. You dont even have most of the items listed in that file. Why have it? Edit: Side note it has races that are not even present here like "SPECIES_UNATHI"

Because all the missing / corrupt loadouts are fixed , but there might be some in the future.

**Comment by SirRichardFrancis** [comment]
> Because all the missing / corrupt loadouts are fixed , but there might be some in the future.

His point is that nothing even in theory uses loadout.txt, hence it's completely redundant.
Which, fair enough, looks like a valid point, there is no references to it in the code.
Could be in some script though, there is one that _checks for misspelling of NanoTrasen_, so maybe loadout too being checked at some point.

**Comment by Trilbyspaceclone** [comment]
Simply put, any error in their was detected on bay, not here.
Nothing here links to that file.
The data in that file is outdated and does nothing.

**Review by TheShown911 — APPROVED** [review]

**Pull request merged**
