### PR TITLE
Fix disco elysium reference sprite

### PR DESCRIPTION
**Pull request by Firefox13**
## About The Pull Request
Fix visible calves on dark comfortable clothing which is a disco elysium reference

## Why It's Good For The Game
I do not like visible sheens people stop spriting with jackboots on

## Changelog
:cl:
fix: added missing pixel on dark comfortable clothing sprite
/:cl:

### CODE REVIEW

**Comment by SirRichardFrancis** [comment]
image
This is a Disco Elysium reference?? Looks super generic, no vibe, no soul, no nothing.

**Comment by MLGTASTICa** [comment]
> 

the vaga uniform is more of a reference to disco elysium than these plants.

**Comment by Firefox13** [comment]
The jacket (actual reference) is a suit. This is what under the jacket + pants.

**Comment by Firefox13** [comment]
изображение

**Comment by SirRichardFrancis** [comment]
It looks like more like this:

image

Rather than this:

image
image

All of the colors are different, only similarity - there is pants on the picture. That's it.
Also Kim had a sleeveless shirt, but on a sprite it's a generic t-shirt.

**Comment by Firefox13** [comment]
sprite it thyself I only fixed ankles sprite like I did before like #5442

**Review by SirRichardFrancis — APPROVED** [review]

**Review by Pink-Chink — APPROVED** [review]

**Comment by Firefox13** [comment]
I fucking hate .dmi conflicts, I'll remake it quick

**Pull request closed without merging**
