### PR TITLE
Comments out benzin

### PR DESCRIPTION
**Pull request by Humonitarian**
## About The Pull Request

Removes benzin roaches

## Why It's Good For The Game

Might fix lag

## Changelog
:cl:
del: No more benzin
/:cl:

### CODE REVIEW

**Comment by garrulousTeamotei** [comment]
Salt PR

**Comment by Humonitarian** [comment]
> Salt PR

### I fucking love Benzin roaches! I want to fucking shoot benzin roaches and destroy essential infrastructure! I want to fucking gib them and burn to death because I was smoking a cigarette due to the billion negative sanity effects despite running the highest vig build possible! I am in fucking love with atmos breaking and shitting from all the active fires and several hundred celsius of temperature!**

**Comment by garrulousTeamotei** [comment]
Sounds like a skill issue.

**Comment by Humonitarian** [comment]
> Sounds like a skill issue.

There is not a speck of sarcasm in any of my words. I experience the most genuine joy when I see benzins do whatever they do

**Comment by assortedbeads** [comment]
Counterpoint add more benzins

Add a plasma roach that plasma floods the area when shot

**Comment by pexel5** [comment]
cringe

**Pull request merged**
