### PR TITLE
Hotkey tweaks

### PR DESCRIPTION
**Pull request by Moltovz**
## About The Pull Request
The hotkey-help verb states that you can cycle intents with CTRL+F and CTRL+G on hotkey or normal mode, however mechanically this was not the case. This PR fixes that. Also adds missing binds to the hotkey-help verb. Changes the color of the "Hotkey mode" section of hotkey-help to make it more distinguishable from the other section.

## Testing
Tested locally.

https://user-images.githubusercontent.com/61367602/210183188-b5444363-e8ef-4bb2-a2d1-76985a2a2572.mp4

## Changelog
:cl:
fix: You can cycle intents with a bind while in hotkey mode.
fix: Adds missing binds to hotkey-help's hotkey mode list
tweak: Hotkey mode and any mode now have different colors in the hotkey-help verb.
/:cl:

### CODE REVIEW

**Comment by Firefox13** [comment]
That list of changes is very hard to read, there's a lot of unnecessary changes

**Comment by Moltovz** [comment]
> That list of changes is very hard to read, there's a lot of unnecessary changes

sure, reverted the color change, and the hotkey-help change. Hotkey-help will remain inaccurate, for now.

**Comment by Firefox13** [comment]
I mean these changes, other were fine.
изображение
изображение

**Comment by Moltovz** [comment]
> 

I think those were just dream daemon or VSC's automatically doing changes, lmao. Quirky. I changed skin.dmf with dream maker, not sure why all of those happened. I'll revert my reverts (Christ) and change skin.dmf manually so those automatic changes dont occur.

**Comment by Moltovz** [comment]
https://user-images.githubusercontent.com/61367602/210211467-917b501e-15d7-41e3-817b-108195aff8e1.mp4

Yeah, modifying the .dmf in dream maker automatically changed a ton. Manually added this to the .dmf in VSC and it works fine, love dream maker.........
                
```
                name =  "CTRL+F"
		command = "a-intent left"
	elem
		name = "CTRL+G"
		command = "a-intent right"
```

**Review by hyperioo — APPROVED** [review]

**Pull request merged**
