### PR TITLE
badges resprite

### PR DESCRIPTION
**Pull request by CeUvi**
## About The Pull Request

title.
badges

## Why It's Good For The Game

bay leftovers bad.
awful, even.

## Changelog
:cl: CeUvi
imageadd: new badges
imagedel: bayleftover badges
/:cl:

### CODE REVIEW

**Comment by Kegdo** [comment]
gucci

**Comment by Faryaa** [comment]
On-mob sprites could be smaller, but inventory sprites are great.

**Comment by CeUvi** [comment]
but they're almost the same size as they were before.

**Comment by SirRichardFrancis** [comment]
Badge name in `icons/inventory/accessory/mob.dmi` is spelled wrong, should be `marshalbadge`, not `marshallbadge`.
Pretty sure it will be invisible in game, have you actually tested that PR?

**Review by SirRichardFrancis — COMMENTED** [review]
Badge name in `icons/inventory/accessory/mob.dmi` is spelled wrong, should be `marshalbadge`, not `marshallbadge`.
Pretty sure it will be invisible in game, have you actually tested that PR?

**Comment by CeUvi** [comment]
> have you actually tested that PR?

of course i did

**Comment by ValoTheValo** [comment]
Can you give inspector a badge?

**Comment by GrayRachnid** [comment]
can you make it so badges can be attached to armors? currently they can only be attached to jumpsuits.
We should have the code to support this.

**Comment by CeUvi** [comment]
If only I knew how to code.

**Comment by SirRichardFrancis** [comment]
> can you make it so badges can be attached to armors? currently they can only be attached to jumpsuits. We should have the code to support this.

Badges can be attached to armor no problem. @Humonitarian coded it like a month ago, IIRC.

**Comment by Humonitarian** [comment]
I go unnoticed yet again 😔

**Review by TheShown911 — APPROVED** [review]

**Review by mattroks101 — APPROVED** [review]

**Pull request merged**
