### PR TITLE
replaces NeoTheologian with NeoTheology

### PR DESCRIPTION
**Pull request by Firefox13**
## About The Pull Request
replaces all instances of NeoTheologian with NeoTheology

## Why It's Good For The Game

it's not a real word, neotheologist is. NeoTheology can work as adjective
this broken english bothered me for long enough

## Changelog
:cl:
spellcheck: instances of NeoTheologian was replaced with NeoTheology
/:cl:

### CODE REVIEW

**Comment by Firefox13** [comment]
Ignore the commit history

**Comment by Kurgis** [comment]
> it's not a real word, neotheologist is.
Not sure what this is explicitly trying to state, since Neotheologist isn't specifically a word. If it's referring to "theologist", well, "theologian" is also a word. Actually, theologian would fit in most of these use cases better than theologist anyways.

**Comment by Firefox13** [comment]
изображение
This is here from ancient times and "NeoTheologians" were added by DarkLevel (his english skill are lacking).
I hate both those words.

**Comment by Firefox13** [comment]
Both wiki pages, techno doc and in-game mention NeoTheology and Neotheology.
I don't know.

**Pull request merged**
