### PR TITLE
Removes faction voidsuits from maint

### PR DESCRIPTION
**Pull request by Garen7**
## About The Pull Request

People have been asking for this for a while(I think theres like 3 requests or so in the #feedback channel in discord) so I'm gunna go ahead and put it through the proper channels so that someone who has the authority can either approve, refuse, or request modifications to the proposed changes. I modified the rarity of the blood red voidsuit so that it wont become more common since the spawn pool is shrinking, see the spawn pool charts below.

## Why It's Good For The Game

1. The armored voidsuits in maint have been power creeping on the armor already in maint
2. The above reason has led to a reduced design space where people feel like a new armor needs to have 50-70 armor stats to be viable
3. Improved clarity, people often mistake vagabonds for technomancers, IH, or miners since vagabonds are so prone to wearing their voidsuits
 
## Changelog
:cl:
tweak: Removed faction voidsuits from maint loot
/:cl:

Before:
Before

After removal but before blood red rarity adjustment:
beforeRarity

After:
After

### CODE REVIEW

**Review by MadmanMartian — APPROVED** [review]
Nice adjustment to the rarity value.

**Comment by ArmolitskiyCarpoeb** [comment]
And what kind of voidsuits will appear there then? We do not have any ordinary spacesuits that are not from any faction.

**Review by TorinoFermic — APPROVED** [review]
Excellent graphs showing the proof of your change

**Comment by TorinoFermic** [comment]
> And what kind of voidsuits will appear there then? We do not have any ordinary spacesuits that are not from any faction.

The default would be NASA spacesuit

**Comment by genessee596** [comment]
> And what kind of voidsuits will appear there then? We do not have any ordinary spacesuits that are not from any faction.

Default, red NASA voidsuit.

**Comment by ArmolitskiyCarpoeb** [comment]
I suggest adding 1-2 regular, generix spacesuits first.

**Review by genessee596 — APPROVED** [review]
Actual graphs? Incredible

**Comment by genessee596** [comment]
> I suggest adding 1-2 regular, generic spacesuits first.

No need, we already have four different voids that are spawning after this PR gets merged.

**Comment by ArmolitskiyCarpoeb** [comment]
Okay, I've been thinking about it a bit. I think people will wear armor more often, because the suits in the maints are bad, boring and ugly.

**Comment by ArmolitskiyCarpoeb** [comment]
Cool PR

**Comment by Garen7** [comment]
> Cool PR

Thanks, and yeah the whole point is to make it so maint voidsuits aren't completely better than maint armor, any voidsuit you wana sprite or have added to maint that wouldnt compete with actual armor I'll code even any special effects you would want on it like reduced vision or whatever ill work with you for

**Pull request merged**
