### PR TITLE
Revert "Add Christmas alternative to benzin roaches"

### PR DESCRIPTION
**Pull request by Firefox13**
Reverts discordia-space/CEV-Eris#7940

изображение

### CODE REVIEW

**Comment by DiaFRAME444** [comment]
picture doesn't demonstrate a problem.

**Comment by Firefox13** [comment]
A shitton of explosions roundstart and some time after that.
As well as being, as much as Christmas spirit it gives, really memey.

**Comment by ValoTheValo** [comment]
1984

**Review by TheShown911 — APPROVED** [review]
Christmas is ruined

**Comment by Firefox13** [comment]
It can also trigger breaches roundstart.

**Pull request merged**
