### PR TITLE
Fix invisible metal rods

### PR DESCRIPTION
**Pull request by HentaiStorm**
## About The Pull Request

Fix of missing stacks of metal rods

## Why It's Good For The Game

Metal rods are displayed correctly and there will be no way to make an invisible hologram out of them

## Changelog
:cl:
fix: fix of missing stacks of metal rods
fix: fix opened water bottle sprite
fix: fix missing halbert back sprite
/:cl:

### CODE REVIEW

**Comment by SirRichardFrancis** [comment]
Fixes are great, but there is a better way of fixing that issue.
I blame #6907 for fucking up the rod icons. Just bring those back I guess.
image

**Comment by MLGTASTICa** [comment]
Laziest fix possible. Wouldnt recommend merging.

**Comment by TheShown911** [comment]
There are other icons changed in this PR that are not mentioned in the PR itself.

**Comment by hyperioo** [comment]
If the new NT halbert sprite and opened water bottle sprite are intented, add them to the changelog and PR description.

**Review by hyperioo — APPROVED** [review]

**Pull request merged**
