### PR TITLE
Makes HALLOSS obey energy armour

### PR DESCRIPTION
**Pull request by Jackofashepard**
In addition if you have really good energy armour it'll soak most of the HALLOSS (The only armour this strong atm is the ablative vest)

### CODE REVIEW

**Comment by Coureere** [comment]
Well, i assume usual armor with energy value of 30 would help as well, i assume? Did you test its effectiveness?

**Comment by Jackofashepard** [comment]
Yes, armour 30 would remove 0.375% of the halloss

**Comment by Jackofashepard** [comment]
I promted for ARMOUR_ENERGY/80 since a lot of our armours have extremely low if any energy resistance

**Comment by TorinoFermic** [comment]
Can you edit this code at end of this proc so it looks like this     
```
//No armor? Damage as usual
    if(armor_effectiveness == 0)
        apply_damage(effective_damage, damagetype, def_zone, used_weapon, sharp, edge)
        return effective_damage
    //Here we split damage in two parts, where armor value will determine how much damage will get through
    else
        //Pain part of the damage, that simulates impact from armor absorbtion
        //For balance purposes, it's lowered by ARMOR_AGONY_COEFFICIENT
        if(!(damagetype == HALLOSS ))
            var/agony_gamage = round( ( effective_damage * armor_effectiveness * ARMOR_AGONY_COEFFICIENT ) / 100 )
            apply_effect(agony_gamage, AGONY)
        else 
            var/agony_gamage = round( ( effective_damage * armor_effectiveness * (getarmor(def_zone, ARMOR_ENERGY)/80) ) / 100 )
            apply_effect(agony_gamage, AGONY)

        //Actual part of the damage that passed through armor
        var/actual_damage = round ( ( effective_damage * ( 100 - armor_effectiveness ) ) / 100 )
        apply_damage(actual_damage, damagetype, def_zone, used_weapon, sharp, edge)
        return actual_damage
```

**Comment by TorinoFermic** [comment]
Are you there ? Jackofashepard

**Comment by SpadesSlick** [comment]
Obsolete.

**Pull request closed without merging**
