### PR TITLE
Makes havelock a little bit better

### PR DESCRIPTION
**Pull request by Iglpigl**
## About The Pull Request

Makes havelock do 10% damage and have 10% penetration.

## Why It's Good For The Game

It's a gun that was almost never used and the general consensus is that it's quite weak.

## Changelog
:cl:
tweak: tweaked havlocks damage and penetration, it now does 10% more of both
:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
It doesn't need a buff , 40% damage and 40% penetration at .35 is already a very good deal.

**Comment by Humonitarian** [comment]
No buff needed, it can already compete with a Novak, especially when wielded.

A buff is fine if you raise the price, though, to something like 1200-1400.

**Comment by TheShown911** [comment]
A small, cheap and mass produced gun is supposed to be bad, the problem isn't that this gun is useless, but that you can acquire top tier guns easily so this is never used.

**Comment by Firefox13** [comment]
> 
> 
> A small, cheap and mass produced gun is supposed to be bad, the problem isn't that this gun is useless, but that you can acquire top tier guns easily so this is never used.

This. The current problem is amount of top tier guns, not the low-tier guns being awful.

**Pull request closed without merging**
