### PR TITLE
Advanced subsurface ore detector

### PR DESCRIPTION
**Pull request by MadmanMartian**
Adds an advanced mining scanner, to help with locating subsurface materials more precisely

I could not test this on local, as I was not robust enough to get the ship running to move it to a mining asteroid.

## About The Pull Request
After playing some rounds as a shaft miner, I found that, while surface minerals were plentiful, it was misleading and mostly carbon.

## Why It's Good For The Game
This gives something for moebius to give to miners besides atomic cells, and helps with optimizing subsurface mining.

## Changelog
:cl:
add: Adds the advanced subsurface ore detector
/:cl:

### CODE REVIEW

**Comment by ACCount12** [comment]
>I could not test this on local, as I was not robust enough to get the ship running to move it to a mining asteroid.

Bruh.

**Comment by MadmanMartian** [comment]
Surprisingly no

**Comment by MadmanMartian** [comment]
Right, finally got to testing it and it currently doesn't work

**Comment by MadmanMartian** [comment]
Okay, may be the testing environment, as the asteroid doesn't seem to be loading properly for me.

The turfs have "has_resources" equal to 1, but they don't seem to actually have said resources

image

**Comment by MadmanMartian** [comment]
image

It works

**Pull request merged**
