### PR TITLE
Makes it so the mindswapper uses a list

### PR DESCRIPTION
**Pull request by Cocacola4124**
## About The Pull Request
Makes it so the mindswapper uses a list of mobs that can be swapped, rather than every type of carbon mob, which let players swap into mobs that just don't work well with actual players occupying them(Mob A.I taking over). 

## Why It's Good For The Game
Adds a few new types of mobs that the mindswapper works on, players can now swap into robots for example. Something I felt was missing. I wanted to also allow this for AI, and PAI but it didn't seem to work well.

## Changelog
:cl:
tweak: Changes the mindswapper to use a list for swappable mobs.
/:cl:

### CODE REVIEW

**Comment by MadmanMartian** [comment]
No more roachswapping?

**Comment by Cocacola4124** [comment]
> 
> 
> No more roachswapping?

Better to put stuff in separate pulls. There's a lot of small things that are annoying me that I have non-existent priority on fixing. Like that stupid cat meowing forever after dying.

**Comment by Alliostra** [comment]
As far as I'm aware, mob AI taking over if someone is swapped into a mob was fixed in the most recent carrion update. But really, even if it's bugged, being able to swap into everything is neat and actually unique, so why remove it?

**Comment by Cocacola4124** [comment]
> 
> 
> As far as I'm aware, mob AI taking over if someone is swapped into a mob was fixed in the most recent carrion update. But really, even if it's bugged, being able to swap into everything is neat and actually unique, so why remove it?

You can't swap into everything. Presumably whoever made mindswappers didn't know that superior animals and slimes were a subtype of carbon. Felt like a list is a little easier because you can switch into robots, meanwhile if you just allowed every mob to be switched into it'd break stuff if you didn't limit it to only non-synthetics(Because a lot of weird things are considered mobs)

**Comment by Cocacola4124** [comment]
A blacklist could work, but I doubt it'd be maintained as stuff got added.

**Comment by TheShown911** [comment]
But people should be able to swap into roaches and slimes, don't see a point in this PR. Robotic minds shouldn't be swapped with people in the first place as one is an AI and the other is a real brain.

**Comment by Cocacola4124** [comment]
Robots can use real brains. How does the mindswapper even work. There's still inconsistencies in that logic because you can transfer into kraftwerk roaches.

**Comment by Cocacola4124** [comment]
I'm nitpicking because I want to transfer into robots. I'll try something else.

**Pull request closed without merging**
