### PR TITLE
Roaches sprites update: Part 1

### PR DESCRIPTION
**Pull request by Bloodpriest**
## About The Pull Request
This is one part of the big roaches-resprite update.
Resprited idle and dead sprites, added moving animation: 
**Kampfer**
roach_idle
roach_move
**Panzer**
panzer_idle
panzer_move
**Seuche**
seuche_idle
seuche_move
**Jager**
jager_idle
jager_move
**Gestrahlte**
gestrahlte_idle
gestrahlte_move

## Why It's Good For The Game

Improvement mob sprites makes the visual part game more pleasant

## Changelog
:cl:
imageadd: resprited idle and dead sprites, added moving animation for Kampfer, Panzer, Seuche, Jager and Gestrahlte roaches.
/:cl:

### CODE REVIEW

**Review by TheShown911 — APPROVED** [review]
hqdefault

**Review by TorinoFermic — APPROVED** [review]

**Comment by TorinoFermic** [comment]
Approved

**Comment by Garen7** [comment]
image

**Comment by ArmolitskiyCarpoeb** [comment]
FINALLY, ROACHES

**Pull request merged**
