### PR TITLE
Brace rework

### PR DESCRIPTION
**Pull request by Humonitarian**
## About The Pull Request

Removes Kegdo brace, implements stationary bracing.

Recoil is massively reduced while shooting without movement, scaling with the size of your gun.
Recoil provides a slowdown, but guns no longer stun your movement.

Bipods now activate when stationary.

Includes balance patch to Takeshi as it made such an easily avaliable item way too powerful out-of-the-box.

## Why It's Good For The Game

More accuracy, more combat depth.

## Testing

I shot a variety of guns, ran around while holding them. Worked fine.

Major balance changes, live testing required.

## Changelog
:cl:
del: Removed bracing on tables
fix: Foregrip gives foregrip modifier
balance: Standing still improves accuracy when shooting, especially with larger guns
del: Removed recoil gained from movement
balance: Shooting guns no longer stuns your movement
balance: Recoil provides a scaling slowdown
balance: Takeshi stats nerfed, LMG recoil increased
/:cl:

### CODE REVIEW

**Comment by Faryaa** [comment]
As we have a separate HUD button for holding weapons with both hands - why won't we have a separate button for bracing? Which would brace your weapon on nearby suitable surface and prevent movement untill you unbrace (or move on Help or Harm intent specifically)

**Comment by Humonitarian** [comment]
> As we have a separate HUD button for holding weapons with both hands - why won't we have a separate button for bracing? Which would brace your weapon on nearby suitable surface and prevent movement untill you unbrace (or move on Help or Harm intent specifically)

Bracing is gonna be based on standing still, rather than aiming

**Comment by Humonitarian** [comment]
> With this PR, it is possible for the recoil stacked from going full dakka to hamper the user's movement so much that they will be on equal speed terms with T*keshi players.


There was a bug that prevented FA weapons from run and gunning. I fixed that, but as it involves the removal of a key slowdown mechanic, I replaced that with the slowdown you see.

> A solution to this would be to make a simple size/caliber check for guns in **both** hands; if the caliber is low enough, like .35 or .25, the recoil slowdown would be either much less, or completely ignored.

It does scale with how big the weapon is. An SMG provides much less slowdown than a battle rifle.

> Same for melee, if this applies to every item and not only guns. This would also render cheesing Tak*shi by shooting and then switching to offhand to ignore gun-slowdown impossible.

Anything that isn't a gun provides the same slowdown as being emptyhanded, which is a fraction of what most guns have.
Emptyhanded -> least slowdown
HMG -> most slowdown



Overall your criticism is valuable, though testing on the testserver would give us a much more clear picture, as I could only test on local so far.

**Comment by ValoTheValo** [comment]
honestly just kill bracing, no further changes needed. it was a salt mechanic that was terribly implemented

**Review by hyperioo — APPROVED** [review]

**Pull request merged**
