### PR TITLE
The Scrapyard

### PR DESCRIPTION
**Pull request by zombiemimic**
## About The Pull Request
Adds in the Scrapyard, a barren rock filled with derelict ships and angry aliens! Can you fight your way off, or will you become stranded and fated for xeno food?
battleroyale1

Look for the hobo or prison guard to join the fun!

## Why It's Good For The Game
gives more life to the game

## Changelog
:cl:
add: Added Scrapyard map
add: Added shuttle that goes from scrapyard to the Eris
add: Added Nanotrasen softcap and uniform, sprites by Armolitskiy
add: Added more mapping things for the Scrapyard
/:cl:

### CODE REVIEW

**Review by Firefox13 — CHANGES_REQUESTED** [review]
Map isn't in TGM format, use mapmerge2 tool.
Why there's teleport parent object out in nowhere?
изображение
The wiring does not works like that. You need to generate the directions and put them like they would look in-game, look at Eris map for reference.
изображение
Some of the sprites are literally missing: blast doors on whiteship(did you just copied it over, as well as delta station?) and other ships, cigar case in captain's quarters.
No APCs at all.
No piping either but there are meters.
No buttons to controls the blast doors.
> nanotrasen security

#5656, It's not Nanotrasen and it was a bad joke with this acronym anyway. You didn't mention its author, too.
And don't add Nanotrasen here please. It's long dead.

No trash or oddities on scrapyard at all.

You also didn't mention that you've added the pod that goes to centcomm.

Why did you made the away roles into antagonists?

Did you even test it?

**Comment by zombiemimic** [comment]
1. what is TGM format/mapmerge2?
2. I don't see the teleport parent
3. I'm removing wiring altogether, I clearly wasn't thorough enough
4. old picture, boltguns/cigarcase/blood trails all work in game
5. will remove apc's and piping stuff
6. will add buttons
7. added credit, will change the security corpse gear
8. will remove trash spawners and oddities
9. the pod only goes through admin map because of transit
10. their outfits are only antagonist for the outfit tags
11. yes, I did test it

**Comment by Firefox13** [comment]
>     1. what is TGM format/mapmerge2?

TGM format is made to avoid conflicts between BYOND versions, it's in tools folder in build with instructions on how to use it.

>     2. I don't see the teleport parent

Use CTRL+F to find it.

>     5. will remove apc's and piping stuff
>
>     8. will remove trash spawners and oddities
> 

I meant to fucking add it and not remove whatever does not exist there already

**Comment by drexample** [comment]
I am unsure they should have a way to fly to Eris.

**Comment by zombiemimic** [comment]
this is a handful of derelict spaceships, so I don't think that we should put in functional power/atmos

**Comment by RagMaggot** [comment]
HOLY SHIT TG RUINS IN ERIS!
THIS IS A DREAM FOR ME

**Comment by zombiemimic** [comment]
will repost due to github dickery

**Pull request closed without merging**
