### PR TITLE
ADD ROACH JETPACK, ROACH LUNCHBOX, AND ROACH VODKA

### PR DESCRIPTION
**Pull request by Kmc2000**
https://gyazo.com/5bbac068a3667a50b1eab3ab53d588b6

Add 5 roach meat to a tank to turn it into a roach jetpack (fuel sold seperately)

### CODE REVIEW

**Comment by RandomColonist** [comment]
Vodka and lunchbox seems fine, but jetpack from roach meat seems like pure bullshit to me.

**Comment by RandomColonist** [comment]
- What you did in tanks file is pure shitcode. You even have fucking var which counts pieces of meat. We have crafting system for reason, you can't just bypass it and take a dump in tanks.dm, leaving pile of shitcode instead of adding recipe for it in crafting system.
- Lunchbox is in place and seems like good joke.
- Vodka is just resprite. Can you implement proper reagent with recipe, different effects and proabably it should do something to roaches, maybe?

**Comment by mattroks101** [comment]
Is the meme dead? Can I close this now?

**Comment by ACCount12** [comment]
Just the roach lunchbox would be fine, but the rest of it is just too meme, not to mention poor code quality.

**Pull request closed without merging**
