### PR TITLE
Armor rework revert

### PR DESCRIPTION
**Pull request by MLGTASTICa**
## About The Pull Request
Reverts the armor rework PR and all subsequent PR's that are meant to tweak it
## Why It's Good For The Game
The rework only made armor less effective in general,bringing back insta-kill head-bursts , making people die faster , and in general , shaking the balance while fixing none of the main issues of armor.

## Changelog
:cl:
balance: Reverted the armor rework and subsequent PR's.
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
salt PR

**Comment by assortedbeads** [comment]
Salt pr but not even subtle, amazing

**Comment by maikilangiolo** [comment]
Like he was asked multiple times in nearly every discord channel, SPCR is welcome to substantiate his claims and provide proof, after he himself admitted he didn't know how the new damage and armor worked. 
The code is open source and thus it wouldn't be particularly hard to look up the damage formula and gun stats.

**Comment by Firefox13** [comment]
You've been told numerous times how this rework works yet you refuse to listen.

**Pull request closed without merging**
