### PR TITLE
Removes guild

### PR DESCRIPTION
**Pull request by Wouju**
## About The Pull Request

Replaces most of guild with a giant hole to space
image
image
image

## Why It's Good For The Game

~~merge this for april fools next year no balls~~

No one likes guild. A hole to space is more useful.

it's a hole

## Changelog
:cl:
balance: Rebalanced the entire gameplay loop by replacing guild with a giant hole to space, which is 10000% more useful
/:cl:

### CODE REVIEW

**Comment by Alanii** [comment]
Sorry, we are too busy adding felinds to think about this.

**Comment by ValoTheValo** [comment]
speedmerge this

**Comment by maikilangiolo** [comment]
I don't make PRs i am the commenter of PRs and you broke the rules buddy, https://wiki.cev-eris.com/Content_GuidelinesEn you should try reading these. This PR is useless and you should be ashamed you ever made it, get out of my sight.


Either way, I cast my vote in favor.

**Comment by Tokanova** [comment]
> I don't make PRs i am the commenter of PRs and you broke the rules buddy, https://wiki.cev-eris.com/Content_GuidelinesEn you should try reading these. This PR is useless and you should be ashamed you ever made it, get out of my sight.
> 
> Either way, I cast my vote in favor.

cringe

**Comment by MemedHams** [comment]
This man is the hero we don't deserve

**Comment by Jackofashepard** [comment]
True TG style PR, very unique, i am impressed.

**Comment by Alliostra** [comment]
I don't make PRs i am the commenter of PRs and you broke the rules buddy, https://wiki.cev-eris.com/Content_GuidelinesEn you should try reading these. This PR is useless and you should be ashamed you ever made it, get out of my sight.

Either way, I cast my vote in favor.

**Comment by Medcar** [comment]
I don't make PRs i am the commenter of PRs and you broke the rules buddy, https://wiki.cev-eris.com/Content_GuidelinesEn you should try reading these. This PR is useless and you should be ashamed you ever made it, get out of my sight.

Either way, I cast my vote in favor.

**Comment by Firefox13** [comment]
Not even funny already

**Comment by AgentMA1** [comment]
Literally 1984

**Comment by Wouju** [comment]
This is just like that book Fahrenheit 420 and nineteen eighty four

**Comment by MemedHams** [comment]
This reminds me of the crazy goverment from a Lemon Clockwork Nineteen Sixty Nine. Very sad that a genius was put down before his time

**Pull request closed without merging**
