### PR TITLE
goodbye, obj/item/weapon.

### PR DESCRIPTION
**Pull request by vode-code**
## About The Pull Request
This PR finally gets obj/item/weapon out of our codebase, and also edits a gitignore that made it harder to mess with code/game/objects/items/weapons/tools, code/game/objects/items/weapons/tools/mods, code/modules/detectivework/tools, and code/modules/research/xenoarchaeology/tools to only apply to the proper path.

## Why It's Good For The Game
obj/item/weapon should not have been left in our code for so long, also the gitignore gets in the way.

## Changelog
:cl: Chickenish
del: code: obj/item/weapon is gone.
config: gitignore now has ./tools/ instead of tools/
/:cl:

### CODE REVIEW

**Comment by Wouju** [comment]
5 buck bet this will somehow rip apart reality and doom us for all eternity

**Comment by TheShown911** [comment]
cover3

**Comment by Alliostra** [comment]
lifeconflict
I don't feel so good, Mr. obj/item

**Comment by Kurgis** [comment]
> This PR finally gets obj/item/weapon out of our codebase, and also comments out a gitignore that made it harder to mess with code/game/objects/items/weapons/tools, code/game/objects/items/weapons/tools/mods, code/modules/detectivework/tools, and code/modules/research/xenoarchaeology/tools .
You could just rename those folders to "tool" instead of "tool", or rename the "tools" folder to "tool", and change the .gitignore to "tool" as well. Not sure if the tools folder actually needs to be using .gitignore or not, because it might cause issues if that's changed, just not sure.

**Comment by vode-code** [comment]
> 
> You could just rename those folders to "tool" instead of "tools", or rename the "tools" folder to "tool", and change the .gitignore to "tool" as well. Not sure if the tools folder actually needs to be using .gitignore or not, because it might cause issues if that's changed, just not sure.

the problem was that it wasn't anchored to the root file and so applied to every folder called tools, I fixed that I think.

**Review by mattroks101 — APPROVED** [review]
Fingers crossed

**Comment by TheShown911** [comment]
Double crossed

**Pull request merged**
