### PR TITLE
resprites the technomancer armor

### PR DESCRIPTION
**Pull request by 1glitchycent**
## About The Pull Request
resprites Technomancer armor

## Why It's Good For The Game

Old sprite looked very bland, and didn't fit TM aesthetic.
## Changelog
:cl:

imageadd: new icons for technomancer armor

/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Why do you feel that technomancers need this type of melee protection? 
The energy protection made sense because of what they do but everything else doesn't make too much sense unless I'm missing something.
The bomb protection seems a bit random as well.

**Comment by 1glitchycent** [comment]
> Why do you feel that technomancers need this type of melee protection?
> The energy protection made sense because of what they do but everything else doesn't make too much sense unless I'm missing something.
> The bomb protection seems a bit random as well.

Technomancers tend to fight roaches more than anything, also debris and falling junk would probably be a hazard in their line of work. Bomb protection because explosions may also be a hazard, and discord asked for it.

**Review by Hopekz — CHANGES_REQUESTED** [review]
> Technomancers tend to fight roaches more than anything, also debris and falling junk would probably be a hazard in their line of work. Bomb protection because explosions may also be a hazard, and discord asked for it.

Okay.

Please atomize this part into a separate PR. 
You may keep this PR as a resprite but the two changes should be separated.

**Comment by 1glitchycent** [comment]
@Hopekz okay done.

**Comment by ArmolitskiyCarpoeb** [comment]
respriting my sprite? fuck no

**Comment by Firefox13** [comment]
images please

**Comment by 1glitchycent** [comment]
tmjump
here's the sprite(in like 10 minutes anyways)

**Comment by 1glitchycent** [comment]
new helmet btw 
image

**Comment by Garen7** [comment]
@Firefox13 you can see the images in the icon diff bot
image

**Review by genessee596 — CHANGES_REQUESTED** [review]
i actually liked old TM armor, maybe make this an alternative set instead of a full replacement?

**Review by Hopekz — APPROVED** [review]
> i actually liked old TM armor, maybe make this an alternative set instead of a full replacement?

He's leaving the old sprites under armor_engineering_old. Making it an alternative is outside of the scope of this PR. 
The quality of this sprite is good and I really like the progress that was made here since it doesn't really seem blurry anymore from what I can tell since you addressed Baron's issue.
I don't think this is a mistake so let's see how people react.

**Pull request merged**
