### PR TITLE
High-velocity bullets don't have any damage boost

### PR DESCRIPTION
**Pull request by Kegdo**
## About The Pull Request

removes the 5 dmg point boost from the HV ammo, making it less bonkers, armor penetration and everything else untouched.

## Why It's Good For The Game

less lethal combat? The council of coderbus wanted this thing to be added.

## Changelog
:cl:
tweak: HV ammo doesn't have the 5 dmg point boost now, everything else untouched.
/:cl:

### CODE REVIEW

**Comment by Sparrowbird611** [comment]
I do want to point out that more AP realistically means more damage, so less lethal combat isn't really true except in cases where people are totally unarmored (in which case they'll probably die anyway). I'm not saying this is bad, but I do want to ask if this was made because HV is overperforming or just because someone got in their head that damage = more lethality while AP somehow doesn't. As far as I am aware HV got a decent price hike in one of those uplink rebalances, and I haven't seen very often since then.

**Comment by ValoTheValo** [comment]
Salt PR moment

**Review by hyperioo — COMMENTED** [review]
No problem codewise.

**Comment by Firefox13** [comment]
HV ammo is pretty much "pay more for more bonk" and is for antags; they should have more damage

**Pull request closed without merging**
