### PR TITLE
Boejevic magazine craftable

### PR DESCRIPTION
**Pull request by maikilangiolo**
## About The Pull Request
Makes the pug drum craftable. costs like the .30 drum

## Why It's Good For The Game
pain in the ass to use the pug, you can craft high capacity mags for other guns anyway.

## Changelog
:cl:
add: .50 drum craftable in the crafting station
/:cl:

### CODE REVIEW

**Comment by zombiemimic** [comment]
You're giving the empty version of the drum instead of a loaded one, like others in the kit

**Comment by SirRichardFrancis** [comment]
Other magazines are empty too.

**Review by SirRichardFrancis — APPROVED** [review]
Good PR, btw.

**Comment by zombiemimic** [comment]
PR's good, just denote that the magazine is empty in the menu like the others

**Review by TheShown911 — APPROVED** [review]

**Pull request merged**
