### PR TITLE
Good riddance, telescience.

### PR DESCRIPTION
**Pull request by greggbot**
## About The Pull Request

Obviously, this PR removes telescience. Gets rid of the machines, the boards, and the research designs for the pad and console. Every other bluespace-related object is untouched.

## Why It's Good For The Game

The telescience pad, specifically, has a number of problems, and the other teleportation methods will still allow for smart use of teleportation. Snares and the like can still be used to extract people, teleporter hubs and beacons can still be set up.
So, now I'm gonna lay out a list of the problems the pad causes. If you disagree with any of them, please quote it and reply.

- The ability to take high-security items with no immediate risk. Even if it causes future conflict, these items are supposed to be difficult to steal, but the presence of telescience trivializes any theft, requiring only memorized coordinates, a little bit of math and a couple of button presses. This even includes faction relics, unique items that can immediately be destroyed for the entire round by deconstructing them for research points.
- The ability to bypass the research shuttle. Barely anybody uses the research shuttle, because telescience is so much more convenient. This means Moebius can essentially jump in and out of dangerous space ruins with halfway decent coordination, bypassing much of the risk, and even scout out locations of lockers and the like for teleportation.
- The ability to grab a "shopping list" of research items to deconstruct. With some planning and a bit of note-taking, I'm sure you could make a list of items to grab with telesci that would give you an absolutely ridiculous research boost.  

## Changelog
:cl:
del: Telescience is gone. Good riddance.
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
salt pr

**Comment by MLGTASTICa** [comment]
> > salt pr
> 
> Please tell me what telescience adds that is actually good for the game, and doesn't bypass intended progression.
> Seriously, give me a well-reasoned argument and I might actually see your side of it. Saying "salt PR" doesn't add anything.

Ability to rescue stranded people , Ability for moebius to teleport people in crit back onboard , Ability for paramedics to teleport to remote location , ability to kidnap the captain by tracking him , ability to teleport a fuhrer ontop of the LT as a declaration of war.

**Comment by MrFoxik** [comment]
> > > salt pr
> > 
> > 
> > Please tell me what telescience adds that is actually good for the game, and doesn't bypass intended progression.
> > Seriously, give me a well-reasoned argument and I might actually see your side of it. Saying "salt PR" doesn't add anything.
> 
> Ability to rescue stranded people , Ability for moebius to teleport people in crit back onboard , Ability for paramedics to teleport to remote location , ability to kidnap the captain by tracking him , ability to teleport a fuhrer ontop of the LT as a declaration of war.

Sounds like it would be better not to remove whole telesci, but to remove ability to put in coords, and choose only those which are medbay ones, sync systems and all of that

**Comment by Honestly101** [comment]
this is the first step to becoming TG, a nuetered playerbase with all the fun broken mechanics removed from it.

**Comment by Rumplenutskin** [comment]
Bluespace snares are very cool. How would removing this affect the tech tree?

**Comment by Evankhell561** [comment]
this is laziness.

**Comment by Honestly101** [comment]
instead of outright removing telesci, it would be better to have some form of a announcement of when a teleportation takes place, for example "Bluespace anomanly detected at {location}" this should give off the fact that moebius is up to no good, but if that is not enough, then have the secured displayed have teleportation protections and so you would need two people to operate the telesci and be about to steal with it, one gets teleported nearby the location and if he gets caught stealing it's basically game over for moebius, this adds risk to stealing if someone happens to be nearby at the time of the theift, as there will be the station announcement aswell.

**Comment by Evankhell561** [comment]
> > this is laziness
> 
> Please explain exactly what you mean by this, and why you think keeping telescience in is better than removing it.
> I understand we could use a few more bluespace tools. I intend to port quantum pads later, when I'm not in the middle of a fever. But telesci isn't a tool, it's a swiss army knife. It can do everything better. It's just too good.

Make it take two people to operate this machine. I could give you more indications of what this would be like but I would like you to make an effort to come up with a better system instead of simply removing this beautiful feature.

**Comment by Honestly101** [comment]
> > > this is laziness
> > 
> > 
> > Please explain exactly what you mean by this, and why you think keeping telescience in is better than removing it.
> > I understand we could use a few more bluespace tools. I intend to port quantum pads later, when I'm not in the middle of a fever. But telesci isn't a tool, it's a swiss army knife. It can do everything better. It's just too good.
> 
> Make it take two people to operate this machine. I could give you more indications of what this would be like but I would like you to make an effort to come up with a better system instead of simply removing this beautiful feature.

Nah man, only one person needs to operate it, but to be able to steal thing with it, you would need the second person to actually be the one teleported to the targeted location, it would make no sense for there to be two people needed for it to simply function correctly.

**Comment by Honestly101** [comment]
i think it's time for some democracy, sure it will work, purge telesci yes or no?

**Comment by Firefox13** [comment]
изображение

**Pull request closed without merging**
