### PR TITLE
Makes pets overpowered ( Pets now heal sanity)

### PR DESCRIPTION
**Pull request by MLGTASTICa**
## About The Pull Request
Pets heal sanity , Ian provides -2 , Normal cats , parrots and corgis -1, and Runtime -2

## Why It's Good For The Game
Makes pets more usefull.
## Changelog
:cl:
add: Pets now heal sanity .
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
> I can't fucking believe you'd do Iriska dirty like this, you bastard

Fuck iriska she bites .

**Comment by Humonitarian** [comment]
New club meta

**Comment by ValoTheValo** [comment]
buff iriska

**Comment by Firefox13** [comment]
These values are really big for ambience heal

**Comment by MLGTASTICa** [comment]
> These values are really big for ambience heal

plants and statues have -2 im preety sure

**Comment by Cyaneer** [comment]
Now a 200IQ move would be to have the sanity buff scale according to the pet's hunger, also having a sanity _de_gen if you're near dead pets. Pets will now no longer be ignored and left to starve, and will finally be a treasured posession.

**Review by TheShown911 — COMMENTED** [review]
horrible deeds is only 2 sanity damage, so 4 may be too much

**Comment by MLGTASTICa** [comment]
> horrible deeds is only 2 sanity damage, so 4 may be too much

made bones and ian only give -2 then.

**Review by TheShown911 — APPROVED** [review]

**Pull request merged**
