### PR TITLE
Add more space heaters

### PR DESCRIPTION
**Pull request by SirRichardFrancis**
## About The Pull Request

Added ~20 (I lost count) space heaters to atmospherics, substations and throughout the maintenance tunnels, per jannie-with-long-nickname reqiest.

## Why It's Good For The Game

Benzin roach fires is a lot of trouble, and high temperature kills fast, meanwhile ship only have three (3) space heaters and coolant is nerfed to hell.

## Changelog
:cl:
add: more space heaters to maintenance, substations and atmos
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
benzin roaches were a mistake

**Comment by maikilangiolo** [comment]
Benzin roaches are good. Benzin leaving fuel puddles isn't. Just stop them from cumming welder fuel all over maint and they're fine.

**Comment by Firefox13** [comment]
> and coolant is nerfed to hell.

my friend it literally set the room temperature to zero if you spilled enough of it before

**Comment by maikilangiolo** [comment]
Zero Kelvin, that is. So -287°C.
Accidentally shooting a coolant tank (including wall overpen) essentially ended the round unless it was a restricted zone of maint. It was impossibile to heat back up

**Comment by SirRichardFrancis** [comment]
Not saying that coolant was good and balanced before, only that it's not a viable option anymore, that went from "so powerful it causes more problems than it solves" to "it might as well not exist at all".
If only our contribution guidelines forbid nerfing stuff by bazillion percent in a single PR... :thonkercat:

**Comment by maikilangiolo** [comment]
Considering Firefox himself made the PR and he is (and was at the time) project lead...
He just ported over current bay coolant tanks too.

**Review by Firefox13 — APPROVED** [review]
~~It's -273, not -287~~
On baystation fire extinguishers can (effectively) lower room's temperature, which we should port but it uses some math and I was lazy back then
Anyway, good change, I guess

**Pull request merged**
