### PR TITLE
Nerf's paramedic's roundstart ammo supply.

### PR DESCRIPTION
**Pull request by Sparrowbird611**
## About The Pull Request

Reduce's the Paramedic's ammo significantly

## Why It's Good For The Game

The paramedic had no need for four highcap magazines roundstart. If he feels he needs more ammunition, he can obtain them easily through the FS vendor or via an ammo disk. He retains his gun and other equipment.

## Changelog
:cl:
tweak: Reduced the amount and type of magazines the paramedic spawns with for his handgun.
/:cl:

### CODE REVIEW

**Comment by zombiemimic** [comment]
you just up and removed the gun entirely. bruh

**Comment by ValoTheValo** [comment]
IH and Vagabond Stealthbuff. I dont see how this change was needed anyway. The Anne and Svallin arent all that powerfull

**Comment by ArmolitskiyCarpoeb** [comment]
STOP FUCKING NERFING I HATE YOU ALL

**Comment by TGCMbetcher** [comment]
I'll be back, going to remove IHs armory theres no need for so.much ammo round start. If they feel like they need more ammunition they can obtain them easily from the FS vendor or via an ammo disc. IH never had a reason for lethals round start as they cant use them until antags show themselves.

**Comment by Sparrowbird611** [comment]
> you just up and removed the gun entirely. bruh

I actually made peace with him having a gun so nah.

**Comment by Sparrowbird611** [comment]
Everyone else can be retarded and cope all you want. Let's give doctors martins (to defend themselves against patients) technos Atredies (they have to go into maint more than NT for their jobs so they need defense against roaches) and the guild AK-47's (to stop people breaking in roundstart). Hell, let's give vagabonds RPGs roundstart so they can fight against roaches without worry. Learn the incredibly difficult skills of walking to the FS vendor and spending literally 200 credits on a gun or ammo.

Also you're technically right betcher, there's a lethal ammo disk, a non-lethal ammo disk, the IH vendor, the crates full of spare ammo, and enough metal to print anything you want. Crazy amount of ammo in that place.

**Comment by MLGTASTICa** [comment]
descent to madness.

**Comment by SirRichardFrancis** [comment]
Cringe PR from cringe contributor.
Imagine deleting a gun entirely instead is removing one line of code, that's some big brain moves here.

**Comment by Sparrowbird611** [comment]
> Cringe PR from cringe contributor. Imagine deleting a gun entirely instead is removing one line of code, that's some big brain moves here.

Seemed unnecessary to keep a martin clone if it's going to be removed from most areas. I could have left it in the NT supply crate but that seemed a waste.

Just doing my part to reduce the gun bloat complaints ;)

**Comment by zombiemimic** [comment]
much better

**Comment by Humonitarian** [comment]
Solid

**Comment by TheShown911** [comment]
Still don't see what this PR brings to the game.

**Comment by Humonitarian** [comment]
> Still don't see what this PR brings to the game.

Balance. I played paramedic, the amount of starting mags is waaay too excessive.

**Review by hyperioo — APPROVED** [review]
No problem codewise, it's just a change of `/obj/item/ammo_magazine/hpistol/rubber = 4` into `/obj/item/ammo_magazine/pistol/rubber = 1`.

Balance decision.

**Pull request merged**
