### PR TITLE
Yet another chameleon projector nerf

### PR DESCRIPTION
**Pull request by MadmanMartian**
## About The Pull Request

Removes the default saved item from the chameleon projector, as it broke the new pixel standard

## Why It's Good For The Game

haha, 2 pixel hitbox that can move at 3 tiles per second!

## Changelog
:cl:
balance: Something moving over a chameleon projection now disables the projection
balance: Removes the cigarette butt from being the default projection of a cham projector
/:cl:

### CODE REVIEW

**Review by TorinoFermic — APPROVED** [review]

**Comment by TorinoFermic** [comment]
Don't forget about flashbangs, I remember tg flash bang grenades also affect it.

**Comment by mattroks101** [comment]
Would it be possible to have something else be the default here? Those defaults let you tell at a glance what the code is supposed to do, and it's pretty useful for people who might be new looking at it. If that's not feasible that's fine though.

**Comment by MadmanMartian** [comment]
I could leave a doc-comment on them sure

**Review by mattroks101 — APPROVED** [review]

**Comment by mattroks101** [comment]
This is good enough for now.

**Pull request merged**
