### PR TITLE
Wormhole fix

### LINKED ISSUE #3238: Shining flashlights at wormholes is bad news
If you shine a flashlight at a wormhole, it'll aggressively spark for a few seconds and presumably teleport the light to the other side. On top of that, it apparently messes with your ability to move - I was unable to move for the rest of the round until someone cryoed me.

### PR DESCRIPTION
**Pull request by soslow4u**
Fixes #3238. Feeling that leaving light effect on wormhole is quite shit, but thereare no more infinite loops about teleporting now.

### CODE REVIEW

**Comment by ACCount12** [comment]
There might be a similar bug on stationary teleporters, etc.

**Comment by soslow4u** [comment]
Was sure it all uses /obj/effect/portal/proc/teleport()

**Comment by ACCount12** [comment]
Stationary teleporter is its own structure AFAIK.

**Comment by soslow4u** [comment]
Just checked it, everything is fine.
scrnshot1

**Pull request merged**
