### PR TITLE
Makes the AI self destruct roundstart

### PR DESCRIPTION
**Pull request by TheShown911**
## About The Pull Request

Makes the AI self destruct roundstart. Intended to be merged at a specific date.

## Why It's Good For The Game

Makes the game more compliant with the lore.

## Changelog
:cl:
add: AI self destructs roundstart
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
Truely Based PR

**Comment by Alliostra** [comment]
speedmerge

**Comment by thedarkcrusader** [comment]
What's with the pickels

**Comment by DerpiestBruh** [comment]
....so fvcking..... zased..

**Comment by Humonitarian** [comment]
> > speedmerge
> 
> World isn't ready yet.

Soon™️

**Comment by xlink97** [comment]
truly based and organicpilled

**Comment by Kegdo** [comment]
It also spawns a pickle. Based as fuck. Now do this for every head role.

**Review by hyperioo — APPROVED** [review]
Just need to have an admin ready to save the poor soul that will innocently choose roundstart AI

**Pull request merged**
