### PR TITLE
the artist now has the clumsy mutation

### PR DESCRIPTION
**Pull request by Evankhell561**
## About The Pull Request
This is an idea of the community and I wanted the staff to have the possibility to evaluate it.

## Why It's Good For The Game
people want it?

## Changelog
:cl:
tweak: the artist now has the clumsy mutation
/:cl:

### CODE REVIEW

**Comment by Fatherperhaps** [comment]
keep the mutation but if possible just make it so the actor can only use crafted art guns

**Comment by ArmolitskiyCarpoeb** [comment]
nooooooo pls nooo

**Review by genessee596 — CHANGES_REQUESTED** [review]
I'm okay with this as long as you let artists use their art guns normally.

**Comment by MadmanMartian** [comment]
where's the image?

**Comment by genessee596** [comment]
image

**Pull request closed without merging**
