### PR TITLE
Fix an unacepptable, godawful, terrible fault in the code that is truly the worst defect in the Eris codebase

### PR DESCRIPTION
**Pull request by Firefox13**
## About The Pull Request

reinfoced shoes

## Why It's Good For The Game

изображение

## Changelog
:cl:
fix: Moebius reinfoced shoes were replaced with Moebius reinforced shoes.
/:cl:

### CODE REVIEW

**Review by TheShown911 — APPROVED** [review]
Endless calamity

**Comment by Hopekz** [comment]
As someone that goes through changelogs sometimes when searching for something, I think the changelog entry is unnecessary and creates spam for such a small correction.
Like fixing a simple runtime etc.

**Review by Hopekz — CHANGES_REQUESTED** [review]
As someone that goes through changelogs sometimes when searching for something, I think the changelog entry is unnecessary and creates spam for such a small correction.
Like fixing a simple runtime etc.

**Comment by Firefox13** [comment]
> 
> 
> As someone that goes through changelogs sometimes when searching for something, I think the changelog entry is unnecessary and creates spam for such a small correction.
> Like fixing a simple runtime etc.

Sure.

**Comment by TheShown911** [comment]
> As someone that goes through changelogs sometimes when searching for something, I think the changelog entry is unnecessary and creates spam for such a small correction.
> Like fixing a simple runtime etc.

Our head dev is very insistent on everything being put on the changelog

**Comment by Hopekz** [comment]
> Our head dev is very insistent on everything being put on the changelog

Alright. 
No-one told me this in the 20+ PR's I've made here without a changelog because I thought it was spam but if the spam is preferable I can start adding those changelogs.

**Comment by genessee596** [comment]
I'm shocked and apalled that this horrible mistake made it into our codebase. I'm dialing up the CEO of coding right now and letting him know of this apocalyptic blunder that we've created.

**Review by TorinoFermic — APPROVED** [review]

**Review by TorinoFermic — APPROVED** [review]
I am double approving as how bad this is !

**Review by mattroks101 — APPROVED** [review]

**Pull request merged**
