### PR TITLE
IH bulletproof helmet resprite, NVG BP helmet side states offset fix, NVG BP helmet making masks invisible fix 2: Electric i'm going insane someone send help

### PR DESCRIPTION
**Pull request by CeUvi**
## About The Pull Request
read the title
ih bph
just merg it already for fuck sake
+
nvg bp helmet side states offset fix
+
nvg bp helmet making masks invisible fix
## Why It's Good For The Game
it's fucking bad, this trash old sprite
bugs are bad too.
## Changelog
:cl: CeUvi
fix: nvg bp helmet side states offset
fix: nvg bp helmet making masks invisible
imageadd: ih bp helmte
/:cl:

### CODE REVIEW

**Comment by CeUvi** [comment]
fixing NVG helmet too
can't make a separate PR because icon conflicts

**Comment by ValoTheValo** [comment]
I dont think this looks any better...

**Comment by CeUvi** [comment]
think better

**Comment by Kegdo** [comment]
ngl these both are bad ex dee lmao rofl kek kringe.

**Comment by SirRichardFrancis** [comment]
What, AGAIN? :ziklonB:

**Comment by CeUvi** [comment]
the what who added stuff to head

**Pull request closed without merging**
