### PR TITLE
new welder sprite  #orders are orders 

### PR DESCRIPTION
**Pull request by fernandos13**
## About The Pull Request
new welder sprite #orders are orders 
https://gyazo.com/bad29a17768d30116c4d104106127b31
https://gyazo.com/7010ae051fb86045f64d0635d9c55f65
https://gyazo.com/be1a4a49b0bc22bb34899fdfb7538411 (didn't changed but its fitting i'd say)

## Why It's Good For The Game
new welder sprite  #orders are orders 

## Changelog
:cl:
tweak: new welder sprite (just a recolor of the adv one)
/:cl:

### CODE REVIEW

**Comment by SpadesSlick** [comment]
I think Grey meant another one? He also mentioned inhands.

**Comment by fernandos13** [comment]
oh like a new type

**Comment by GrayRachnid** [comment]
I did not want a new welder. I wanted inhands for the advanced welder and the onestar welder while adding an on variant for them.

**Comment by fernandos13** [comment]
humm i see. well i'll leave it for more... artistic people then. i'm not at all a good spriter. and i still a REAAALLY long way from being able to properly draw a tool. sorry for the annoying pr by the way. i understood the order in the wrong meaning

**Pull request closed without merging**
