### PR TITLE
Players' high-priority role shows up in lobby tab

### PR DESCRIPTION
**Pull request by EvenInDeathIStillServe**
image

### CODE REVIEW

**Comment by EvenInDeathIStillServe** [comment]
image

After discussion, we figured it would be better if it showed character names instead of Ckeys.

**Comment by mattroks101** [comment]
Alright I guess that's fair.

**Comment by EvenInDeathIStillServe** [comment]
image
This is for admins using the Who verb

**Comment by EvenInDeathIStillServe** [comment]
I removed the Lobby tab altogether. The Status tab now takes care of the duty of the Lobby tab when you're in the lobby.
I made it so that you can see the storyteller in the status tab when you're ingame.

**Pull request merged**
