### PR TITLE
Fix ban panel, fix bans check, fix admin flags

### PR DESCRIPTION
**Pull request by btwotwo**
1. Fixed irremovable bans
2. Fixed "Unban" button inside the ban panel
3. Fixed admin verbs adding
4. Fixed not working permajobbans
5. Fixed ban panel ckey search
6. Removed admins now have rank "player" instead of "Removed"

### CODE REVIEW

**Comment by NanakoAC** [comment]
Could you possibly add some explanation and notes on what this fixes? There is literally no description for this PR

Are there any github issues that it fixes? Quite probably, check and link them up if so

**Comment by btwotwo** [comment]
@NanakoAC done

**Comment by NanakoAC** [comment]
Does this PR fix any of these issues?
#951
#950
#712

**Comment by SpadesSlick** [comment]
@NanakoAC nope. They are simply working now.

**Pull request merged**
