### PR TITLE
Revert "Leather satchels are stylish"

### PR DESCRIPTION
**Pull request by Iglpigl**
Reverts discordia-space/CEV-Eris#7820

### CODE REVIEW

**Review by SirRichardFrancis — APPROVED** [review]
Based.

**Comment by pexel5** [comment]
Make another leather bag and transfer this PR to it, as well as shove it into style vendomat, the most optimal solution.

**Comment by Iglpigl** [comment]
The guy that made #7820 can do that, this is good enough for now.

**Comment by SirRichardFrancis** [comment]
> Make another leather bag and transfer this PR to it, as well as shove it into style vendomat, the most optimal solution.

Cringiest solution thus far.

**Comment by pexel5** [comment]
> > Make another leather bag and transfer this PR to it, as well as shove it into style vendomat, the most optimal solution.
> 
> Cringiest solution thus far.

But which is a solution both for the coder and for players unhappy with this

**Comment by SirRichardFrancis** [comment]
> But which is a solution both for the coder and for players unhappy with this

And which leaves them unhappy, fixing nothing.

**Comment by Iglpigl** [comment]
It looks like #7820 didn't even make em stylish only reduced their capacity, humon didn't test his PRs yet again, even more reason to merge this.

**Comment by Firefox13** [comment]
изображение

**Comment by Iglpigl** [comment]
1984

**Comment by pexel5** [comment]
1984

**Comment by SirRichardFrancis** [comment]
1984

**Pull request closed without merging**
