### PR TITLE
Last Tosshin Reference Eliminated

### PR DESCRIPTION
**Pull request by Mycah142**
## About The Pull Request
Found an antiquated reference to the Tosshin in guns.dm while stumbling along. Moved it to the proper caliber in the list, and renamed it to Kadmin, matching the ingame name.

## Why It's Good For The Game
Inconsistencies bad.

## Testing
I added it to a disk and it was named Kadmin.
TEMKEpzYkP

## Changelog
:cl:
fix: fixed last Tosshin reference to Kadmin
/:cl:

### CODE REVIEW

**Comment by Firefox13** [comment]
> I don't even know where guns.dm is used ingame. This is just a backend thing.

It's not, the file contains recipes used in disks. You can test this.

**Comment by Mycah142** [comment]
> > I don't even know where guns.dm is used ingame. This is just a backend thing.
> 
> It's not, the file contains recipes used in disks. You can test this.

That's a different guns.dm, this seemed like just a repository of ballistic guns, as recipes for it were referenced proper by the right name in two or three other locations, one of them had the material requirements.

Also still doesn't tell me where it's used to even test it, a I was unable to find any reference to Tosshin in-game before or after doing this.

**Comment by Firefox13** [comment]
It's a list of recipes used for autolathe disks.
The recipe isn't used anywhere.

**Comment by Mycah142** [comment]
And I test a recipe that doesn't exist HOW?

**Comment by Mycah142** [comment]
I weep.

**Comment by Mycah142** [comment]
There, I did the thing. Thoroughly tested three lines of code that never has been seen ingame and couldn't be seen ingame without variable edits.

**Review by hyperioo — APPROVED** [review]

**Pull request merged**
