### PR TITLE
Modify the beer keg sprite

### PR DESCRIPTION
**Pull request by Twomoon-Github**
## About The Pull Request

Modify the beer keg sprite
## Why It's Good For The Game

The beer keg sprite was a bit old, and looked very different to the rest of the items.
## Testing

beerkeg showcase

## Changelog
:cl:
imageadd: New beerkeg sprite
imagedel: Old beerkeg sprite
/:cl:

### CODE REVIEW

**Comment by Firefox13** [comment]
Can you give a bigger image of it in-game? What palette does it use, is it the wall ones? (it should use an already existing palette. Bonsai was a special case)

**Comment by Twomoon-Github** [comment]
> Can you give a bigger image of it in-game? What palette does it use, is it the wall ones? (it should use an already existing palette. Bonsai was a special case)

it use the palette from the donut briefcase (metal). except with one transition color added, and no problem, here is your pic:
beerkeggit

**Review by Firefox13 — APPROVED** [review]

**Comment by Twomoon-Github** [comment]
image
made the front handle a bit darker, to make it more obvious that its one of the top handle of the keg

istockphoto-1159558591-612x612

**Comment by MLGTASTICa** [comment]
im of opinion this looks worse than the current sprite.  The shadowing is just.. from left to right and doesn't follow the 3/4 top-down perspective for structures.

**Comment by Twomoon-Github** [comment]
> im of opinion this looks worse than the current sprite. The shadowing is just.. from left to right and doesn't follow the 3/4 top-down perspective for structures.

honestly, i understand, i might close the pr and works more on it later, im not entirely satisfied too, especially about the top part, perhaps i'll just keep the current keg shape and update its palette to fix it the sprite.

**Pull request closed without merging**
