### PR TITLE
Fix mouse goonchat

### PR DESCRIPTION
**Pull request by SirRichardFrancis**
## About The Pull Request

Turns whatever mouse says into "Squeak!" in a floating message.

Before:
image

After:
image

## Why It's Good For The Game

Fixes cool.

## Changelog
:cl:
fix: horrible case of language barrier breaching by mice
/:cl:

### CODE REVIEW

**Comment by zombiemimic** [comment]
No more tempting souls into violence. sad

**Comment by Fatherperhaps** [comment]
Rat is the most enriching role in this game.

**Comment by Alliostra** [comment]
https://www.youtube.com/watch?v=3KcJ5Ji4WfM

**Comment by Rumplenutskin** [comment]
this would be a sad change. I've had so many fun mouse interactions. don't become tg on me

**Comment by Omni44** [comment]
Remove the part where you remove the whole chat thing from mice, and add part where player spawned mice do not disintegrate after few seconds and you'll have good PR and a half there.

**Comment by mattroks101** [comment]
This is a really big bandaid fix for this. Can we not do a deep dive onto why this isn't respecting mice language in the first place?

**Comment by TheShown911** [comment]
It should also be tested how goonchat works with other simplemobs.

**Review by hyperioo — COMMENTED** [review]
I agree with matt, it hides the issue rather than fix it. The same kind of issue would remain with current/future talking mobs.

**Comment by drexample** [comment]
Yeah that doesn't fix the issue of parts of language system being ignored by runechat.

**Pull request closed without merging**
