### PR TITLE
Mad Libs Research Data

### PR DESCRIPTION
**Pull request by greenteaguzzler**
## About The Pull Request

- Research data disks now pick from a list of buzzwords to generate their names.
- Fixed some weird grammar in secdocs.dm
- Some examples:
image

## Why It's Good For The Game
Makes science more sciency

## Changelog
:cl:
tweak: research data disks get new titles
spellcheck: fixed a few typos in secdocs.dm
/:cl:

### CODE REVIEW

**Comment by Kegdo** [comment]
Gigabased gigacool ultraamazing

**Comment by ValoTheValo** [comment]
kinda liked the old names better for the secdocs. and it might fuck with lore in the future even if thats a long way down the line

**Review by SirRichardFrancis — COMMENTED** [review]
Looks interesting. But I think that better be turned into new junk item that give research points on being scanned/deconstructed, leaving secret documents as oddities, with content too crazy to comprehend.

**Comment by greenteaguzzler** [comment]
> kinda liked the old names better for the secdocs. and it might fuck with lore in the future even if thats a long way down the line. as apparently some of the secret docs have things written for them that could be implemented

Lore aspect just depends on the words in the list it can pick from, I just cannibalized the old names into the new pool. Idk about the rest

**Comment by ValoTheValo** [comment]
i still don't think this is a good change to secret docs. pointlessly fucking with lore bad. the old ones atleast got you thinking while this is just meaningless

**Comment by Kegdo** [comment]
what the FUCK are you talking about? What lore? These names are le funny references and memes - you really think Discordia is something related to lore? Unknown blueprints??

**Comment by Kegdo** [comment]
Hmmm yes, this Le door phenomenon got me thinkin
(Literally nothing related to lore)

**Comment by SirRichardFrancis** [comment]
> what the FUCK are you talking about? What lore? These names are le funny references and memes - you really think Discordia is something related to lore? Unknown blueprints??

That's header for very first doc about CEV Eris and looks like and old name for server itself that have been changed at some point.

image


image

It's not _just_ funny memes, okay.

**Comment by SirRichardFrancis** [comment]
image

**Comment by Kegdo** [comment]
I know that our domain is discordia, it's not related to eris lore.
The 'real reason one star fell' is. Yet, idc.

**Comment by Kurgis** [comment]
I agree that lore concerns are, or rather, shouldn't really be a concern. The current texts are so nonsensical that they may as well be removed entirely, yet they're being replaced instead here with something somewhat interesting. Not in the endearing nonsensical either that the early Hivemind had either with their broken English, but simply not good. Additionally, due to lore rewrites (it is a mess), it is unknown to me how many references within the original list even will be developed going further.

**Comment by ValoTheValo** [comment]
Thing created by a random generator is far less interesting and doesnt make you think. Its just random

**Comment by Kegdo** [comment]
^ tl;dr good change, remove reerenglish and ~~bay~~ old lore leftovers

**Comment by Kegdo** [comment]
> Thing created by a random generator is far less interesting and doesnt make you think. Its just random

It's good because it's random, new, funny and kind of unique. Those are old, there are few of these, and they are not related to lore.

I really don't understand why you want everything to stay the same, old, stale shit.

**Comment by ValoTheValo** [comment]
> > Thing created by a random generator is far less interesting and doesnt make you think. Its just random
> 
> It's good because it's random, new, funny and kind of unique. Those are old, there are few of these, and they are not related to lore.
> 
> I really don't understand why you want everything to stay the same, old, stale shit.

I don't understand why you want to endlessly tweak things that are fine instead of adding new things. This still doesnt even fix the issue with secret docs being unreadable.

**Comment by ValoTheValo** [comment]
> > Thing created by a random generator is far less interesting and doesnt make you think. Its just random
> 
> It's good because it's random, new, funny and kind of unique. Those are old, there are few of these, and they are not related to lore.
> 
> I really don't understand why you want everything to stay the same, old, stale shit.

How does randomness make this good. Its meaningless. There was no thought put into it and its just random words that have no meaning. The old ones had some thought put into them even if it was never elaborated on. Why not elaborate on it instead of adding rng to make it meaningless

**Comment by Kegdo** [comment]
> I don't understand why you want to endlessly tweak things that are fine instead of adding new things. 

Because adding new things takes more time and I also need sprites. While waiting for the said sprites, it's a good idea to tweak stuff in favor of players, or to fix stuff that annoys the said players. I am both addin and tweaking, but until I get the sprites there won't be much adding.


>that are fine

They barely work, optimisation and improvement is crucial to make Eris good.

>This still doesnt even fix the issue with secret docs being unreadable.

Never heard of it, ergo it doesn't exist.

**Comment by greenteaguzzler** [comment]
Randomly generated titles may seem meaningless at a glance. However, the individual words suggest much larger forces at play.

Consider "The impact of linear-time algorithms on cyanotranslocation." The author felt the need to specify "linear time"; is there another way of thinking about time in this setting? Cyanotranslocation sounds like a buzzword (and it is) until you realize cyano- means blue and translocation means movement. They're researching bluespace teleportation.

I think random titles can still have meaning. Are they more meaningful that the old ones? Maybe, maybe not, I'll just make a separate item for these

**Comment by Kegdo** [comment]
Maybe replace the "old data" disk with old names?

**Comment by SirRichardFrancis** [comment]
Random name generation looks interesting. But our current secret documents looks good too.
Make something new instead of changing old things with no visible gain. That's change for the sake of change that bring fucking nothing to the game.
Why the hell this oddity "barely work" and why changing the name should fix it I do not comprehend.

**Comment by ValoTheValo** [comment]
> > I don't understand why you want to endlessly tweak things that are fine instead of adding new things.
> 
> Because adding new things takes more time and I also need sprites. While waiting for the said sprites, it's a good idea to tweak stuff in favor of players, or to fix stuff that annoys the said players. I am both addin and tweaking, but until I get the sprites there won't be much adding.
> 
> > that are fine
> 
> They barely work, optimisation and improvement is crucial to make Eris good.
> 
> > This still doesnt even fix the issue with secret docs being unreadable.
> 
> Never heard of it, ergo it doesn't exist.

How the fuck is paper poorly optimized what are you smoking

**Comment by MLGTASTICa** [comment]
> 

i can attest that the documents are at fault for 23~ ish percent of the lag , due to the fact that their names simply runtime when picked.

**Comment by MLGTASTICa** [comment]
> > > I don't understand why you want to endlessly tweak things that are fine instead of adding new things.
> > 
> > 
> > Because adding new things takes more time and I also need sprites. While waiting for the said sprites, it's a good idea to tweak stuff in favor of players, or to fix stuff that annoys the said players. I am both addin and tweaking, but until I get the sprites there won't be much adding.
> > > that are fine
> > 
> > 
> > They barely work, optimisation and improvement is crucial to make Eris good.
> > > This still doesnt even fix the issue with secret docs being unreadable.
> > 
> > 
> > Never heard of it, ergo it doesn't exist.
> 
> How the fuck is paper poorly optimized what are you smoking

i can attest that they are behind 23 ish ~ percent of lag , they simply runtime , causing infinite loops to appear and to sink performance , its why late game performance gets so broken.

**Comment by ValoTheValo** [comment]
> > > > I don't understand why you want to endlessly tweak things that are fine instead of adding new things.
> > > 
> > > 
> > > Because adding new things takes more time and I also need sprites. While waiting for the said sprites, it's a good idea to tweak stuff in favor of players, or to fix stuff that annoys the said players. I am both addin and tweaking, but until I get the sprites there won't be much adding.
> > > > that are fine
> > > 
> > > 
> > > They barely work, optimisation and improvement is crucial to make Eris good.
> > > > This still doesnt even fix the issue with secret docs being unreadable.
> > > 
> > > 
> > > Never heard of it, ergo it doesn't exist.
> > 
> > 
> > How the fuck is paper poorly optimized what are you smoking
> 
> i can attest that they are behind 23 ish ~ percent of lag , they simply runtime , causing infinite loops to appear and to sink performance , its why late game performance gets so broken.

I dont think this PR fixes that

**Comment by MLGTASTICa** [comment]
> 

it does by reworking the way it is done.

**Comment by ArmolitskiyCarpoeb** [comment]
>i can attest that they are behind 23 ish ~ percent of lag , they simply runtime , causing infinite loops to appear and to sink performance , its why late game performance gets so broken.

OH MY GOD AHAGAGAGAGAGA SHIR

**Comment by TheShown911** [comment]
What if just new non-random names that are based on lore?

**Comment by ValoTheValo** [comment]
Good change. I like research data having funky names

**Comment by hyperioo** [comment]
The system itself looks ok, we can always change the lore words if needed with another PR.

It seems some changes that were previously included in the PR have been removed (otherwise I don't understand some of the comments...)

**Pull request merged**
