### PR TITLE
Give MBO a dartgun instead of a Anne and some ammo/poison roundstart

### PR DESCRIPTION
**Pull request by Firefox13**
## About The Pull Request
Replaces his roundstart anne and a dartgun, three mags for it and a random poison vial

## Why It's Good For The Game
Dartgun is a pretty forgotten weapon - it's essentially a syringe gun+ and it's foudn either only from junk or uplink. Given MBO works in medical and has access to chemistry I believe it would be more fitting for him to be armed with a dartgun.

## Changelog
:cl:
balance: MBO now starts with a dartgun, 3 mags and random poison vial instead of Anne and 2 rubber mags for it
/:cl:

### CODE REVIEW

**Comment by Humonitarian** [comment]
> The syringe gun is useless and bugged since clothing stops it, and the same goes for the dartgun. It also won't work half the time, including not recognizing regents loaded into it.
> 
> It's a forgotten relic that no one cares about because no one likes funny chem mixes that instant kill or stun you.

This is true.

A possible alternative would be a chemthrower from the fire rework PR loaded with acid, maybe.

**Comment by Firefox13** [comment]
I'm going to fix dart gun ok.

**Comment by pexel5** [comment]
> I'm going to fix dart gun ok.

This is the beginning of something horrible

**Comment by pexel5** [comment]
Although what I'm talking about, we have cyanide / plasma and biomatter injected into the blood cannot kill

**Comment by SaltyOldBull** [comment]
what the fuck why

**Comment by Iglpigl** [comment]
Salt PR.

**Comment by DiaFRAME444** [comment]
> I'm going to fix dart gun ok.

Firefox, you spent so much time balancing guns, and now people are going to insta chloral hydrate others with the dart gun again? Why not just let the Voodoo into the game in its current state, then?

**Comment by ErisMeleeEnjoyer** [comment]
maybe the solution is to remove chloral hydrate.

**Comment by maikilangiolo** [comment]
> Why not just let the Voodoo into the game in its current state, then?

Copium. New content shouldn't be half assed from the start

**Comment by Firefox13** [comment]
> now people are going to insta chloral hydrate others with the dart gun again? 

Syringe gun works by the way. Use it.

I'll return to this PR when I figure out how to make dart gun work. Yeah...

**Comment by Firefox13** [comment]
Was fixed in #8386

**Comment by Firefox13** [comment]
Oh, I mixed PR up a little.
Basically dartgun will suck compared to a normal gun
:mitosis:

**Pull request closed without merging**
