### PR TITLE
New medkit, bandaid and adv medkit sprites **UPDATED** + Morgue slabs, NT/Serb kits

### PR DESCRIPTION
**Pull request by githubuser4141**
## About The Pull Request

Replaces the sprites of adv medpacks, med boxes, autoinjectors (wip), medscanners, ointment/bandaids and makeshift bandaids with modernized ones by infrared_baron

## Why It's Good For The Game

Modernized sprites (Image has been MS paint'd to adjust for requested sprite changes, any artefacts are not in-game)
image
image

## Testing

Tested, works (see screenshots)

## Changelog
:cl: Sprites by INFRARED_BARON
imageadd: New sprites for medkits, ointment, bandaid, injectors, splints, adv medkit, morgue slabs, NT/Serb kits, medical HUD and scanner
imagedel: Old sprites for medkits, ointment, bandaid, injectors, splints, adv medkit, morgue slabs, NT/Serb kits, medical HUD and scanner
/:cl:

### CODE REVIEW

**Review by Firefox13 — COMMENTED** [review]
There are other medkits still having "old" style, and they'll look like ass compared to new medkits.

Discussing with Baron in DMs we came to conclusion that existing medkits can stay.

**Comment by githubuser4141** [comment]
image

**Comment by githubuser4141** [comment]
> What I'm interested in is will injectors still have their old reagent alpha after they're used.

Doesn't look like it...
image
image

**Comment by thevandie** [comment]
Very cool

**Review by hyperioo — APPROVED** [review]

**Pull request merged**
