### PR TITLE
Nerfs spoons

### PR DESCRIPTION
**Pull request by MLGTASTICa**
## About The Pull Request
You can spoon someone to instantly force feed them without any actual checks , this changes that
## Why It's Good For The Game
I was walking in a hallway , and then a chemist passes by me , turns around  then goes away , suddenly i fall asleep and im being organ harvested. I was wearing heavy armor so i  was wondering how such thing is possible . I have found that spoons are simply overpowered.

## Changelog
:cl:
fix: Spoons not checking wheter a person can be fed and wheter the timer to do so has been run
/:cl:

### CODE REVIEW

**Review by mattroks101 — APPROVED** [review]

**Comment by granodd** [comment]
Holy fucking shit.

**Comment by Kegdo** [comment]
What do you mean I can't spoon feed cyanide to someone anymore? Salt pr!!

**Comment by Anonmare** [comment]
Check it for forks too via food injected with chems

**Comment by SirRichardFrancis** [comment]
> What do you mean I can't spoon feed cyanide to someone anymore? Salt pr!!

Cyanide? Nah, you can drink/inject a bucket and it will deal laughable low toxin damage.

**Comment by Moltovz** [comment]
Man Y'all fuckin' Powergaming with spoons now? Cant have fuckin shit on space station 13.

**Comment by ValoTheValo** [comment]
Comically large skill issue

**Pull request merged**
