### PR TITLE
more sinks. less vendors. and the return of Bones and Punpun

### PR DESCRIPTION
**Pull request by fernandos13**
## About The Pull Request
well as suggested from the #feedback channel in discord.
replaces snack vendors all around the ship. that and

medbay got 2 extra sinks

RnD now have 1

bones. and punpun are back at their houses

https://gyazo.com/collections/01819e163794e3fc0d80cce71f9188ea

## Why It's Good For The Game
to make bar and garden more meaningfull. since the sanity on itself didn't brought it to eris needs

also
adds sinks to medbay and robotics surger. for surgeons. to clean their paws
adds pets. cause cmon you gotta love em (and incentive to pick MBO and Bar manager)

## Changelog
🆑 Fernandos33
add: 3 sinks to moebius
del: snack vendors
tweak: seed servitor are in the same level as garden now. no more cardio needed
balance: some vendors got replaced with battery. cigarette and a soviet machine even.
/🆑

### CODE REVIEW

**Comment by fernandos13** [comment]
finally

**Comment by fernandos13** [comment]
its a map change travis why it failed please explain to me

**Comment by Kurgis** [comment]
Did you place step_x/y on any objects? Try closing and re-opening as well.

**Comment by fernandos13** [comment]
only changed the
DIR 
var on some vendors no step thing

**Comment by Kurgis** [comment]
You need to prepare the map before you make changes again.

**Comment by fernandos13** [comment]
lets try it once more. "i prepared it. i'll try to get a default dmm. and prepare with that. and then change for the new dmm" and then merge... would that.. work

**Comment by fernandos13** [comment]
uh.. why now.. travis. its the same error again.. dammit i need to redo it later. today still

**Comment by fernandos13** [comment]
FINALLY

**Comment by SpadesSlick** [comment]
Should be checked for conflicts with #5184.

**Comment by fernandos13** [comment]
i mean i haven't touched any of those buttons. so it should be ok. but how can i double check it?. is there a way to merge that PR into mine?

**Comment by fernandos13** [comment]
ps: manually comparing boths. shows they are compatible. since changes where made in different locations.

**Comment by fernandos13** [comment]
ok idk why merging the master created a error. neither whats this thing that forced itself to be merged. i'll get back to it later if it fails travis

**Comment by fernandos13** [comment]
meging master once more
but rebased

**Comment by drexample** [comment]
@fernandos13 Please fix your PR for the review or it will be closed in 5 days.

**Comment by fernandos13** [comment]
i'll redo it

**Pull request closed without merging**
