### PR TITLE
Fancy sinks

### PR DESCRIPTION
**Pull request by infraredbaron**
## Why It's Good For The Game

Before:
image_2019-09-18_15-24-30

After:
image_2019-09-18_15-24-40

## Changelog
:cl:
add: new sprites for sink and sink_alt
/:cl:

### CODE REVIEW

**Comment by Kurgis** [comment]
From where?

**Comment by infraredbaron** [comment]
From TG - https://github.com/tgstation/tgstation/pull/45199
sorry for posting this later than I should

**Comment by drexample** [comment]
Those sprites look worse than original ones.

**Comment by Kurgis** [comment]
https://user-images.githubusercontent.com/20824501/61550836-ee4e4a00-aa29-11e9-82c4-ff86fc5c0d46.png

**Pull request closed without merging**
