### PR TITLE
Borer infest fix

### PR DESCRIPTION
**Pull request by AltHit**
## About The Pull Request
Added check for being a monkey. That's about it
## Why It's Good For The Game
Expands worm roleplay variety? IDK, we just forgot to add this check and now it's working as it was intended
## Testing

- Confirming bug
Spawned a monkey and tried infesting it - fail. Issue confirmed
- Resolving issues
Dug into infest code and added check for monkey next to check for human
- Checking if issue is solved
Spawned monkey, stunned it, crawled inside
Double check. Spawned monkey and crawled inside without stun in case it was depended on stunning target
Success in both cases. Issue resolved!

## Changelog
:cl:
fix: Fixed borer not being able to infest monkeys
/:cl:

### CODE REVIEW

**Comment by vode-code** [comment]
#8398 
next time, check for if you're wrong, instead of checking for if you are right.

**Comment by SaltyOldBull** [comment]
intended behaviour, not a bug.

**Comment by Mycah142** [comment]
> intended behaviour, not a bug.

Yeah well it's fucking lame to only be able to infest roaches (which usually kill you if they're alive, so dead roaches), or logged in players who immediately sugar you and surgically remove you.

**Comment by Deal5** [comment]
> intended behaviour, not a bug.

no, it's a bug

**Review by hyperioo — APPROVED** [review]

**Pull request merged**
