### PR TITLE
Revert #7226

### PR DESCRIPTION
**Pull request by SirRichardFrancis**
## About The Pull Request

What it says on the tin, revert of #7226.

## Why It's Good For The Game

Hopefully I won't be getting any more hate mail from admins regarding that nonsense.

## Changelog
:cl:
code: reverted ammo kits code to pre May 13 state
/:cl:

### CODE REVIEW

**Comment by maikilangiolo** [comment]
Bruh don't be childish. I've already told you the change is great. Only the recipes need rebalance and they are like 5 number changes

**Comment by Trilbyspaceclone** [comment]
The craft station changes were really good imo, just rebalance the prices not revert
Could also have cog help with gaining more points or something like that.

**Comment by TheShown911** [comment]
Leaving this one in stasis for a while...

**Comment by Firefox13** [comment]
inactivity yadda-yadda-yadda Kirov stop bothering me on discord

**Comment by SirRichardFrancis** [comment]
There is no inactivity, PR is ready to be merged at any moment, no conflicts here.

Meanwhile #6009 is staying open for 626 days and in merge conflict for almost as long.

**Pull request closed without merging**
