### PR TITLE
Introduce Moebius voidsuit

### PR DESCRIPTION
**Pull request by Firefox13**
## About The Pull Request

This PR adds a new(that's been in the code for two months atleast) a new spacesuit - Moebius combat voidsuit. It's researchable and located on the very end of combat tree(behind laser cannon) and is printable.
Armor values(same for the helmet and suit):
изображение

Matter values:
MATERIAL_PLASTEEL = 20,
MATERIAL_STEEL = 15,
MATERIAL_GLASS = 5,
MATERIAL_PLASTIC = 10,
MATERIAL_PLATINUM = 5
(both from the helmet and the suit itself)
~~Gold~~ Platinum is a rare material that'll hamper the ability to mass-produce the voidsuit so every vagabond don't ends up wearing the suit. The only way to acquire it is through mining.
The price is 1400(1200 for the suit and 200 for the helmet).
The suit was also introduced to beacon trading system in #5133 as well.
BONUS: colored helmets! On suit spawn(construction/buy) it chooses a random helmet color.
изображение

Also I fixed few required_technologies in the combat tree.

## Why It's Good For The Game

изображение
Slightly outdated image, but only a pair of pixels on the earpiece were changed.
The variety of the available armor is good, the suit is (intended to) be slightly better than IH voidsuit and be superior against laser weapons, since it's located behind laser prototype weapon. Moebius lacks only armor at this point, but I don't think the material values(even with upgraded protolathe) will allow to produce it en-masses.
изображение
изображение

## Changelog
:cl:
add: Moebius combat voidsuit.
/:cl:

### CODE REVIEW

**Comment by Sparrowbird611** [comment]
It looks cool. I just wanted to make sure you were aware this thing has more laser protection than the traitor red suit. It's not by a huge amount, but I thought it worth mentioning anyway.

**Comment by DarkLevelSS13** [comment]
For a void suit it's have a very high stats, most like some kind of rig.
To be sure, here some stats of "combat hardsuit control module":
               melee = 45,
		bullet = 50,
		energy = 45,
		bomb = 50,
		bio = 100,
		rad = 50
And here goes an "ironhammer voidsuit":
		melee = 35,
		bullet = 40,
		energy = 30,
		bomb = 25,
		bio = 100,
		rad = 75

**Comment by Firefox13** [comment]
> 
> 
> For a void suit it's have a very high stats, most like some kind of rig.
> To be sure, here some stats of "combat hardsuit control module":
> melee = 45,
> bullet = 50,
> energy = 45,
> bomb = 50,
> bio = 100,
> rad = 50
> And here goes an "ironhammer voidsuit":
> melee = 35,
> bullet = 40,
> energy = 30,
> bomb = 25,
> bio = 100,
> rad = 75

It is, indeed, got high stats. The drawback is, it's located at the end of the combat tree(though in the long runs it may not be an issue) and requires quite resources to print...
But the more I think of it, the worse I feel about the numbers. What do you suggest?
~~I'm aiming for(or trying to) for high energy protection, since it's located in the end of combat tree behind laser weaponry and all that Moebius based on laser weapons it should have decent laser protection.~~

**Comment by Sparrowbird611** [comment]
I think with the way the RnD thing works, it's a bit questionable since I've seen people speedrun the entire thing within 15 minutes. The resource cost is sufficient though.

The stats aren't honestly that bad, but I think could use some tweaking. To stay with the energy armor theme, I'd lower the ballistic armor down to perhaps 35% while keeping the energy protection at its current level. That's better than your average armor piece (Miner voidsuits have 35% ballistic protect, while most armors sit at about 30%). It may be ok to go to 50% energy protection, just to put it a step above other ablative options (techno armor and oberth gear), but I'm not super confident on that one, so test that before you give it that number.

**Comment by Iglpigl** [comment]
Well firstly using the monkey method this can be researched in seven minutes and that's if you get unlucky, gold is almost an infinite resource considering tesla coils from modular consoles give one gold each, I can see every round on EN server with all mobius wearing this armor by the fiftieth minute, not sure if that's what we really want.

**Comment by Firefox13** [comment]
> gold is almost an infinite resource considering tesla coils from modular consoles give one gold each

Don't forget that the gold isn't the only required material. Do you have any ideas what I should replace it with? Excluding uranium(wearing uranium armor is a bit unintuitive) and diamond(it's *too* rare)

**Comment by GrayRachnid** [comment]
platinum

**Comment by Iglpigl** [comment]
Honestly considering what you said nothing would make sense, maybe costing plasma and gold but that might be too much.

**Comment by Iglpigl** [comment]
> platinum

Platinum is rarer than diamond considering diamonds are trash loot and platinum is not as far as I know, and fox explicitly stated that diamond is too rare, making it take platinum defeats Fox's point.

**Comment by GrayRachnid** [comment]
> 
> 
> > platinum
> 
> Platinum is rarer than diamond considering diamonds are trash loot and platinum is not as far as I know, and fox explicitly stated that diamond is too rare, making it take platinum defeats Fox's point.

Platinum is very common when mining

**Comment by Firefox13** [comment]
> 
> 
> > > platinum
> > 
> > 
> > Platinum is rarer than diamond considering diamonds are trash loot and platinum is not as far as I know, and fox explicitly stated that diamond is too rare, making it take platinum defeats Fox's point.
> 
> Platinum is very common when mining

🤔 That's actually a good idea - there's plenty of platinum on the asteroid...
I'll use platinum.

**Comment by Iglpigl** [comment]
> > > platinum
> > 
> > 
> > Platinum is rarer than diamond considering diamonds are trash loot and platinum is not as far as I know, and fox explicitly stated that diamond is too rare, making it take platinum defeats Fox's point.
> 
> Platinum is very common when mining

That is absolutely true, but making mining less tedious would help with that, the giant drill literally starts with only a 1000 L cell and with that cell lasts around 15 seconds, moving the ship screws over miners and it's generally not worth it, mining isolates the miners completely except their shuttle having a radio, our asteroid is boring and not worth going into all things considered, also mobious shuttle doesn't even have giant drill, miners who aren't new players never mine, making it platinum after the changes from the design doc are done seems reasonable, but making things tedious is generally a bad idea, and making it require platinum would probably justify increasing it's energy armor at least, but it all comes down to what Fox wants to do with this PR.

**Comment by Firefox13** [comment]
> but it all comes down to what Fox wants to do with this PR.

It all comes to me trying both not to give science infinity armor and actually give it to them. Adding a platinum material is hard and bold counter for mass-producing it and it encourages inter-departmental cooperation between Moebius and Guild.
~~if you have better ideas excluding increasing numbers required - go on~~

**Comment by Iglpigl** [comment]
> > but it all comes down to what Fox wants to do with this PR.
> 
> It all comes to me trying both not to give science infinity armor and actually give it to them. Adding a platinum material is hard and bold counter for mass-producing it and it encourages inter-departmental cooperation between Moebius and Guild.
> ~if you have better ideas excluding increasing numbers required - go on~

I thought about it and platinum is pretty reasonable, making science and guild have more reasons to communicate is actually pretty helpful, and mass production of the armor wouldn't be good balance wise, requiring platinum makes it pretty unique,all in all it's in a pretty good spot right now.

**Review by TheShown911 — APPROVED** [review]

**Pull request merged**
