### PR TITLE
Remap merch base

### PR DESCRIPTION
**Pull request by pexel5**
## About The Pull Request

New merch base.

## Why It's Good For The Game

The old base is quite inconvenient and most of the things that would be good for mercenaries are not there

## Changelog
:cl:
tweak: Remap serbian base. add some thinks.
/:cl:

### CODE REVIEW

**Comment by hyperioo** [comment]
Can you post before/after pictures?

**Comment by SirRichardFrancis** [comment]
Where are screenshots, Billy?
image
We want screenshots!

**Comment by pexel5** [comment]
> Can you post before/after pictures?

fogot about it mybad

unknown (10)](https://user-images.githubusercontent.com/66647116/168342589-e2f0c0ad-c30c-4e68-86fe-ad5bce666961.png)
2570-7862d2f1-096c-4705-80c5-a28288ccfec4.png)
.

**Comment by pexel5** [comment]
unknown (10)

**Comment by pexel5** [comment]
> Where are screenshots, Billy? image We want screenshots!

:D

**Comment by FortuneMaster** [comment]
first off - whats the point of abandoned rooms?
second - attach screenshots to PR description

**Comment by ValoTheValo** [comment]
> first off - whats the point of abandoned rooms? second - attach screenshots to PR description


Firstly there is absolutely no reason for this to be made, secondly it will screw up recoil and make all these guns impossible to shoot, thirdly, one and possibly more gun recoil changes are direct violation to contributing guidelines, you should try reading them. https://wiki.cev-eris.com/Content_GuidelinesEn

**Comment by garrulousTeamotei** [comment]
The two airlocks seemingly accidentally forgotten in the middle of space really push the "Eris" Aesthetic.

**Review by Firefox13 — COMMENTED** [review]
> equipment behind barricades

*No.* You want to speed through the prep room without spending time breaking cades. This isn't a /tg/ pirate ship
> insulated gloves

Mercs spawn with shock-proof ones.
> Autolathe

It's *very* little of use for them - if they miss something really important from it they should either get it from uplink or you map the item itself.

> extra tool/uniform modification kit?

> bunch of smoke grenades

use a smoke grenades box instead

Overall equipment area is very oversized and can be shrinked down - it's just 6 people there at max, no need to make it that big. Something like this:
изображение

> Chem equipment

Dunno about this one, but if you want to expect them to make chems atleast make it an upgraded one. Ask on discord for help with that.|

> fumo

based

**Comment by Firefox13** [comment]
Could also use the suit storage units for SCAFs.

**Comment by Firefox13** [comment]
Equipment room layout should be made in mind with traffic in it - you do not need O2 caniste to refill oxygen tanks next to the entry as people will push each other, same goes for satchels/SCAFs. More important equipment (read: guns) should stay in the center for ease of access (which you already did, good) and support equipment (tools/medicines) are out of the way (which you also did).

**Comment by pexel5** [comment]
> 

As for chemicals, it is there only so that if someone wants to do something simple, he can do it, if chemistry is really needed, then uplink is used, for bAlAnCe i think. 

Okay, I'll move some things a little bit by the type of tools and places to refill the cans.

Just for information, why did I make some rooms abandoned? Because they are not absolutely mandatory to use and do not contain something very strong or important, but allows you to pass at any time if you want to come up with some gimmick. Let's say the same chemistry, you won't be able to do anything strong, but you can play around and make a couple of grenades with gas and the like. The chemistry itself was most likely done so that if the Serbs were early, they could prepare better and the crew would benefit from it. (Spend your 20 minutes creating chemicals and break into the ship with your fun gimmick or something else)

^^

**Comment by pexel5** [comment]
Why don't give the players wander around the base and explore it, some closed rooms are quite funny to me

**Comment by pexel5** [comment]
> 

But if it gets in the way too much, I'll remove them. Whatever you say.

**Comment by pexel5** [comment]
> 

image

good?

**Comment by pexel5** [comment]
last version 
image

**Comment by UltraNumeron** [comment]
where is their armor by the way

**Comment by pexel5** [comment]
> where is their armor by the way

under the bags

**Review by hyperioo — APPROVED** [review]

**Pull request merged**
