### PR TITLE
IH bulletproof helmet resprite, NVG BP helmet side states offset fix, NVG BP helmet making masks invisible fix

### PR DESCRIPTION
**Pull request by CeUvi**
## About The Pull Request
ih bph
## Why It's Good For The Game
dealing with my past mistakes, old sprite looked awful
## Changelog
:cl: CeUvi
imageadd: resprited IH BP Helmet
fix: NVG BP helmet side states offset fix
fix: NVG BP helmet making masks invisible fix
/:cl:

### CODE REVIEW

**Comment by SirRichardFrancis** [comment]
^
That dog meme is very related.

image

**Comment by CeUvi** [comment]
> ^ That dog meme is very related.
> 
> image

now compare the item states

**Comment by SirRichardFrancis** [comment]
> now compare the item states

No u

**Comment by CeUvi** [comment]
> No u

ok
image

**Comment by CeUvi** [comment]
> I don't really like the new helmet sprite

that's a bruh moment

**Comment by CeUvi** [comment]
new sprite was made

**Comment by SirRichardFrancis** [comment]
> new sprite was made

Still sucks.

**Comment by SirRichardFrancis** [comment]
> cry about it

cry

You've been told many times by different people that while current item state is meh, mob state is good and shouldn't be fucked with.
Change for the sake of change again, and obvious downgrade at that.

**Comment by CeUvi** [comment]
> You've been told many times by different people that while current item state is meh, mob state is good and shouldn't be fucked with.

I didn't like my old sprite, I made it better.
cope and seethe


> Change for the sake of change again, and obvious downgrade at that.

well, your holy doors for example is change for the sake of change, so I can't see the issue

**Comment by SirRichardFrancis** [comment]
> I don't think it's new and unique more like, same airlock as others, but bugged, with shitty sprite and dumb features

Maybe. Maybe not.

> literally play IH every round @ enjoy playing IH @ but not like the sprites @ resprite to make them look not so awful

@
Fail
@
PR it anyway

> Stop crying

Stop PRing cringe.

> you're not even playing the game.

Playing it quite often. Cope.

**Comment by drexample** [comment]
old sprite is good

**Pull request closed without merging**
