### PR TITLE
Maybe fixes Roaches needing admin only plants to be tamed?

### LINKED ISSUE #4162: [BUG] roach taming is broken and only works with admin-spawned ambrosia

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request
Maybe makes roaches not as picky about needing an admin spawned plant to even be tamed 

# untested

## Details
closes #4162

### CODE REVIEW

**Comment by SpadesSlick** [comment]
Well, testing is needed.

**Comment by Nozarati** [comment]
I tested this and currently it doesn't work with grown ambrosia even with the changes. This feature is quite under developed and not really relevant anymore due to the addition of Fuhrerole and its roach pacifying qualities. I don't really see any reason to keep it in, simply because it doesn't work and likely nobody cares enough to develop it further.

**Comment by Trilbyspaceclone** [comment]
I dont even know what broke it tbh.

**Comment by MadmanMartian** [comment]
Grown food is of the type /obj/item/weapon/reagent_containers/food/snacks/grown, so unless you access the seed data and check there, you're not going to be able to differentiate grown ambrosia from an apple

**Comment by Trilbyspaceclone** [comment]
Ye my plan was to make them just tame-able via any plant, thats why its now closed.

**Comment by MadmanMartian** [comment]
ah, okay.

That could be a way of doing it. As from reading, the hallucinogenics in the ambrosia is what tames them.

Maybe just have it check for a plant, and if it contains hallucinogen?

**Pull request closed without merging**
