### PR TITLE
Fix biosuit hiding shoes

### PR DESCRIPTION
**Pull request by SirRichardFrancis**
## About The Pull Request

What it says on the tin.

image

image

image

## Why It's Good For The Game

Fixes cool.

## Changelog
:cl:
fix: biosuit hiding shoes
/:cl:

### CODE REVIEW

**Comment by Humonitarian** [comment]
Realistically you'd want to wear your biosuit over your shoes to prevent a hole in the barrier, just like with spacesuits and softsuits, but I imagine you could stuff the biosuit in your shoes just as well.

**Comment by SirRichardFrancis** [comment]
> Realistically you'd want to wear your biosuit over your shoes to prevent a hole in the barrier, just like with spacesuits and softsuits, but I imagine you could stuff the biosuit in your shoes just as well.

image
You care about realism suddenly? Go ahead, resprite the biosuit then.

> Bomb suit not as flexible. That thing has thickness, and is basically just a massive voidsuit without pressure protection. Can't fit in shoes.

Bomb suit is not changed in this PR, but in #6954.

**Comment by Humonitarian** [comment]
> 

I just stated what I knew. Also the screenshots mentioned bomb suits, so I did too.
No need to get worked up and to make it personal.

**Comment by SirRichardFrancis** [comment]
> I just stated what I knew. Also the screenshots mentioned bomb suits, so I did too. No need to get worked up and to make it personal.

Nothing personal, just that your complaint about realism is hardly reasonable, especially after you dismissed appeals to realism yourself.

**Comment by ValoTheValo** [comment]
> Realistically you'd want to wear your biosuit over your shoes to prevent a hole in the barrier, just like with spacesuits and softsuits, but I imagine you could stuff the biosuit in your shoes just as well.
> 
> Bomb suit not as flexible. That thing has thickness, and is basically just a massive voidsuit without pressure protection. Can't fit in shoes.

yes let me go into a biohazard area with bare feet this is a good idea

**Comment by Humonitarian** [comment]
> yes let me go into a biohazard area with bare feet this is a good idea

What?

**Comment by TheShown911** [comment]
I think what people want to say is that biosuits should come with shoes covering the feet like voidsuits, but medical shoes are separate from biosuits, and there are no biosuit specific shoes.

**Review by TheShown911 — APPROVED** [review]

**Pull request merged**
