### PR TITLE
You get Nun-thing! You lose! Good day, sir!

### PR DESCRIPTION
**Pull request by Mycah142**
## About The Pull Request
Neotheology got alot of content. Y'know why? Because they're cool to make content for. Aesthetic is cool. So they get more content again.

I have added suit sprites from asset storage (Thank you nearbird (CKEY), your work is fantastic) to the Eris repository, and have written in a couple to be usable ingame, the Medicus Robes and the NeoTheology Crosier.

The Medicus Robes are, at their core, a space suit for healers. They are not a voidsuit, they don't have the protection of a voidsuit. But you know what they DO have?

Motherfucking POCKETS. What every healslut actually wants. Pockets. Pockets for medicine. Lipstick. A gun. Everything you could want. Unless it's bigger than a small item, or not-medical. Guns are medical. They cure you of the dumb. Thanks to these pockets, the robes are also stylish. Because that still means something, right?

The second item is the Crosier. It's a big golden stick to bean people with. Why? I counter with Why Not? Get beaned, kid.

## Why It's Good For The Game
Content, fancy sprites getting used, setting up for future content.

## Testing
https://puu.sh/JMU80/431963e5a2.webm
video was too long to post directly, so here's a link instead. Will not stand the test of time.

## Changelog
:cl:
add: NT Medicus Robes, a healer's space suit.
add: NT Crosier, acolyte disciplinary tool.
add: A bunch of NT themed sprites from asset storage for future content.
/:cl:

### CODE REVIEW

**Comment by thevandie** [comment]
mycah, Ik you were probably being ironic, but that was genuinely pretty funny, 10/10 comedian

**Comment by Firefox13** [comment]
Screenshots would be more welcome tbh for quicker exam but video is fine too

**Comment by thevandie** [comment]
> Screenshots would be more welcome tbh for quicker exam but video is fine too

image
his version might have gloves, but this is the suit

bonk stick
image

**Comment by Mycah142** [comment]
> Screenshots would be more welcome tbh for quicker exam but video is fine too

I've done videos for like 80% of my PRs. I got a theme going. Maybe one day I'll write a script.

**Review by TheShown911 — APPROVED** [review]

**Comment by hyperioo** [comment]
Conflict after merging #8242

**Review by hyperioo — APPROVED** [review]

**Pull request merged**
