### PR TITLE
martyr is a pistol not a LMG

### PR DESCRIPTION
**Pull request by fernandos13**
## About The Pull Request
nerfs martyr fire rate

## Why It's Good For The Game
nerfs martyr fire rate

## Changelog
:cl:Fernandos33
balance: nerfs martyr fire rate
/:cl:

### CODE REVIEW

**Comment by AMM101902** [comment]
This doesn't look like it changes anything. The Melt firemode only has one shot, and the Stun firemode remains unchanged. I recommend setting the fire delay of the weapon to 8 which seems to be the value used for light plasma bolts, and in the firemode section setting the fire delay to null so it is not overwritten.

**Comment by fernandos13** [comment]
the default delay was summing up with the firemode one. so it worked. and didn't matter the plasma mode delay siince it was one shot. but i do like your way of. "coding" better so i'm changing it to the exact metrics you said. thanks

**Comment by AMM101902** [comment]
Thanks for the correction, I didn't know that's how it works with fire delay.

**Comment by fernandos13** [comment]
me neither to be honest. took me some time to understand but basicall all the firemode date is "overlayed on top of the default gun one"

**Comment by fernandos13** [comment]
pretty sure people will be pleased, that i closed my prs. i was after all annoying

**Comment by fernandos13** [comment]
i'm annoying.  and i did my annoying part of today

**Review by TheShown911 — APPROVED** [review]

**Pull request merged**
