### PR TITLE
Replace vomitol with mold in trash foods

### PR DESCRIPTION
**Pull request by Kegdo**
## About The Pull Request
yum!
Replaces vomitol in (most of) oldified food with mold, which damages sanity(2 per tick, spider venom deals 3, for scale) and gives a very little toxin damage(equal to pararein)
The taste is horrendous.
## Why It's Good For The Game

So, basically, homemade pararein. More potent(and common) version of vomitol, that can be extracted and added to normal drinks and foods to trol people
Vomitol, which is actually medicine, shouldn't be in old foods. So it's just a chem that you make now.
P. S. I decided to not add any warnings to the user about the mold processing and dealing sanity damage, but I can add them if needed.
## Changelog
:cl:
add: mold toxin. Mold deals sanity damage and a little bit of toxin damage.
tweak: vomitol in trash foods is replaced with mold.
/:cl:

### CODE REVIEW

**Comment by TheShown911** [comment]
Toxin makes you vomit, not low sanity

**Comment by Kegdo** [comment]
> Toxin makes you vomit, not low sanity

no it doesn't make you vomit
and the old food should lower sanity instead of dealing toxin damage, don't know about you but I'd prefer to not, under any circumstances, eat chips that have moldy fungus on it
and if I'd eat them, I'd have a mental breakdown

**Comment by TheShown911** [comment]
You would also get food poisoning

**Comment by Humonitarian** [comment]
> > Toxin makes you vomit, not low sanity
> 
> no it doesn't make you vomit and the old food should lower sanity instead of dealing toxin damage, don't know about you but I'd prefer to not, under any circumstances, eat chips that have moldy fungus on it and if I'd eat them, I'd have a mental breakdown

Old food doesn't have toxin. It has random dispenser chems, or vomitol. Some can cause major burn damage.

Vomitol makes you vomit, denying you any nutrition.

This PR outright buffs maintfood as sanity isn't that big of an issue, unless it only adds moss as another chem option for maintfood items to contain.

**Comment by maikilangiolo** [comment]
> no it doesn't 

I mean it does make you vomit but just pop dylo lmao. I like this. Little toxin and sanity damage

**Comment by Kegdo** [comment]
> Old food doesn't have toxin. It has random dispenser chems, or vomitol. Some can cause major burn damage.

bro
image


> Vomitol makes you vomit, denying you any nutrition.
> 
> This PR outright buffs maintfood as __!!sanity isn't that big of an issue!!__, unless it only adds moss as another chem option for maintfood items to contain.

bro stop ODing on space drugs and smoke please bro your family needs you bro
about vomitol, there is no improvised version of it, so I might give the mold puking on ODing

**Comment by Humonitarian** [comment]
> bro stop ODing on space drugs and smoke please bro your family needs you bro about vomitol, there is no improvised version of it, so I might give the mold puking on ODing

If you've done any amount of ghetto chem in the past month or paid attention to PRs, you should know maintfood contains the chems I listed.

#6149 

It seems toxin from oldification is handled separately, as the randoms chems are handled through spawners.

**Comment by Kegdo** [comment]
> > bro stop ODing on space drugs and smoke please bro your family needs you bro about vomitol, there is no improvised version of it, so I might give the mold puking on ODing
> 
> If you've done any amount of ghetto chem in the past month or paid attention to PRs, you should know maintfood contains the chems I listed.
> 
> #6149
> 
> It seems toxin from oldification is handled separately, as the randoms chems are handled through spawners.

yea, I just found it. Still, some chems that may be found in the said food don't do anything(even sulfur???) on ingestion/injection, soooo
might just remove them ex dee

**Comment by Humonitarian** [comment]
> yea, I just found it. Still, some chems that may be found in the said food don't do anything(even sulfur???) on ingestion/injection, soooo might just remove them ex dee

They help keep some food edible for those with enough skill to find them, and to further improve ghetto chem.

Right now foods are the only ghetto source for several dispenser chems.

Finally, to quote Sparrow,
> Is there really a reason to make it more painful to get food in the first place? This doesn't really help the club all that much IMO, it just makes eating more obnoxious.

**Comment by Kegdo** [comment]
> They help keep some food edible for those with enough skill to find them, and to further improve ghetto chem.

yep, they weren't removed but vomitol was "uncommoned", and replaced with mold, making the former a weaker version of the latter. Also, the mold itself can be called a ghetto sanity poison, so you don't go killing and butchering spiders.

> Finally, to quote Sparrow,
> 
> > Is there really a reason to make it more painful to get food in the first place? This doesn't really help the club all that much IMO, it just makes eating more obnoxious.

not enough.
there is never enough pain in trash food

**Comment by Humonitarian** [comment]
At this point it feels like change for the sake of change. Mold also isn't fleshed out, cannot be converted into or from any chem either.

I can't say I like this PR.

**Comment by Kegdo** [comment]
> Mold also isn't fleshed out, 

then tell me how to flesh it out, cuz I think it's fine.

>cannot be converted into or from any chem either.

intended

**Comment by infraredbaron** [comment]
Very based. If there would be a mold overlay for foods it will be even better.

**Comment by CeUvi** [comment]
wysi

**Comment by Kegdo** [comment]
> Very based. If there would be a mold overlay for foods it will be even better.

wysi
we got the oldifier making the sprites look old, so.

**Comment by Humonitarian** [comment]
> then tell me how to flesh it out, cuz I think it's fine.
> cannot be converted into or from any chem either.

> intended
How so? What other chems work like this?

**Comment by Kegdo** [comment]
> How so? What other chems work like this?

According to the toxins.dm:
the basic toxin, oil, plasma, cyanide, potassium chloride, zombiepowder, DN-toxin, lexorin, polyacid, soporific, chloral hydrate... 
the list goes on, not every chem/toxin has a heating point.

**Comment by drexample** [comment]
> added mold

> didn't add a way to make spacecillin out of it 

bruh

**Comment by Humonitarian** [comment]
> According to the toxins.dm: the basic toxin, oil, plasma, cyanide, potassium chloride, zombiepowder, DN-toxin, lexorin, polyacid, soporific, chloral hydrate... the list goes on, not every chem/toxin has a heating point.

Most of those are either used in recipes, or are the result of recipes, allowing an electrolyser to break them apart.

**Comment by Kegdo** [comment]
> didn't add a way to make spacecillin out of it

well sorry I am not a biologist. But here, it's added now, penicilline it is

**Comment by Kegdo** [comment]
> Most of those are either used in recipes, or are the result of recipes, allowing an electrolyser to break them apart.

ok.
😎

**Review by TheShown911 — COMMENTED** [review]
I don't understand what this adds to the game.

**Comment by zombiemimic** [comment]
> I don't understand what this adds to the game.

there's no sanity loss from old food, which there should be

**Comment by Humonitarian** [comment]
I feel like vomitol should still be included.
Helps make maint food that much more punishing, while benefiting maintchem.

Still very iffy about mold's implementation.

**Review by hyperioo — COMMENTED** [review]
Yeah, making people slightly vomit seems like something you would get by eating decades-old molded food, not just that 10 percent chance on OD

**Comment by Kegdo** [comment]
> Yeah, making people slightly vomit seems like something you would get by eating decades-old molded food, not just that 10 percent chance on OD

made it vomit on affect_ingest with the chance `if(prob(20 * effect_multiplier))`

**Comment by Kegdo** [comment]
@hyperioo any suggestions on how to make this better?

**Review by hyperioo — APPROVED** [review]
Seems ok now. This basically add an alternative to vomitol that makes you vomit + sanity loss when you eat rotten food. Can be used to make ghetto spaceacilin.

**Comment by drexample** [comment]
This PR went from meh to good, great job everyone.

**Pull request merged**
