### PR TITLE
Add grain

### PR DESCRIPTION
**Pull request by hack-wrench**
## About The Pull Request

Add screen grain by sanity level:
0:30 = medium grain (how on pic)
30:60 = light grain
60+ = without grain

## Why It's Good For The Game

It's just cool pic

## Changelog
:cl:
add: screen grain by sanity level
/:cl:

### CODE REVIEW

**Comment by Firefox13** [comment]
Looks neat but values very likely will need some adjustments

**Comment by CeUvi** [comment]
imagine playing IH Op / vagabong and having a permanent light/medium grain

**Comment by MLGTASTICa** [comment]
Could you put this togheter with sanity as a whole and not in its separate folder ? we need things to be neatly organized and not all over the place.

**Comment by Alliostra** [comment]
fuckccomdom
Hello, this is floor filth calling

**Comment by HentaiStorm** [comment]
Thank god its been shut off ^

**Comment by ValoTheValo** [comment]
The values should probably be tweaked so it only appears when your going really insane as a mental break kinda thing rather than an over present thing every time you have low sanity

**Pull request merged**
