### PR TITLE
makes the telecomms consoles scan for any telecomms machines on the Z-level

### PR DESCRIPTION
**Pull request by nichlas0010**
requested by @GrayRachnid

### CODE REVIEW

**Comment by NanakoAC** [comment]
I seem to remember saying something about level data on another PR, it would apply here too

**Comment by nichlas0010** [comment]
Yeah, forgot to close this PR too 😄

**Comment by NanakoAC** [comment]
why close it, can't you improve it?

**Comment by nichlas0010** [comment]
I've no clue how level data works, and I couldn't personally I see a reason why the usage of map_data in is_on_same_plane_or_station() is wrong, so I just moved on to other projects 🤷‍♂️

**Pull request closed without merging**
