### PR TITLE
Armor changes and additions

### LINKED ISSUE #4467: Rouge Pixels on the Agrolyte Hoodie
image
(look at the feet)

### PR DESCRIPTION
**Pull request by Kurgis**
## About The Pull Request

Our current antagonists aren't using their unique clothing since doing so is not viable compared to even wearing nothing at all, this PR seeks to address that. This PR also adds the helmet counterparts for the armored vests, while also making vests more viable to be used. Adds a clothing information UI taken from tool information, currently only shows the armor value of a held clothing item.

fixes #4467 

## Details

<details>
  <summary>Expand</summary>

Added: Added generic reinforced shoes and jackboots for the general crew, which helps highlight Ironhammer's palette in-game.

Refactor: Moved some suits and headwear out of the Security uniform file. Space suit helmets no longer an unnecessary subtype of helmet. An armor type has been created for head items, and it follows close to the layout of suits. Moved head/helmet.dm into head/armor.dm.

Mapchanges: Replaces the paths of the aforementioned items.

Balance: Preacher's coat and jacket follow after the stats of the Guild jackets. The SCAF suits have been unashamedly buffed so that they outperform all equipment onboard the ship. Helmets perform better against melee, while relatively keeping the general stats of their suit counterparts. Combat RIGs have been adjusted as they already still out-perform nearly everything in the repo. Acolyte armor has been beefed up, while taking on an additional slowdown malus. The light RIG has been adjusted, and no longer gives full bio protection since it's not airtight. Hazard RIG, generic voidsuit, and gem-encrusted voidsuit have been given slight adjustments regarding their energy armor. The Syndicate space suit now actually is capable of performing some kind of role. Excelsior armor has been given straight buffs, suffers from the same problem of players avoiding it due to not being able to compete with other onboard suits, while being a clear declaration. Heavier suit armor have been made viable again by reducing their slowdown to be lower to able to compete with voidsuits. Removes armor value from jackboots, and most shoe items. Removes armor value from combat gloves, and most glove items.

Fixes: The Agrolyte skaf is no longer offset of the mob sprite by one pixel.

Tweaks: Adjusted the cloth spawners for the new items with stats in mind. Acolytes can find jackets in their lockers as an alternative to their heavier skafs. The mercenary magboots start already activated.

</details>

### CODE REVIEW

**Comment by Kurgis** [comment]
There's an issue with the action UI, which breaks the action toggle buttons. Will resolve soon by removing the UI code I added.

**Comment by Kurgis** [comment]
Ready for review.

**Comment by ACCount12** [comment]
conflict

**Comment by Kurgis** [comment]
Conflicts resolved.

**Pull request merged**
