### PR TITLE
fix vomiting not stunning

### PR DESCRIPTION
**Pull request by ErisMeleeEnjoyer**
## About The Pull Request

Bay12 code is a piece of putrid garbage.

## Why It's Good For The Game

code starts actually working from simply increasing a number by **1**.

## Changelog
:cl: Kegdo
fix: vomit stun not working
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
please no we dont need more broken stun timers

**Review by Firefox13 — CHANGES_REQUESTED** [review]
can we actually like remove it I feel it's been better without stun

**Comment by ErisMeleeEnjoyer** [comment]
it might be, but without stun, neural accumulation overdose is a joke, and gut punch is a joke as well. a necessary evil, i say

**Comment by Rexdyer1** [comment]
> it might be, but without stun, neural accumulation overdose is a joke, and gut punch is a joke as well. a necessary evil, i say

I disagree. neural is a massive pain. and usage of chemicals aside from painkillers is already not worth it. adding a stun to vomiting will just really take away and drive to use combat or mechanical chems....also stuns suck in general

also vomits without stuns are already painful for non NT. because it requires you being without food and having to scope out without the eating prayer.

**Comment by ErisMeleeEnjoyer** [comment]
> I disagree. neural is a massive pain. and usage of chemicals aside from painkillers is already not worth it. adding a stun to vomiting will just really take away and drive to use combat or mechanical chems....also stuns suck in general

neural is absolutely nothing without stuns unless you go 150> NSA, combat and stat chems are usable even with stuns since their main drawback is high NSA, not 100+ NSA.

> also vomits without stuns are already painful for non NT. because it requires you being without food and having to scope out without the eating prayer.

what, just eat a food from maint and you are good, even if it's moldy.

**Review by Firefox13 — APPROVED** [review]
After all a bug is a bug, so...

**Pull request merged**
