### PR TITLE
Ultimate Earmuff Buff

### PR DESCRIPTION
**Pull request by thevandie**
## About The Pull Request

Makes earmuffs only require 1 ear slot, instead of both, as well as putting them in the style vendor and asters misc disk.
(Yes I did this from my master accidentally, I fucked up and started making changes without making a unique branch, woops...)

## Why It's Good For The Game

Literally no one uses earmuffs right now, so I've made them less shitty so people will actually give them a chance. Earmuffs are only useful for ONE very specific niche scenario, that being flashbangs. Giving up your headset for that ability made it very unappealing, especially since the earmuffs didn't even look that good. Now they've both been given a better sprite, and are more usable, plus you still have to give up that free extra slot for protection so it's... kinda balanced.

## Testing

Woops, forgot this tab existed, yeah I booted up local and checked all the things. The autolathe and vendors work, and it only takes one ear.

## Changelog
:cl:
add: earmuffs to the style vendor
add: earmuffs to the asters misc pack disk for autolathe use
add: earmuff item sprite (the mob sprite was already added with my other pr, I just couldn't find where the item sprite was stored back then. It's from asset-storage).
tweak: earmuffs only require one ear to equip
/:cl:

### CODE REVIEW

**Comment by Humonitarian** [comment]
While funny and I like it, this will introduce a new earmuff meta

**Comment by thevandie** [comment]
We don't know how bad it'll be till people start using them, we can always curb it later if it's an issue.

**Comment by TheShown911** [comment]
What is the downside of earmuffs?

**Comment by Humonitarian** [comment]
> What is the downside of earmuffs?

You can't wear radios, and speech/bullets are slightly quieter.

Iirc it also muffles whispers.

**Comment by TheLeopold** [comment]
Except with that PR you can wear radio

**Comment by hyperioo** [comment]
I'm not against making earmuffs more common but I feel everyone is gonna wear one if it's one-ear only.

> you still have to give up that free extra slot for protection so it's... kinda balanced.

What else can you put on ears? Except dual-headset to have access to more channel (with different encryption keys in both headsets), nothing comes to mind.

**Comment by thevandie** [comment]
Literally any tiny item

**Comment by ValoTheValo** [comment]
> I'm not against making earmuffs more common but I feel everyone is gonna wear one if it's one-ear only.
> 
> > you still have to give up that free extra slot for protection so it's... kinda balanced.
> 
> What else can you put on ears? Except dual-headset to have access to more channel (with different encryption keys in both headsets), nothing comes to mind.

Pills/Syringes with Medicine,  Screwdrivers,  Pack of Cigarettes with a lighter in it,  Penlight (this one is kinda useless tho), Small Cells and i think some other items are what i usally see in ear slots

**Pull request merged**
