### PR TITLE
Buffs internal storage module for RIG's

### PR DESCRIPTION
**Pull request by joookschad**
## About The Pull Request

This essentially brings the internal storage module for RIG's in line with satchels
## Why It's Good For The Game

Not a lot of people use rigs, even after Omni added a way to easily get modules, maybe this will make using rigs less cbt and more fun

## Changelog
:cl: 

balance: internal storage for RIGs is now satchel sized

/:cl:

### CODE REVIEW

**Comment by Wouju** [comment]
Overall good change

**Comment by MLGTASTICa** [comment]
Very good changes , makes hardsuits viable like they are meant to be , bulky and exo-powered suits shouldnt be extremly crappy because of storage size..

**Comment by CeUvi** [comment]
can you put boxes (medkits and so) in storage module now?

**Comment by joookschad** [comment]
> can you put boxes (medkits and so) in storage module now?

yea

**Comment by FortuneMaster** [comment]
nah, they are fine

**Comment by CeUvi** [comment]
> nah, they are fine

no they're not

**Review by Firefox13 — APPROVED** [review]

**Pull request merged**
