### PR TITLE
Remove "breacher" ammo

### PR DESCRIPTION
**Pull request by SirRichardFrancis**
## About The Pull Request

That projectile under specific circumstances may create over 9000 explosions and switch server to turn-based mode or outright kill.
It should go for now.

## Why It's Good For The Game

Dead server is not fun.

## Changelog
:cl:
del: "breacher" .60 ammo
/:cl:

### CODE REVIEW

**Comment by thedarkcrusader** [comment]
Could we. Attempt to fix those 100 mini explosions

**Comment by SirRichardFrancis** [comment]
> Could we. Attempt to fix those 100 mini explosion issue first

We could. But I personally don't like that ammo type at all, so would rather remove it entirely.
SPCR said that they may look into the issue later, but there is no promises.

**Comment by MLGTASTICa** [comment]
I fixed it , this PR is no longer needed . https://github.com/discordia-space/CEV-Eris/pull/6717

**Comment by SirRichardFrancis** [comment]
> I fixed it , this PR is no longer needed . #6717

:ok_hand:

**Pull request closed without merging**
