### PR TITLE
Makeshift melee PR

### PR DESCRIPTION
**Pull request by Sparrowbird611**
## About The Pull Request

Makes the baseball bat into a tool instead of a material weapon.
Adds two new weapons, the junkblade and the bone club.
Also increases the AP on the powerhammer a bit and decreases the degradation on the makeshift mace.

## Why It's Good For The Game

More makeshift equipment is always nice, and material weapons are wacky.

## Changelog
:cl:
add: Adds the junkblade and the bone club. They can be crafted in the crafting menu.
refactor: Made the baseball bat a regular weapon.
/:cl:

### CODE REVIEW

**Comment by Alliostra** [comment]
why is the bone sword better than a regular claymore while being easy to craft?

**Comment by Sparrowbird611** [comment]
> why is the bone sword better than a regular claymore while being easy to craft?

......bone sword?? The bone club is 20 damage 15 AP, the claymore is like 26 damage and 20-26 AP. If you mean the junkblade, it's a downgrade of both the claymore and the katana, taking the damage of a claymore and the AP of a katana.

**Comment by Medcar** [comment]
would be cool if they had on suit sprites

**Comment by Sparrowbird611** [comment]
Er, that was an accidental merge....

**Pull request closed without merging**
