### PR TITLE
Vagabonds can Loadout a toolbelt with makeshift tools

### PR DESCRIPTION
**Pull request by assortedbeads**
## About The Pull Request
Adds a toolbelt option to the loadout
- Gives a toolbelt full of six makeshift tools
- Costs 3 points
- Is restricted to vagabonds

## Why It's Good For The Game
Makeshift tools are rarely made outside of gimmicks because they are worse than normal tools, and the makeshift omnitool is made even less because you have to craft about six different makeshift tools and then craft it.
Makeshift tools are also rarely made because there is zero tool scarcity in the game. Anyone can walk up to the public lathe and print out a full set of tool within 5 minutes.
The toolbelt costs 150 credits. Personally I always buy one, and I've never been in a round where I couldn't find one. 
Still it's useful, so I've given the option a 3 point cost.

It's my hope that people will pick this option as an alternative to printing tools, or to use the tools inside to make a makeshift omnitool.
It's likely they might also just pick it for the free toolbelt but, toolbelts were never scarce in the first place.

## Changelog
:cl:
add: Adds a toolbelt full of makeshift tools to the loadout under utility
/:cl:

### CODE REVIEW

**Comment by TheShown911** [comment]
This is just an automatic pick for every vagabond, with nothing to lose... why?

**Comment by assortedbeads** [comment]
> This is just an automatic pick for every vagabond, with nothing to lose... why?

It costs 3 points which you could use for other stuff like smokes, a flashlight, a uniform, coat

And you're spending 3 points for worse tools, every vagabond already goes to the public lathe to print standard tools, so what's the issue with spending 3 points to get the worse, more limited makeshift ones?

**Comment by TheShown911** [comment]
Yeah, and you get 10 points. Only beneficial thing from them is a crowbar and a flashlight that is required to navigate the ship if it has no power. Cigs and clothes are situational. I don't see why every vagabond should start with a full tool belt.

**Comment by assortedbeads** [comment]
> Yeah, and you get 10 points. Only beneficial thing from them is a crowbar and a flashlight that is required to navigate the ship if it has no power. Cigs and clothes are situational. I don't see why every vagabond should start with a full tool belt.

10 points which run out quickly, I've never not maxxed out my points between taking clothes and utility stuff

You're focusing on the full toolbelt as an issue when toolbelts and tools arent even scarce

Toolbelts cost 150 creds, they are at least 3 and at least 6 vendors that sell them.
They are also in lockers and trash frequently.
Tools are printed from the public lathe for no cost.
The tools this gives you are again, worse than the Free tools you can print for **No Cost** 1-3 minutes after spawning, 5 assuming other people are printing as well.

By choosing this you're actively picking worse tools than what you can get for free, whose only use is rp or making a makeshift omnitool, which is again worse than just having a tool belt with basic tools.

Or is it the point cost you dont like? Because makeshift tools are shit without very high mech

**Comment by TheShown911** [comment]
I don't understand how tools can be used for "RP", they are tools with a clear gameplay benefit. Normal tools aren't scarce yes, but they still cost materials to build. 150 credits is around 20% of the starting cash of a vagabond, depending on RNG.
Besides, the loadout is not meant to give players any gameplay advantage, just the essentials and different clothes to customize your character. I never get to 10 points in the loadout as I only use it for a crowbar and a flashlight, as that is all you need to play vagabond.

**Comment by assortedbeads** [comment]
> I don't understand how tools can be used for "RP", they are tools with a clear gameplay benefit. Normal tools aren't scarce yes, but they still cost materials to build. 150 credits is around 20% of the starting cash of a vagabond, depending on RNG.
> Besides, the loadout is not meant to give players any gameplay advantage, just the essentials and different clothes to customize your character. I never get to 10 points in the loadout as I only use it for a crowbar and a flashlight, as that is all you need to play vagabond.

Normal tools cost metal and plastic at most.
Lockers are 10 steel, chairs are 1-5, tables are plastic and steel, scrap recycles into steel, you find sheets on tables and racks, walls are made of steel.
Unless you actively refuse to go in the tunnels for 2 minutes you will always have steel to use

As a vagabond you'll never not have enough for a toolbelt and mesons, what else are you buying? Extra cash comes from selling to guild if you really need to, Ive gone several round without needing to.

Using a loadout for 2 items is fine and your choice, but everyone else picks clothing options because they like customizing their dolls.

**Comment by TheShown911** [comment]
Yes, loadout SHOULD be used for cosmetics and customization, not items with clear benefits, with exceptions of essentials. You shouldn't have a choice of looking better or being stronger round start.

Steel and plastic are common materials? Yes, but does that mean we should give the autolathe an infinite supply, as it's always only a table or a locker away? No. Getting and managing materials is still part of the vagabond gameplay.

Also I don't see how this fixes the problem of good quality tools being available round start, and "always" being printed by vagabonds. This makes it even easier in fact, by providing a free toolbelt and free materials you can recycle from your old tools to make new ones.

**Comment by DiaFRAME444** [comment]
The more I look at this the more I think vagabonds should just start with all the makeshift tools.

**Comment by assortedbeads** [comment]
> The more I look at this the more I think vagabonds should just start with all the makeshift tools.

I was tempted to do that but then I ran into the issue of storing them when you spawn

Considered making a toolbelt offshoot that only stored makeshifts but that'll need a different sprite, which means sprite approval.

I guess a duffel/backpack could work but eh

**Comment by garrulousTeamotei** [comment]
If you want to fix the who free 150 credit toolbelt (I mean, cigs cost 100 credits, and what, have a point cost of 1?) You could go with an engineering Hardcase instead (can be made by the basic tool disk) or its makeshift version instead.

**Comment by assortedbeads** [comment]
> If you want to fix the who free 150 credit toolbelt (I mean, cigs cost 100 credits, and what, have a point cost of 1?) You could go with an engineering Hardcase instead (can be made by the basic tool disk) or its makeshift version instead.

Oh damn I didnt consider that, yeah Ill check out the hardcase storage

**Comment by SirRichardFrancis** [comment]
> Oh damn I didnt consider that, yeah Ill check out the hardcase storage

Nooooo it's whole 20 steel!! Why not add takeshi in loadout next!!

The maintainers don't want you to know, but tools from public lathe are free, require twenty times less effort to make and ~70% better than makeshift ones. I have 458 tools in my vagabond den.

image

Jokes aside, only reason anyone would ever go trough the trouble of making a makeshift set, is when they want to roleplay some kind of scrapper, junkborn or some such. What fucking balance impact you're seeing here, holy shit.
Vagabonds can get a cigar pack, that worth more than their entire starting cash for 2 points. Balance issue much?

**Comment by ErisMeleeEnjoyer** [comment]
As a TRUE REAL ABSOLUTE vagabond main, I can confirm that we, in fact, have a LOT of stuff to spend points on, and three points for a toolbelt with MAKESHIFT tools is a good idea, and a good trade.

> Only beneficial thing from them is a crowbar and a flashlight that is required to navigate the ship if it has no power.

Maintenance is dark and needs a weapon like a crowbar to reliably explore. Play the game.

> Cigs and clothes are situational.

Cigars give sanity boost, while some clothes slightly increase your style. Play the game.

> Not items with clear benefits, with exceptions of essentials. 

Cigars and zippos, flasks, a clown outfit, a WHEELCHAIR are all in loadout. Play the game.

> Normal tools aren't scarce yes, but they still cost materials to build.

They are free in the autolathe that has around 100 steel sheets roundstart. There is no reason nor any incentive to use makeshift ones as result. Play the game.

> I never get to 10 points in the loadout as I only use it for a crowbar and a flashlight, as that is all you need to play vagabond.

We literally have style over substance as a game mechanic, yet instead of picking any cosmetic you go with THE THINGS THAT GIVE YOU CLEAR BENEFITS. ????? YOUR PDA HAS A BUILT-IN FLASHLIGHT. THEN WHY ARE YOU PICKING ONE IN LOADOUT? WHY ARE YOU SAYING THAT LOADOUT SHOULDN'T HAVE ANYTHING WITH MECHANICAL BENEFITS IN IT THEN WHY ARE YOU MENTIONING CROWBAR AND FLASHLIGHT IN THE SAME BREATH?

> You shouldn't have a choice of looking better or being stronger round start.

...

**Comment by assortedbeads** [comment]
So is your issue the toolbelt or the tools

**Comment by maikilangiolo** [comment]
I agree with shown, honestly I'm feeling half of the PRs being made are just to skip inconveniences or minor setups so you can junk faster or more easily, or whatever people do in 5 hours that makes the ship feel empty.
What's next, vagabonds spawn with a free makeshift revolver?

**Comment by assortedbeads** [comment]
It's laughable that you think anyone will willingly junk with a junk shovel

**Comment by maikilangiolo** [comment]
Yeah it fits more tool mods from he get go. It's better than the normal one because you can stack up all the common tool mods for speed.

**Comment by assortedbeads** [comment]
Assuming you find the other tool mods when you can just put them on a better tool for max speed

But hey, keep pretending that junktools are some kinda sleeper hit or stealth op tool

**Comment by SirRichardFrancis** [comment]
> I have played the game more than probably anyone here.

image

:mitosis:

image

**Comment by maikilangiolo** [comment]
Huh? Why would I be pretending? I just said this is just a PR that skips minor inconveniences for the benefit of one person or two. As well as giving all the tools to immediately make a makeshift omnitool, which is bypassing the time expenditure and effort it's supposed to require. If it takes 5 minutes to print all the tools, it also takes 5 minutes to make a makeshift omnitool, it's not that difficult.

**Comment by TheShown911** [comment]
> > I have played the game more than probably anyone here.
> 
> image
> 
> :mitosis:
> 
> image

The game, as in, eris.
Also foolish to assume i would ever reveal my first account (:

**Comment by TheShown911** [comment]
> So is your issue the toolbelt or the tools

My issue is the concept of the PR, I don't think loadout is something to be used for convenience but either for necessity or for looking good in game (not the style mechanic).
Maybe that's just me and my old way of thinking, you can still get approval from others.

**Comment by Firefox13** [comment]
Loadout is reserved for either very basic essentials (Neotheology book, flashlight&crowbar) or for customization/clothing.
Tools is a bit too much.

**Pull request closed without merging**
