### PR TITLE
Fix dieth pot buff, and add data disks and mortar

### PR DESCRIPTION
**Pull request by Autisem**
## About The Pull Request
Hot fix the potency plant issue, aswel as adding data disks and a mortar for hydro to use

ALSO now adding the bee stuff so people can experiment with it

## Why It's Good For The Game
Fixed a bug, add the data disks they need and gave them a pedestsel so they can grind there own plants

Also bees might be a fun side project for hydro until bees can be implement more usefully, get people to know it

## Changelog
:cl:
add: data disks to hydro
add: mortar to hydro
add: bee stuff to hydroponics
fix: diethlymine will now boost the plant stats properly
/:cl:

### CODE REVIEW

**Comment by TorinoFermic** [comment]
There's fuckload of lines changed for the map.

**Comment by Autisem** [comment]
> 
> 
> There's fuckload of lines changed for the map when compared to the current master.

Indeed, no idea what caused it though. I might redo this PR without any map fuckery

**Comment by Kurgis** [comment]
DreamMaker does not like the tdm format, and will revert it. Use the Mapmerger tools in the tools folder, or alternatively, text edit the map.

**Comment by SpadesSlick** [comment]
Will this PR be fixed?

**Comment by drexample** [comment]
@Autisem This PR will be closed in 7 days.

**Pull request closed without merging**
