### PR TITLE
Better shelter 2: Bluespace boogaloo

### PR DESCRIPTION
**Pull request by TheLeopold**
## About The Pull Request
Resurrection of #8111
If no ghosts signed up for a disciple, Last shelter will teleport existing cruciforms. It will also rip cruciforms off of dead **unrevivable** bodies.
Cruciform should not be inside one of blacklisted containers/machines (generally ones that can destroy cruciform) or in someone's inventory

Removed "Search" litany
Added proc to check if atom is inside one of selected things

Special thanks to Humon, Handy and MLGTASTICa.

## Why It's Good For The Game
Last Shelter matches description.
Allows that gibbed cruciformed technomancer in the dark corner of engimaint to be saved.
Guys whose whole shtick is being immortal now harder to kill.

## Testing
cruciform on the floor, floor/bag, floor/bag/box, locker/bag/box, in hand, in pocket, in my bag, in my bag/box, locker/my hands, locker/my bag/box, every blacklisted machine, dead body, live body, hands of dead body
killed and resuscitated disciple, deleted disciple, deleted cruciform

## Changelog
:cl:
balance: last shelter will teleport existing cruciforms if no ghost found
code: added is_inside proc
del: Search litany (now partly covered by Last Shelter)
/:cl:

### CODE REVIEW

**Comment by TheLeopold** [comment]
Testmerge this or no balls :catgun:

**Comment by Firefox13** [comment]
> Makes Last Shelter behave as expected.

Its intended purpose is to provide church with new blood, not serve as a sethome location.

> Allows that gibbed cruciformed technomancer in the dark corner of engimaint to be saved.

Make search lithany target cruciforms (with a ckey attached, so it doesn't target ones in the church for baptism)

**Comment by DiaFRAME444** [comment]
This does follow Reere's document idea of letting NeoTheology members teleport lost cruciforms. In fact its actually weaker, since in his version requires the Last Shelter and his doesn't.
Although,

> Removed "Search" litany

Seems unneccessary.

**Comment by Humonitarian** [comment]
@Mycah142

**Comment by TheLeopold** [comment]
> Its intended purpose is to provide church with new blood, not serve as a sethome location.

Maybe.
But when description literally says: "Powerful scanner that **can teleport a cruciforms** of pilgrims lost in this sector of space."
One would expect it to actually teleport actual cruciforms.

**Comment by Firefox13** [comment]
Well changing the whole way an artifact works (that impacts balance very much) because you got confused on how it works is kinda ~~gay~~ over-the-top, don't you think?

"Search" lithany is already powerful enough, both to find dead (to rescue) and living (for shits and giggles). If someone went through the trouble of cutting cruciform out then they deserve guarantee of that person being death - same deal of beheading people.

**Comment by ValoTheValo** [comment]
good PR, finally makes the last shelter feel finished and not half assed

**Comment by assortedbeads** [comment]
> Well changing the whole way an artifact works (that impacts balance very much) because you got confused on how it works is kinda ~~gay~~ over-the-top, don't you think?
> 
> "Search" lithany is already powerful enough, both to find dead (to rescue) and living (for shits and giggles). If someone went through the trouble of cutting cruciform out then they deserve guarantee of that person being death - same deal of beheading people.
> 

Naw when it comes to The Immortality Faction they should be extremely hard to kill and keep dead short of atomizing the cruciform, sending it to deepspace or something equally drastic.

Plus beheading people isnt a guaranteed death, we stitch heads on bodies and revive them almost every launch

**Comment by TheLeopold** [comment]
> because you got confused on how it works is kinda ~gay~ over-the-top, don't you think?

I think that making thing's behavior match its description is right.

Otherwise its description should be changed to something like "Serves as a beacon for cruciforms sent from New Rome" or something. And that **is** gay.

**Comment by DiaFRAME444** [comment]
> I think that making thing's behavior match its description is right.

You edited the description.

**Comment by ValoTheValo** [comment]
the item whos purpose is to find lost cruciforms in middle of nowhere should find lost cruciforms in middle of nowhere.

**Comment by TheLeopold** [comment]
> the item whos purpose is to find lost cruciforms in middle of nowhere should find lost cruciforms in middle of nowhere.

That

**Comment by null-Aurelian** [comment]
Dumb idea, but would it be good if it was a device that "consumes" cruciforms and spawns inhabited ones? So rather than pulling cruciforms it pulls the soul into an existing cruciform

**Comment by Goofyclark** [comment]
I was just wondering, what If there was an easy-ish way to prevent cruciforms from being effected by this, like using some tools on it. That way, if the the person was intentionally killed, it wouldn't be that hard to keep their cruciform hidden away, but if they just died from roaches in maints you could just teleport them back to the church.

**Comment by DiaFRAME444** [comment]
> what If there was an easy-ish way to prevent cruciforms from being effected by this

Like keeping it in your backpack, or melting it in any autolathe if you want to get rid of the evidence?

**Comment by Goofyclark** [comment]
> > what If there was an easy-ish way to prevent cruciforms from being effected by this
> 
> Like keeping it in your backpack, or melting it in any autolathe if you want to get rid of the evidence?

I was thinking more like using a screwdriver and multitool on it to disable the teleportation, so the cruciform can still be manually recovered and fixed (Although "hacking" a cruciform with some basic tools might not fit in lore-wise)

**Comment by DiaFRAME444** [comment]
NT would rather kill everyone within a 10 kilometer radius before ever allowing someone to "screwdriver" into the cruciform.

As I said, disabling cruciform teleportation is more than easy.

**Comment by Humonitarian** [comment]
DevDel here and I approve this PR. The ways to counter this (inventory, blacklisted storage) are sufficient in my opinion to satisfy the balance criteria.
Valo, an admin, also supports this PR.

On this basis, I request this be approved @Firefox13

**Review by Humonitarian — APPROVED** [review]
Discussed with project lead, we decided to try this change. Design is approved for live merge.

**Review by hyperioo — COMMENTED** [review]
I am wondering about two points:
* When `death` is called, the cruciform is added to `lost_cruciform`, yet if the guy is revived with chemicals it will stay in that list. It's only removed from the list if the person is revived through NT ritual.
* Might have to add a smol check in `get_cruciform` because if a disciple dies and the cruciform get qdeled in the meantime, you will have a null in `lost_cruciform`. So if `var/obj/item/implant/core_implant/picked = pick(cruciforms_temporary)` choses it, then it will runtime trying to call `null.is_inside` (except if qdeletion checks all list globally to remove the reference everywhere, not sure)

**Comment by TheLeopold** [comment]
> I am wondering about two points:
> 
>     * When `death` is called, the cruciform is added to `lost_cruciform`, yet if the guy is revived with chemicals it will stay in that list. It's only removed from the list if the person is revived through NT ritual.
> 
>     * Might have to add a smol check in `get_cruciform` because if a disciple dies and the cruciform get qdeled in the meantime, you will have a null in `lost_cruciform`. So if `var/obj/item/implant/core_implant/picked = pick(cruciforms_temporary)` choses it, then it will runtime trying to call `null.is_inside` (except if qdeletion checks all list globally to remove the reference everywhere, not sure)

I'll look into that when I get free time (not soon).

**Comment by TheLeopold** [comment]
> * Might have to add a smol check in `get_cruciform` because if a disciple dies and the cruciform get qdeled in the meantime, you will have a null in `lost_cruciform`.

If I instead clear nulls from the list before picking the cruciform, will it suffice?

**Comment by TheLeopold** [comment]
Updated

**Comment by TheShown911** [comment]
Sure hope this works!

**Pull request merged**
