### PR TITLE
Minor Gun nerf

### PR DESCRIPTION
**Pull request by zombiemimic**
## About The Pull Request
Done in line with documentation.

## Why It's Good For The Game
lessens people's dependance on firearms

## Changelog
:cl:
tweak: tweaked gun balance
/:cl:

### CODE REVIEW

**Review by SirRichardFrancis — APPROVED** [review]
Nothing to see here citizens, move along.

**Comment by Kegdo** [comment]
HAHAHAHAHA
THIS IS EXACTLY WHAT I DREAMED OF
FINALLY, MELEE IS VIABLE!

**Comment by Jan-Blasiak** [comment]
Nothing sussy over yonder.

**Comment by MLGTASTICa** [comment]
Finally , stamina combat.

**Comment by garrulousTeamotei** [comment]
The melee buff we all needed.

**Review by hyperioo — APPROVED** [review]
It is indeed a minor gun nerf.

**Pull request merged**
