### PR TITLE
AMR good: changes to .60 and buffs to AMR

### PR DESCRIPTION
**Pull request by maikilangiolo**
## About The Pull Request
.60 stats got nerfed, since there is talk of a future HMG using .60 and it shouldnt do AMR damage. to compensate, amr got 2x damage mod and extra damage so its slightly less shit (seriously, buckshot was better than the AMR). Hitscan was given to the AMR by setting the step delay to 0, as per humon's suggestion.

PR in preparation of a new makeshift gun PR, and needs #7546 to work since refactor of gun assembly. 

## Why It's The Game
AMR no more shit, .60 can be used in other guns without being too broken.

## Changelog
:cl:
balance: rebalanced .60 stats. AMR stats changed accordingly and buffed
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
>nerfs damage to half.

**Comment by maikilangiolo** [comment]
> > nerfs damage to half.

aha checkmate! as I already told you in discord, it was buffed. amr damage went 65 -> 72 (because 18x2x2 is more than 33x2). now it does more damage than a buckshot shotgun!

**Comment by Firefox13** [comment]
> since there is talk of a future HMG using .60 and it shouldnt do AMR damage

this sounds like a terrible idea

**Comment by maikilangiolo** [comment]
> > since there is talk of a future HMG using .60 and it shouldnt do AMR damage
> 
> this sounds like a terrible idea

I am not who wanted to add it. The nerf makes possible to have guns using an AMR barrel without being broken OP. AMR bullet is a slightly weaker slug that has higher pen and velocity. The makeshift shotgun and the Bancroft in #7548 require the .60 base nerf. Plus, this PR makes the AMR slightly less shit, with some deserved damage improvements.

**Review by TheShown911 — COMMENTED** [review]
I have no clue what any of these numbers mean.

**Comment by maikilangiolo** [comment]
> I have no clue what any of these numbers mean.

tl:dr makes the .60 base ammo do less damage than slugs, but keeping faster than normal bullets (0.8 delay) and high AP. The AMR, with the 2x damage bonus and proj step mult = 0, does 70 something damage (a slight buff) and is still hitscan

**Pull request merged**
