### PR TITLE
Tweak firemodes of AK-47

### PR DESCRIPTION
**Pull request by BASIC-BIT**
- Remove 3 round burst from AK-47
- Add Full Auto (400 RPM) to AK-47

I feel as these are the more "iconic" AK-47 mechanics - Safe, Semi-Auto, and Full Auto.  Obviously this isn't important but why not try ¯\\\_(ツ)\_/¯

### CODE REVIEW

**Comment by Keekenox** [comment]
Fuck yeah.

**Comment by RandomColonist** [comment]
AK-47 supposed to be in line with Sol being carbine rather than AR. That was discussed with project leader and can't be merged without his allowance. My personal suggestion: either just rise up price of AK or add auto-fire to Excelsior AK only without removal of three - round burst, rising price of only Exc AK.

**Comment by BASIC-BIT** [comment]
Yeah, I really should have labelled this PR as a suggestion and not a real "tweak" - It would also maybe be interesting to use "short burst" rather than "3 round burst" - "3 round burst" implies a gun mode, while "short/long burst" imply manual trigger control.

**Comment by SpadesSlick** [comment]
Outdated due #3453.

**Pull request closed without merging**
