### PR TITLE
New ammo

### PR DESCRIPTION
**Pull request by infraredbaron**
## About The Pull Request
In short - will make cargo even more important for gun-conomics.

- cleaned up most unused icons;
- changed their names to appropriate ones;
- gun disks now come with nonlethals only;
- added separate disks for each caliber will all ammo boxes and packets (except HV, for sure);
- each gun now have 4 different ammo types: Lethal, Practice, High-Velocity and Rubber (except shotguns and .60 Antimaterial);
- added missing mags to each caliber;
- reintroduced ammo packets for all ammo types - .35, .40, .20, .25, .30;
- buffed ammo boxes to 240 and ammo packets to 60;
- IH Wintermute now use general .20 mag;
- .20 mags have new icon;
- Changed .20 mag to straight and reduced ammo to 20, per request;
- introduced new HV ammo to uplink;
- new shotgun ammo type - incendiary;
- incendiary ammo accessible in RnD;

## Screenshots
<details>
  <summary>Expand</summary>

unknown

unknown (1)

</details>

### CODE REVIEW

**Comment by infraredbaron** [comment]
Added incendiary ammo to RnD, per request;
Reduced number of new ammo disks to two;
Removed stun, ion, laser shells completely;
Removed all short mags from the game, changed capacity of .20 mag to 20, per request;
Deleted unused ammo;
Fixes wrong gun on moebius disk;

**Comment by SpadesSlick** [comment]
Incendiary must be a shotgun only.

**Comment by Kurgis** [comment]
> cleaned up most unused icons;

Due to the number of icon states which have been changed on existing icons, it's near impossible to tell which is a deleted sprite, or a sprite which was assigned to a different icon. Would you be able to list the sprites removed?

**Comment by infraredbaron** [comment]
It would be far easier to tell which ones are left:
pistol, both revolver, magnum .25 and .30 ammo remain the same;
.20 gets new sprite, which was unused since caliber reduction;
rest goes into the trash

**Pull request merged**
