### PR TITLE
Remove FBP

### PR DESCRIPTION
**Pull request by Evankhell561**
## About The Pull Request

this feature was introduced in an inatomical pr that was supposed to allow players to create their own prosthetics. 
On its own, the FPB has many gameplay implications and has not been considered in that pr and there is no one working on making it work harmoniously with the rest of the game.

At the moment this feature is mostly a constant source of bugs that need to be fixed constantly. On the other hand, in our design document we have a race that is supposed to do the function that the FBP wants to occupy.

#5779

## Changelog
:cl:
del: FBP
/:cl:

### CODE REVIEW

**Comment by TheShown911** [comment]
Does this work?

**Comment by Evankhell561** [comment]
> Does this work?

that's all ROBO introduced in his pr, additionally I don't find that this pr broke anything.

**Comment by SaltyOldBull** [comment]
Yeah no, I'll have to at least say my piece here.
I agree, giving Moebius the FBP as they were was the first mistake (good armor, no ability to feel pain, limbs that do not explode upon taking damage greater than their health pool), the second was insisting on it by changing everything else instead of straight-up removing them before fixes. However, just as how no people are working on fixing their quirks and making them better suited to the game, there are equally no people working on the race that is supposed to be occupied by the FBP in the kot map itself.

I'll say this change is premature at best, seeing as the FBP could well be taken as the temporary measure they were meant to be in the first place until that robot-human race is being actively developed. The second being that the issues that made people complain about FBPs as they were before nerfs are intrinsic to both the player base and the broken ass nature of the pain system, Moebius players will continue to powergame and the pain system will still be broken unless it gets a rework, which brings me to my third point.

The robot-human race will fill the same functions as FBPs, meaning it will be immune to pain, it will be very scuffed at early implementations and it most definitely will cause loads of salt and powergaming in equal measures (seeing as how vagabonds are also meant to have access to it); as it stands the FBP post-nerfs and fixes is a differently colored skin for your character with some different mechanics, the same thing which will invariably happen to the new race upon meeting the player base.

The final point being, the FBPs are largely harmless now and have done comparatively a lot less damage to overall balance than the loot reworks themselves, the only difference being the junk is still receiving attempts at being fixed. 

There is no inherent need to remove FBPs right now at this moment.

**Comment by Evankhell561** [comment]
> Yeah no, I'll have to at least say my piece here.
> I agree, giving Moebius the FBP as they were was the first mistake (good armor, no ability to feel pain, limbs that do not explode upon taking damage greater than their health pool), the second was insisting on it by changing everything else instead of straight-up removing them before fixes. However, just as how no people are working on fixing their quirks and making them better suited to the game, there are equally no people working on the race that is supposed to be occupied by the FBP in the kot map itself.
> 
> I'll say this change is premature at best, seeing as the FBP could well be taken as the temporary measure they were meant to be in the first place until that robot-human race is being actively developed. The second being that the issues that made people complain about FBPs as they were before nerfs are intrinsic to both the player base and the broken ass nature of the pain system, Moebius players will continue to powergame and the pain system will still be broken unless it gets a rework, which brings me to my third point.
> 
> The robot-human race will fill the same functions as FBPs, meaning it will be immune to pain, it will be very scuffed at early implementations and it most definitely will cause loads of salt and powergaming in equal measures (seeing as how vagabonds are also meant to have access to it); as it stands the FBP post-nerfs and fixes is a differently colored skin for your character with some different mechanics, the same thing which will invariably happen to the new race upon meeting the player base.
> 
> The final point being, the FBPs are largely harmless now and have done comparatively a lot less damage to overall balance than the loot reworks themselves, the only difference being the junk is still receiving attempts at being fixed.
> 
> There is no inherent need to remove FBPs right now at this moment.

I could argue one thing or another but I made this pr to carry out the intentions of some players, maintainers should judge it based on feedback from the community (including you).

**Comment by Omni44** [comment]
This is very much necessary. Idea of FBPs as they are was divorced from any plans for the game to begin with and actively invaded space desiganted for these things. It doesn't necessarily matter if there's nobody to work on these plans right now, it should be up to debate among community and developers' consideration whether to change these plans from kotmap, not game of "who gets there first".
FBPs were extraordinarily broken balance  wise, at the release, and subsequent bandaid rebalance efforts in order to just try to make these things work reasonably (at least balance wise, apparently code wise they are still bugged six days to sunday)  has screwed over all people using prosthetics and led to some absurdities that go completely counter to what prosthetics offered to begin with. effectively nullifying any advantages they had.
This has outlived its opportunity to show that it's net benefit to the game as it is. I personally also do not consider it fitting aesthetic as well. The only downside to removing this that I see as noteworthy is depriving content starved technos of minor feature, sad but just sacrifice.
It's just too much problems and hussle than it's worth, in short.

**Comment by driecg36** [comment]
I know FBPs were (and in some ways still are) overpowered and powergamer bait, but I am still adamantly against removing them. A massive premise of the server - where augmented humans duke it out against fundamentalist body purists - has had the former MASSIVELY neglected for years, only getting a handful of moderately useful augments that are entirely monopolized by moesci and cyberlimbs that were worse than human ones. We finally get something that itches that transhumanist itch that the server so desperately need it, and because cringe moebius powergamers abuse them we have to remove it completely? You'd be better off nerfing RnD printing and maint loot if you wanted to nerf that flavor of powergamer. 

FBPs are absolutely not perfect in the current state, I will concede that much. However, I still think that they are a correct step in fleshing out the server and should not be simply thrown out because of what are purely temporary balance concerns.

**Comment by Omni44** [comment]
In what world were prosthetics ever (before FBPs) worse than human limbs, let alone worse than they are now? FBPs had seen prosthetics all nerfed to the ground just to hamfist this thing into game for dubious reasons without it being go-to choice for being invincible. There are few implants across the server, that I will give you, but that's hardly related. You could always try to code some more. There's at the same time, no need to resign from FBPs forever (even though I am not fond of them as an idea), ut this incarnation is broken, simply and plainly, and has done more wrong than good.

**Comment by driecg36** [comment]
Prosthetics that malfunction at extremely low damage thresholds (always have, and it was even worse long ago before FBPs were added), which don't work with many of the very powerful chem cocktails we have now, were absolutely much worse than vanilla limbs even with decent mech skill. It just meant you had to carry both tools to fix the metal parts and meds to fix the fleshy parts. With poor mech skill, FBPs and prosthetics are still worse than flesh limbs.

**Comment by basedcringe** [comment]
FBPS at the moment have a whole lot of weaknesses and I feel this should be a complaint against augments themself as that is what atleast I see as making them strong as an in augmented FBP is very weak

**Review by MadmanMartian — CHANGES_REQUESTED** [review]
What about the groins?

**Review by MadmanMartian — CHANGES_REQUESTED** [review]
To properly remove the FBPs, you should be looking at code/modules/organs/body_modifications.dm, change the body_parts from ``body_parts = list(BP_L_ARM, BP_R_ARM, BP_L_LEG, BP_R_LEG, BP_CHEST, BP_GROIN, BP_HEAD)
`` to ``body_parts = list(BP_L_ARM, BP_R_ARM, BP_L_LEG, BP_R_LEG)``

**Comment by Evankhell561** [comment]
> To properly remove the FBPs, you should be looking at code/modules/organs/body_modifications.dm, change the body_parts from `body_parts = list(BP_L_ARM, BP_R_ARM, BP_L_LEG, BP_R_LEG, BP_CHEST, BP_GROIN, BP_HEAD) ` to `body_parts = list(BP_L_ARM, BP_R_ARM, BP_L_LEG, BP_R_LEG)`

Thank you, I will take care of it depending on whether it is decided to approve this suggestion.

**Comment by machinedDesign** [comment]
let us hack them. self punching protocols/remote control enabled

**Comment by TheShown911** [comment]
FBPs are going to be updated, not removed, so this PR can be closed.

**Pull request closed without merging**
