### PR TITLE
Harpoon nerf beta

### PR DESCRIPTION
**Pull request by MadmanMartian**
## About The Pull Request

Attempting to jump into a wall will now telefrag you.

## Why It's Good For The Game

I was informed that you can, indeed, just jump onto a wall then teleport to either of the rooms that wall is part of.

This should prevent some illicit access from being gained with it.

I elected to not have it telefrag others than the user, as you can just build a wall on the turf you're on and bring others in, telefragging them.

## Changelog
:cl:
balance: Using the Harpoon to teleport onto a wall now telefrags you.
/:cl:

### CODE REVIEW

**Review by genessee596 — CHANGES_REQUESTED** [review]
Make the teleport just fail if the user attempts to teleport another person into a wall to prevent tag-team cap-spare rushes.

Additionally, make the harpoon not work if you can see the tile through mesons alone.

**Comment by MadmanMartian** [comment]
The teleport already fails if you can only see the tile via mesons. That report was false.

**Comment by genessee596** [comment]
Oh, then just go ahead and do the first suggestion, sorry bout that

**Comment by drexample** [comment]
YES!

**Comment by MadmanMartian** [comment]
gotta rework it a little more

**Review by TorinoFermic — APPROVED** [review]

**Review by genessee596 — APPROVED** [review]

**Review by mattroks101 — APPROVED** [review]

**Pull request merged**
