### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Wesreidau**
Hivemind dialog, mob names and descriptions by request.

### CODE REVIEW

**Comment by ACCount12** [comment]
It looks like someone force-pushed development branch at some point. Mind reopening this PR without all this mess of conflicts and suffering?

**Comment by Wesreidau** [comment]
> It looks like someone force-pushed development branch at some point. Mind reopening this PR without all this mess of conflicts and suffering?

No idea how.

**Comment by ACCount12** [comment]
You are not familiar with git, right? If not, it would be easier for me to open a new PR with your changes.

**Comment by ACCount12** [comment]
This PR is now a shining example of why you shouldn't force push branches anyone else might be working on.

**Pull request closed without merging**
