### PR TITLE
Make melee damage scale with limb efficiency

### PR DESCRIPTION
**Pull request by hex37**
## Why It's Good For The Game

Melee needs a nerf, and this allows it to hit as hard as it always has... Until someone's arms take damage.

## Changelog
:cl:
tweak: Causes the damage dealt by a melee attack to scale based on limb efficiency (And by extension, the amount of damage someone's arms has taken)
/:cl:

### CODE REVIEW

**Comment by Alliostra** [comment]
The remarks about melee needing a nerf were sarcastic, you know?

**Comment by Wouju** [comment]
>get shot several times in the arm
>rip it off, replace with healthy arm pulled out of satchel
>keep shooting

jokes aside this is a terrible idea, worse than my hivemind PRs

melee never needed a nerf

**Comment by MemedHams** [comment]
:confused:
If this had fun scaling and was a little less "being shot in the arm smashes your melee power down to like 25% instantly" I might be a little more behind it- but no, having a bunch of extra muscles layered on will do absolutely nothing due to it being capped at normal. 
Melee is already pretty much outmoded due to the reality of "I have a gun, you are standing over there, you are dead before you arrive at my position", we don't need to also reduce it's efficiency by the time the idiot using it walks through the hail of bullets to their target.

**Comment by hex37** [comment]
@MemedHams @Wouju @Alliostra 

Don't know if you all realize hard it is to decrease limb efficiency. It isn't calculated by the brute damage on the arm- it's internal. 

You have to do enough damage to your muscles, nerves, and bones that the _average damage to all of them_ is significantly impacted. I've seen people killed by explosions who could easily still swing a hammer.

**Comment by Alliostra** [comment]
doesn't change the fact that melee does absolutely not need to be nerfed.

**Comment by Wouju** [comment]
> You have to do enough damage to your muscles, nerves, and bones that the _average damage to all of them_ is significantly impacted. I've seen people killed by explosions who could easily still swing a hammer.

Okay, and? The main disadvantage of melee weapons is the fact you need to close the distance, not to mention the fact that missing your hit (by accidentaly hitting the floor instead of the enemy for example) allows the guy to get a distance from you, whilst doing virtually nothing yourself

This is a terrible idea, a terrible salt PR, and there is no reason to have this accepted and merged.

**Comment by Humonitarian** [comment]
clamp the value between 1 and 2

**Comment by Humonitarian** [comment]
> It's a shame how this probably won't go through, Eris is probably the only action-focused server with actual consequences for being shot that isn't HRP. This makes melee more useful for ambuses on people who aren't paying attention which makes a ton more sense then melee being viable as your go-to tactic.

The problem with that is that melee _already is not viable as a go-to tactic_
Guns are king, that hypersaw won't do nothing unless you close the distance.
Even in raw damage output, a revolver can outdo the majority of melee weapons.

**Comment by githubuser4141** [comment]
> 

I mean, is that necessarily a problem? It's about picking your battles, not engaging in a ranged fight if you don't have a ranged weapon. If you charge down a hallway at someone who's aiming at you and die that's on you really? OTOH I/other people have died numerous times in heavy armor w/ a gun to melee users once they're up close, and I've seen people in fully-kitted combat mechas die to dudes with NT swords and basic armor if they get up close.

**Comment by MemedHams** [comment]
> > 
> I mean, is that necessarily a problem? It's about picking your battles, not engaging in a ranged fight if you don't have a ranged weapon. If you charge down a hallway at someone who's aiming at you and die that's on you really?
> 
> On the other hand I/other people have died numerous times in heavy armor w/ a gun to melee users once they're up close, and I've seen people in fully-kitted combat mechas lose to dudes with mid-range (NT swords, katanas, etc) melee weapons.

The "I've died with heavy armor to people who are using melee" is kind of a skill issue, if I'm being honest- When you see someone with a melee weapon, you can just pedal backwards and fire in their direction to effectively hard counter them, unless they're right in your face and tilestrafing(this satisfies the conditions of "ambush" or otherwise extraneous situation, though, since they had to get there somehow)

Alongside this, as much as "ahahah realism do not bring a knife to a gunfight" is a thing, we also are playing a videogame, and putting balance in a position where "All combat must be done via picking battles, if you are fighting a ranged opponent you must fight them at range or die" does a disservice to the variety and interest of our combat- better if you have to adapt to multiple types of opponents than if every fight is a slog of two people strafing while firing at each other in an open hallway.

Look, we literally have mechanics that allow people to gain a recharging shield against ranged attacks based on how much drip they're wearing. Realism is already out the window, we're focusing on gameplay quality and feel.

Also, the combat mecha thing is just an issue with mechs- you can reliably destroy a mech with a .35 giskard without them being able to effectively defend themselves, because mechs continue to be awful.

**Comment by githubuser4141** [comment]
You absolutely cannot reliably destroy a combat mech with a .35 giskard, though, on account of it doing approximately 3-5 damage. A wrench will probably cap out at 1-2 damage per hit while the mech can strafe and reverse and hit back for 60 damage a punch.

It's probably a skill issue but you can't pull that in every argument or nothing would happen. Melee is very effective if you're able to close the distance via either mechanical skill or talking them into it which unfortunately requires them to have some sort of social interest. 'IRL' someone with a knife can actually stab a gun user if they're incompetent or caught unaware or don't manage to hit a vital organ, sure. I dunno, I'm probably biased but when everyone's toting automatic rifles I think if you manage to pull off a melee build it should be something to be proud of.

**Comment by Humonitarian** [comment]
> You absolutely cannot reliably destroy a combat mech with a .35 giskard, though, on account of it doing approximately 3-5 damage. A wrench will probably cap out at 1-2 damage per hit while the mech can strafe and reverse and hit back for 60 damage a punch.
> 
> It's probably a skill issue but you can't pull that in every argument or nothing would happen. Melee is very effective if you're able to close the distance via either mechanical skill or talking them into it which unfortunately requires them to have some sort of social interest. 'IRL' someone with a knife can actually stab a gun user if they're incompetent or caught unaware or don't manage to hit a vital organ, sure. I dunno, I'm probably biased but when everyone's toting automatic rifles I think if you manage to pull off a melee build it should be something to be proud of.

Reminder that in general guns have more damage, and especially, way more penetration. Your argument is therefore nil.

Also the strongest mech armor has 80 bullet protection, against 34 bullet damage and 8 AP. That means, quite shortly, that a giskard will deal 7.2 damage per shot, despite the horrible statistics. For comparement, a venger has 26.4 damage and 20 AP, resulting in 7.3 damage per shot.

This same mech armor has **_85 melee protection._**

**Comment by githubuser4141** [comment]
> Also the strongest mech armor has 80 bullet protection, against 34 bullet damage and 8 AP. That means, quite shortly, that a giskard will deal 7.2 damage per shot, despite the horrible statistics. For comparement, a venger has 26.4 damage and 20 AP, resulting in 7.3 damage per shot.
> 
> This same mech armor has **_85 melee protection._**

Yeah, that's what I'm saying. 7 damage per shot is too low to reliably destroy an armed mech, hell, even a mech with heavy arms and no weapons would out-damage you. 85% will reduce a wrench down to effectively zero.

**Comment by hex37** [comment]
I get the feeling that if I said "Buffs Melee," which this PR can also allow for if used correctly, people would also still be mad about it.

The PR is good.

**Comment by SirRichardFrancis** [comment]
It does not harm regular melee combat due to how hard it is to damage internal organs, player would die sooner than their muscles/nerves take enough damage to affect anything.
This change will only allow for one-hit-kill meta, that is not going to be fun and people will rage quit.
So yeah, while idea isn't bad and author intentions is good, there is just no gain for gameplay, only loss.

**Pull request closed without merging**
