### PR TITLE
hooly door resprite

### PR DESCRIPTION
**Pull request by CeUvi**
## About The Pull Request
holy door
holy door opening
## Why It's Good For The Game
no more piss doors
## Changelog
:cl: CeUvi
imageadd: added some iriska holy doors
imagedel: deleted some piss holy doors
/:cl:

### CODE REVIEW

**Comment by SirRichardFrancis** [comment]
NT цыгане

image

**Comment by CeUvi** [comment]
> NT цыгане
> 
> image

да у них вообще всё в золоте

**Comment by Wouju** [comment]
> nah

1984

**Comment by CeUvi** [comment]
> 1984

i actually did that

**Pull request merged**
