### PR TITLE
Silicon Economy Update Part 1 (The Implants) [Get it, because silicon] {pls laugh}

### PR DESCRIPTION
**Pull request by Mycah142**
## About The Pull Request
Adds the ability for the Service Gripper (unique to Service model cyborgs) to pick up and handle cash.

## Why It's Good For The Game
Previously it was a pain for a Service cyborg to accept payments from customers, could only drag the pile away, or drag the ETPOS to the counter. At least with this, the cyborg can actually handle the money. Next step: Silicon bank accounts. Stay tuned.

## Testing
[dreamseeker_9FLY2hBAfy.webm](https://user-images.githubusercontent.com/11076040/231897447-a701b765-d63b-408c-938f-50393cc412db.webm)

## Changelog
:cl:
tweak: Added service gripper functionality to include credit handling
/:cl:

### CODE REVIEW

**Comment by stupidnerd32** [comment]
finally cybernetic capitalism

**Comment by Humonitarian** [comment]
Can blitz do it too?

**Comment by Humonitarian** [comment]
`/obj/item/gripper/antag
	name = "Objective Gripper"
	desc = "A special grasping tool specialized in 'dirty' work. Can rip someone's head off if you need it."
	can_hold = list(
		/obj/item/implanter,
		/obj/item/device/spy_sensor,
		/obj/item/computer_hardware/hard_drive,
		/obj/item/reagent_containers,
		/obj/item/spacecash,
		/obj/item/device/mind_fryer,
		/obj/item/organ/external/head,
		/obj/item/oddity/secdocs,
		/obj/item/stack/telecrystal //To reload the uplink
		)`

They can apparently.

**Comment by Mycah142** [comment]
Which means they always could've and I didn't impact it. Probably because our antag uplink contract system being so broadly used is a mistake.

**Review by TheShown911 — APPROVED** [review]
Soulless automaton taking our holy cash.

**Pull request merged**
