### PR TITLE
Adds boot stomping sound to IH boots

### PR DESCRIPTION
**Pull request by thedarkcrusader**
Adds a new sound  and makes IH boots now have a  stomping effect 

## About The Pull Request

lets let those  criminal scum know that there's a whup-ass elemental in the vicinity. 
This PR adds a new sound  and makes IH boots now have a  stomping effect when walking and running  with them this only changes the IH jackboots other jackboots do not  have this sound This means everyone knows when IH is running by to break your legs

## Why It's Good For The Game
I think it would be a great change the sound serves as a warning to others  and as guide to freinds and Foes and it just feels  bad ass when your marching in a line.

## Changelog
:cl:
add: Added  boot crunch to IH boots happens when you walk and run
soundadd: added a new sound boot crunch
/:cl:

### CODE REVIEW

**Comment by Firefox13** [comment]
Can we have a video of how it actually sounds in-game?

**Comment by Omni44** [comment]
Video of both running and walking with them would be appreciated.

**Comment by thedarkcrusader** [comment]
my PC is not the best for recording sounds or video or anything but i think this will do it gets dodgy at the end and thats my PC's fault 
[https://s41.aconvert.com/convert/p3r68-cdx67/qq4y2-jimnw.mp4](url)

**Comment by thedarkcrusader** [comment]
https://s41.aconvert.com/convert/p3r68-cdx67/qq4y2-jimnw.mp4

**Comment by Alanii** [comment]
> https://s41.aconvert.com/convert/p3r68-cdx67/qq4y2-jimnw.mp4

Okay, that is literally just the /TG/ sound effects, and its really loud.

Maybe drop the volume it plays at or something because that noise would get very annoying quickly.

**Comment by Omni44** [comment]
Dollars to donuts this can be heard even on Centcomm, knowing the way sounds work here.
Good effort I guess, but it sounds bad, it's turbo loud, and it takes away my capacity to sneak up on people by walking quietly.

**Comment by Firefox13** [comment]
Given how the move sound is literally taken from another server, it's just a single one and it'll get very annoying, aren't affected by the "Quiet As Mouse" perk, will stack with normal movesound, can be simply cheesed by taking the different jackboots and it can fucking echo it isn't really a good change because it'll kill all the stealth.
Good PR, though.

**Pull request closed without merging**
