### PR TITLE
techno omnitool change

### PR DESCRIPTION
**Pull request by bigbubbos**
## About The Pull Request
gives technomancer omnitool hammer quality because it makes sense

## Why It's Good For The Game
makes life easier

## Changelog
🆑
add: adds hammer quality 25 to technomancer omnitool
/🆑

### CODE REVIEW

**Comment by Iglpigl** [comment]
Fix changelog.

**Comment by bigbubbos** [comment]
> Fix changelog.

removed it

**Comment by Iglpigl** [comment]
No, you do not remove it, look at any other open PR and make it like that.

**Comment by bigbubbos** [comment]
> No, you do not remove it, look at any other open PR and make it like that, it has a set template you need to follow otherwise you break in-game changelog.

how about it now

**Comment by Iglpigl** [comment]
Looks good!

**Review by Firefox13 — APPROVED** [review]

**Pull request merged**
