### PR TITLE
replaces guns in roachless forgotten closets with gun parts

### PR DESCRIPTION
**Pull request by vode-code**
## About The Pull Request
This PR replaces the two gun loot spawners in roachless forgotten closets with three copies of a new spawner, gun_adjacent_loot.
The gun_adjacent_loot spawner has mostly gun parts, with a chance for a knife, ammo, a gun upgrade, or a holster.

## Why It's Good For The Game
Gun Parts are supposed to be used to make guns, but when the main source of them is destroying guns, it's hard to justify doing so. This PR makes gun parts more available.

## Changelog
:cl: Chickenish
balance: roachless forgotten closets now contain gun parts instead of guns.
/:cl:

### CODE REVIEW

**Comment by Alliostra** [comment]
based now remove trash

**Comment by zombiemimic** [comment]
I think gun_loot spawners also include stuff like ammo, holsters, and gun parts

**Comment by vode-code** [comment]
> 
> 
> I think gun_loot spawners also include stuff like ammo, holsters, and gun parts

it does, but it has a higher chance to contain a gun than to contain a gun part, which is simply unacceptable for something as easy as a roachless forgotten closet.

**Review by TheShown911 — APPROVED** [review]
I support the idea, it's a nice start, but it's gonna take a lot more work to fix loot.

**Review by drexample — APPROVED** [review]
Good

**Pull request merged**
