### PR TITLE
Fix space and grab diving

### PR DESCRIPTION
**Pull request by SirRichardFrancis**
## About The Pull Request

Players can no longer dive/slide in space or when grabbed by someone.

## Why It's Good For The Game

Fixes cool.

## Changelog
:cl:
fix: diving in space
fix: diving when grabbed
/:cl:

### CODE REVIEW

**Comment by thedarkcrusader** [comment]
Does this fix escaping from grabs while diving in general

**Comment by SirRichardFrancis** [comment]
> Does this fix escaping from grabs while diving in general

What do you mean "while diving in general"?

**Comment by thedarkcrusader** [comment]
If your grabbed (any level aggressive kill etc) you can escape out of it just by diving and sliding making grabs pointless

**Comment by SirRichardFrancis** [comment]
That's exactly what this PR is intended to fix.

**Comment by MLGTASTICa** [comment]
Salt PR.

**Comment by glaciusinfinity** [comment]
Damn, I can no longer fly around space like super man...
<div class="tenor-gif-embed" data-postid="21239978" data-share-method="host" data-aspect-ratio="1.07023" data-width="100%"><a href="https://tenor.com/view/emoji-disintergrating-meme-emoji-disintegrating-meme-gif-21239978">Emoji Disintergrating GIF</a>from <a href="https://tenor.com/search/emoji-gifs">Emoji GIFs</a></div> <script type="text/javascript" async src="https://tenor.com/embed.js"></script>

**Review by TheShown911 — APPROVED** [review]

**Pull request merged**
