### PR TITLE
tunnel snake variants now are different

### PR DESCRIPTION
**Pull request by fernandos13**
## About The Pull Request
fixes a bug that made tunnel snake jackets look all the same

## Why It's Good For The Game
fixes a bug that made tunnel snake jackets look all the same

## Changelog
:cl:
fix: fixes a bug that made tunnel snake jackets look all the same, the 3 variants are now visible when you are wearing it
/:cl:

### CODE REVIEW

**Comment by fernandos13** [comment]
👍 thanks for the fast review torino :D this is the kinda stuff that motivates. even when its a correction on something i messed up. seeing some feedback always gets some endorphin running

**Comment by GrayRachnid** [comment]
Can you show screenshots of this ingame?

**Comment by fernandos13** [comment]
sure can do. all angles?
or just the back

**Comment by GrayRachnid** [comment]
just show that it works please

**Comment by fernandos13** [comment]
https://gyazo.com/57e3fdf5101bf07162a76ca5765f8f9a
foto ^^^^
https://gyazo.com/4b94b34f56a5123e7327d3b35409e7fe
gif of changing jacket ^^^^

**Pull request merged**
