### PR TITLE
Makes humanmob and organ health unreasonably high.

### PR DESCRIPTION
**Pull request by drexample**
## About The Pull Request

Turns all humanmobs and their limbs into bullet sponges. Yes.

## Why It's Good For The Game

We are not actually sure, this PR is less to be merged and more to go on the testserver and see what happens. If we deem the result positive, this PR will be extended into scaling with stats and more reasonable (or more extreme) numbers.

## Changelog
:cl:
tweak: Quadruples health of humanmobs and organs.
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
i dont think this is a good change. bulletsponge combat bad

**Comment by drexample** [comment]
> i dont think this is a good change. bulletsponge combat bad

You'd think that, but consider:
1. Ammo becomes more valuable
2. Firefights become longer
3. Much more opportunities for escape
4. Ability to call for backup and not die while it's coming
5. Far less salt from someone out-skilling you by having a better gun
6. Making antags actually get creative with their killings

**Comment by drexample** [comment]
Also, as said in desc, this PR is for testing, not for straight up merging in the state it is.

**Comment by ValoTheValo** [comment]
> > i dont think this is a good change. bulletsponge combat bad
> 
> You'd think that, but consider:
> 
> 1. Ammo becomes more valuable
> 2. Firefights become longer
> 3. Much more opportunities for escape
> 4. Ability to call for backup and not die while it's coming
> 5. Far less salt from someone out-skilling you by having a better gun
> 6. Making antags actually get creative with their killings

1:dont make this become like TG where you unload 300 rounds into someone to get them down. it just makes firefights boring and unfun 
2: firefights are already long enough. 
3: you can already run away people just don't
4: i thought this is why codespeak existed.  
5:haha funni salt PR
6: i dont see how making everyone take 400 gunshots to kill will make antags more creative. will just incentivise maxcapping and gibbing someone so you dont have to do this whole bullshit again

also as reere literally said like a day ago. make new content not endless stream of pointless balance PRs

**Comment by drexample** [comment]
1

> > > i dont think this is a good change. bulletsponge combat bad
> > 
> > 
> > You'd think that, but consider:
> > 
> > 1. Ammo becomes more valuable
> > 2. Firefights become longer
> > 3. Much more opportunities for escape
> > 4. Ability to call for backup and not die while it's coming
> > 5. Far less salt from someone out-skilling you by having a better gun
> > 6. Making antags actually get creative with their killings
> 
> 1:dont make this become like TG where you unload 300 rounds into someone to get them down. it just makes firefights boring and unfun 2: firefights are already long enough. 3: you can already run away people just don't 4: i thought this is why codespeak existed. 5:haha funni salt PR 6: i dont see how making everyone take 400 gunshots to kill will make antags more creative. will just incentivise maxcapping and gibbing someone so you dont have to do this whole bullshit again
> 
> also as reere literally said like a day ago. make new content not endless stream of pointless balance PRs

Compelling points, but consider:
My opinion > your opinion

**Comment by ValoTheValo** [comment]
> 1
> 
> > > > i dont think this is a good change. bulletsponge combat bad
> > > 
> > > 
> > > You'd think that, but consider:
> > > 
> > > 1. Ammo becomes more valuable
> > > 2. Firefights become longer
> > > 3. Much more opportunities for escape
> > > 4. Ability to call for backup and not die while it's coming
> > > 5. Far less salt from someone out-skilling you by having a better gun
> > > 6. Making antags actually get creative with their killings
> > 
> > 
> > 1:dont make this become like TG where you unload 300 rounds into someone to get them down. it just makes firefights boring and unfun 2: firefights are already long enough. 3: you can already run away people just don't 4: i thought this is why codespeak existed. 5:haha funni salt PR 6: i dont see how making everyone take 400 gunshots to kill will make antags more creative. will just incentivise maxcapping and gibbing someone so you dont have to do this whole bullshit again
> > also as reere literally said like a day ago. make new content not endless stream of pointless balance PRs
> 
> Compelling points, but consider: My opinion > your opinion

yes but i drew you as a soyjack
soycoder

**Comment by drexample** [comment]
> > 1
> > > > > i dont think this is a good change. bulletsponge combat bad
> > > > 
> > > > 
> > > > You'd think that, but consider:
> > > > 
> > > > 1. Ammo becomes more valuable
> > > > 2. Firefights become longer
> > > > 3. Much more opportunities for escape
> > > > 4. Ability to call for backup and not die while it's coming
> > > > 5. Far less salt from someone out-skilling you by having a better gun
> > > > 6. Making antags actually get creative with their killings
> > > 
> > > 
> > > 1:dont make this become like TG where you unload 300 rounds into someone to get them down. it just makes firefights boring and unfun 2: firefights are already long enough. 3: you can already run away people just don't 4: i thought this is why codespeak existed. 5:haha funni salt PR 6: i dont see how making everyone take 400 gunshots to kill will make antags more creative. will just incentivise maxcapping and gibbing someone so you dont have to do this whole bullshit again
> > > also as reere literally said like a day ago. make new content not endless stream of pointless balance PRs
> > 
> > 
> > Compelling points, but consider: My opinion > your opinion
> 
> yes but i drew you as a soyjack soycoder

There's only two people in this discussion and it's you and me.
There are two soyjaks in the picture. 

YOU DREW US AS SOYJAKS YOU FOOL

**Comment by ValoTheValo** [comment]
> > > 1
> > > > > > i dont think this is a good change. bulletsponge combat bad
> > > > > 
> > > > > 
> > > > > You'd think that, but consider:
> > > > > 
> > > > > 1. Ammo becomes more valuable
> > > > > 2. Firefights become longer
> > > > > 3. Much more opportunities for escape
> > > > > 4. Ability to call for backup and not die while it's coming
> > > > > 5. Far less salt from someone out-skilling you by having a better gun
> > > > > 6. Making antags actually get creative with their killings
> > > > 
> > > > 
> > > > 1:dont make this become like TG where you unload 300 rounds into someone to get them down. it just makes firefights boring and unfun 2: firefights are already long enough. 3: you can already run away people just don't 4: i thought this is why codespeak existed. 5:haha funni salt PR 6: i dont see how making everyone take 400 gunshots to kill will make antags more creative. will just incentivise maxcapping and gibbing someone so you dont have to do this whole bullshit again
> > > > also as reere literally said like a day ago. make new content not endless stream of pointless balance PRs
> > > 
> > > 
> > > Compelling points, but consider: My opinion > your opinion
> > 
> > 
> > yes but i drew you as a soyjack soycoder
> 
> There's only two people in this discussion and it's you and me. There are two soyjaks in the picture.
> 
> YOU DREW US AS SOYJAKS YOU FOOL

coder to coder communication

**Comment by CeUvi** [comment]
CEV "/teegee/" Eris
please don't.

**Comment by Kegdo** [comment]
The best buff to melee: now them bullets simply won't work~~, Jon~~

**Comment by Voldirs** [comment]
bruh
also fuck stats

**Comment by Humonitarian** [comment]
Quadruple sounds a little excessive... But I see the spirit behind it.

With health so bad positioning and running into gunfire might not be crippling enough to make combat intense and dangerous, but we can't know until we test it.

**Comment by TheShown911** [comment]
I don't think this will do much as both the crit and death threshold defines remain unchanged

**Comment by Omni44** [comment]
What shown said. Alas, this is direction worth trying out, combat *is* too fast, too lethal and too onesided, but there's very thin line to walk between human bulletsponges and unfun degree of lethality. But there's no other option than to find that line.

**Comment by maikilangiolo** [comment]
I'd like to try it. It's a test server merge, if it goes nowhere it doesn't matter. It would end funny delimb due to shrap removal/self surgery, block head aim cheese to take advantage of lower part HP and helmet armor values. Pain and instead death threshold are still there anyway

**Comment by MLGTASTICa** [comment]
I do agree that fights currently end too fast , but quadripling health wasn't really the way to fix it, keep in mind all the mobs that need their damage amounts rebalanced.
The major issue with fights as it is is that there is no way to get tired , there is nothing to limit the rate at which combat is done at , at which shots are fired , etc. The mechanics behind this are simply too weak to make any difference.
This is what i want to adressed by making stamina (by limiting ramboing with guns , etc by making it give you stamina damage and slow you, make people pay a price for wearing heavy armor by reducing their stamina , etc)
All this will do since the crit thresholds are still unchanged is make people pain knockout people , and then spend a good minute smashing their head in.

**Comment by zombiemimic** [comment]
>stamina

even in exile, SCPR still shills his ideas

**Comment by MLGTASTICa** [comment]
> fuck stamina. let's go even further beyond!! TURN-BASED COMBAT AND SKILL COOLDOWN!!!!!!!

Would fit right in , with the performance at 60+ players

**Comment by Kegdo** [comment]
literally underrail in space

**Comment by Fritcher36** [comment]
What about stealth murders? Would there be any way to destroy someone before they are able to fully describe your appearance and location, compose a sonet and sing it?

**Comment by Kegdo** [comment]
Yes, there is a way to do that, but I won't tell you how.

**Comment by Humonitarian** [comment]
This PR is pretty fun if you want to do IH combat training with lethals, based on testing.

Yeah.

**Comment by drexample** [comment]
> What about stealth murders? Would there be any way to destroy someone before they are able to fully describe your appearance and location, compose a sonet and sing it?

That is actually quite a good idea! Make creative takedowns be effective!

**Comment by ValoTheValo** [comment]
from testing this is extremely unbalanced with painkiller and just generally makes combat really painfull if you are trying to get a kill. organ damage is also nonexistant

**Comment by githubuser4141** [comment]
This seems like an interesting idea, I hope it doesn't make it too difficult for antagonists to kill people in 'conventional' ways, I feel like creativite murder doesn't have to revolve around spending hours in chemistry/toxins, I feel like it'd ruin faction warfare, and prevent antags from having a faction murder your opponent for you. I wish there were more environmental hazards that could be used to murder somebody without that being the only reason you'd use it. (I.E, toxins which is basically only used for PvP reasons.)

**Comment by drexample** [comment]
I got pretty much all info I needed, thank you for joining test server.

Expect a far worse and controversial PR in the future.

**Pull request closed without merging**
