### PR TITLE
New mid-threat antag: Pirates

### PR DESCRIPTION
**Pull request by hyperioo**
## About The Pull Request

This PR implements a new antag faction whose goal is to plunder the ship for valuable loot before getting back to their base (and not being killed by the crew). The raiding shuttle has several loot crates that must be filled with loot (no need to close the crates) and be inside the shuttle to count toward the objective.

Comes with:
- New pirate base to get geared
- New pirate shuttle to raid CEV Eris
- A few predefined raiding locations around the ship
- Their own pirate channel for in-raid communication
- A timed objective - you have 45 minutes to steal stuff.
- A plunder objective - you must steal 15000 credits of loot per pirate.
- Mid-thread gear (mostly AKs and bulletproof vests)
- A hailer to check the current looted value (one minute cooldown)
- A new rum keg (like the beer keg)

Raid shuttle cannot go back to Eris once it has gone back to pirate base. Automatic mechanisms prevent the pirate shuttle from going back to pirate base if there is an alive outsider inside the shuttle so that its location remains undiscovered.

Numerical values might be adjusted depending on player feedback. The timed objective will be improved later to make it more interesting (like if you reach the loot threshold, the mission duration is extended and you have to steal more loot to extend more and more).

The faction has a temporary cartoonish pirate theme (the already-existing pirate costume) but custom stuff might come later to make them more stylish with their own sprites.

_Pirate base:_
image

_Pirate shuttle with loot crates and hailer:_
image

_Ready to breach the ship:_
image

## Why It's Good For The Game

Provide more diversity for out-of-ship antags alongside blitz and serbs. Not as "sneaky lone wolf" as blitz, but not as "end of round" threatening as serbs.

## Testing

- Spawned as pirate by forcing pirate in storyteller panel
- Checked objectives were properly displayed
- Entered the shuttle, flew to the ship
- Stole some stuff, checked that hailer is working well
- Checked that shuttle cannot launch with alive non-pirate on board
- Flew back to base, enjoy greentext
- Checked shuttle could not go back to Eris

## Changelog
:cl: Hyperio
add: Add new Pirates antags : pirate base, pirate shuttle, landmark locations, pirate channel, pirate objectives, pirate hailer
/:cl:

### CODE REVIEW

**Comment by SirRichardFrancis** [comment]
No screenshots?
image

So basically it's a meme version of Serbs, just less powerful?

Can't spawn without at least two ghosts too. If game needed "Serbs, but not as threatening", then solo Serb could be allowed to spawn. Would do the thing and give lone observer something to do (since blitzshell is a sad joke and incredibly unfun to play as).

**Comment by thevandie** [comment]
>If game needed "Serbs, but not as threatening", then solo Serb could be allowed to spawn.

Nah nah nah, this has merit
More flavor is nice, and I personally wanna build off of this with pirate variations
Hell, we already have some of the sprites for that, Jimmy's IH deserters
More variations of serbs is a cool concept and adds some flavor the game is kinda missing

**Comment by thevandie** [comment]
But yes, also add solo serb please
They'd both be good for the game

**Comment by thevandie** [comment]
Use. Real. Walls.

**Comment by Mycah142** [comment]
> Use. Real. Walls.

Why? It's a shuttle. You want people to be able to dismantle it or something?

**Comment by thevandie** [comment]
no no, I mean make proper walls that actually look good and not like it's from 20 years ago
even if it's just a normal wall sprite, it should be a normal wall
mostly with the base

**Comment by hyperioo** [comment]
In another PR we would have to add to unsimulated walls the logic that changes the wall sprites depending on other nearby walls so that we have an unsimulated version of the classic Eris walls. It's not much to do.

**Pull request merged**
