### PR TITLE
New setting-compliant NekoVend

### PR DESCRIPTION
**Pull request by Kurgis**
## About The Pull Request

Fixes the issues regarding #5701, which failed due to being rushed to PR. All credits to Shazbot for the new wonderful icons!

In-game screenshot:
Untitled

## Why It's Good For The Game

Improves game immersion, improves lore, improves improvements.

## Changelog
:cl:Shazbot
add: Added a new vendor type!
imageadd: Corrects some old icons.
/:cl:

### CODE REVIEW

**Review by MadmanMartian — CHANGES_REQUESTED** [review]
Also no.

**Review by genessee596 — CHANGES_REQUESTED** [review]
I probably shouldn't approve this if I want to keep my job

**Comment by Hopekz** [comment]
There was no issue to fix with  #5701 from what I can tell
R3i4Q5makS-export_deny

Why do we need a direct TG reference in our codebase they don't have any references from us except maybe a stolen sprite

**Comment by TheShown911** [comment]
I'm reopening this just to have the satisfaction of closing it

**Comment by shazbot194** [comment]
I want it on record I didn't make this sprite. Someone else took my meme neko vending machine and did this. I in no way endorse this PR and request an update to the description.

**Comment by Kurgis** [comment]
@shazbot194 As per your request the description has been updated.

**Comment by shazbot194** [comment]
The issue is still there, shall I spell it out for you?

**Comment by Kurgis** [comment]
> The issue is still there, shall I spell it out for you?

Does it start with an "O"?

**Comment by shazbot194** [comment]
You see, the part that says
"All credits to Shazbot for the new wonderful icons!"
It should read
"Icons are modified by <person>, original sprites by shazbot."

**Pull request closed without merging**
