### PR TITLE
Ammo loading/unloading fixes and tweaks

### PR DESCRIPTION
**Pull request by LagannPM**
Loading magazines and ammoboxes is a little different now
You can load ammo in magazine by clicking on it with ammo in your hand
You can unload full stack from it by clicking on it with empty hand
You can unload one casing from it by alt clicking with ammo or empty hand on it
***
Stacking ammo from turf is easier now
***
Ammobox quick unload on selfclick is removed, click on turf for that
***
Magazines and ammo can be unloaded from guns by dragging gun in empty hand(just like removing battery)
***
Fixed 32 caliber not fitting in ammo box and a typo ".38"

### CODE REVIEW

**Comment by Voldirs** [comment]
I'd suggest another implementation. Alt-click is too unobvious. If one clicks the mag or box with empty hand he gets full stack of ammo which is 5, or less if there were less ammo left.
If one clicks the mag with stack of ammo, he loads one ammo from that stack.

**Comment by LagannPM** [comment]
I'll leave alt click interaction but ill implement your suggestion

**Comment by EvenInDeathIStillServe** [comment]
If you're going to add alt-click interaction, the game should tell you when you examine the ammo box.

**Comment by NanakoAC** [comment]
I agree with @LagannPM here.
If altclick isn't obvious, its because players haven't learned to use it yet. They will in time. And the more things we add with this control scheme, the more players will grow accustomed to it

**Pull request merged**
