### PR TITLE
Adds new autolathe design disks that print armor

### PR DESCRIPTION
**Pull request by genessee596**
## About The Pull Request

This PR adds five new autolathe design disks, all produced by the Ironhammer Combat Equipment division.
_'Standard Armor'_, which has designs for the basic helmet and basic armor vest. This disk can be bought at an Asters Print-o-Mat for 800 credits, and is uncommon in maintenance.
_'Bulletproof Armor'_, which has designs for a bulletproof helmet and bulletproof vest, and can found relatively rarely in maintenance.
_'Laserproof Armor'_, which has designs for an ablative helmet and ablative vest, and can be found rarely in maintenance.

_'Operator Armor'_, which has designs for the IH helmet and IH vest. This disk can be grabbed for free at a SecTech (but there are only two disks!), and cannot be found in maintenance.
_'Bulletproof Operator Armor'_, which has designs for the full IH headgear and full IH body-armor. This disk can be grabbed for free at a SecTech (but there's only one disk!) and cannot be found in maintenance.

**This PR also adds the Ironhammer Miscellaneous Disk to the SecTech, in case IH needs to print more knives with their Autolathe.**

## Why It's Good For The Game

It's weird how we can print guns, but not armor. This also gives IH some more branded disks, since at the moment there's only one IH disk.

Here is me getting approval from a maintainer to go ahead and make this PR.
image

## Changelog
:cl:
add: Three new autolathe disks that can print armor can now be found in maintenance, one of which that can also be bought at an Asters Print-o-Mat. Two more disks that print IH faction armor can be found in the SecTech.
tweak: The SecTech now vends Ironhammer Miscellaneous Pack design disks.
/:cl:

### CODE REVIEW

**Review by TorinoFermic — DISMISSED** [review]
Looks clean

**Comment by TheShown911** [comment]
That's quite a number of lines changed.

**Comment by genessee596** [comment]
> That's quite a number of lines changed.

I was a bit lazy and replaced a few files directly instead of copying over my changes. Oops.

**Review by Hopekz — CHANGES_REQUESTED** [review]
> I was a bit lazy and replaced a few files directly instead of copying over my changes. Oops.

Do it the un-lazy way so it is easier to track your changes and review your PR.

**Pull request closed without merging**
