### PR TITLE
Buffs bombsuits melee/bullet/energy resist to be 40

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Basically the title.

## Why It's Good For The Game
This thing isn't even useful for bomb disposal, and I think that it protecting more is fine for the game personally. It gives it a niche as an incredibly slow and situational armor.

## Changelog
:cl:
balance: bomb suits now have 40 bullet/melee/energy resist.
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Dont forget to change the helm's armor.
Also, isnt this the best soft space suit?

**Comment by jaffjafferson** [comment]
not the best at all, it's very slow and with the buff, it'l be about as good protection wise as the much faster and more common blood red suit

**Comment by Wouju** [comment]
Like jeff said, it's _slow_, slowest piece of clothing ingame I think. And it's not very common. I feel like keeping the helmet at 30/30/30 would be fine.

**Comment by Trilbyspaceclone** [comment]
Correct me if im wrong, but 0g combat dosnt have suit slowdown.
Also, looked at caps soft suit, and this would be better then theirs, other then the helmet.
Maybe only secs should be buffed to have more armor then scis and maints versions too?

**Comment by jaffjafferson** [comment]
there are a total of zero (0) instances where zero g combat has ever happened on eris
caps suit is an ancient bay holdover that hasn't been looked at since like 1945, and i think it's shitcode so it's not even a real space suit

**Comment by seekin4u** [comment]
Bomb suit with ENERGY RESIST, bruh don't to it pls

**Comment by TheShown911** [comment]
I don't like this PR.

**Pull request merged**
