### PR TITLE
cuckedshot

### PR DESCRIPTION
**Pull request by Harrivchaw**
## About The Pull Request
Buckshot and slug doesn't knockback, they now have a slight agony damage stacked on top in exchange

## Why It's Good For The Game
Fixes double slug hitting bug and buckshot punting you across the ship

## Changelog
:cl:
tweak: Shotgun slug and buckshot does not knockback, agony damage increased
fix: Shotgun slug and buck bug is now fixed
/:cl:

### CODE REVIEW

**Comment by ArmolitskiyCarpoeb** [comment]
>Buckshot and slug doesn't knockback
👎

**Review by MadmanMartian — CHANGES_REQUESTED** [review]
Maybe try fixing the reason knockback is so OP

**Comment by Harrivchaw** [comment]
yea no can do, try seeing for yourself why the shotgun code is fucked

**Comment by Garen7** [comment]
Right, incase anyone isnt aware of what Madman Martian is referring to, apparently if a shotgun knocks someone into a wall it will allow the bullet to hit the target a second time, or so I've been told. I haven't looked into this issue myself so I can't verify that its this but I'm posting here since this info needs to be available to anyone who begins looking into it.

**Pull request closed without merging**
