### PR TITLE
Sheath fix

### PR DESCRIPTION
**Pull request by pexel5**
Sheath fix

## About The Pull Request

little fix Sheath, added the ability to shove katana/nano katana/toy katana/ junkblade into them, as well as sprites for them made by Rosalimo. And also fixed the display of the scourge extended sword in the scabbard and on the doll. turned the junkblade sword over the way all swords lie

## Why It's Good For The Game

Fix`s good/

## Changelog
:cl:
tweak: Turned the junkblade sword over the way all swords lie.
fix: Sheath and swords for them.

/:cl:

### CODE REVIEW

**Review by SirRichardFrancis — APPROVED** [review]
Probably could get away with just
```
	can_hold = list(
		/obj/item/tool/sword,
		/obj/item/toy/katana)
```
assuming that all of the "bad" swords are blacklisted, but that's not a big deal.

**Comment by SirRichardFrancis** [comment]
>this is a terrible filename and should be changed why is it a separate file even?

`sheath_` part is required by code, rest is just that sword name.

**Comment by Firefox13** [comment]
I mean the filename, `sh_tr.dmi`, not the icon name

**Comment by Firefox13** [comment]
Wait why that FILE EVEN EXISTS

**Comment by pexel5** [comment]
what i broke again?

**Review by Firefox13 — APPROVED** [review]

**Pull request merged**
