### PR TITLE
Revert

### PR DESCRIPTION
**Pull request by budgetcommander**
## About The Pull Request

Reverts all of my PRs, save for the numbered sanity ui which was done in large part by PinkChink.

## Why It's Good For The Game

I don't want to be associated with this server anymore for a number of reasons. Removing my work would be highly appreciated.

## Testing

None, but the server worked just fine without my additions.

## Changelog
:cl:
del: Removed the armour damage calculator from the weapon UI
del: Removed style from the clothing UI
tweak: Changed the burst delay on the 3-round rapid burst
tweak: Holiness is no longer capitalised in the sanity UI

/:cl:

### CODE REVIEW

**Comment by DiaFRAME444** [comment]
That's not how open source code works.

**Comment by budgetcommander** [comment]
Sure. If you want to keep my code, then I can't stop you. Just know that I sincerely regret dedicating time and effort towards helping you folk.

**Comment by budgetcommander** [comment]
Your welcome for adding basic shit y'all were too moronic to even realize was necessary. Still no obscuration or stiffness in the clothing UI, by the way. Guess you'll just live with that, because I know damn well you're too stuck up your own asses to get around to it.

**Comment by Firefox13** [comment]
If you have any issues with your name appearing on the server - reverting all your changes is not the right thing to do. If you seriously want to remove your name from changelogs (which can be edited out) you should reach headstaff instead.

**Pull request closed without merging**
