### PR TITLE
Makes Blitzshell a fun role

### PR DESCRIPTION
**Pull request by Humonitarian**
## About The Pull Request

Gives Blitzshell language

## Why It's Good For The Game

Makes playing Blitzshell a viable way to have fun

## Testing

Tested locally, blitz could speak. Blitz language is no longer "Transmit" however, which might cause problems in blitz to blitz comms. (Not that it matters considering blitz are generally lone-ops)

## Changelog
:cl:
tweak: blitz speaks language
/:cl:

### CODE REVIEW

**Comment by Mycah142** [comment]
Finally, I can ERP the technomancer exaltant for special perks.

**Comment by Humonitarian** [comment]
https://cdn.discordapp.com/attachments/265411548963405824/1150364518032080896/image.png

**Comment by Alliostra** [comment]
captain_confirmed_catgirl

**Review by TheShown911 — APPROVED** [review]
You could speek fluent morse code with *beep and *buzz, this is just dumbing down blitzshell gameplay for the casual audience.

**Pull request merged**
