### PR TITLE
Makes status not log.

### PR DESCRIPTION
**Pull request by nichlas0010**
image

### CODE REVIEW

**Comment by NanakoAC** [comment]
whats the purpose of this, just to reduce log spam?

simple changes can be targeted at master

**Comment by nichlas0010** [comment]
the code for this is in the world/Topic commits, which isn't on master yet.

**Comment by nichlas0010** [comment]
And yes, it's to reduce log-spam

**Comment by NanakoAC** [comment]
lots of conflicts, please resolve

**Pull request closed without merging**
