### PR TITLE
Players get additional stats when they become an antag.

### PR DESCRIPTION
**Pull request by Kurgis**
This requires discussion, and likely code improvement. Each stat modifier list increases said stats by listed values, this does not replace. So an Assistant with 8 starting Robustness, would have 13 robustness if they were to become a traitor.

**Antag stats:**
Traitor: STAT_ROB = 5, STAT_TGH = 5, STAT_BIO = 5, STAT_MEC = 5, STAT_COG = 5, STAT_VIG = 15
The traitor gets a supplement towards all stats, and a needed heavy boost to Vigilance.

Inquisitor: STAT_TGH = 10, STAT_VIG = 10
Inquisitors are now much more resilient to pain, and are capable of shooting weaponry.

Excelsior Leader: STAT_ROB = 5, STAT_TGH = 5, STAT_MEC = 10, STAT_COG = 5, STAT_VIG = 15
Excelsior Leaders get higher mechanical & cognition skills for constructing their machinery, they are a bit more robust, and they can shoot a projectile weapon. This does not affect Excelsior converts, their stats remain the same.

Changeling: STAT_TGH = 5, STAT_VIG = 15
They can now use guns, they'd be too far at a disadvantage to not be able to do so.

**Crew-aligned:**
Marshal: STAT_ROB = 5, STAT_VIG = 15
The Marshal intentionally gets a lower total amount of stats, but a focus on Vigilance.

Security Document Defenders: Nothing.
They can seek help from others if the going gets too tough.

**Problems:**
- If an admin removes antag status from a player's character, their stat changes remain.

### CODE REVIEW

**Comment by Kurgis** [comment]
Closed & re-opened to poke Travis.

**Comment by Kurgis** [comment]
This is now ready for review.

**Comment by fernandos33** [comment]
won't this make IH antags hell of strong?? .. plus well a doctor can't hit shit with a gun but there are other ways to kill and be a traitor, sure some jobs need better skillset like medspec and doctor paramedic chemist (and all the thing with the biology skill no idea if its needed but i sure know that some think there is a need), but giving every antag this boost feels like making them VERYY strong. and the thing is the more they can HIT with a gun the less likely they will use other methods. i gotta tell you as science guy you can mass produces bombs of soporific, mechs and a lot of stuff that don't need VIG. as cargo you can order whateer you d like and as techno mancer you can literaly control maint and power at your will, you can bobby trap ANY APC without anyone giving a fuck (i think there are better ways to improve it than just a plain blind boost to any job that gets antag)

**Comment by Kurgis** [comment]
@fernandos33 IH cannot become Traitors, Excelsior Leaders, Changelings, or Marshals.

You give an interesting point, that lacking Vigilance will encourage antags to pursue alternative paths. Even with these paths available, trapping APCs, ordering Super Matter, and making explosives isn't going to help an antag defend themselves when anyone attacks them. Many of the guns in their uplinks are now more situational at best, as they need to be at CQC range to hit their mark. This change is intentionally done to make Traitors be on-par with IronHammer Operatives, the boost is intentionally large.

**Comment by Kurgis** [comment]
I'm going to attempt to re-work this to check for on character stats, and depending on said stat's values, change them differently. So if someone with Vigilance 0 becomes an antag, it'd see that their stat is at 0, and would set it to the basic skill level check of 15, before applying any other changes for example.

**Comment by zamolxius** [comment]
if its lower than 15, make it 15, if not leave it as it is

**Comment by Kurgis** [comment]
This has gone stale, and I'm no longer actively working on it. I will re-open this PR if that changes, but I don't want to leave this up to give false impressions.

**Comment by Kurgis** [comment]
This is ready for review on its existing merits.

**Pull request merged**
