### PR TITLE
Fixes a lot of stuff and updates the map-view images for camera monitoring / crew monitoring.

### PR DESCRIPTION
**Pull request by MLGTASTICa**
## About The Pull Request
Fixes looking up not always working
Fixes players not rendering properly when using a jetpack to go upwards at times
Fixes a multi-z-PB bug that lets you PB when not looking
adds updated map preview images for map view
Fixes catwalks being hittable by lasers and bullets alike.
Fixes being able to multi-Z pb unintended objects
Updates the maps for Map view in crew monitoring and security camera monitoring
## Why It's Good For The Game
Bug fixes + newer maps , less CBT for paramedics and security alike

## Changelog
:cl:
fix: Fixed look up not working at times
fix: Fixed player icons breaking when moving upwards with a jetpack at times
fix: Fixed multi-z PB being able to be used when not intended
add: Updated Map view PNG's
fix: Fixes catwalks being hittable by lasers and projectiles.
fix: Fixes being able to multi-Z pb unintended objects.
/:cl:

### CODE REVIEW

**Review by TheShown911 — COMMENTED** [review]
Can you post the new map pictures?

**Comment by MLGTASTICa** [comment]
> Can you post the new map pictures?

You can see them by clicking rich-binary on their files

**Comment by TheShown911** [comment]
The resolution looks weird, wasn't there a discussion about this somewhere?

**Comment by MLGTASTICa** [comment]
> The resolution looks weird, wasn't there a discussion about this somewhere?

There was. But ingame it looks fine ,you can check Purgatory for the discussion

**Comment by TheShown911** [comment]
Waiting for head dev/project lead approval

**Comment by MLGTASTICa** [comment]
> Waiting for head dev/project lead approval

Just as a disclaimer ,the map does indeed need to be bigger because of the issues there are with it remaining small , predominantly people in space and being unable to see locations even at 2.5x

**Review by drexample — CHANGES_REQUESTED** [review]
Regenerate the image using the in-game tools. Do not use actual render of the map.

**Comment by MLGTASTICa** [comment]
> Regenerate the image using the in-game tools. Do not use actual render of the map.

image

**Pull request closed without merging**
