### PR TITLE
Adds the ability to shoot people near ladders from below/above

### PR DESCRIPTION
**Pull request by MLGTASTICa**
## About The Pull Request
Gives players the ability to shoot people on the other side of ladders as long as they are adjaecent to it, this it to counter ladder camping and give people a viable choice other than grenade spam

## Why It's Good For The Game
More robust combat for multi-z , more robust counters

## Changelog
:cl:
add: You can now shoot people adjacenet to ladders you look through from above/elow
/:cl:

### CODE REVIEW

**Comment by zoktiik** [comment]
I like this concept quite a bit, but I think it needs to become more developed, tested, balanced, etc. as a fully fledged feature. Overall these needs to be more meat on these bones before this gets merged.
One idea I have is perhaps applying a "blinded" overlay before allowing you to look up the ladder, so that you can't just see absolutely everyone and everything that's near its destination.

**Comment by MLGTASTICa** [comment]
> I like this concept quite a bit, but I think it needs to become more developed, tested, balanced, etc. as a fully fledged feature. Overall these needs to be more meat on these bones before this gets merged.
> One idea I have is perhaps applying a "blinded" overlay before allowing you to look up the ladder, so that you can't just see absolutely everyone and everything that's near its destination.

What are you insinuating ?  It prevents shooting turfs to heat people that are not adjaecent.

**Comment by zoktiik** [comment]
> What are you insinuating ? It prevents shooting turfs to hit people that are not adjaecent.

It's not a feature that's fleshed out, it's not well-integrated with the game, it's a very basic change that's made without consideration of its compatibility with other game mechanics or its potential impact. 

And I know that it prevents shooting non-adjacent turfs, but the fact that you have perfect vision of what's above or below you just because a ladder's there is a bit broken. Realistically, you'd only be able to see what's immediately around the ladder, so a "blinded" overlay that only lets you see what is adjacent would work pretty well. It also reinforces the fact that you can't hit anything beyond what is close to the ladder.

In fact, I can see ladder-camping becoming WORSE if this gets merged without the overlay, because you can simply watch and wait at one end of the ladder, fire at the exact moment someone approaches/starts climbing the other end, and then you can step away from that ladder afterwards so they can't immediately retaliate. With the overlay, a camper wouldn't be able to see someone walking up to the ladder, only if they're close to it. I don't know why I need to explain how this would be better.

And that's just one aspect, really. I wish I wasn't the only one giving input on this PR, because I already feel like I'm putting way more effort into this feedback than I really should. In its current state, this PR would have very negative consequences on gameplay if it gets merged. I've talked about gameplay, but there's likely bugs or even runtimes that could crop up during testing (I don't like that `blanker.client.eye`, for example.) This needs more thought put into it. It's incomplete. Do not merge please.

**Comment by MLGTASTICa** [comment]
> > What are you insinuating ? It prevents shooting turfs to hit people that are not adjaecent.
> 
> It's not a feature that's fleshed out, it's not well-integrated with the game, it's a very basic change that's made without consideration of its compatibility with other game mechanics or its potential impact.
> 
> And I know that it prevents shooting non-adjacent turfs, but the fact that you have perfect vision of what's above or below you just because a ladder's there is a bit broken. Realistically, you'd only be able to see what's immediately around the ladder, so a "blinded" overlay that only lets you see what is adjacent would work pretty well. It also reinforces the fact that you can't hit anything beyond what is close to the ladder.
> 
> In fact, I can see ladder-camping becoming WORSE if this gets merged without the overlay, because you can simply watch and wait at one end of the ladder, fire at the exact moment someone approaches/starts climbing the other end, and then you can step away from that ladder afterwards so they can't immediately retaliate. With the overlay, a camper wouldn't be able to see someone walking up to the ladder, only if they're close to it. I don't know why I need to explain how this would be better.
> 
> And that's just one aspect, really. I wish I wasn't the only one giving input on this PR, because I already feel like I'm putting way more effort into this feedback than I really should. In its current state, this PR would have very negative consequences on gameplay if it gets merged. I've talked about gameplay, but there's likely bugs or even runtimes that could crop up during testing (I don't like that `blanker.client.eye`, for example.) This needs more thought put into it. It's incomplete. Do not merge please.

If maintainers agree with the overlay part sure . Its fully complete and the code won't runtime , i don't know how much knowledge you have with DM Coding ,but this will only runtime when someone fucks up really badly with proc-calls.

**Comment by zoktiik** [comment]
> If maintainers agree with the overlay part sure . Its fully complete and the code won't runtime , i don't know how much knowledge you have with DM Coding ,but this will only runtime when someone calls the fire proc on weapons without an user (which never happens)

My main point is that testing this makes multiple alarm bells go off in my head, mainly with the potential for abuse (i.e. with fueltanks!), and also how hacky this solution is.

**Review by Firefox13 — APPROVED** [review]

**Pull request merged**
