### PR TITLE
Rublies money

### PR DESCRIPTION
**Pull request by Kegdo**
## About The Pull Request
removed turning the mone
replaced the mone
image
either this or #6759 
## Why It's Good For The Game

old money bad

## Changelog
:cl:
imageadd: new(good) credits sprite (by Près de l'oiseau#2625)
imagedel: old(bad) credits sprite
/:cl:

### CODE REVIEW

**Comment by Alanii** [comment]
Looks better than whatever shit you have in the other PR.

**Comment by zombiemimic** [comment]
absolutely sexy bills

**Comment by Kegdo** [comment]
I have an idea about rublies, but that's for later. Democracy!

**Comment by TheShown911** [comment]
I don't like it.

**Comment by Kegdo** [comment]
image
also added a 5 coin, so less 1 credit spamming

**Comment by Humonitarian** [comment]
It's pretty nice now that it has coin

**Comment by Kegdo** [comment]
image

**Comment by SirRichardFrancis** [comment]
> I don't like it.

Yeah, why have those pretty cool sprites when we can have _this_ generic bullshit instead.

image

**Comment by Humonitarian** [comment]
> > I don't like it.
> 
> Yeah, why have those pretty cool sprites when we can have _this_ generic bullshit instead.
> 
> image

Exactly.

Massive improvement.

**Comment by Kegdo** [comment]
It can be even better if someone (not me) makes a second state for coins.

**Review by SirRichardFrancis — APPROVED** [review]

**Comment by drexample** [comment]
It's not perfect, but it IS better than what we have.

**Pull request merged**
