### PR TITLE
Connects missing wires

### PR DESCRIPTION
**Pull request by Kurgis**
## About The Pull Request
Small oversight where a downward wire was never connected to a wire below it.
image

## Why It's Good For The Game
Connects missing wires

## Testing
Tested on local, wires are connected.

## Changelog
:cl:
fix: Adds missing wire section within maintenance.
/:cl:

### CODE REVIEW

**Comment by Firefox13** [comment]
Um... Isn't it connected in the different place? Follow the existing wire.

**Comment by Firefox13** [comment]
Rather, the wire from the club. It is connected to the substation.

**Comment by Kurgis** [comment]
> Um... Isn't it connected in the different place? Follow the existing wire.

You are correct, though regular course of gameplay tends to disconnect it, which is how I happened to notice the missing connection here.

**Comment by Firefox13** [comment]
> regular course of gameplay tends to disconnect it

This is not a mapping issue.

**Comment by Firefox13** [comment]
So.

Wires are actually connected (if you do not believe me, I can provide a video later), and redundancy in wires and supply/scrubber pipes isn't usually a thing in mapping. You can look at Eris, at /tg/, at bay and other servers, pipe and wire systems are meant to be easily sabotageable, for better or worse.

Mostly worse.

**Pull request closed without merging**
