### PR TITLE
New makeshift weapon

### PR DESCRIPTION
**Pull request by jaffjafferson**
## About The Pull Request

Adds makeshift battle hammer with high AP but low base damage.
(Reere has requested more melee weapons)

## Screenshots

<details>
https://imgur.com/a/KgkJQBL
  <summary>Expand</summary>

</details>

### CODE REVIEW

**Comment by jaffjafferson** [comment]
shits fucked i cant into byond
will reopen once i become into byond

**Comment by Coureere** [comment]
We already have plenty melee high AP weapons such saws and swords. Maybe make it high damage, but low AP? It will make a lot more sense.

**Comment by jaffjafferson** [comment]
maybe?, blunt force weapons like hammers and maces are more often used vs armor, though

**Comment by Coureere** [comment]
We will have maces for that purpose.

**Comment by jaffjafferson** [comment]
reopened because i was told it was not wack, maybe still wack?, shits wack

**Comment by jaffjafferson** [comment]
fuck shit is seriously wack

**Comment by jaffjafferson** [comment]
shits wack and coderman told me to close it and open the unwack version

**Pull request closed without merging**
