### PR TITLE
Rage cage now mapped

### PR DESCRIPTION
**Pull request by fernandos13**
## About The Pull Request
officially maps rage cage in:
https://gyazo.com/8ad1af4fa85ceed8b0c02729689341fe

comes with the rage cage
a rag and a plate

also a new gamble booth north of the cage, with fancy glass to tint from inside the both. and a button to open and close the cage

"""the cage is """"locked""" with a showcase allowing for it to be broken"""

plus access is public so anyone can open and close it. 

## Why It's Good For The Game
add some stimuli for the bar and a new attraction. its really rare to see the rage cage done. but when its there people often use it, lets make it official

## Changelog
:cl:
add: rage cage
/:cl:

### CODE REVIEW

**Comment by fernandos13** [comment]
travis will spot the X and Y error don't worry i'm waiting for him to make it so i can fix it
for some reason all map merge i try it happens

**Comment by fernandos13** [comment]
fix commited and going up at any moment

**Comment by fernandos13** [comment]
and ready

**Comment by Alanii** [comment]
No one discusses much in comments regarding PRs, but I have to say few thing.

The 'Rage Cage' is normally reserved for Vagabonds for Vagabonds, and normally built by Vagabonds for entertainment. The Club Manager gives permission if it can be built or not and a lot of the time, the Club doesn't see any profit from such actions.

Simply mapping it into the club would mean the Vagabonds are related the Club in some manner.

I would suggest instead of putting the rage cage in main areas, for you to throw it into a maintenance area that is seldomly used anymore. This way the vagabonds can have their prebuilt rage cage, and if they want too, continue to build one in the Club when permitted by the club's owner.

Simply throwing it into the Club makes few sense relating to why it would be there in first place.

**Comment by AMM101902** [comment]
Alternative areas would be the area above guild lobby, and the area above holodeck in maint. The first one is a public area thats unused and isn't owned by a faction, and the latter is a large unused space in maint.

**Comment by Sparrowbird611** [comment]
> No one discusses much in comments regarding PRs, but I have to say few thing.
> 
> The 'Rage Cage' is normally reserved for Vagabonds for Vagabonds, and normally built by Vagabonds for entertainment. The Club Manager gives permission if it can be built or not and a lot of the time, the Club doesn't see any profit from such actions.
> 
> Simply mapping it into the club would mean the Vagabonds are related the Club in some manner.
> 
> I would suggest instead of putting the rage cage in main areas, for you to throw it into a maintenance area that is seldomly used anymore. This way the vagabonds can have their prebuilt rage cage, and if they want too, continue to build one in the Club when permitted by the club's owner.
> 
> Simply throwing it into the Club makes few sense relating to why it would be there in first place.

Think of it this way, since I've actually seen it work out this way in the past. The rage cage attracts customers who otherwise wouldn't come to the rage cage. People are more likely to buy products if they came to see the rage cage, since they're already there, and they might as well fill up their hunger while they watch. This isn't even mentioning the fact that if the rage cage is in the bar, the club manager has the potential to charge people to watch fights.

Rage cage fights are an amusing event, and the bar benefits from having more people come to watch the fights. Having the cage there makes the bar just a little bit more into what it should be, a place where you chill, socialize, and eat/drink while you amuse yourself.

Additionally, it isn't just vagabonds who enter the rage cage. Sure, they're some of the main ones, but I've seen more than enough technomancers and Ironhammer operatives enter the ring, and hell, even a few clowns.

All in all, I think this is a good thing for the bar to have.

**Comment by Voldirs** [comment]
Rage cages are awfull. Please don't turn Eris into a decivilized piece of steel by design. It goes so during round. Leave it somewhere in maints.
Just add piano to club...

**Comment by Firefox13** [comment]
изображение
These windows look odd in the dream maker... Are you sure you used proper spawners?

**Comment by SpadesSlick** [comment]
Mapping here is just plainly bad. It's not mergeble in current state.

**Comment by fernandos13** [comment]
> изображение
> These windows look odd in the dream maker... Are you sure you used proper spawners?

also this are polarized windows they can be like a regular window, are like a dark tinted without any light coming in

**Pull request closed without merging**
