### PR TITLE
Layers. Fix #1845, fix 1841

### LINKED ISSUE #1841: Coffin invisible under mass driver
plane or layering issue

### LINKED ISSUE #1845: Altar hides chatbox
plane or layering issue

### PR DESCRIPTION
**Pull request by LethalGhost**
Fix typing indicators and massdriver layers.
TODO: merge typing indicaotors in one.

Edit by nanako:
fixes #1845
fixes #1841

### CODE REVIEW

**Comment by NanakoAC** [comment]
Please reference the issues you're fixing

I assume that this PR fixes #1845 
and also fixes #1841?

Got to mention them like that so the issues will be autoclosed

**Comment by LethalGhost** [comment]
I know how to do that but thanks for issues IDs.

**Comment by NanakoAC** [comment]
it doesnt have to be in the title, i personally find it neater to do in the PR description, works just the same <3

**Comment by NanakoAC** [comment]
Infact it seems putting it in the title doesnt work at all?
only my reference shows https://i.imgur.com/mCtPrOL.png

**Pull request merged**
