### PR TITLE
Revert "Seize means of fatfingering"

### PR DESCRIPTION
**Pull request by Firefox13**
Reverts discordia-space/CEV-Eris#7696

For some reason it works fine on local but not on live server.

### CODE REVIEW

**Comment by Firefox13** [comment]
I'll fix it
Later
:tm:

**Comment by SirRichardFrancis** [comment]
Think guy who reported stash missing just messed something up. Code of spawning stash is the same.

**Comment by Firefox13** [comment]
I just tested it on live. It does not work.

**Comment by ValoTheValo** [comment]
> Think guy who reported stash missing just messed something up. Code of spawning stash is the same.

it doesnt. about 3 more missing stash spawns happened since then. not one successful and fox tested it on live and it didn't work

**Pull request merged**
