### PR TITLE
Burst fire define, zoom factor fix, aim code removal.

### PR DESCRIPTION
**Pull request by Kurgis**
## About The Pull Request
@Kmc2000 Burst fire now uses a define, automatic weapons no longer inherit zoom factor, removes aim code that was passed over when the mechanic was being removed.

## Why It's Good For The Game
Easier to edit firemodes in a uniform way, removes old deprecated stuff, every firearm doesn't allow you to zoom out ridiculously far.

## Changelog
:cl:
balance: You can no longer aim down an entire hallway with the AK or other automatic weapons without a scope.
refactor: Burst fire now uses a define for better uniformity.
/:cl:

### CODE REVIEW

**Comment by drexample** [comment]
@Kurgis was the code tested aside from compiling?

**Comment by Kurgis** [comment]
@drexample Yes, it's working in-game.

**Comment by drexample** [comment]
@Kurgis, please fix the conflict

**Comment by Kurgis** [comment]
resolved

**Pull request merged**
