### PR TITLE
large syringe price change. and typo in tastes, amd Emt plus medical belt changes

### PR DESCRIPTION
**Pull request by fernandos13**
large syringe now uses 1 silver. and is in Moebius Medical Designs" (20 liscense points)

typo in the "taste like"

EMT now can hold everything that regular medical belt does, except for the blood bag plus:
crowbar
mini extinguisher
and flashlight,

that medical belt can now hold bloodbags

and both are able to hold glasses and gloves to make surgery swaps easier, if you wanna go for that

## About The Pull Request
large syringe now uses 1 silver. and in Moebius Medical Designs" (20 liscense points)

typo in the "taste like"

gives medical belts and EMT belts some more unique stuff

## Why It's Good For The Game
fixes

picking up one belt or the other should be more of a choice now

## Changelog
:cl:Fernandos33
balance: large syringe now uses 1 silver. and is in Moebius Medical Designs" (20 liscense points)
fix: typo in the "THIS taste like"
add: EMT now holds, crowbar, mini extinguisherand, flashlight.
add: medical belt can now hold bloodbags
/:cl:

### CODE REVIEW

**Comment by GrayRachnid** [comment]
image

**Comment by fernandos13** [comment]
i'll fix that too. thanks

**Comment by TheShown911** [comment]
You could probably use `can_hold_extra` similarly to how it's used in https://github.com/discordia-space/CEV-Eris/pull/5487 for a smaller wall of text

**Comment by fernandos13** [comment]
if i do that it will make the EMT belt a straight upgrade from medical. not a different option. and it would make so the IV bags that is now unique to medical belt. also a option for the EMT. ((giving the player no reason to pick the medical, and making it a noob trap))

**Comment by Firefox13** [comment]
~~do we really need two separate belts?~~

**Comment by fernandos13** [comment]
i mean we already have them.. so why not make their difference more than just.. an icon

**Review by TheShown911 — APPROVED** [review]

**Review by genessee596 — APPROVED** [review]
Delegate stamp of approval.

I always thought it was weird how normal syringes costed the same as large syringes. This'll make sure that normal syringes stay relevant.

Already got code review from Shown, so this PR is ready to go.

**Comment by genessee596** [comment]
Got this cleared by Shown to merge. Congrats.

**Pull request merged**
