### PR TITLE
Mortem supply pack

### PR DESCRIPTION
**Pull request by HentaiStorm**
## About The Pull Request

Gifts for the approaching Halloween

## Why It's Good For The Game

1. Add stutter with russian language
2. Remove checking `SSticker.current_state` in character's setup view = Instant dressing a character in setup
3. Refactoring `/obj/effect/overmap/ship/proc/handle_wraparound()` = Adds the ability to move the ship across space boundaries
4. Add `apply_sanity_effect` in `/datum/reagent/drink/affect_ingest` = Adds the ability to gain insight for desires by light drinks
5. Replace `"Vagabond"` by `ASSISTANT_TITLE` = More control over vagabonds in code
6. Add `is_hot` proc for rag = Corrects fuel ignition with a rag
7. Replace most important` usr << browse` by nanoui with utf8 = Some windows having support of russian language
8. Dress in loadout replaced by this valid `*/gray` subtype = Corrects to view dressing in loadout
9. Add `standing.color = belt.color` in `update_icons` = Corrects to view belt color
10. Refactoring kaiser `gas_attack` proc = Fix the Kaiser ability to make gas attack 
11. Add `desires.Cut()` in `finish_rest()` = Corrects getting rest to prevent getting a double rest
12. Add `organ.replaced(organ.get_limb())` = Corrects to valid reattach organ

No idea what the updated rust_g.dll is doing here, but it has more features

## Changelog
:cl:
add: Add stutter with russian language
fix: Instant dressing a character in setup
add: Adds the ability to move the ship across space boundaries
add: Adds the ability to gain insight for desires by light drinks
code: More control over vagabonds in code
fix: Corrects fuel ignition with a rag
fix: Some windows have nanoui with russian language support
fix: Corrects to view belt color
add: Adds the Kaiser ability to make gas attack 
fix: Corrects getting rest to prevent getting a double rest
fix: Corrects to valid reattach organ
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
vagabonds already are not on the manifest

**Comment by HentaiStorm** [comment]
> vagabonds already are not on the manifest
```
/datum/datacore/proc/manifest_inject(var/mob/living/carbon/human/H)
-	if(H.mind && !player_is_antag(H.mind, only_offstation_roles = 1) && H.job != "VagaBond")
+	if(H.mind && !player_is_antag(H.mind, only_offstation_roles = 1) && H.job != ASSISTANT_TITLE)
```
Maybe you mean the records?

**Comment by zombiemimic** [comment]
that's a lotta fuckin commits

**Comment by Firefox13** [comment]
Vagabonds already do not appear in crew manifest/records. Are you fixing your downstream bugs that nonexistent on upstream?

**Comment by Firefox13** [comment]
Also yeah those commits...

**Review by SirRichardFrancis — CHANGES_REQUESTED** [review]
Firstly, https://www.google.com/search?q=commit+squash
Secondly, changes to the rust_g.dll shouldn't be here.
Merging a PR that does god knows what changes to a library is a really, really bad idea.
All I can say is that checksum of this and any of rust_g releases since may do not match.

image

**Comment by ValoTheValo** [comment]
Also please atomize your prs i beg you. This is like 19 unrelated changes

**Pull request closed without merging**
