### PR TITLE
Balaclava Resprite

### PR DESCRIPTION
**Pull request by Medcar**
## About The Pull Request

Resprites balaclava and adds it to the vending machine
## Why It's Good For The Game

Old sprite bad, new one good, and now it's obtainable
image

## Changelog
:cl: Code - Medcar | Sprite - CeUvi
add: Added new balaclava sprite and added it to the vending machine
/:cl:

### CODE REVIEW

**Comment by drexample** [comment]
WHY IS IT CALLED THAT

**Comment by CeUvi** [comment]
> WHY IS IT CALLED THAT

yes

**Comment by infraredbaron** [comment]
Why we need another one?

**Comment by Medcar** [comment]
> Why we need another one?

This one is obtainable

**Comment by infraredbaron** [comment]
> > Why we need another one?
> 
> This one is obtainable

I have to upset you - the other one is pretty easy to obtain as well

**Review by Firefox13 — CHANGES_REQUESTED** [review]
What is the point of having two absolutely almost the same sprites without any noticeable changes? If you want to add a new balaclava, replace its parent with your new sprite, old one is ugly.
And isn't "sosalka" is a balaclava with mouth cut?

**Comment by Medcar** [comment]
Changes done

**Pull request closed without merging**
