### PR TITLE
Add more designs to back alley organs disk + organ descriptions

### PR DESCRIPTION
**Pull request by Kegdo**
## About The Pull Request
Adds more organs with buffed stats to the back alley disk.
Super-strength muscle (muscle 1.5x eff, 0.6 size)
Hypersensitive nerves (nerve 1.5x eff, 0.1 size)
Extensive blood vessels (blood 1.5x eff, 0.6 size)
Five chamber heart (heart 1.5x eff, 2,3 size)
Gargantuan liver (liver eff 1.5, size 1.2)
image
Added descriptions to most organic vital organs. I tried to make as many puns as possible.
## Why It's Good For The Game
Not enough upgraded organs to mess around with.
No descriptions on certain items.

## Changelog
:cl:
add: Added upgraded versions of muscles, nerves, blood vessesl, heart and liver in the back alley organs disk.  Sprites done by SPCR/MLGTASTICa
tweak: descriptions for organic vital organs.
/:cl:

### CODE REVIEW

**Comment by Humonitarian** [comment]
Weren't nerves 0 size?

**Comment by Humonitarian** [comment]
Yup, sensitive nerves shouldn't be bigger than even regular muscles.

The niché of nerves is taking up no space, but causing pain.

**Comment by Kegdo** [comment]
> Yup, sensitive nerves shouldn't be bigger than even regular muscles.
> 
> The niché of nerves is taking up no space, but causing pain.

sure, here.

**Comment by TheShown911** [comment]
Did you get permission to yoink all of these PR-s? Also i still think organs but bigger on a disc are boring

**Comment by Kegdo** [comment]
Yes, spcr said this is "based." And I think it's a good feature. Maybe boring, sure, but it's a way to make yourself stronger without adding steel implants(that are rejected by cruciform)
Also, I thought about adding printing basic and chonky organs to bio research tree, but I'll do it later.

**Comment by drexample** [comment]
All is well, but the organs need more creative names, those sound kinda bland

**Comment by Kegdo** [comment]
> All is well, but the organs need more creative names, those sound kinda bland

@drexample here, made them a bit better.

**Pull request merged**
