### PR TITLE
Autodoc

### PR DESCRIPTION
**Pull request by soslow4u**
**Adds:**
1. Autodoc machine with that would need your ID and monies ready to get you healthy
2. Autodoc RIG module, that would 'fail'(not really) when you move. You can find it in uplink, yey
3. Autodoc circuit and autodoc processor datums: communist and capitalist edition

capitalism edition
**How does it work:**
You scan - it shows you list of organs with available operations
You pick operations or you jam button to do everything
You wait - it does its job done
No real medical stuff like chems is used there 

**Possible operations**
- Toxin kelation: just lowers your toxins
- Fix damage: fixes both brute and burn 
- Treat wounds: salves, closes, patches and disinfects open _external_ wounds
- Rest is self-explanatory

**Needed:**
1. Sprite for autodoc machine
2. Guideline how to keep this bitflag clusterfuck readable enough
3. Suggestions about prices
4. Feature requests
5. Hella cool bodypart buttons in autodoc UI

### CODE REVIEW

**Comment by fernandos33** [comment]
the shrapnel removal on head. works like regular surgery?
(in the way that it may take the implant out?)

**Comment by MrFoxik** [comment]
Are you sure, that will work same with baymed? That stuff will need some rework after it. Probably.

**Comment by soslow4u** [comment]
> the shrapnel removal on head. works like regular surgery?
It looks only for shrapnel, all other implants are ignored
> Are you sure, that will work same with baymed?
Sure not, but feature was suggested and requested right now

**Comment by soslow4u** [comment]
Main issue I would point out that this machine wont do anything about stumps and limb replacement. By the way its not clear what to do about it in current state

As suggestion: add new menu with cool augments like new arms and legs, arm blades, integrated toolsets and such. With extra costs, of course and based on research tech levels

**Comment by ACCount12** [comment]
I think that it shouldn't manufacture its own implants, modules, limbs, etc. It should merely install what was inserted into it. Augs can be sold in a separate vendomat, and doing so allows people to install augs they found or "found" elsewhere.

**Comment by infraredbaron** [comment]
[autodock.zip](https://github.com/discordia-space/CEV-Eris/files/3349265/autodock.zip)
Got sprites for ya

**Comment by ACCount12** [comment]
Your Travis is failing.

**Comment by soslow4u** [comment]
Any issues since last commit?

**Comment by SpadesSlick** [comment]
Will be done in different PR.

**Pull request closed without merging**
