### PR TITLE
Leather satchels are stylish

### PR DESCRIPTION
**Pull request by Humonitarian**
## About The Pull Request

Makes leather satchels stylish, but have less storage space (28->20)

## Why It's Good For The Game

Sacrificing storage space for style is cool

## Changelog
:cl:
balance: leather satchel has less storage space, but is stylish
/:cl:

### CODE REVIEW

**Comment by Iglpigl** [comment]
One of the worst PRs I ever seen, I recommend immediately closing it and gitbanning the person who made this abomination.

**Comment by Alliostra** [comment]
> One of the worst PRs I ever seen, I recommend immediately closing it and gitbanning the person who made this abomination.

I don't make PRs i am the commenter of PRs and you broke the rules buddy, https://wiki.cev-eris.com/Content_GuidelinesEn you should try reading these. This PR is useless and you should be ashamed you ever made it, get out of my sight.

**Comment by Iglpigl** [comment]
You joke but humon has so far successfully been advancing his scheme to systematically destroy cev eris with him and his balancetards followers coding things bad for the game and this is the final nail in the coffin, we must stop him before it's too late.

**Comment by ValoTheValo** [comment]
awful PR

**Comment by Humonitarian** [comment]
What the fuck did you just say about my design document, you little delegate? I'll have you know I graduated top of my slave group in the shaft. I've been involved in numerous secret loot reworks on al-sojourn and I have over 300 confirmed leaderboard points. I'm trained in gorilla designing and I'm the top miner in the entire CEV Eris administration. You are nothing to me but just another incentivized order. I will wipe your design doc the fuck out with precision the likes of which have never been seen before on this earth, mark my fucking comments. You think you can get away with writing that "design documentation" over the internet? Think again, delegate. As we speak, I am contacting my secret network of maintainers across the github and your repository is being traced right now, so you better prepare for the report, faggot. the report of inappropriate language that wipes out the pathetic little thing you call your google doc. I can be anywhere, anytime I want, and I can implement my changes in over 700 ways, and that's just with the bare github editor. Not only am I extensively trained in untrained coding, but I have access to entire patreon donations of the CEV Eris cyberpunk roleplaying server and I will will use it to it's full extent to wipe your miserable little code off the face of the server, you little shit. If only you could've known what unholy code you little "clever" design doc was about to bring down upon you, maybe you would've held your fucking tongue. But you couldn't, you didn't, and now you're paying the price. I will shit code all over you and you will drown in it. You're fucking design'd, delegato.

**Comment by SirRichardFrancis** [comment]
Surprise surprise. Yet ANOTHER balance PR. It's only been the fiftieth time this weekend. Ever notice how Humon ALWAYS breaks stuff in another dumbass PR, or ALWAYS pushes some ridiculous balance change? You think this is a coincidence? I think not, especially with allegations that balancetards has accepted donations to buff people's favorite metas. Do you think a person like him wouldn't alter his own favorite meta to ALWAYS WIN CQC? I don't think so. Admins? I leave the case in your hands

**Comment by Humonitarian** [comment]
I do need balance. And shitcode. Wanna know why? "I have a dream." That one day, every person in this server will code their OWN destiny. A codebase of the TRULY free, dammit. A server of FEATURE PRs, not comments. Ruled by DESIGN DOCS, not rushed PRs. Where the guideline changes to suit the individual, not the other way around. Where merge rights and coder control are back where they belong: in the hands of the people! Where every man is free to think -- to act -- for himself! Fuck all these limp-dick maintainers and chicken-shit development delegates. Fuck this 24/7 Internet spew of trivia and sinbin bullshit. Fuck "Eris balance". Fuck all of it! Eris is diseased. Rotten to the core. There's no saving it -- we need to pull it out by the roots. Wipe the slate clean. BURN IT DOWN! And from the ashes, a new Eris will be born. Evolved, but untamed! The balancers will be purged, and the feature coders will thrive -- free to live as they see fit, they will make Eris GREAT AGAIN!

**Comment by SirRichardFrancis** [comment]
Whenever I check this server's github there is a 75% chance that a PR would be balance-related and I honestly really dig reading how developers justify their 0.05 modifier change, I get off on it. You people will never realize that the reason this server is going downhill is that nobody wants to be in charge and set a development plan for the server (a plan that is actually followed don't talk to me about that googledoc thingy with scuffed and fancy headlines that never got achieved) gray lost interest after the great plasma burn, reere went to get milk and abandoned us and only 5% of the devs actively play the game.
A server full of project hoarders, they pick 10 project then work on all of them at the same time ditching them then moving on to a new smaller project.
Every launch I check the devblog and it's at most gun balancing (which is not needed), or misc stuff and whenever you say that the lack of new features is killing the server they say (wyci lul).
In a last effort to try to fix the server management did 2 things.
-add new admina to an almost dead server.
- a fucking lore channel(many actually) to a server where the peak RP situation you can be put in is getting executed by IH and thrown out of the airlock.
I hope that the devs set their balancetardism aside and work on 1 or 2 projects at most so the server actually goes forward.

**Comment by GrayRachnid** [comment]
i was going to leave valo's message up but I might as well nuke it with everything else

**Review by Firefox13 — APPROVED** [review]
Oh the humanity

**Comment by TheShown911** [comment]
One of the worst PRs I ever seen, I recommend immediately closing it and gitbanning the person who made this abomination.

**Pull request merged**
