### PR TITLE
Technomancer rig suit

### PR DESCRIPTION
**Pull request by Medcar**
## About The Pull Request

Adds the techno rig

## Why It's Good For The Game

Techno content

## Changelog
:cl: Medcar - Code | CeUvi - sprite
add: Added techno rig suit and the disk for it
/:cl:
image

It takes around 50 plastic, 12 plasteel, 30 steel, 6 glass and 3 silver to print
It also scales with the lathe nerf so unless you print it in the nanoforge it will be shitty
~~firefox please merge this before other sprite prs I don't want to experience icon conflict cbt~~

### CODE REVIEW

**Comment by granodd** [comment]
The shading and coloring on the in-hand sprites looks good. Though it looks a little odd without the capes or cloths that the other techno suits have. The torso all being a singular piece in the front that stretches down to the groin also gives off a bit of a 'tubby' look. Overall I think its fine, though perhaps touch up on the front plate of the chest, and possibly cloth around the legs like the technos' voidsuit.

**Comment by Omni44** [comment]
I don't like it being printable. None of the RIGs are, heck, you can't even print TM voidsuits in game. It's also extremely cheap compared to other armors in game, and can be produced infinitely. Better yet, it has 0 slowdown when online, drain of 2, 50/40/50 protection, has complete fire protectionand  can be produced for everyone cheaply...
Compare it to RIGs we already have in game, This is better than Crimson RIG dude, it's madness

RIGs

**Comment by Sparrowbird611** [comment]
Not completely sure about letting these be printable. I would say at least make the disk limited and give some roundstart stock, but I find it difficult to judge anything when we let NT have infinite heavy armor disks. It's probably ok, but you should see about putting a few in the suit storage section technos have.

**Review by Firefox13 — CHANGES_REQUESTED** [review]
Should've also said it here:
Putting a hardsuit onto a autolathe disk is absolutely a no-no. They should follow IH(or paramedics, your call) pattern - one or two of them lying in a voidsuit room with modules near them.

**Comment by Firefox13** [comment]
This PR will be closed on next friday if no activity is shown regarding the requested changes.

**Comment by Firefox13** [comment]
Closing this PR since #6330 has been merged

**Pull request closed without merging**
