### PR TITLE
Remove twirling humans on help intent

### PR DESCRIPTION
**Pull request by ErisMeleeEnjoyer**
## About The Pull Request
removed the twirling proc that happened when both the attacker and the victim have help intents

## Why It's Good For The Game

i have been told that people sometimes they keep twirling people around instead of irish whipping them. Haram!
Besides, this is obscure and bloat. ~~and this is also not written on wiki because I was unaware of this~~
## Changelog
:cl:
del: twirling instead of irish whipping on help intent
/:cl:

### CODE REVIEW

**Comment by assortedbeads** [comment]
Skill issue, they shouldn't have been on help intent

**Comment by L74814** [comment]
soulless

**Comment by Humonitarian** [comment]
Skill issue, just get a better mindset (intent to harm)

**Comment by ErisMeleeEnjoyer** [comment]
Yes, this is a salt PR and a skill issue. I don't care. I am forklift certified.

**Review by TheShown911 — APPROVED** [review]

**Pull request merged**
