### PR TITLE
Shaper Devcice

### PR DESCRIPTION
**Pull request by sgtmind**
## About The Pull Request
Adds in the Shaper Device from the Design Document

## Why It's Good For The Game

Adds a far faster way of building and rebuilding things without going through the tedious process of builing one item at a time

## Changelog
:cl:
add: Added new things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by SirRichardFrancis** [comment]
Uh oh. I'm afraid letting technomancers using regular buildmode (with no constraints even) would be absolutely disastrous.

**Comment by sgtmind** [comment]
> Uh oh. I'm afraid letting technomancers use regular buildmode (with no constraints even) would be absolutely disastrous.

Shit, I forgot to set it to draft

**Comment by sgtmind** [comment]
I am putting this here more in case others wis to contribute

**Comment by assortedbeads** [comment]
> Uh oh. I'm afraid letting technomancers use regular buildmode (with no constraints even) would be absolutely disastrous.

Let me play eris creative mode :guncat:

**Comment by DiaFRAME444** [comment]
Do it.

**Comment by sgtmind** [comment]
I am closing this because I realized that this is WAY too complicated, especially when I barely have experience

**Pull request closed without merging**
