### PR TITLE
Added head and torso prosthesis to tech and fabricator

### PR DESCRIPTION
**Pull request by AManofCoding**
## About The Pull Request

Added regular and advanced head and torso prosthesis to known designs. Changed prosthesis to moebius type instead of unbranded for aesthetics.

## Why It's Good For The Game

You can now make any body part as a prosthesis. It also makes sense that moebius makes their own branded prosthesis.

## Changelog
:cl:
add: added torso and head to basic biotech
add: added reinforced torso to augmentations biotech
change: changed basic prosthesis type to moebius instead of unbranded
/:cl:

### CODE REVIEW

**Comment by GrayRachnid** [comment]
how does it spawn

**Comment by ValoTheValo** [comment]
torsos are unusable but the heads can be used

**Comment by AltHit** [comment]
But kill contact from uplink can be completed with brainless old head, which means completing kill contract without any killing just by changing person's head prosthesis
That sounds like a balance issue

**Comment by AManofCoding** [comment]
> how does it spawn

It just works. It seems to be made by the exosuit fabricator just fine.

**Comment by Rexdyer1** [comment]
can you add basic robotic organs too? if someone loses their eyes or something they are basically game overed

**Review by TheShown911 — APPROVED** [review]

**Pull request merged**
