### PR TITLE
Splinting no longer prevents ALL downsides on limbs + general timer limit

### PR DESCRIPTION
**Pull request by MLGTASTICa**
## About The Pull Request
Splinting no longer prevents all downsides from having shrapnel , having a splinted limb with shrapnel will now give pain
Splinting a organ no longer prevents all bone break related effects ,(no longer prevents dropping items in hand fully , just makes them very rare , but still prevents full damage)
Makes timers prevent stacking in general
## Why It's Good For The Game
Splint your organ prematurely , never fix your bone, get shrapnel , never lose the splint? profit .
Adds timer management that prevents stacking timers in general
## Changelog
:cl:
balance: Splints no longer fully prevent effects from having shrapnel
balance : Splints no longer fully block effects from a limb being broken
fix: Fixed timers not being checked for stacking in general.

/:cl:

### CODE REVIEW

**Comment by SirRichardFrancis** [comment]
Might just remove splints from the game at that point.

**Comment by mattroks101** [comment]
Those should be two separate PRs.

**Comment by MLGTASTICa** [comment]
> Those should be two separate PRs.

Eh , i'd be surprised if this doesn't get merged, splinting right now fully negates the need for surgery when done.

**Comment by mattroks101** [comment]
> > Those should be two separate PRs.
> 
> Eh , i'd be surprised if this doesn't get merged, splinting right now fully negates the need for surgery when done.

These should be two separate PRs because the changes have nothing to do with each other. You should stack unrelated changes in PRs like this.

**Comment by drexample** [comment]
Those should be two separate PRs.

**Pull request closed without merging**
