### PR TITLE
Advanced Tools disk for technomancers on a table in their spawn.

### PR DESCRIPTION
**Pull request by MacBlaze1**
## About The Pull Request
<details>
<summary>
	Technomancers get an Advanced Tools disk in their equipment and spawn room.
</summary>
<hr>
Technos deserve this because they are easily outpaced at their jobs by anyone else, and the lore says they have advanced tech. This will also give people an incentive to play technomancer.
<hr>
</details>
## Changelog
:cl:
add: Added an advanced tools disk to the engineering equipment and spawn room.
/:cl:

### CODE REVIEW

**Comment by SpadesSlick** [comment]
That's an item they suppose to scavenge in maints.

**Comment by MacBlaze1** [comment]
> That's an item they suppose to scavenge in maints.

I thought the lore said they had advanced technology, and we give them average tools? Its also an incentive to play technomancer.

**Comment by runecap** [comment]
Usually guild takes the Techno supertools disk and the department never buys it, or they're just too lazy to switch to unmodded tools. I'd prefer if they just started with a toolbelt FULL of advanced tools.

**Comment by SpadesSlick** [comment]
We shall fix this with adding more features to technos later, but providing them with gear meant for looting is not a good solution.

**Pull request closed without merging**
