### PR TITLE
Adds a chemial recipe for nicotine.

### PR DESCRIPTION
**Pull request by Jan-Blasiak**
## About The Pull Request
It's my first pull request ever, decided for something easy. It's a recipe for nicotine, same as in cigarettes.

## Screenshots

cev WIN

### CODE REVIEW

**Comment by Jackofashepard** [comment]
A diamond brought from the mines, you made us proud son

**Comment by TorinoFermic** [comment]
It looks nice but can you show me how to make toxins chem to complete the recipe ?

**Comment by Jan-Blasiak** [comment]
Toxin is a base ingredient from what I remember. You can find one bottle in some staff room in medical main floor. SW part as far as I remember.

Or simply spawn a bottle with debug.

**Comment by Jan-Blasiak** [comment]
On the photo, I've been screwing around trying to get capsaicin, neither pepper nor spray had what I needed.

**Comment by TorinoFermic** [comment]
> 
> 
> On the photo, I've been screwing around trying to get capsaicin, neither pepper nor spray had what I needed.
> 
> In the end I spawned it

capsaicin could come from plants, thus tying with botany. but toxins needs to be made or as a loot, but I think they can ground up from expired food found in maints.

**Comment by Jan-Blasiak** [comment]
Aaah, so that's why I almost died last time...

**Comment by TorinoFermic** [comment]
MRE foods are excluded from being toxic because they are Meals Ready to Eat meant to last years.

**Comment by Anonmare** [comment]
Toxin can be acquired by thermally decomposing Pararein and other venoms as well.

The recipe seems fine, capascin'll require botanical cooperation so I don't see an issue. Nictoine's a really weak painkiller and sanity buffer so it's not got any balance concerns.

**Pull request merged**
