### PR TITLE
[Icons needed]The grand stim update (Adds 2 stim related perks!)

### PR DESCRIPTION
**Pull request by MLGTASTICa**
## About The Pull Request
Adds DeathWish perk for Menace
-Makes you take 0 pain
-Heals you by 25 brute and burn on use. 
-Lets you fire two-handed guns with only 1 gun
-Removes weapon recoil
-Makes you incapable of vomiting
-You have a huge change to counter any agressive grab
-You deal 30 more brute with punching
-You have a high chance to block enemy punches
-Lets you snap the necks of grabbed enemies as long as they're not wearing a rig/voidsuit (breaks the blood vessels in the head , deals pain and oxyloss)

When all of the menace has metabolized , it deals 80 heart damage and 50 hallos

Adds AtomicTouch perk for Partydrops
-Gives you basic AI shortcuts for doors/apc/atmos (as long as you actually have the acces)
-Gun assemblies give 7 more options
-Genetics Decoder  is way faster when you are on partydrops
-Acces decrypter is always silent and 4 times faster when on partydrops
-Tool usage is now instant , regardless of pain

When all of the party drops is gone , it deals 50 brain damage.

## Why It's Good For The Game
These stims are quite the challange to make by default , they should be rewarding , considering their extreme NSA.
They both require atleast 3 units in volume to work, and get removed when below.
Also , far more fun in general.

## Changelog
:cl:
add: Deathwish perk for menace
add: Atomic Touch perk for partydrops
code: Added AI-CONTROL-LIKE component , can be applied to any human to simulate AI controls
code: Added Shift, Ctrl and Alt click signals for mobs.
/:cl:

### CODE REVIEW

**Comment by null-Aurelian** [comment]
I think these are some very neat ideas, but I'd like to know what the metabolism rate is for these drugs and how long we can expect them to stay in a player's system assuming this is a full 30u injection or 120u beaker consumed

**Comment by null-Aurelian** [comment]
Another idea might be to split/atomize the perk effects across the component stims

**Comment by Humonitarian** [comment]
Atomize this PR, as requested above.

Other than that,

> -Makes you take 0 pain

I'd rather see the pain threshold go into the sky

> -Heals you by 25 brute and burn on use.

As stated long before, instant healing effects are not a good idea, even with the severe organ damage when the chemical leaves the system

-Lets you fire two-handed guns with only 1 gun

Ridiculously powerful

-Removes weapon recoil

Ridiculously powerful (makes you reliably hit the head with every bullet from a takeshi with no bullet spray)

-Makes you incapable of vomiting

Considering this is a chem that was supposed to carry the disadvantage of NSA, this is also broken. It'll allow combining it with a load of healing chems with little to no real disadvantage.

-You have a huge change to counter any agressive grab

Already covered in the Robustness buff

-You deal 30 more brute with punching

I'd rather see some kind of general buff to all melee. Other than that, 30 is excessive, even if melee in on itself isn't strong.

-You have a high chance to block enemy punches

Why?

-Lets you snap the necks of grabbed enemies as long as they're not wearing a rig/voidsuit (breaks the blood vessels in the head , deals pain and oxyloss)

Once again making melee worthless compared to the might of grabfu

As for party drops, instant tool usage is a massive balance risk, as it allows instant repairs.

As for the instant organ damages when the chem is metabolized, guh? Might want some sort of withdrawal effect instead?

**Comment by ValoTheValo** [comment]
the party drops changes are just awful. it goes from a niche utility Chem into being an active detriment to you. 

menace is now just plain overpowered. instant healing, no pain, full accuracy and dual wielding LMGs. and the damage at the end can just be subverted by carrion stasis

also what happened to the contribution guidelines of not massively buffing or nerfing things in one PR

**Comment by Humonitarian** [comment]
> the party drops changes are just awful. it goes from a niche utility Chem into being an active detriment to you.
> 
> menace is now just plain overpowered. instant healing, no pain, full accuracy and dual wielding LMGs. and the damage at the end can just be subverted by carrion stasis. and funny how you started maining chemist right before making this PR
> 
> also what happened to the contribution guidelines of not massively buffing or nerfing things in one PR

Iirc LMGs don't allow akimbo

Plenty guns simply won't doubleshoot due to akimbo being turned off on them, even if they work onehanded

**Comment by ValoTheValo** [comment]
> Iirc LMGs don't allow akimbo
> 
> Plenty guns simply won't doubleshoot due to akimbo being turned off on them, even if they work onehanded

"-Lets you fire two-handed guns with only 1 gun"
Is one of the listed effects

**Comment by MLGTASTICa** [comment]
> > Iirc LMGs don't allow akimbo
> > Plenty guns simply won't doubleshoot due to akimbo being turned off on them, even if they work onehanded
> 
> "-Lets you fire two-handed guns with only 1 gun" Is one of the listed effects

yes it lets you fire two-handed gun with only 1 hand , but you are still firing only 1 gun. You cant fire 2 non-akimbo guns at the same time.

**Comment by MLGTASTICa** [comment]
> Atomize this PR, as requested above.
> 
> Other than that,
> 
> > -Makes you take 0 pain
> 
> I'd rather see the pain threshold go into the sky
> 
> > -Heals you by 25 brute and burn on use.
> 
> As stated long before, instant healing effects are not a good idea, even with the severe organ damage when the chemical leaves the system
> 
> > -Lets you fire two-handed guns with only 1 gun
> 
> Ridiculously powerful
> 
> > -Removes weapon recoil
> 
> Ridiculously powerful (makes you reliably hit the head with every bullet from a takeshi with no bullet spray)
> 
> > -Makes you incapable of vomiting
> 
> Considering this is a chem that was supposed to carry the disadvantage of NSA, this is also broken. It'll allow combining it with a load of healing chems with little to no real disadvantage.
> 
> > -You have a huge change to counter any agressive grab
> 
> Already covered in the Robustness buff
> 
> > -You deal 30 more brute with punching
> 
> I'd rather see some kind of general buff to all melee. Other than that, 30 is excessive, even if melee in on itself isn't strong.
> 
> > -You have a high chance to block enemy punches
> 
> Why?
> 
> > -Lets you snap the necks of grabbed enemies as long as they're not wearing a rig/voidsuit (breaks the blood vessels in the head , deals pain and oxyloss)
> 
> Once again making melee worthless compared to the might of grabfu
> 
> As for party drops, instant tool usage is a massive balance risk, as it allows instant repairs.
> 
> As for the instant organ damages when the chem is metabolized, guh? Might want some sort of withdrawal effect instead?



> Atomize this PR, as requested above.
> 
> Other than that,
> 
> > -Makes you take 0 pain
> 
> I'd rather see the pain threshold go into the sky
> 
> > -Heals you by 25 brute and burn on use.
> 
> As stated long before, instant healing effects are not a good idea, even with the severe organ damage when the chemical leaves the system
> 
> > -Lets you fire two-handed guns with only 1 gun
> 
> Ridiculously powerful
> 
> > -Removes weapon recoil
> 
> Ridiculously powerful (makes you reliably hit the head with every bullet from a takeshi with no bullet spray)
> 
> > -Makes you incapable of vomiting
> 
> Considering this is a chem that was supposed to carry the disadvantage of NSA, this is also broken. It'll allow combining it with a load of healing chems with little to no real disadvantage.
> 
> > -You have a huge change to counter any agressive grab
> 
> Already covered in the Robustness buff
> 
> > -You deal 30 more brute with punching
> 
> I'd rather see some kind of general buff to all melee. Other than that, 30 is excessive, even if melee in on itself isn't strong.
> 
> > -You have a high chance to block enemy punches
> 
> Why?
> 
> > -Lets you snap the necks of grabbed enemies as long as they're not wearing a rig/voidsuit (breaks the blood vessels in the head , deals pain and oxyloss)
> 
> Once again making melee worthless compared to the might of grabfu
> 
> As for party drops, instant tool usage is a massive balance risk, as it allows instant repairs.
> 
> As for the instant organ damages when the chem is metabolized, guh? Might want some sort of withdrawal effect instead?

Pain threshold going into the sky just makes the effects useless , it becomes from a deathtrooper chem to a shitty NSA taker that only stops you from taking any decent painkiller.
Healing on use is not a balance issue, its meant to be used as last resort.
NSA still carries disadvantages,  just pair tramadol and menace together and you will get a heart attack.
Robustness buff increases punch damage by exactly a meager 4.5,  (robustness / 10) , barely worth its cost.
Melle is still very much worthwhile , most  melle's wielded still deal more damage than punching (even with the buff). And when combined with the no-pain aspect , it makes melle-builds more viable.

**Comment by Humonitarian** [comment]
> > Iirc LMGs don't allow akimbo
> > Plenty guns simply won't doubleshoot due to akimbo being turned off on them, even if they work onehanded
> 
> "Lets you fire two-handed guns with only 1 hand" Is one of the listed effects

That's a different mechanism from akimbo.

**Comment by Humonitarian** [comment]
> > Atomize this PR, as requested above.
> > Other than that,
> > > -Makes you take 0 pain
> > 
> > 
> > I'd rather see the pain threshold go into the sky
> > > -Heals you by 25 brute and burn on use.
> > 
> > 
> > As stated long before, instant healing effects are not a good idea, even with the severe organ damage when the chemical leaves the system
> > > -Lets you fire two-handed guns with only 1 gun
> > 
> > 
> > Ridiculously powerful
> > > -Removes weapon recoil
> > 
> > 
> > Ridiculously powerful (makes you reliably hit the head with every bullet from a takeshi with no bullet spray)
> > > -Makes you incapable of vomiting
> > 
> > 
> > Considering this is a chem that was supposed to carry the disadvantage of NSA, this is also broken. It'll allow combining it with a load of healing chems with little to no real disadvantage.
> > > -You have a huge change to counter any agressive grab
> > 
> > 
> > Already covered in the Robustness buff
> > > -You deal 30 more brute with punching
> > 
> > 
> > I'd rather see some kind of general buff to all melee. Other than that, 30 is excessive, even if melee in on itself isn't strong.
> > > -You have a high chance to block enemy punches
> > 
> > 
> > Why?
> > > -Lets you snap the necks of grabbed enemies as long as they're not wearing a rig/voidsuit (breaks the blood vessels in the head , deals pain and oxyloss)
> > 
> > 
> > Once again making melee worthless compared to the might of grabfu
> > As for party drops, instant tool usage is a massive balance risk, as it allows instant repairs.
> > As for the instant organ damages when the chem is metabolized, guh? Might want some sort of withdrawal effect instead?
> 
> > Atomize this PR, as requested above.
> > Other than that,
> > > -Makes you take 0 pain
> > 
> > 
> > I'd rather see the pain threshold go into the sky
> > > -Heals you by 25 brute and burn on use.
> > 
> > 
> > As stated long before, instant healing effects are not a good idea, even with the severe organ damage when the chemical leaves the system
> > > -Lets you fire two-handed guns with only 1 gun
> > 
> > 
> > Ridiculously powerful
> > > -Removes weapon recoil
> > 
> > 
> > Ridiculously powerful (makes you reliably hit the head with every bullet from a takeshi with no bullet spray)
> > > -Makes you incapable of vomiting
> > 
> > 
> > Considering this is a chem that was supposed to carry the disadvantage of NSA, this is also broken. It'll allow combining it with a load of healing chems with little to no real disadvantage.
> > > -You have a huge change to counter any agressive grab
> > 
> > 
> > Already covered in the Robustness buff
> > > -You deal 30 more brute with punching
> > 
> > 
> > I'd rather see some kind of general buff to all melee. Other than that, 30 is excessive, even if melee in on itself isn't strong.
> > > -You have a high chance to block enemy punches
> > 
> > 
> > Why?
> > > -Lets you snap the necks of grabbed enemies as long as they're not wearing a rig/voidsuit (breaks the blood vessels in the head , deals pain and oxyloss)
> > 
> > 
> > Once again making melee worthless compared to the might of grabfu
> > As for party drops, instant tool usage is a massive balance risk, as it allows instant repairs.
> > As for the instant organ damages when the chem is metabolized, guh? Might want some sort of withdrawal effect instead?
> 
> Pain threshold going into the sky just makes the effects useless , it becomes from a deathtrooper chem to a shitty NSA taker that only stops you from taking any decent painkiller. Healing on use is not a balance issue, its meant to be used as last resort. NSA still carries disadvantages, just pair tramadol and menace together and you will get a heart attack. There is no guarantee the robustness PR gets merged , and even if it does , i don't want to see someone on Menace get grab'fud and killed in 25 seconds because they did not spam space fast enough. Robustness buff increases punch damage by exactly a meager 4.5, (robustness / 10) , barely worth its cost. Melle is still very much worthwhile , most melle's wielded still deal more damage than punching (even with the buff). And when combined with the no-pain aspect , it makes melle-builds more viable.

#7198

**Comment by MLGTASTICa** [comment]
> > > Atomize this PR, as requested above.
> > > Other than that,
> > > > -Makes you take 0 pain
> > > 
> > > 
> > > I'd rather see the pain threshold go into the sky
> > > > -Heals you by 25 brute and burn on use.
> > > 
> > > 
> > > As stated long before, instant healing effects are not a good idea, even with the severe organ damage when the chemical leaves the system
> > > > -Lets you fire two-handed guns with only 1 gun
> > > 
> > > 
> > > Ridiculously powerful
> > > > -Removes weapon recoil
> > > 
> > > 
> > > Ridiculously powerful (makes you reliably hit the head with every bullet from a takeshi with no bullet spray)
> > > > -Makes you incapable of vomiting
> > > 
> > > 
> > > Considering this is a chem that was supposed to carry the disadvantage of NSA, this is also broken. It'll allow combining it with a load of healing chems with little to no real disadvantage.
> > > > -You have a huge change to counter any agressive grab
> > > 
> > > 
> > > Already covered in the Robustness buff
> > > > -You deal 30 more brute with punching
> > > 
> > > 
> > > I'd rather see some kind of general buff to all melee. Other than that, 30 is excessive, even if melee in on itself isn't strong.
> > > > -You have a high chance to block enemy punches
> > > 
> > > 
> > > Why?
> > > > -Lets you snap the necks of grabbed enemies as long as they're not wearing a rig/voidsuit (breaks the blood vessels in the head , deals pain and oxyloss)
> > > 
> > > 
> > > Once again making melee worthless compared to the might of grabfu
> > > As for party drops, instant tool usage is a massive balance risk, as it allows instant repairs.
> > > As for the instant organ damages when the chem is metabolized, guh? Might want some sort of withdrawal effect instead?
> > 
> > 
> > > Atomize this PR, as requested above.
> > > Other than that,
> > > > -Makes you take 0 pain
> > > 
> > > 
> > > I'd rather see the pain threshold go into the sky
> > > > -Heals you by 25 brute and burn on use.
> > > 
> > > 
> > > As stated long before, instant healing effects are not a good idea, even with the severe organ damage when the chemical leaves the system
> > > > -Lets you fire two-handed guns with only 1 gun
> > > 
> > > 
> > > Ridiculously powerful
> > > > -Removes weapon recoil
> > > 
> > > 
> > > Ridiculously powerful (makes you reliably hit the head with every bullet from a takeshi with no bullet spray)
> > > > -Makes you incapable of vomiting
> > > 
> > > 
> > > Considering this is a chem that was supposed to carry the disadvantage of NSA, this is also broken. It'll allow combining it with a load of healing chems with little to no real disadvantage.
> > > > -You have a huge change to counter any agressive grab
> > > 
> > > 
> > > Already covered in the Robustness buff
> > > > -You deal 30 more brute with punching
> > > 
> > > 
> > > I'd rather see some kind of general buff to all melee. Other than that, 30 is excessive, even if melee in on itself isn't strong.
> > > > -You have a high chance to block enemy punches
> > > 
> > > 
> > > Why?
> > > > -Lets you snap the necks of grabbed enemies as long as they're not wearing a rig/voidsuit (breaks the blood vessels in the head , deals pain and oxyloss)
> > > 
> > > 
> > > Once again making melee worthless compared to the might of grabfu
> > > As for party drops, instant tool usage is a massive balance risk, as it allows instant repairs.
> > > As for the instant organ damages when the chem is metabolized, guh? Might want some sort of withdrawal effect instead?
> > 
> > 
> > Pain threshold going into the sky just makes the effects useless , it becomes from a deathtrooper chem to a shitty NSA taker that only stops you from taking any decent painkiller. Healing on use is not a balance issue, its meant to be used as last resort. NSA still carries disadvantages, just pair tramadol and menace together and you will get a heart attack. There is no guarantee the robustness PR gets merged , and even if it does , i don't want to see someone on Menace get grab'fud and killed in 25 seconds because they did not spam space fast enough. Robustness buff increases punch damage by exactly a meager 4.5, (robustness / 10) , barely worth its cost. Melle is still very much worthwhile , most melle's wielded still deal more damage than punching (even with the buff). And when combined with the no-pain aspect , it makes melle-builds more viable.
> 
> #7198

the calculations only affect break chance , not speed.

**Comment by Humonitarian** [comment]
> > > > Atomize this PR, as requested above.
> > > > Other than that,
> > > > > -Makes you take 0 pain
> > > > 
> > > > 
> > > > I'd rather see the pain threshold go into the sky
> > > > > -Heals you by 25 brute and burn on use.
> > > > 
> > > > 
> > > > As stated long before, instant healing effects are not a good idea, even with the severe organ damage when the chemical leaves the system
> > > > > -Lets you fire two-handed guns with only 1 gun
> > > > 
> > > > 
> > > > Ridiculously powerful
> > > > > -Removes weapon recoil
> > > > 
> > > > 
> > > > Ridiculously powerful (makes you reliably hit the head with every bullet from a takeshi with no bullet spray)
> > > > > -Makes you incapable of vomiting
> > > > 
> > > > 
> > > > Considering this is a chem that was supposed to carry the disadvantage of NSA, this is also broken. It'll allow combining it with a load of healing chems with little to no real disadvantage.
> > > > > -You have a huge change to counter any agressive grab
> > > > 
> > > > 
> > > > Already covered in the Robustness buff
> > > > > -You deal 30 more brute with punching
> > > > 
> > > > 
> > > > I'd rather see some kind of general buff to all melee. Other than that, 30 is excessive, even if melee in on itself isn't strong.
> > > > > -You have a high chance to block enemy punches
> > > > 
> > > > 
> > > > Why?
> > > > > -Lets you snap the necks of grabbed enemies as long as they're not wearing a rig/voidsuit (breaks the blood vessels in the head , deals pain and oxyloss)
> > > > 
> > > > 
> > > > Once again making melee worthless compared to the might of grabfu
> > > > As for party drops, instant tool usage is a massive balance risk, as it allows instant repairs.
> > > > As for the instant organ damages when the chem is metabolized, guh? Might want some sort of withdrawal effect instead?
> > > 
> > > 
> > > > Atomize this PR, as requested above.
> > > > Other than that,
> > > > > -Makes you take 0 pain
> > > > 
> > > > 
> > > > I'd rather see the pain threshold go into the sky
> > > > > -Heals you by 25 brute and burn on use.
> > > > 
> > > > 
> > > > As stated long before, instant healing effects are not a good idea, even with the severe organ damage when the chemical leaves the system
> > > > > -Lets you fire two-handed guns with only 1 gun
> > > > 
> > > > 
> > > > Ridiculously powerful
> > > > > -Removes weapon recoil
> > > > 
> > > > 
> > > > Ridiculously powerful (makes you reliably hit the head with every bullet from a takeshi with no bullet spray)
> > > > > -Makes you incapable of vomiting
> > > > 
> > > > 
> > > > Considering this is a chem that was supposed to carry the disadvantage of NSA, this is also broken. It'll allow combining it with a load of healing chems with little to no real disadvantage.
> > > > > -You have a huge change to counter any agressive grab
> > > > 
> > > > 
> > > > Already covered in the Robustness buff
> > > > > -You deal 30 more brute with punching
> > > > 
> > > > 
> > > > I'd rather see some kind of general buff to all melee. Other than that, 30 is excessive, even if melee in on itself isn't strong.
> > > > > -You have a high chance to block enemy punches
> > > > 
> > > > 
> > > > Why?
> > > > > -Lets you snap the necks of grabbed enemies as long as they're not wearing a rig/voidsuit (breaks the blood vessels in the head , deals pain and oxyloss)
> > > > 
> > > > 
> > > > Once again making melee worthless compared to the might of grabfu
> > > > As for party drops, instant tool usage is a massive balance risk, as it allows instant repairs.
> > > > As for the instant organ damages when the chem is metabolized, guh? Might want some sort of withdrawal effect instead?
> > > 
> > > 
> > > Pain threshold going into the sky just makes the effects useless , it becomes from a deathtrooper chem to a shitty NSA taker that only stops you from taking any decent painkiller. Healing on use is not a balance issue, its meant to be used as last resort. NSA still carries disadvantages, just pair tramadol and menace together and you will get a heart attack. There is no guarantee the robustness PR gets merged , and even if it does , i don't want to see someone on Menace get grab'fud and killed in 25 seconds because they did not spam space fast enough. Robustness buff increases punch damage by exactly a meager 4.5, (robustness / 10) , barely worth its cost. Melle is still very much worthwhile , most melle's wielded still deal more damage than punching (even with the buff). And when combined with the no-pain aspect , it makes melle-builds more viable.
> > 
> > 
> > #7198
> 
> the calculations only affect break chance , not speed to upgrade the grab.

But it does affect break chance.

**Comment by MLGTASTICa** [comment]
> > > > > Atomize this PR, as requested above.
> > > > > Other than that,
> > > > > > -Makes you take 0 pain
> > > > > 
> > > > > 
> > > > > I'd rather see the pain threshold go into the sky
> > > > > > -Heals you by 25 brute and burn on use.
> > > > > 
> > > > > 
> > > > > As stated long before, instant healing effects are not a good idea, even with the severe organ damage when the chemical leaves the system
> > > > > > -Lets you fire two-handed guns with only 1 gun
> > > > > 
> > > > > 
> > > > > Ridiculously powerful
> > > > > > -Removes weapon recoil
> > > > > 
> > > > > 
> > > > > Ridiculously powerful (makes you reliably hit the head with every bullet from a takeshi with no bullet spray)
> > > > > > -Makes you incapable of vomiting
> > > > > 
> > > > > 
> > > > > Considering this is a chem that was supposed to carry the disadvantage of NSA, this is also broken. It'll allow combining it with a load of healing chems with little to no real disadvantage.
> > > > > > -You have a huge change to counter any agressive grab
> > > > > 
> > > > > 
> > > > > Already covered in the Robustness buff
> > > > > > -You deal 30 more brute with punching
> > > > > 
> > > > > 
> > > > > I'd rather see some kind of general buff to all melee. Other than that, 30 is excessive, even if melee in on itself isn't strong.
> > > > > > -You have a high chance to block enemy punches
> > > > > 
> > > > > 
> > > > > Why?
> > > > > > -Lets you snap the necks of grabbed enemies as long as they're not wearing a rig/voidsuit (breaks the blood vessels in the head , deals pain and oxyloss)
> > > > > 
> > > > > 
> > > > > Once again making melee worthless compared to the might of grabfu
> > > > > As for party drops, instant tool usage is a massive balance risk, as it allows instant repairs.
> > > > > As for the instant organ damages when the chem is metabolized, guh? Might want some sort of withdrawal effect instead?
> > > > 
> > > > 
> > > > > Atomize this PR, as requested above.
> > > > > Other than that,
> > > > > > -Makes you take 0 pain
> > > > > 
> > > > > 
> > > > > I'd rather see the pain threshold go into the sky
> > > > > > -Heals you by 25 brute and burn on use.
> > > > > 
> > > > > 
> > > > > As stated long before, instant healing effects are not a good idea, even with the severe organ damage when the chemical leaves the system
> > > > > > -Lets you fire two-handed guns with only 1 gun
> > > > > 
> > > > > 
> > > > > Ridiculously powerful
> > > > > > -Removes weapon recoil
> > > > > 
> > > > > 
> > > > > Ridiculously powerful (makes you reliably hit the head with every bullet from a takeshi with no bullet spray)
> > > > > > -Makes you incapable of vomiting
> > > > > 
> > > > > 
> > > > > Considering this is a chem that was supposed to carry the disadvantage of NSA, this is also broken. It'll allow combining it with a load of healing chems with little to no real disadvantage.
> > > > > > -You have a huge change to counter any agressive grab
> > > > > 
> > > > > 
> > > > > Already covered in the Robustness buff
> > > > > > -You deal 30 more brute with punching
> > > > > 
> > > > > 
> > > > > I'd rather see some kind of general buff to all melee. Other than that, 30 is excessive, even if melee in on itself isn't strong.
> > > > > > -You have a high chance to block enemy punches
> > > > > 
> > > > > 
> > > > > Why?
> > > > > > -Lets you snap the necks of grabbed enemies as long as they're not wearing a rig/voidsuit (breaks the blood vessels in the head , deals pain and oxyloss)
> > > > > 
> > > > > 
> > > > > Once again making melee worthless compared to the might of grabfu
> > > > > As for party drops, instant tool usage is a massive balance risk, as it allows instant repairs.
> > > > > As for the instant organ damages when the chem is metabolized, guh? Might want some sort of withdrawal effect instead?
> > > > 
> > > > 
> > > > Pain threshold going into the sky just makes the effects useless , it becomes from a deathtrooper chem to a shitty NSA taker that only stops you from taking any decent painkiller. Healing on use is not a balance issue, its meant to be used as last resort. NSA still carries disadvantages, just pair tramadol and menace together and you will get a heart attack. There is no guarantee the robustness PR gets merged , and even if it does , i don't want to see someone on Menace get grab'fud and killed in 25 seconds because they did not spam space fast enough. Robustness buff increases punch damage by exactly a meager 4.5, (robustness / 10) , barely worth its cost. Melle is still very much worthwhile , most melle's wielded still deal more damage than punching (even with the buff). And when combined with the no-pain aspect , it makes melle-builds more viable.
> > > 
> > > 
> > > #7198
> > 
> > 
> > the calculations only affect break chance , not speed to upgrade the grab.
> 
> But it does affect break chance.

break chance is worthless if you are instantly upgraded to aggro grab.

**Comment by TheShown911** [comment]
I am not reading this.

**Comment by ErisMeleeEnjoyer** [comment]
> You have a huge change to counter any agressive grab

#7464?

**Pull request closed without merging**
