### PR TITLE
Excelsior Machine Gun

### PR DESCRIPTION
**Pull request by Harrivchaw**
## About The Pull Request
excel machine gun keeps popping up on gun spawner, it's functionally the same as a PK more or less save for one bit, it can't be fired while **wielded.**
This fixes that, also makes it that you have to wield the damn thing to fire, maybe PK should need two hand to fire as well?

## Why It's Good For The Game
unbroke the broken machine gun

## Changelog
:cl:
fix: Fixes Excelsior Machine Gun
/:cl:

### CODE REVIEW

**Comment by TheShown911** [comment]
What if we just remove it, it's ancient, can't be printed by excels, doesn't even have full auto and isn't balanced around anything.

**Comment by Harrivchaw** [comment]
it does have full auto, though i'm not entirely averse to just blacklisting the gun from spawners

**Review by genessee596 — CHANGES_REQUESTED** [review]
this probably shouldn't exist in the spawn tables at all

please remove it from said table

**Comment by Harrivchaw** [comment]
there, the excel machine gun shouldn't spawn anymore, its magazine is also blacklisted

**Comment by MadmanMartian** [comment]
Did you manually add it to the blacklist?

**Comment by Harrivchaw** [comment]
yea i changed it directly on the spawn data

**Comment by MadmanMartian** [comment]
eeeeh, that'll get removed as soon as somebody calls the auto update on the table.

Set its spawn_blacklisted to true

**Comment by Kurgis** [comment]
This was an admin weapon I edited because I wanted to get huge fire-rate while hosting locally. Blacklist can also be bypassed, so you might just want to assign it as a `bad_type`.

**Review by genessee596 — APPROVED** [review]

**Review by TheShown911 — APPROVED** [review]

**Review by TorinoFermic — APPROVED** [review]

**Pull request merged**
