### PR TITLE
Gives spiders japanese names and descriptions

### PR DESCRIPTION
**Pull request by genessee596**
## About The Pull Request

Gives our favorite spiders three new names, similar to how roaches have german names.
The guard spider is now the Senshi Spider, or the Warrior Spider.
The nurse spider is now the Kouchiku Spider, or the Building Spider.
The hunter spider is now the Sokuryou Spider, or the Scout Spider.

## Why It's Good For The Game

Gives the spiders more character, does something Reere had been planning to do anyways, and makes it a standard for all our insects to have non-english prefixes. Very nice.

## Changelog
:cl:
tweak: Giant spiders now have class-specific names and descriptions.
/:cl:

### CODE REVIEW

**Comment by FrownTown** [comment]
Don't you think this is kinda... anime

**Comment by genessee596** [comment]
> Don't you think this is kinda... anime

动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

**Comment by MadmanMartian** [comment]
Fairly sure posting that copypasta is against github's TOS

**Comment by genessee596** [comment]
Can't believe github hates the funny

**Comment by MadmanMartian** [comment]
> 
> 
> Don't you think this is kinda... anime

Just because it is using the japanese language, does not mean it's from an animated cartoon.

**Comment by Hopekz** [comment]
These names don't roll off the tongue, seem to be hard to quickly type when needed, and are just generally confusing. They don't seem like names.

The German roaches are good in my opinion because they're using Americanized words but you've chosen the most awkward and random names for these spiders.

**Comment by ArmolitskiyCarpoeb** [comment]
пошел нахуй, анимешка

**Comment by Alanii** [comment]
> These names don't roll off the tongue, seem to be hard to quickly type when needed, and are just generally confusing. They don't seem like names.
> 
> The German roaches are good in my opinion because they're using Americanized words but you've chosen the most awkward and random names for these spiders.

For me they are rolling off tongue easily.

But yes unles you are usual to eastern language its not easy for others. I simply gave name that make sense as request by genesesewee. Problem is maybe nurse spider need name better becuase they make baby.

**Review by TermService — APPROVED** [review]

**Comment by TermService** [comment]
Im not a developer but we need it ASAP

**Review by TorinoFermic — APPROVED** [review]

**Pull request merged**
