### PR TITLE
[WIP] DRAFT OF STORYTELLER REWORK DON'T EVEN TOUCH THIS UNTIL IT'S READY OR I WILL STRANGLE YOU 

### PR DESCRIPTION
**Pull request by drexample**
## About The Pull Request

This is the original PR of it on VG - https://github.com/vgstation-coders/vgstation13/pull/19548 , but at this point it was modified so many times, the real deal can be compiled by looking through VG's repo instead.

## Changelog
:cl:
refactor: Ported and """adapted""" VG's dynamic gamemode to be our storyteller.
/:cl:

### CODE REVIEW

**Comment by SpadesSlick** [comment]
Link the original PR to obide the license requirements please.

**Comment by TheShown911** [comment]
Is this real?

**Comment by Hopekz** [comment]
Is this a project being worked on?
I don't see any changes here for the last two months and wouldn't want this to perpetually stay in draft mode as a open PR.

**Comment by drexample** [comment]
Yes

**Comment by LethalGhost** [comment]
Is it still alive?

**Pull request closed without merging**
