### PR TITLE
Remove the cigarette monopoly

### PR DESCRIPTION
**Pull request by Firefox13**
## About The Pull Request
Changes cig crate price

## Why It's Good For The Game
You won't be able to cheese money now...

## Changelog
:cl:
del: Cigarette monopoly
/:cl:

### CODE REVIEW

**Comment by Wouju** [comment]
Wouldn't it be better to change the export price for nicotine (or whatever influences the export price of a cigarette)?

**Comment by Alanii** [comment]
But what about the profit margins!

We need to pump those numbers up!

**Review by hyperioo — APPROVED** [review]
Code wise there is nothing wrong.
Then it's a matter of balance if you want to diminish the export price instead.

**Comment by Firefox13** [comment]
This PR was made by me in a spite of anger of seeing a fuckton of cigarette crates on test server and there should be a better way to unfuck the economy rather than increasing the crate price.

**Pull request closed without merging**
