### PR TITLE
Adds a new coat for MEO, armours up MEO, MBO & Medspec's coats 

### PR DESCRIPTION
**Pull request by Anonmare**
## About The Pull Request

Adds a special coat for the MEO (Codersprite ahoy!) and makes it somewhat resilient to damage, about 1/2 that of a standard armour vest. The medspec's coat is now notably more resilient to harm, providing med specs a reason to use it for the greater mobility and storage it offers over dedicated combat armour - and making them much cleaner to identify at a glance. Moebius scientists also have some minor RAD protection at a loss of BIO to distinguish them just because I can and it's my PR.
Also fixes the labcoats weird double BIO and BOMB armour that didn't do anything.

Third time's the charm, I am thoroughly embarassed at how much effort this took.

## Why It's Good For The Game

Makes the Moebius heads consistent with the rest of command by giving them /some/ armour but explicitly weaker as they are non-combatants (in theory), and for medspec see above. In additiion, the MEO's needed his own coat for some time now, I can't sprite but I'd like to see what people would have in mind for it.
## Changelog
:cl:
add: After significant badgering of the bean counters, the MEO has his own coat now.
balance: Following a shortage of staff due to assassination attempts, Moebius and Ironhammer are now armouring their /key/ personnel's labcoats - MBOs, MEOs and Medspecs rejoice.
fix: Fixed a weird double BIO/BOMB value with the labcoat.
/:cl:

### CODE REVIEW

**Comment by GrayRachnid** [comment]
image

**Comment by Anonmare** [comment]
@GrayRachnid I modified from the tox_labcoat, it has that exact same issue

**Comment by Anonmare** [comment]
@GrayRachnid If it's not, I'll fix tox_labcoat whilst I'm in there

**Comment by drexample** [comment]
Mmm sprite conflict

**Comment by Anonmare** [comment]
I'm at a loss here, I literally just replaced every sprite in the conflicting files with the ones on the master branch and added the MBO coat at the end - it physically should not be possible for there to be conflicts still.

**Comment by L74814** [comment]
Oh, I believe these are for #6371 lmao

**Comment by Anonmare** [comment]
Yeah I can't figure this out, I give up.

**Pull request closed without merging**
