### PR TITLE
Adds a roach minigun for traitors!

### PR DESCRIPTION
**Pull request by Kmc2000**
¬SOUNDS CREDIT OF TGMC¬

привет тараканы Блядь

https://streamable.com/tvk85

This PR adds a new 10 TC weapon which lets you weaponize roaches!

Combine with: https://github.com/discordia-space/CEV-Eris/pull/3505 for extra badassery

### CODE REVIEW

**Comment by mattroks101** [comment]
This is the worst thing I've ever seen in my entire life.

**Comment by GrayRachnid** [comment]
this one's awful

**Comment by RandomColonist** [comment]
Can we not merge this meme?

**Comment by Stealthkibbler** [comment]
My suggestions would be
Make it cost more or-
Make the spooling take a bit longer so people have more time to react i.e close the door or move away or
Make it shoot less and make the roach marginally slower because of said weapon.

**Comment by Pariah919** [comment]
Okay theres a point where the memes have to end kmc.

**Comment by mattroks101** [comment]
My suggestion would be for this to not exist. This code is atrocious and the meme isn't funny enough for all the shitcode.

**Pull request closed without merging**
