### PR TITLE
Openspace vis_contents 2

### PR DESCRIPTION
**Pull request by Camper12345**
Fixed issues from previous pr

### CODE REVIEW

**Comment by NanakoAC** [comment]
this will need thorough testing before approval

**Comment by NanakoAC** [comment]
Pickup and putdown animations are broken

**Comment by NanakoAC** [comment]
i feel like the darkness overlay is too strong for a single Zlevel, can you tone it down a little?

https://i.imgur.com/cPSPTDz.png

**Comment by NanakoAC** [comment]
the gravity thing is unrelated, don't worry about that

**Comment by Camper12345** [comment]
image
It's a bit lighter now and pretty close to current.

**Pull request merged**
