### PR TITLE
Removing of generatable data of loot system

### PR DESCRIPTION
**Pull request by AlexMorgan3817**
## About The Pull Request

Loot data now ignoring by git.

## Changelog
:cl:
refactor: Loot data now ignoring by git.
/:cl:

### CODE REVIEW

**Comment by MadmanMartian** [comment]
I'm unfamiliar with .gitignore standards, aren't you supposed to keep them all in one file?

**Comment by AlexMorgan3817** [comment]
> I'm unfamiliar with .gitignore standards, aren't you supposed to keep them all in one file?

Not really important, adding of local `.gitignore`s making folders modular... 🤔
But maybe should be moved to core .gitignore... I think we need to write in CONTRIBUTING.md about this.

**Comment by Evankhell561** [comment]
this will present a problem when someone adds a new item or attempts to change the rarity value of an item, with no real way of knowing how the changes made to the spawn system are affecting. Whoever wants to see how their changes affect the system will now have to 1. change the configuration of their locar server, 2 remove these files from gitnore, 3 compile, 4 make changes and compile. analyze that data. 5 add that folder back to gitnore. 
if there is a better way to go about this process I would love to know.

**Comment by AlexMorgan3817** [comment]
> this will present a problem when someone adds a new item or attempts to change the rarity value of an item, with no real way of knowing how the changes made to the spawn system are affecting. Whoever wants to see how their changes affect the system will now have to 1. change the configuration of their locar server, 2 remove these files from gitnore, 3 compile, 4 make changes and compile. analyze that data. 5 add that folder back to gitnore.
> if there is a better way to go about this process I would love to know.

Better to not litter a build for one process, and you can automate this process by writing unit or python or etc test that raising by github actions or Travis.

**Comment by Evankhell561** [comment]
> Better to not litter a build for a single process, and you can automate this process by writing unit or python or etc test that raising by github actions or Travis.


Shouldn't this pr include a guide to do this automatically? instead of just removing these files from github?

**Comment by Evankhell561** [comment]
> > Better to not litter a build for a single process, and you can automate this process by writing unit or python or etc test that raising by github actions or Travis.
> 
> Shouldn't this pr include a guide to do this automatically? instead of just removing these files from github?

I mean, this pr leaves the setting to generate data useless.

**Comment by AlexMorgan3817** [comment]
> > > Better to not litter a build for a single process, and you can automate this process by writing unit or python or etc test that raising by github actions or Travis.
> > 
> > 
> > Shouldn't this pr include a guide to do this automatically? instead of just removing these files from github?
> 
> I mean, this pr leaves the setting to generate data useless.

Why generate this info at all? Is it generating everytime you launch build or it use text files to cache it?

**Comment by AlexMorgan3817** [comment]
If it just debug data, it shouldn't be saved in build and should be hidden by default

**Comment by Evankhell561** [comment]
> If it just debug data, it shouldn't be saved in build and should be hidden by default anyway


and that is why there is a configuration that prevents it from being generated. If no one can see it then the changes will be made blind.

**Comment by AlexMorgan3817** [comment]
Dude, when i get new-generation of this strings i found that there was ~30-50 strings, i think it's because everyone discard this  and not commit, if you use it as "checking for loot system" it's very, VERY unstable way to test

**Comment by Evankhell561** [comment]
> Dude, when i get new-generation of this strings i found that there was ~30-50 strings, i think it's because everyone discard this and not commit, if you use it as "checking for loot system" it's very, VERY unstable way to test


If no one commits to it, the system will eventually break down and no one will know what happened or when it happened.

**Comment by AlexMorgan3817** [comment]
> > Dude, when i get new-generation of this strings i found that there was ~30-50 strings, i think it's because everyone discard this and not commit, if you use it as "checking for loot system" it's very, VERY unstable way to test
> 
> If no one commits to it, the system will eventually break down and no one will know what happened or when it happened.

It is shit that dudes must commit autogenerated data

**Comment by Evankhell561** [comment]
> > > Dude, when i get new-generation of this strings i found that there was ~30-50 strings, i think it's because everyone discard this and not commit, if you use it as "checking for loot system" it's very, VERY unstable way to test
> > 
> > 
> > If no one commits to it, the system will eventually break down and no one will know what happened or when it happened.
> 
> It is shit that dudes must commit autogenerated data


the data is not generated by default and there is a configuration for it. it's even more crap to make a change and have no way of knowing how this change affects.

**Review by TorinoFermic — APPROVED** [review]

**Pull request closed without merging**
