### PR TITLE
Force conversion objective removal

### PR DESCRIPTION
**Pull request by Iglpigl**
## About The Pull Request

Force conversion objective for inquisitor removed.

## Why It's Good For The Game

Dokter proposed the idea and I agree with him, it goes against NT and generally fucks em over considering they have to kill the one they convert anyway because the person is hostile in most cases.

## Testing

It doesn't show up so it works.

## Changelog
:cl:
del: inquisitor force conversion objective removed
/:cl:

### CODE REVIEW

**Comment by SaltyOldBull** [comment]
agreed

**Comment by ValoTheValo** [comment]
Of all the objectives to remove from inquisitor force convert is not one of the ones that should be removed
Remove the brig objective or the pain objective

It creates interdepartmental conflict and is an interesting challenge.
Why not improve the objective. Update and Re-Add the obey cruciform "upgrade" as a high TC unlock that goes away after one cloning so you dont immediately have to murder the guy you convert or give inquisitor more stun tools like the Zeus or Councilor stunguns in thier uplink

Dont just axe an interesting objective cause it has issues

**Comment by ValoTheValo** [comment]
Of all the objectives to remove from inquisitor force convert is not one of the ones that should be removed
Remove the brig objective or the pain objective

It creates interdepartmental conflict and is an interesting challenge.
Why not improve the objective. Update and Re-Add the obey cruciform "upgrade" as a high TC unlock that goes away after one cloning so you dont immediately have to murder the guy you convert or give inquisitor more stun tools like the Zeus or Councilor stunguns in thier uplink

Dont just axe an interesting objective cause it has issues

**Comment by Iglpigl** [comment]
Unfortunately out of scope of this PR.

**Comment by ValoTheValo** [comment]
> Unfortunately out of scope of this PR.

Then close the PR until you can have it in scope? Force convert isnt even the worst objective for inquisitor to have

**Comment by TheShown911** [comment]
Bruh?

**Comment by Iglpigl** [comment]
No, will see what Firefox and mainteners think.

**Comment by DiaFRAME444** [comment]
> Remove the brig objective or the pain objective

I agree with this though.

**Comment by DiaFRAME444** [comment]
> Its an interesting objective to have to take someone down alive and get them back to NT. 
Look, I thought it over and its not really worth it. The players don't want to play along with forced conversion, speaking as a frequent Inquisitor. Giving NT Excel-style brainwashing isn't a good thing either.
There's really no way this objective will turn out well.

**Comment by Mycah142** [comment]
I can see where Valo is coming from, as it's the only objective that's specifically flavoured for Inquisitor specifically.

As much as I dislike forced conversions, as yeah it normally just... Turnes into "well if we don't kill them, they'll tattle and the entire ship will bomb is from orbit", it at least has flavour.

Brig has no real NT flavour to it, hence my once suggestion to replace it with putting people into door prison.

Pain does have some flavour, and hell the Scourge exists. Seems on-par.

In the end, forced conversion ends up being a more complicated assassinate objective because the player base is the player base. I wish there was an alternative I could think of that's a long the same line, still with flavour.

**Comment by Firefox13** [comment]
An NT-themed objective for an NT-themed antagonist that instigates conflict with Neotheology faction.  Perhaps you should take a different approach when completing the objective? I don't see a point in removing it because "it goes against NT" and "fucks them over" - of course it fucks them over, that's the point of antagonists - conflict.

**Comment by Mycah142** [comment]
>I don't see a point in removing it because "it goes against NT" and "fucks them over" - of course it fucks them over, that's the point of antagonists - conflict.

Meanwhile, me the agrolyte.

Haven't left garden in two hours. Making food, huzzah.

IH raids the department and kills me, my chickens, my cow, and grenades all my plants.

Find out later some vagabond Inquisitor force converted the TE.

"Good" conflict. Glad I, my chickens, and my entire department dies because of one man I had no idea even existed.

What you don't get is that the actions of a single churchie reflects on all.

**Comment by Alanii** [comment]
> An NT-themed objective for an NT-themed antagonist that instigates conflict with Neotheology faction. Perhaps you should take a different approach when completing the objective? I don't see a point in removing it because "it goes against NT" and "fucks them over" - of course it fucks them over, that's the point of antagonists - conflict.

notice me 先輩。

**Comment by DiaFRAME444** [comment]
Mycah, that's what department conflict is.

**Comment by Iglpigl** [comment]
> An NT-themed objective for an NT-themed antagonist that instigates conflict with Neotheology faction. Perhaps you should take a different approach when completing the objective? I don't see a point in removing it because "it goes against NT" and "fucks them over" - of course it fucks them over, that's the point of antagonists - conflict.

You are right about the different approach, I will make force sell objective to guild so the can sell each other, force heal objective to medbay to damage and heal someone from med, force SM objective to technos that completes with dusting a technomancer with SM, force food objective making you make soylent green out of someone from club as club, force brig objective forcing you to perma some operative, force research objective making you turn a scientist to slime and researching his slime core, thanks for this wonderful ideas this will surely enrich everyone's game.

**Comment by Mycah142** [comment]
> Mycah, that's what department conflict is.

My plant autism coming to a wordless, abrupt end because some unassociated cunt tried to greentext sucks ass. I wasn't the antag, I wasn't involved, I just existed and died because of it.

That isn't fun gameplay for anyone more than the violent types. I should be able to play the game how I choose to.

**Comment by Firefox13** [comment]
Might want to a-help if you've been doing nothing but growing plants and suddenly eat a .40 to your head.
Faction conflict this, fanction conflict that, but killing someone who isn't even fighting you and is unarmed is cringe.

**Review by Shadow-Quill — APPROVED** [review]

**Comment by Mycah142** [comment]
> Might want to a-help if you've been doing nothing but growing plants and suddenly eat a .40 to your head. Faction conflict this, fanction conflict that, but killing someone who isn't even fighting you and is unarmed is cringe.

Department conflict should result in the winning department benefiting.

One dude's greentext doesn't benefit the whole department.

We can't support this objective by saying it supports Dept Conflict when it resolves as a single dudes gamer moment.

**Comment by SirRichardFrancis** [comment]
> I can't click on buttons to save my life. That was supposed to be marked as "requested changes".

*suggested changes.

**Review by SirRichardFrancis — CHANGES_REQUESTED** [review]
Just delete the file?

**Comment by Iglpigl** [comment]
Fixed not compiling.

**Pull request closed without merging**
