### PR TITLE
Update meson/science/thermal overlay

### PR DESCRIPTION
**Pull request by Twomoon-Github**
## About The Pull Request

Update the meson/thermal/science hud/nvg overlay.
they are now more transparent and have very subtle scan lines animated
## Why It's Good For The Game

old overlay ruined the game visual and was quite painful to the eyes.
now its more transparent making it better for your eyes, and have very tiny scanlines animated (going down vertically), subtle to not annoy the player, but still here to get the overlay a bit more detailed and more in line with the cassette futurism of eris

## Testing

see video: 

https://github.com/discordia-space/CEV-Eris/assets/45800756/18b00870-f8a8-48f5-b029-e29bb2ee5877

(bad video quality it seems, sorry, its better on discord but still not a perfect quality xd)

(i made the same modification for the nvg, but i dont know any item that use it, since the nvg helmet and nvg googles dont use the overlays, also never saw them ingame, but if someone want to add the nvg overlay to a future item, it will stay consistant with the other overlays)

## Changelog
:cl:
tweak: modify the overlay for thermal etc
/:cl:

### CODE REVIEW

**Comment by Humonitarian** [comment]
Night Vision exists with the Tactical Helmet guild can order.

Other than that, NV, Thermals *and* Xray all exist as mutations. Just a heads up it might look weird to have scan lines with mutations.

**Comment by Twomoon-Github** [comment]
> Night Vision exists with the Tactical Helmet guild can order.
> 
> Other than that, NV, Thermals _and_ Xray all exist as mutations. Just a heads up it might look weird to have scan lines with mutations.

thanks, i think i know how to solve the issue, the overlays are just a filter and dont change how they works, its just a semi-transparent red, so either i give the mutations one their own overlays, or i remove them the overlay and they will still have night vision, the ability to see mobs behinds walls etc.

do you know how to admin-give yourself specifics mutations pls?

**Comment by Twomoon-Github** [comment]
> Night Vision exists with the Tactical Helmet guild can order.
> 
> Other than that, NV, Thermals _and_ Xray all exist as mutations. Just a heads up it might look weird to have scan lines with mutations.

just tested for all of these mutations, they do not use the overlays (that took me so long to get them all and test),  here is an example with the x-ray mutation;

xray

**Review by Humonitarian — APPROVED** [review]
Content approved. Code review still necessary.

**Review by hyperioo — COMMENTED** [review]
I checked the content of the .dmi, it's indeed just a texture change to overlays.

**Pull request merged**
