### PR TITLE
Autolathe nerf

### PR DESCRIPTION
**Pull request by TheShown911**
## About The Pull Request

Pretty simple, all autolathes print items with very similar effects to oldified items found in maints, with some effects removed to make sense in game. Machines spared from this effect are the moebius protolathe, exofab and the circuit imprinter, as they can only print specific designs, the clown bench and the nanoforge. (The normal, excelsior and NT autolates all have this effect). The only machine that can print disk designs with no side effects is the newly renamed technomancer (auto-)nanoforge.

## Why It's Good For The Game
As one disk can print up to 4 guns and the main (almost only) source of disks is maints this should be a nerf to vagabonds. This is mostly targeted to vagabonds but the guild and the NT lathe are also affected by this, so this may be changed. Also lore compliance.

## Changelog
:cl:
balance: items printed in an autolathe have various negative effects applied to them.
/:cl:

### CODE REVIEW

**Comment by Wouju** [comment]
Incredibly based

**Comment by Omni44** [comment]
This does not affect anything other than price of item, sprite and names, right?

**Comment by TheShown911** [comment]
Nope, look inside `code/modules/scrap/oldificator.dm`

**Comment by Omni44** [comment]
Oh, so it does add trash gunmods to lathe printed guns and all taht jazz?

**Comment by TheShown911** [comment]
Yep.

**Comment by Omni44** [comment]
> guild and the NT lathe are also affected by this, so this may be changed
Lets not forget IH lathe, taht too is sort of important.
I have a mixed feelings about that one, especially since biolathe can't be upgraded at all and already takes literal ages to print things. How would you go about changing it to affect departments less, if at all?

**Comment by Sparrowbird611** [comment]
Why exactly does everything need to be shit?

**Comment by TheShown911** [comment]
IH shouldn't really be a producer of well anything, guild can already order a ton of stuff so they don't rely on printing. I'm mostly worried about NT, but full quality prints are reserved for factions with advanced technology.

**Comment by Sparrowbird611** [comment]
It sounds kind of crappy and pointless to be honest. Everyone uses and relies on these disks, with IH being the least likely to use them, but even they still use it consistently to print spare ammo. There just doesn't seem to be a great reason to make all these things terrible copies of existing guns, tools, armors, and more.

Also what exactly do you mean by "just print again."

**Comment by TheShown911** [comment]
If a 3D print fails you adjust the settings and try again. Guns start with gun mods that can be removed. Printing ammo has a chance to spawn magazines that are not full, so you just print more. If you roll bad stats on a piece of armor you roll again. Tools are only less sturdy so if they break you print another one (they can't break). No needs for innovation and new designs just print print print.

**Comment by Sparrowbird611** [comment]
So what's wrong with the way things currently work that makes it necessary to have you spam print, waste licenses, and just overall add tedium to this. The average gun disk gets you two guns on average, excluding energy weapons, since you also need to print mags, most armor disks end up making two pairs of armor at most and as little as one for others, and almost every disk except for the most basic has a license limit. I don't see how this makes things better.

**Comment by TheShown911** [comment]
The main way of getting disks is maints, compared to a single gun spawning a gun disk can get you up to 4 guns and a single armor disks gives you 2 sets (2x2). If you need more ammo you get an ammo disk. If you print a bad armor/tool/gun you can trade it to someone else. The best main gear is highly more likely to be in the form of a disk rather than a straight spawn.

**Comment by Sparrowbird611** [comment]
Who the fuck is going to buy an armor that takes an hour to put on, moves like a truck, and has less protection than some pieces of ordinary clothing man? That's what oldified armor is like. Why aren't you just nerfing the spawn rates of better quality disks or preventing them from spawning if they are such an issue? You keep saying you can get up to four guns, but on average this isn't what really happens, since people want at least two spare mags and an ammo disk isn't around.

**Comment by TheShown911** [comment]
I can do your boring as fuck straight number nerf, remove all armor disks as they have no point being in the game and nerf high tier guns disk spawns to point of irrelevancy, or I can do this that is lore compliant, adds to the atmosphere of a shit ship destined to die, with floppy disks used as data storage and very imperfect autolathe technology.

**Comment by Sparrowbird611** [comment]
> I can do your boring as fuck straight number nerf, remove all armor disks as they have no point being in the game and nerf high tier guns disk spawns to point of irrelevancy, or I can do this that is lore compliant, adds to the atmosphere of a shit ship destined to die, with floppy disks used as data storage and very imperfect autolathe technology.

What fucking atmsophere? Making all the tools and weapons terrible isn't atmosphere, it just means they're terrible. If it weren't for the fact that there's actually an easy way to remove oldification from clothing right now, armor would be made absolutely fucking useless if it was printed oldified. You keep saying gun disks can print 4 guns, but I've said three times now that realistically, they have half the capacity you've already said, making them oldified and spawn with barely any fucking ammo in the printing disks means one per disk. The "problem" you've mentioned, that we have too many disks, is literally solvable by making the high quality disks rarer and the more lower tier ones more common, and maybe adding more gun parts/way to craft gun parts and a way to craft scrap ammo.

**Comment by TheShown911** [comment]
I understand why you would think like that but:
1. All tools and guns would be very very far from terrible, as tools are functionality unaffected and guns can be fixed by removing a few tool mods.
2. If you need a lot of ammo you get an ammo disk, they are available for purchase at the guild vendor round start, and flat ammo is sold at the IH vendor. The fact that not a single person buys any of these means that ammo is common enough. I don't think a single disk should be able to equip 2 people with a gun and 3 magazines each. If you want to sell guns from the disk you print all 4, if you want to keep 1 and sell the others you print 3 and 3 ammo mags, if you want to split it with a friend you each get a gun and 3 mags, even if the mags aren't fully loaded it should still be enough ammo until you get some more, this was the internet of the original license point system.
3. It's not barely any ammo, on average it's 50% enough to last a while but not the 3 full mags that last the whole round.
4. Finally making rare disks more rare and common disks more common isn't a good solution. Disks with no value will still be ignored and the gang that gets a dallas or PK disk once will still destroy you, just less often. With this that lucky gang will at least need to repair their guns and scrounge up ammo before being a walking armory.

**Comment by Sparrowbird611** [comment]
I think you got a point on all of those. The only thing I think is wrong is that ammo, which I feel is going to be CBT to get now. A way to more effectively craft scrap ammo or something would help with that, but that's not really related to this I guess.

**Comment by TheShown911** [comment]
Yeah, i can see that. There was some discussion of ghetto ammo presses and ammo using a gunpowder reagent to make but nothing concrete as of yet. If players in game don't find any workarounds or think it's too CBT it can be adjusted.

**Comment by Omni44** [comment]
I like it because it curbs vagabonds' powerhouse a bit and makes TMs stand out a bit.
I don't like it because:
a) Toolhealth and old gunmods may as well not exist, that's how inconsequential they are. nobody has ever run out of toolhealth, and I think you'd have to try to dismantle whole ship to get there. Gunmods can be removed in 3 secodns, and most it will achieve is cuck some noob.
b) Ammo is an issue, yeah. It just doesn't sound really great, not in current set up where ways of crafting ammo are rather scarce otherwise. On average you will print 50% of desired volume of ammo, but 50% is already kinda little, so people on less lucky part of the curve will get jack shit for all these license points, mats and time
c) I feel like this is good opportunity to maybe link the whole thing to components used in lathes and whether disks are new or old themselves, to at least give players some modicum of control over it.
d) I feel like this doesn't curb  impotant issue being cloned disks/unlimited license ones.
e) Bioprinter thing and, IH being potentially unable to get supply of enough ammo.

**Comment by MLGTASTICa** [comment]
I dont think this is the right way to handle the autolathe issue. What would really curb most weapon printing would be if autolathe printing requires reagents. For me this overall feels like a change that serves to increase player tedium , which is not great for a game with so much content already.Ontop of weapon printing requiring reagents i believe you could also just allow maint disks to spawn "corrupted" , thus making a fair bit of the  tarnished/old disks not have their gun. Guns could also require more than steel , plasteel and plastic,  the dallas for example could be more "exotic" and require diamonds or metallic hydrogen , the valkrie could require diamond , the nemesis could require 60u of toxin and uranium , the wintermule could require some silver because of the scope , and perhaps all guns could require 30-15u of tungsten.

**Comment by TheShown911** [comment]
Update: NT lathe can print all NT designs without problems, excelsior lathe is now an autoforge and can print everything perfectly and ammo mags spawn at least 50% full, so they have 75% max ammo on average.

**Review by infraredbaron — APPROVED** [review]
Everything seems fine.
A bit of buff for moebius, but we can figure out it later.

**Review by Firefox13 — APPROVED** [review]

**Pull request merged**
