### PR TITLE
Adds hydroponics trays circuit boards to the guild vendor with other circuit boards

### PR DESCRIPTION
**Pull request by Iglpigl**
## About The Pull Request

Adds hydroponics trays circuit boards to the guild vendor.

## Why It's Good For The Game

Has been suggested in feedback and it's a good idea overall.

## Testing

Screenshot_1

## Changelog
:cl:
tweak: guild vendor now sells hydroponics trays circuit boards
/:cl:

### CODE REVIEW

**Comment by DiaFRAME444** [comment]
No, Guild has a vending machine for a few common circuits.

**Comment by Iglpigl** [comment]
Also it's tested yes they don't start anchored they started wrenched you can simply unwrench em.

**Comment by Firefox13** [comment]
Sorry, I meant guild station, if it's not in a board.
So do they start wrenched or not? If you need to unwrench in order to move it needs to be changed.
Or even if they can be moved but have to be "unwrenched" first.

**Comment by Iglpigl** [comment]
> Or even if they can be moved but have to be "unwrenched" first.

Currently it's this way but I have no idea how to change it honestly.

**Comment by Firefox13** [comment]
Add a subtype that starts unwrenched.

**Comment by Iglpigl** [comment]
Sure thing, will try it later today.

**Comment by glaciusinfinity** [comment]
In my opinion, trays should be more expensive than 100 creds, that's less expensive than the pack of candles. 350-500 seems to be a bit more reasonable for something that's going to keep providing for you for the rest of the round.

**Comment by garrulousTeamotei** [comment]
With the options of adding it to the guild and adding it is a  MoeSci protolathe item, and you chose the NT vendor?

**Comment by SirRichardFrancis** [comment]
> With the options of adding it to the guild and adding it is a MoeSci protolathe item, and you chose the NT vendor?

Eris coder thought process when adding something be like:
Is something a gun?
Yes - give it to IronHammer.
No - give it to the Guild.

**Comment by TheShown911** [comment]
Should really be a circuit, not vending a whole tray...

**Comment by Iglpigl** [comment]
> Stuffing FIFTY trays into a vending machine? They should be sold through guild vendor in such a package instead unless you want to code a board for them (it doesn't exist). In case you make a board it should be on one of the NT disks.

Addressed, there are circuit boards for them now, currently not on any disks but you can buy them from the guild vendor.

**Review by TheShown911 — APPROVED** [review]

**Pull request merged**
