### PR TITLE
Gun disk rebalance (Feedback wellcome)

### PR DESCRIPTION
**Pull request by TheShown911**
## About The Pull Request
Makes gun disks more rare (mainly by removing them from /obj/random/techpart), rebalances other loot to make up for it, expect more finsished guns in maints and more ammo disks for guns you do find. All feedback is wellcome.

## In Game Tests

<details>
  <summary>Expand</summary>
Both tests done on a set of 10 random tech lockers.

Current Situation:

test old

FS
.40 miller
Rifle ammo x3
Gladstone SG
PDW martin

TM
Circuts x2
Components x2
Conveyors
Adv tools

Guild
Misc pack x2

Moebius
Artemis dartgun x4 (???)

NT
Lightfall LG
Regulator SG

SRB
Novakovic boltgun

Total: 22 (2.2 disks per locker)

After this update:

loot_tech_post

FS
Lethal ammo disk
Non lethal ammo x2
.35 and .40 ammo
.35 colt

TM
Components x2
Conveyors
Adv tools x2

Guild
Devices and instruments
Misc pack x2

Moebius
Computer parts
Artemis dartgun

IH
Misc pack

Total 16 (1.6 disks per locker)
(It should be considered that there are more parts insdead of disks)

</details>

### CODE REVIEW

**Comment by Coureere** [comment]
I strongly suggest you to add more guns to spawn. Our current gun spawners has rather VERY limited amount of guns that can spawn. You can vastly expand it with almost no effort. I am particularly talking about `gun_cheap`, `gun_normal` and etc from that file. Issue with this is being they was made long ago, but from that time we got many new guns added. Just comb through gun files and add every gun for which it makes sence to appear as loot.

**Comment by Jackofashepard** [comment]
This looks ready to go

**Comment by Alliostra** [comment]
I'd suggest making some of the very rare disks more common, you find many high quality handgun, smg and shotgun disks, but very very few of the more rare weapons.

**Comment by TheShown911** [comment]
> I'd suggest making some of the very rare disks more common, you find many high quality handgun, smg and shotgun disks, but very very few of the more rare weapons.

The goal was to make gun disks in general less common, as compensation there there are more finished guns in maints and loot tables were updated to contain more newer guns.

**Comment by MadmanMartian** [comment]
We'll see how this goes for now. I am questioning the addition of the Cassad to the gun loot, but we can hope it doesn't become too much of a problem

**Pull request merged**
