### PR TITLE
new derelict crew

### PR DESCRIPTION
**Pull request by fernandos13**
## About The Pull Request
adds a new ervent for the round
a derelict ship will spawn much like the serbian one. but with derelict crewmembers that must fix and get the ship back to eris

## Why It's Good For The Game
add more ghosts roles. and more ways to get back to the round. as some challanges for people waiting

## Changelog
:cl:fernandos33_and_VALO
add: derelict crew role
/:cl:

### CODE REVIEW

**Comment by ArmolitskiyCarpoeb** [comment]
nice idea, but screenshots please

**Comment by fernandos13** [comment]
still waiting for Valo to do the mapping. and the welcome message.
((thats why the DO NOT MERGE))

**Comment by ArmolitskiyCarpoeb** [comment]
do you need new sprites for derelict crew? and how it be in lore?? maybe onestar old ship?

**Comment by fernandos13** [comment]
idk whatever people decides on. it. i'm jsut adding the "skeleton" for it. 

if people want NT or Onestar. or specific new clothing that can be done too

but ye we do need a new shuttle mapped.   (sprites are optional)

**Comment by genessee596** [comment]
Yo.

Let me know if you're still working on fixing these conflicts - if you don't get back to me, this PR will be closed in one day.

Thanks.

**Pull request closed without merging**
