### PR TITLE
Technomancer Voidsuit resprite

### PR DESCRIPTION
**Pull request by CeUvi**
## About The Pull Request
Resprited techno voidsuit. Added helmet selection (rmb on helmet)
image

## Why It's Good For The Game
New sprotes good

## Changelog
:cl:
add: Added helmet selection to the techno voidsuit
imageadd: updated  old sprites and added 2 more helmet types
/:cl:

### CODE REVIEW

**Comment by CeUvi** [comment]
mmm yes conflicts

**Comment by ArmolitskiyCarpoeb** [comment]
заебал заебал заебал

**Comment by Firefox13** [comment]
Old sprite was OK, why don't you put it as an outdated version in maintenance for difference points?

**Comment by CeUvi** [comment]
fuck

**Review by genessee596 — APPROVED** [review]

**Comment by shazbot194** [comment]
I thought the idea was to wait for the sprite selection project to be done and include these as additional sprites.

**Review by genessee596 — CHANGES_REQUESTED** [review]
fix conflicts

also, make the old engineering void spawn in maintenance with shittier stats

**Comment by CeUvi** [comment]
gonna re-make this pr

**Pull request closed without merging**
