### PR TITLE
Fix all new #6616 sounds except for ballistic ones

### PR DESCRIPTION
**Pull request by Kegdo**
## About The Pull Request
#6616 
Didn't know about Eris' sound """remixing""", Humon tested the code but didn't tell me that it sounds horrible, so I didn't know myself, fixed all the sounds(by remixing them back) except for ballistics, they need a completely different approach
Sounds listed and changed below:
[SoundsOverhaul3_GrabMeleeShieldRanged.zip](https://github.com/discordia-space/CEV-Eris/files/7504812/SoundsOverhaul3_GrabMeleeShieldRanged.zip)
Miss sounds currently not in game
Ballistic sound different ingame for unknown reason, and it seems that they can't be "remixed" back like others, will need a different approach
## Why It's Good For The Game

poopenfarten shit sounds are now good

## Changelog
:cl:
fix: fixed-remixed most of the new sounds, making them sound as it was intended (ballistics excluded)
/:cl:

### CODE REVIEW

**Comment by Kegdo** [comment]
Code is good because there is no code.

**Comment by Humonitarian** [comment]
I did say in my PR that some shields sounds weren't added yet, didn't I?

**Comment by Kegdo** [comment]
> I did say in my PR that some shields sounds weren't added yet, didn't I?

I absolutely and completely ignored it => you didn't say it

**Review by TheShown911 — APPROVED** [review]
Ok.

**Pull request merged**
