### PR TITLE
Removes crash_with proc safely enough

### PR DESCRIPTION
**Pull request by vode-code**
## About The Pull Request
This PR deletes the crash_with proc and restructures the code that used it to hopefully functionally use CRASH.
if . = assignment still works when the proc ends in a CRASH this should be 100% safe.

## Why It's Good For The Game
 crash_with makes things harder ta debug and it's annoying; all crash_with does is call CRASH anyways so I just removed the middleman.

## Changelog
:cl: Chickenish
code: crash_with no longer exists in the code.
/:cl:

### CODE REVIEW

**Comment by SirRichardFrancis** [comment]
Mate, why don't you make new clean branches? Seven months old commits that shouldn't have been added to PR in the first place? Why?

**Comment by MLGTASTICa** [comment]
> Mate, why don't you make new clean branches? Seven months old commits that shouldn't have been added to PR in the first place? **_Seventy two_** commits, and only one of them is relevant. Why?

Who are you , to question the ways of the most important Eris coder.

**Comment by vode-code** [comment]
I thought the bot didn't update sub-branches, I'm gonna try stopping the action.

**Comment by vode-code** [comment]
did that, should be in effect after this PR is merged, if that really does get rid of the commit spam.

**Review by SirRichardFrancis — APPROVED** [review]

**Comment by TheShown911** [comment]
`if . = assignment still works when the proc ends in a CRASH this should be 100% safe.`
If?

**Comment by SirRichardFrancis** [comment]
> If?

Tested it, can confirm.

**Review by hyperioo — APPROVED** [review]
If confirmed then seems ok

**Pull request merged**
