### PR TITLE
Adds the Haywire Android

### PR DESCRIPTION
**Pull request by zombiemimic**
## About The Pull Request
the Eris is an old ship with many secrets and dangers from regimes past. we now have a new danger.
android1
android2

## Why It's Good For The Game
New maint mobs for texture and richness

## Changelog
:cl:
add: Added haywire androids to code
/:cl:

### CODE REVIEW

**Comment by Wouju** [comment]
code wise seems good to me, i'm not a fan of the sprite but that's my bias

**Comment by Sparrowbird611** [comment]
Sprite doesn't make me think of an android, it's a cum monster.

**Comment by Omni44** [comment]
Neither fan of a sprite nor idea of just yet another simplemob that stands around, aggors you when noticed and proceeds to beat/shoot till you're dead.  If it could do something more at least, like grab you, strangle, or whatever...

**Comment by drexample** [comment]
The sprite looks like if Mister X had an anemic younger brother.

**Comment by drexample** [comment]
Also humanoid simplemobs, especially those that spawn on the ship with an ai that isn't far away from roombas are not a good feature. No approval from me.

**Comment by thedarkcrusader** [comment]
> Neither fan of a sprite nor idea of just yet another simplemob that stands around, aggors you when noticed and proceeds to beat/shoot till you're dead. If it could do something more at least, like grab you, strangle, or whatever...

Strangling sounds good to me let it loose the gun maybe it could  jump out from lockers  or  hide under floorboards and triggers when you get close?? just a suggestion.

**Comment by zombiemimic** [comment]
Closing because I'm working on giving superior_mobs ranged attacks

**Pull request closed without merging**
