### PR TITLE
Roach Burgers

### PR DESCRIPTION
**Pull request by Stealthkibblers**
Roach BORGAR
https://youtu.be/c_jomXhjUjI
Aseprite_im2au15KWw
dreamseeker_w7rvso1pWy
dreamseeker_Y6oLeHWNOM
dreamseeker_R5WVxo3ITS
dreamseeker_wQfOUSrf10

:cl:
add: a robust line of burgers made from the freshest roach meat hunted straight from the CEV Eris tunnels.
/:cl:

### CODE REVIEW

**Comment by Keekenox** [comment]
Shit PR close pls

**Comment by GrayRachnid** [comment]
Did you test this?

**Comment by Stealthkibblers** [comment]
yes, compiled multiple times and tested

**Comment by Stealthkibblers** [comment]
it actually took me like 3 hours to get it work

**Comment by Keekenox** [comment]
[https://i.imgur.com/wTx92bw.png](url)

**Comment by John-Peppercorn** [comment]
index

**Pull request merged**
