### PR TITLE
Add more lobby screens and music

### PR DESCRIPTION
**Pull request by SirRichardFrancis**
## About The Pull Request

Pictures taken from the gallery in discord, new track is this:
https://soundcloud.com/dukegneiss/cyborg-emt

image

https://user-images.githubusercontent.com/65828539/172512594-3b939ecf-78fb-4d40-bfdd-08944fd928ef.mp4

image

https://user-images.githubusercontent.com/65828539/172512689-f1990145-d3f5-4251-b8c6-80c4dd3ac9cf.mp4

## Why It's Good For The Game

Looks somewhat refreshing.

## Changelog
:cl:
soundadd: Duke Gneiss - Cyborg EMT
imageadd: two more lobby screens
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
again the techno meme doesnt really fit the other menu screens but the excelsior dude does

**Comment by Alliostra** [comment]
Use this one instead of the techno meme https://cdn.discordapp.com/attachments/372050773162590209/681107329751842846/2000_2000.png

**Comment by TheShown911** [comment]
I like the new track but i feel like new lobby screens are a big quality drop compared to the ones we already have.

**Comment by tristain01** [comment]
The lobby screens look....silly, like something you would see on /TG/.

**Comment by ValoTheValo** [comment]
> Use this one instead of the techno meme https://cdn.discordapp.com/attachments/372050773162590209/681107329751842846/2000_2000.png

yeah that one would fit really well

**Pull request closed without merging**
