### PR TITLE
Moves telecomms sprites into a separate file

### PR DESCRIPTION
**Pull request by ACCount12**
Because `stationobjs.dmi` is cancer.

### CODE REVIEW

**Comment by ACCount12** [comment]
Seems like icon diff bot just died on this one.

**Comment by GrayRachnid** [comment]
A few of them have rogue white pixels in the corner during their animation.

**Comment by ACCount12** [comment]
I don't see any.

**Comment by GrayRachnid** [comment]
image
These are the few I managed to catch in one screenshot, others have it too though.

**Comment by ACCount12** [comment]
I just went through every single icon in `comm_server` sprite, and not a single one of them had a while pixel in that corner.

**Comment by SpadesSlick** [comment]
It's known icon diff bot bag. Ignore it.

**Pull request merged**
