### PR TITLE
Ammo adjustements

### PR DESCRIPTION
**Pull request by MLGTASTICa**
## About The Pull Request
Changes to calibers and ammo
.35 Pistol from 26 brute to 7 brute with a wounding multiplier of 4 (28)
(Not effective against armoured people)
.20 from 24 brute, armor div 1.5, wounding mult 0.75  to  20 brute and armor div of 1, wounding mult 1
(No longer shreds people , but still one of the most armor penetrating calibers)
.25 from  21 brute, armor div 1.5 to 25 brute, 0.6 armor divisor
(Less armor penetrative than .20 but has more punch , roughly same armor penetration qualities)
.30 from 18 brute , armor div 1.5 , wounding mult 1.5 to 30 brute, armor div 0.7 and wounding mult 1
(More damage than .20 , but will not pen above 21 armor at all)
.40 from 21 brute , armor div 1 and wound 1 to 40 brute , armor div of 0.4 and wounding mult of 1
(Magnums have a big punch , but aren't the best at penetrating, they will still penetrate anything below 16)
.60 from 18 brute,  armor div of 3 , wounding mult of 2 to 50 brute , armor div of 1 and wounding mult of 1
Shotgun slug wounding mult changed from 2 to 1 , damage from 25 to 40, styte damage nerfed from 25 to 15
Shotgun pellets changed from  21 brute , armor div of 1 , to 15 brute, armor div of 0.5 (Blocked by armours that also block pistols)
Shotgun pellets style damage buffed from 15 to 40
Material bolt from 27 brute , armor div 2 , wounding mult of 2 and style damage of 40 to 35 brute, armor div of 1, style damage of 30 , and wounding mult of 1

## Why It's Good For The Game
Generally makes armours more effective against bullets
## Testing
Got in and shot guns , its all varible edits anyway..
## Changelog
:cl:
balance: Rebalanced guns
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
can we please not have more meaningless number shuffles. combat is actually in a decent state at the moment

**Comment by DiaFRAME444** [comment]
Having something with a wounding mult of 4 means any toolmod that adds damage suddenly adds 4 times more damage.

Also 5 checks have failed.

**Comment by ValoTheValo** [comment]
> Having something with a wounding mult of 4 means any toolmod that adds damage suddenly adds 4 times more damage.
> 
> Also 5 checks have failed.

quality PR, i think he's a few days too late for april fools

**Comment by thevandie** [comment]
accurate

**Review by Firefox13 — CHANGES_REQUESTED** [review]
It doesn't even compile what do you mean you tested it look at the integration tests.

**Comment by Humonitarian** [comment]
Goes against design for how wounding multiplier is intended to work, among other things.

The goal is noble however, armor does need a type of buff, and style needs a nerf (especially for roundstart).

**Review by hyperioo — COMMENTED** [review]
I'll let Balance people decide if it's ok since I have no idea myself.

**Comment by thevandie** [comment]
it's stale and no one cares about it anymore, someone should close this

**Pull request closed without merging**
