### PR TITLE
bottle names are now more clear

### PR DESCRIPTION
**Pull request by fernandos13**
## About The Pull Request
rename some of the booze bottles for a more clearn identification of its contents. ""idea PINNED from suggestion""

## Why It's Good For The Game
will help new players to get used to its bottle names. and also makes so every bottle got its drink name in it. instead of just a few

## Changelog
:cl:
tweak: bottle names are now more clear about its contents
/:cl:

### CODE REVIEW

**Comment by GrayRachnid** [comment]
Not a fan of some of the changes tbh, not everything needed to be clarified. Maybe only 3 drinks in that list.

**Comment by fernandos13** [comment]
well here goes something i thought people wanted. but actually don't again. (it barely took 1 min to edit names, so thats why i made it and waited a bit  to see responses) thanks for the feedback till next time :D

**Comment by Firefox13** [comment]
> people wanted

The most part of the discussion about that psuggestion was mostly negative.

**Comment by fernandos13** [comment]
i mean i saw it pinned. and wold take 1 min to do. so why not. (thought pinned suggestions were more "wanted")

**Comment by Firefox13** [comment]
It's just the Baron who pins everything he likes.

**Comment by fernandos13** [comment]
oh yeah noted. i thought it had some level of meaning. back then

**Pull request closed without merging**
