### PR TITLE
Change all platinum to titanium

### PR DESCRIPTION
**Pull request by Kegdo**
## About The Pull Request

changes all platinum in the code to titanium. Only name. Sprites and anything unaffected. 

this shit is probably not going to get approved but eh, worth a shot

## Why It's Good For The Game

"SUGG: Rename platinum to titanium, platinum doesn't make much sense as a high-end armor material either ICly or OOCly, some newer miners might not even bother, I think titanium would be more sensible."

## Changelog
:cl:
tweak: platinum is now titanium
/:cl:

### CODE REVIEW

**Comment by Kegdo** [comment]
oh no, cringe.

**Comment by Kegdo** [comment]
no idea why it lintered, there were dumb as fuck errors in unaffected files, but I fixed those.

**Comment by SirRichardFrancis** [comment]
Conflicts with https://github.com/discordia-space/CEV-Eris/pull/6779. Bad timing for that change.

**Comment by Kegdo** [comment]
>:(

**Comment by CeUvi** [comment]
what a shame

**Comment by TheShown911** [comment]
At least get sprites.

**Comment by Kegdo** [comment]
Yeah. Actually. No.

**Pull request closed without merging**
