### PR TITLE
human resprite

### PR DESCRIPTION
**Pull request by CeUvi**
## About The Pull Request
homan
image
silhouettes remain the same, so there should be no issues with clothing.
## Why It's Good For The Game
even less bay (is it bay though) leftovers.
## Changelog
:cl: CeUvi
imageadd: HUMAN resprited
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
We now all have gigachad jawlines

**Comment by CeUvi** [comment]
as we should

**Comment by ValoTheValo** [comment]
> as we should

Yes but that changed the silhouettes. So all the head items gonna have issues

**Comment by CeUvi** [comment]
> Yes but that changed the silhouettes. So all the head items gonna have issues

nope
character had chad jawlines before and it was completely fine.

**Comment by ValoTheValo** [comment]
> > Yes but that changed the silhouettes. So all the head items gonna have issues
> 
> nope character had chad jawlines before and it was completely fine.

(He doesnt play the game)
Currently in game they do not have gigachad jawlines. They have virgin jawlines

**Comment by CeUvi** [comment]
damn, that's actually true
but there are still no items that are broken

**Comment by SaltyOldBull** [comment]
bigger tits, hips, and dick, completely unnecessary resprite. This has no place in a non-ERP server.

**Comment by ValoTheValo** [comment]
> bigger tits, hips, and dick, completely unnecessary resprite. This has no place in a non-ERP server.

Sojurn gonna love this one

**Comment by SaltyOldBull** [comment]
> > bigger tits, hips, and dick, completely unnecessary resprite. This has no place in a non-ERP server.
> 
> Sojurn gonna love this one

let them have it, but not CEV Eris.

**Comment by CeUvi** [comment]
go make a better one then, lmao

**Comment by SaltyOldBull** [comment]
there is no need for a change, explicitly claiming you are removing bay leftovers is no excuse on its own.
*especially* when such a removal consists of minor sprite edits for bigger genitalia.

**Comment by Kurgis** [comment]
> Sojurn gonna love this one

They already have their own resprite (unsure if actually implemented), and frankly, the removal of certain features on the icon would probably make it more awkward for ERP-scenarios (though people engaging ERPing through SS13 are immune to such feelings apparently).

> _especially_ when such a removal consists of minor sprite edits for bigger genitalia.

The size of the genitalia has not been necessarily increased, with exception of the dixel (now bi-dixel), though features have certainly been accentuated with the shading.

> even less bay (is it bay though) leftovers.

I believe this icon was actually an edit done by Walter, though it was at the very beginning stages of the project, it's obviously missing his later polish.

@CeUvi Change the icons `human_m` and `human_f` in `https://github.com/discordia-space/CEV-Eris/blob/master/icons/mob/human.dmi`, these are reference images only I believe, but it will be where their images are usually exported from the code.

**Comment by ValoTheValo** [comment]
just say keep the current head Sprite. If you want to make customization options for head shape that would be absolutely great

**Comment by SaltyOldBull** [comment]
> The size of the genitalia has not been necessarily increased, with exception of the dixel (now bi-dixel), though features have certainly been accentuated with the shading.
Yes, I forgot to include breasts in there as well.

**Comment by CeUvi** [comment]
salty just can't get over his 29px tall dolls from atmos simulator game having boobs

**Comment by SaltyOldBull** [comment]
Do you mean the atmos simulator game server that is explicitly non-ERP?
Go sprite for them if you want to make these things to satisfy your fetishes.
Just don't shove it on the player base here.

**Comment by CeUvi** [comment]
go ask firefox to close the pr then

**Comment by Kegdo** [comment]
why do i feel like literally nothing has changed

**Comment by SirRichardFrancis** [comment]
We've got a bunch of underwear already, now JoJo gigachad human sprites.
But of course, "Reere isn't here anymore" so no point in telling you to go read contribution guidelines.
On the other hand, it _is_ better than old bay sprites except for chad jawline being a default.
Having two head types that could be changed on character creation would be great solution.

**Comment by glaciusinfinity** [comment]
> We've got a bunch of underwear already, now JoJo gigachad human sprites. But of course, "Reere isn't here anymore" so no point in telling you to go read contribution guidelines. On the other hand, it _is_ better than old bay sprites except for chad jawline being a default. Having two head types that could be changed on character creation would be great solution.

Maybe adding customizable body types...
One step closer to re-adding fat people

**Comment by CeUvi** [comment]
> Having two head types that could be changed on character creation would be great solution.

customizable heads? what's next?
customizable cock?

**Comment by Kegdo** [comment]
I AM a coder tho, and I wont do that too
Also both of these sprites are peepee poopoo bad tbh, you can't fix the "bay" human doll, it's literally impossible.

**Comment by Kegdo** [comment]
also this guy's nose make him look like a zionist
image

**Comment by CeUvi** [comment]
> you can't fix the "bay" human doll, it's literally impossible.

it's true
i'm just making them a bit more pretty

**Comment by Humonitarian** [comment]
> also this guy's nose make him look like a zionist image

on Eris everyone is a zionist

**Comment by TheShown911** [comment]
I don't like it.

**Comment by Alliostra** [comment]
why is this still open

**Comment by Kurgis** [comment]
> why is this still open

Sprite Lead hasn't made any comments on it, nor have some other spriters.

**Comment by SirRichardFrancis** [comment]
> Sprite Lead hasn't made any comments on it, nor have some other spriters.

@infraredbaron

**Comment by Kurgis** [comment]
> Sprite Lead hasn't made any comments on it, nor have some other spriters.
Okay, after discussion in the admin channels we don't have a "Sprite Lead" position currently.

**Comment by SaltyOldBull** [comment]
> Okay, after discussion in the admin channels we don't actually have a "Sprite Lead" position.

last time someone tried to claim being a headspriter or leadspriter they got promptly shot down

**Comment by Firefox13** [comment]
sorry we're not chads we don't do chad jawlines here

**Pull request closed without merging**
