### PR TITLE
Combat tool mod for hammers.

### PR DESCRIPTION
**Pull request by DiaFRAME444**
## About The Pull Request
Changes stats and name of flat surface, now its a toolmod made for hammers.

## Why It's Good For The Game
Flat surface didn't add anything to the game and was barely taken. This change lets hammers shine in combat, they didn't have the appropriate toolmods to compete with swords or hypersaws before.

## Changelog
:cl:
tweak: Flat surface toolmod reworked into platsteel surface toolmod. 
/:cl:

### CODE REVIEW

**Review by Firefox13 — CHANGES_REQUESTED** [review]
If you really want to make a separate mod that increases damage for hammers, then make one and don't remove and reuse existing one.
Call it something like "force ehnancer" while in reality it's just some weights that you attach to hammerhead to make it hurt more. Needs a sprite, too.

**Comment by DiaFRAME444** [comment]
#4661
Hammers have been in the game for 2 years partially with the purpose of being weapons and still nobody has fixed them. There was a recent change to make them stronger wielded, but without tool mods they're still suboptimal.
Fix it. Get a spriter. Something.

**Comment by Humonitarian** [comment]
> Yeah, I don't think the flat surface mod has EVER really been used. Adding a quality to an existing tool at a shitty level? It's just not something worth doing. Personally I think there needs to be more than one good combat mod for hammers to really make up the difference, but one is a good start.

Actually, you all are wrong. I had this scenario before - power shovel modded to hell with 900% speed and 30 precision. I added the flat surface, didn't really impact the stats. Suddenly I had a tool that was effectively a maxed out hammer, alongside the usual shovel qualities.

Flat surface is powerful, its only flaw is the lack of uses for hammers.

More useful interactions, such as breaking down bolts on airlocks. That would make it viable.

**Comment by Alliostra** [comment]
I also support this the reasons stated above (unironically)

**Comment by DiaFRAME444** [comment]
Darn, I forgot this thing was here and accidentally deleted the repository.

**Pull request closed without merging**
