### PR TITLE
Mining rework - Cavern system

### PR DESCRIPTION
**Pull request by hyperioo**
## About The Pull Request

* Caverns are just a zlevel of size 100 x 100 that is generated when the deep drill is activated. By themselves the caverns aren’t all that interesting, being just winding corridors of rock and stone, but there are a few crucial features that differentiate mining in the caverns from mining out on the surface, and those are:

* **Ore Density:** Depending on the seismic activity of the bore (the same value that is in use for the current iteration of mining), mined ore walls will drop more ores than they do on the surface. This means that while there might not be more ore tiles in the caverns, each tile is worth exponentially more compared to the surface level.

* **Difficulty Scaling:** While mining on the surface is safe and boring, descending down into the caverns will have you face golems that are dispersed around the entire cavern level, giving the players a bit more breathing room in approaching the enemy while mining. As the seismic activity increases, the golems will get more numerous, and more advanced forms will appear. In that sense, it is analogous to the way it works currently, but because the golems will be much more dispersed, you will have more freedom to find a way to approach them.

* **Points of Interest:** POIs are a system similar to what’s going on in deep maint - just as there are randomly placed, but pre-mapped rooms in deep main, there will be points of interest scattered around the cavern systems. Some of them will only be encountered at higher seimis level to provide incentives to aim for higher-risk higher-reward.

* Wrench a deep drill as you would normally do to mine, then click on it to open the cavern system. Only a single cavern system can exist at a given time. You have to close it by clicking on the mining drill again to be able to open a new one after a cooldown of a few minutes. Being in the cavern while it is being collapsed instantly kill you so be careful to not close it on your mining mate. Cavern walls are undiggable, only the ore patches are.

* More points of interest will come, only very basic ones are implemented for now as placeholders. The golem wave mechanic will come back later with a new structure in caverns.

## Why It's Good For The Game

* The previous part of the mining rework introduced the Deep Drill that’s essentially a point defence game mode for the miners. That alone isn’t bad, but the empirical experience teaches us that it turns the job of a miner into a fairly boring/repetitive task, The mechanic that will take the central stage instead is exploration. When a Deep Drill is used, it will no longer mine minerals while attracting waves of golems. Instead, it will uncover cavern systems that miners can descend into.

## Testing

* Spawned a wrench on asteroid, wrenched it, clicked on it to enter cavern, moved around to check that minerals, POIs and golems were properly spawned. Went out and collapsed caverns, regenerated a new one after cooldown is over. Checked that you cannot open a new cavern system when one is active. Checked that ghosts are not deleted when hovering over carvern.

## Changelog
:cl: Hyperio
add: Mining rework (cavern system)
remove: Golem wave mechanics when deep drill is enabled.
/:cl:

### CODE REVIEW

**Comment by Humonitarian** [comment]
> Caverns are just a zlevel of size 100 x 100 that is generated when the deep drill is activated. By themselves the caverns aren’t all that interesting, being just winding corridors of **_rock and stone_**, but there are a few crucial features that differentiate mining in the caverns from mining out on the surface, and those are:

I see.

**Comment by assortedbeads** [comment]
ROCK AND STONE!
ROCK AND STONE!

Yeah this sounds sick as hell ngl

**Comment by assortedbeads** [comment]
ROCK AND STONE!
ROCK AND STONE!

Yeah this sounds sick as hell ngl

**Review by TheShown911 — COMMENTED** [review]
No clue about the maps but the code looks mostly fine. Only thing im uncertian of is performance. Just cleaning the turfs for each cave gen iterates over 10 000 turfs and qdels the atoms in their contents. I don't know exactly how much the turfs will be populated with POIs but the players could abuse it with a 5 minute cooldown. Also undeleteable items like the nuke should be handled somehow.

**Comment by hyperioo** [comment]
I've forbidden entering caverns while pulling something so that people cannot drag stuff in it to be deleted, it's a narrow entrance after all! :D

**Comment by hyperioo** [comment]
Going up for live test

**Pull request merged**
