### PR TITLE
[RTM] Re Brightens Cyberplant

### PR DESCRIPTION
**Pull request by ValoTheValo**
## About The Pull Request
the club dimmer update made the cyberplant not as bright as before. i didnt like that so i made it as bright as before. now you may be asking why does this need a test merge if you edited a single number. thats because my entire repo shat itself on me and i had to fix it. the issue was random things un ticked themselves for 0 reason. i re ticked them but it could happen again

## Why It's Good For The Game
plant look nice, more usefull for mood lighting

## Changelog
:cl:
tweak: Brightened Cyberplant to old values
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
fuck i accidentally re enabled bay cultures. shit

**Comment by ValoTheValo** [comment]
bay cultures have been banished. think thats it. tell me if i fucked anything else up somehow

**Comment by Iglpigl** [comment]
> bay cultures have been banished. think thats it. tell me if i fucked anything else up somehow

You did yes, why change cev_eris.dme

**Comment by ValoTheValo** [comment]
> > bay cultures have been banished. think thats it. tell me if i fucked anything else up somehow
> 
> You did yes, why change cev_eris.dme

technical difficulties on my end for some godforsaken reason a few things unticked themselves. i had to re tick them.

**Review by TheShown911 — COMMENTED** [review]
Nope, the cev_eris.dme is still changed.

**Comment by ValoTheValo** [comment]
> Nope, the cev_eris.dme is still changed.

Ah god fucking dammit fuck shit fuck balls. Ill try doing it again and see if that works and it doesnt shit itself on me

**Pull request closed without merging**
