### PR TITLE
Add 2 new haircut

### PR DESCRIPTION
**Pull request by Twomoon-Github**
## About The Pull Request

Adds 2 new short haircut, aviator and its variant aviator2

## Why It's Good For The Game

Adds more customisation and short hair options

## Testing

For the aviator2 version, the white doesnt change, only the gradient and the black part in the picture changes if you modify the hair color, it is of course intended

haircut_showcase

## Changelog
:cl: Twomoon
add: Added 2 new haircut
imageadd: Added 2 haircut icons
code: Added 2 haitcut to the char setup
/:cl:

### CODE REVIEW

**Comment by Twomoon-Github** [comment]
the right and left side are slightly different, but i didnt bothered to screen it as its very simillar, you can see here
https://cdn.discordapp.com/attachments/684117667925458949/1144210135384862802/image.png

**Comment by thevandie** [comment]
I want pictures of Spiderman!

**Comment by Firefox13** [comment]
...how do they look with red/cyan/non-black colors? I highly doubt the version with white hair will look good.

**Comment by thevandie** [comment]
> ...how do they look with red/cyan/non-black colors? I highly doubt the version with white hair will look good.

If someone wears neon hair on eris, especially with this haircut, they're missing the point and should be stoned

**Comment by Twomoon-Github** [comment]
> ...how do they look with red/cyan/non-black colors? I highly doubt the version with white hair will look good.

like i said, it looks fine

**Review by Firefox13 — APPROVED** [review]
Discussed this in discord, other colors are fine

**Pull request merged**
