### PR TITLE
Greytide Worldwide

### PR DESCRIPTION
**Pull request by thevandie**
## About The Pull Request

Adds a load of resprites for ancient things, generally related to greytidery. This includes jumpsuits, soft caps, etc. Along with some loadout refactoring to accommodate.

## Why It's Good For The Game

These sprites were ancient, so I have replaced them with cool new variants that most people I've showcased it liked it.

## Testing

Loaded up the game every time I made a change, and tested to make sure the sprite worked.

## Changelog
:cl:
add: new sprite for the old generic jumpsuits, based on the crewman jumpsuit
add: new sprites for old softcaps, to match the jumpsuits (Orange avoided because vagabond resprite is WIP)
add: completely new syndicate cap for crew to use, an old piece of fashion still produced for patriots and history fans alike. Possibly a veteran or two as well
add: new sprite for the baseball bat based on the nailbat's sprite
add: recolor of the galoshes to look better. Matches with insuls, they are both rubber after all
add: new casual suit for people to use, a salmon shirt and corduroy pants. Perfect for an office worker
add: variants of boots and reinforced shoes to the loadout (IH and oberth)
remove: the redundant flat cap from the softcaps selection in the loadout, as it's available elsewhere
remove: the mailman cap from the loadout, specifically the softcap selection
/:cl:

(gasmask not included)
image

image

image

image

image

image

(old jumpsuits for reference) 
image

### CODE REVIEW

**Comment by ValoTheValo** [comment]
please for the love of christ dont make the mistake i did and make the syndicate cap loadout so we don't get another jimmy

**Comment by thevandie** [comment]
I still don't see what the problem with jimmy was?
He was slightly annoying for a couple weeks, then immediately realized his gimmick was too overbearing, and it just sunk into the background.

**Comment by Humonitarian** [comment]
Can you larp as syndicate? I mean, everyone's syndicate...

**Comment by thevandie** [comment]
Exactly
it's just being extra patriotic tbh

**Pull request merged**
