### PR TITLE
Nerf nuka-cola, energy drinks, adrenaline

### PR DESCRIPTION
**Pull request by Firefox13**
## About The Pull Request
Makes energy drinks contain adrenaline (weak stimulant) instead of nuka cola (now not as powergamey as shit)
Lowers nuka cola speedboost significantly, lowers its NSA to 30 to compensate, increases the irradiation effect and increases heartbeat rate, removes the drowsiness removing because you already have sleepy lowering what the fuck is this powergaming piece of drink
Also makes adrenaline increase heart rate too because it's literally adrenaline

## Why It's Good For The Game
It's too strong

## Testing
I compiled it and ~~it worked~~ launched the server. NSA was 30, not 50, other effects included

## Changelog
:cl:
balance: nuka cola now has lower speedboost, lower NSA, doesn't instantly wake you up, irradiates you more and increases heartbeat
tweak: adrenaline increases heartbeat (does this even do anything? a mystery)
tweak: energy drinks now contain adrenaline instead of nuka cola
/:cl:

### CODE REVIEW

**Comment by Mycah142** [comment]
Wasn't adrenaline changed to now just be a painkiller?

**Comment by MLGTASTICa** [comment]
salt PR.

**Comment by Firefox13** [comment]
> Wasn't adrenaline changed to now just be a painkiller?

It was changed long time ago (by me) because it was too OP before. The pulse part is because it logically makes sense to increase heart rate.

**Comment by radarseas** [comment]
overdue PR honestly, although increasing irradation will do nothing to FBPs due to them _simply not being affected from being irradiated_, it'll only hurt people that aren't FBPs and thus subject to toxins and whatever else our medical system throws at them for drinking a gimmicy drink.

**Review by hyperioo — APPROVED** [review]

**Pull request merged**
