### PR TITLE
Adds the energy gun cell mount

### PR DESCRIPTION
**Pull request by zombiemimic**
## About The Pull Request
title

## Why It's Good For The Game
we got it for tools, so why not for guns?

## Changelog
:cl:
add: Added energy gun cell mount
code: changed some variables to facilitate cell modification
/:cl:

### CODE REVIEW

**Comment by thedarkcrusader** [comment]
Good PR

**Comment by GrayRachnid** [comment]
> hello sir would you like your shunted protocannon with 39 shots per cell sir?

**Comment by thedarkcrusader** [comment]
> > hello sir would you like your shunted protocannon with 39 shots per cell sir?

Yes sir yes sir this will be  delightfully divine of you thank you for the offer i shall take this cannon of laser to commit nefarious acts upon my fellow neighbor to whom i hold grudge with

**Comment by Medcar** [comment]
Good pr

**Comment by Honestly101** [comment]
Moebius approves of this PR.

**Comment by Sparrowbird611** [comment]
Should mention that it delays RoF and increases charge cost in description.

**Comment by Firefox13** [comment]
Unfortunately the requisitions centre will have to turn down your 90 shot(18000 cell with 200 per shot) laser cannon offer.

**Pull request closed without merging**
