### PR TITLE
Brings the C20 into line with naming convention. Abbreviates Moebius guns

### PR DESCRIPTION
**Pull request by Anonmare**
## About The Pull Request
Brings the C20 into line with the standardised naming convention. Also clears up a misunderstanding about the C20r being a Moebius product.

## Why It's Good For The Game

I have a crippling phobia of inconsistencies and it is ruining my life.

## Changelog
:cl:
tweak: The C20 is now in line with the standardised naming convention. Moebius gun products are now abbrviated to "ML"
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
all the other moebius guns use ML as thier abbreviation

**Comment by Anonmare** [comment]
@ValoTheValo The Suez is in violation of the convention then 'cause that's what I pulled it from

**Comment by ValoTheValo** [comment]
> @ValoTheValo The Suez is in violation of the convention then 'cause that's what I pulled it from

the Anne.

**Comment by Anonmare** [comment]
@ValoTheValo Had to bring the other guns into line with the Anne. Debating on whether or not to convert the "Prototype" guns.

**Comment by ValoTheValo** [comment]
> @ValoTheValo Had to bring the other guns into line with the Anne. Debating on whether or not to convert the "Prototype" guns.

i was honestly going to unfuck thier names at some point when i had the time and brain energy

**Review by Firefox13 — APPROVED** [review]

**Pull request merged**
