### PR TITLE
Adds the FS LMG .30 Takeshi

### PR DESCRIPTION
**Pull request by Jackofashepard**
## Image
image

## About The Pull Request

Adds the FS LMG .30 Takeshi, .30 rubber box, Takeshi disk, fixed LMG's accepting all .30 mags and some minor naming changes.
Added 2 LMGs, 6 magazines, 2 lethal ammo boxes, 4 rubber ammo boxes to IH.

## Why It's Good For The Game

IH has become fairly weak against new threats and the ever scaling gear curve, i think this will make them more of a challenge again (if they grow the brains to use this properly).

## Changelog
:cl:
add: FS LMG .30 Takshi
add: FS LMG .30 Takshi disk
add: .30 rubber box
tweak: Renamed PK mag to LMG mag
fix: LMG's no longer accept all .30 mags
imageadd: Takeshi 
imageadd: .30 rubber box
:cl:

### CODE REVIEW

**Comment by Sparrowbird611** [comment]
>Brain
>Ironhammer

Pick one.

**Comment by Voldirs** [comment]
Maybe make it in .25 or .20 just not to make another PKM with insignificant difference?

**Comment by Jackofashepard** [comment]
Nah, i like it like this, any lower caliber will make it a worse PKM and its not like we have a bustling arrangement of .30 LMGs, besides firefox liked it as is and i consulted him throughout the design.

**Comment by Firefox13** [comment]
Was it tested, does it appear in-game on map, with all states(in-hand with/without ammo with open/closed cover, inhands with/without boxes open/closed covers), does its disk actually have the designs?

**Comment by Jackofashepard** [comment]
Yes

**Comment by GrayRachnid** [comment]
image
please
map merge

**Comment by Jackofashepard** [comment]
Redo PR time

**Comment by Kurgis** [comment]
> 
> 
> image
> please
> map merge

Map merge was used correctly for this PR, it's just a formatting issue that's resolved in #6071.

**Comment by Jackofashepard** [comment]
I can't believe you made me go through an hour of manual map merge CBT 👎

**Comment by Jackofashepard** [comment]
image

**Review by Firefox13 — APPROVED** [review]

**Pull request merged**
