### PR TITLE
Gives Tosshin a scope & new sprites

### PR DESCRIPTION
**Pull request by zombiemimic**
## About The Pull Request
Sprites by @shazbot194 

Gives the tosshin rifle in the IH armory a scope, for better utility.

tosshin (2)

## Why It's Good For The Game
Gives better utility to the Tosshin rifle, which wasn't really used.

## Changelog
:cl:
tweak: Tosshins are now scoped
imageadd: added new Tosshin sprites
/:cl:

### CODE REVIEW

**Comment by SirRichardFrancis** [comment]
Rename it to "Arisaka" please.

**Comment by Humonitarian** [comment]
> Rename it to "Arisaka" please.

How to be unimaginative

**Comment by SirRichardFrancis** [comment]
> How to be unimaginative

Bold of you to assume that I know what "unimaginative" means.
Anyhow, arisaka just sounds much better than tosshin.

**Comment by Kegdo** [comment]
You can rhyme arisaka to sosaka, so it's ultimately inferior to tosshin.

**Comment by SirRichardFrancis** [comment]
> You can rhyme arisaka to sosaka, so it's ultimately inferior to tosshin.

image

**Review by TheShown911 — APPROVED** [review]

**Pull request merged**
