### PR TITLE
Resprites cahors barrel and beer keg

### PR DESCRIPTION
**Pull request by greenteaguzzler**
## About The Pull Request
What the title says. Beer tank renamed to beer keg.

## Why It's Good For The Game

image
image

## Changelog
:cl:
tweak: Edited the beer tank and barrel sprite
/:cl:

### CODE REVIEW

**Comment by Sparrowbird611** [comment]
Cahors is nice, beer keg makes me think too much of a radioactive waste containment tank though. Can it be made a little clearer it's a beer keg, maybe throw a tap on it like the cahor has.

**Comment by Kegdo** [comment]
remake the beer keg, otherwise perfect
i am a **keg** master(hahahh hehahehehhaeh get it???// lmoa) so my opinion is important

**Comment by hyperioo** [comment]
I had some feedback from our main spriters, keg looks nice but could you tweak a bit the metal barrel so that it is more clear it contains beer? (and not radioactive waste or something else)

**Review by hyperioo — CHANGES_REQUESTED** [review]
See above

**Comment by drexample** [comment]
Beer keg looks like an industrial oil drum, yeah.

**Comment by drexample** [comment]
Don't throw out the drum sprite tho, I think it looks good and can be used for other purposes.

**Pull request closed without merging**
