### PR TITLE
New sprites for old guns

### PR DESCRIPTION
**Pull request by infraredbaron**
Guns

## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

All sprites made by Omejka, if not stated otherwise

unknown

	
<hr>
</details>

## Changelog
:cl:
add: New Icons for Colt, Mateba, Mandella,Molly, Paco, Wintermute, Straylight, STS-35, Z8 Carabine, NT Valkyrie,  Freezegun, Lascannon, Plasma pistol and two boot knifes
add: New icon for kitchen knife by courtesy of The Jeffery Jefferson
add: C20R by Shazbot

/:cl:

### CODE REVIEW

**Comment by megaomega005** [comment]
wery kool approved

**Comment by shazbot194** [comment]
I do want to mention that the STS, Lamia, and Mandela were updated less then a month ago

**Comment by SpadesSlick** [comment]
Why the captains gun facing a wrong direction? Also, why one of it's icon state is missing?

**Comment by infraredbaron** [comment]
lamia reverted

**Comment by infraredbaron** [comment]
> Why the captains gun facing a wrong direction? Also, why one of it's icon state is missing?

Considering that capgun comes with preinstalled cell, there is no way to get that state without adminbuse.

**Comment by SpadesSlick** [comment]
Leave it here, future gun PRs might change that.

**Comment by infraredbaron** [comment]
image

New C20R by Shazbot and new captain's laser by Omejka

**Pull request merged**
