### PR TITLE
Sledgehammers, hammers shake your screen when wielded

### PR DESCRIPTION
**Pull request by ErisMeleeEnjoyer**
## About The Pull Request

adds basic and advanced sledgehammers

turns current sledgehammers into its subtype

sledgehammers gain 1.4 force_wielded_multiplier, onestar gains 1.5 force_wielded_multiplier

rename STRUCTURE_DAMAGE_BORING into STRUCTURE_DAMAGE_DESTRUCTIVE, current destructive renamed into powerful

all sledgehammers are WEAPON_SIZE_HUGE

sledgehammers have good structure_damage increase and armor pen

image

_ALL_ hammers shake the victim's screen on hit for a very short duration with a probability of 70 when they are wielded. This is done by adding a new define to obj/item, which means that you can make an item that is not a hammer shake the victim's screen in future contributions.

## Why It's Good For The Game

First off, hammer time

Second, proper sledgehammer subtype

Third, why was the best structure damage increase called "boring"? I say it's quite exciting and interesting

Fourth, blades are no longer king. Screenshake makes maces, baseball bats, hammers and sledgehammers viable by making the victim miss their shots(usually)

Sledgehammers are great blunt weapons that might not deal much damage and be as toolmoddable as blades, but ignore a lot of armor, because muh concussion force(real physics here)

## Changelog
:cl: Kegdo
add: sledgehammers, basic and advanced
add: hammers shake your screen on hit if wielded
tweak: proper sledgehammer tool type
tweak: STRUCTURE_DAMAGE_BORING renamed into STRUCTURE_DAMAGE_DESTRUCTIVE
/:cl:

### CODE REVIEW

**Comment by DiaFRAME444** [comment]
Increased wield multiplier should allow random homewreckers on maint to tear through reinforced walls roundstart, and now the IH Breaching Hammer is the best melee weapon onstation, better than the Halberd.
Don't do it.

**Comment by ErisMeleeEnjoyer** [comment]
> Increased wield multiplier should allow random homewreckers on maint to tear through reinforced walls roundstart

.......albeit very slowly due to very low damage. This is intended.

> Breaching Hammer is the best melee weapon onstation, better than the Halberd.

Sounds like halberd needs to be nerfed :^)

**Comment by SirRichardFrancis** [comment]
> Increased wield multiplier should allow random homewreckers on maint to tear through reinforced walls roundstart, and now the IH Breaching Hammer is the best melee weapon onstation, better than the Halberd. Don't do it.

It's about numbers again. When are we getting rid of most of that crap?

Low value and high multiplier here, high value and low multiplier there, high value, high multiplier and very high concentration of copium elsewhere. And 0.05 multiplier difference absolutely ruins the balance.

Why don't you go get some lag fixed instead? Holy fucking shit.

**Comment by ValoTheValo** [comment]
This would make the os hammer headgib in one or two hits and be the best melee weapon in the game by far. Not really the best idea

**Comment by ValoTheValo** [comment]
Balance PR moment

**Comment by TheShown911** [comment]
I have never seen the OS hammer in game.

**Comment by ValoTheValo** [comment]
> I have never seen the OS hammer in game.

Go to the dungeon or junk beacon and you will have 12 by the time you go home

**Comment by DiaFRAME444** [comment]
> I have never seen the OS hammer in game.

There's no reason to pick them up even if you find them, since they aren't particularly good.
Before this PR, anyways.

**Comment by ErisMeleeEnjoyer** [comment]
ok lowered it a bit, and also buffed all the hammers(they are OP now)

**Review by SirRichardFrancis — APPROVED** [review]

**Comment by Firefox13** [comment]
Screenshake is... A really fucking weird way to balance things.

**Comment by SirRichardFrancis** [comment]
Who said it's for balance?

**Comment by Rexdyer1** [comment]
Imma leave my two cents. having the malus for using the item be something that actively makes it unpleasant to play the game is not a good idea. Ya'll remember when drugs would make the game echoey and rainbow tinted for like 20 minutes? its not a good idea...secondly. having hammers be extremely OP kinda takes away the point of using other melee weaponry. maybe have hammers be extremely easily parried or blocked to make up for it? maybe slowing down when wielding?

**Comment by DiaFRAME444** [comment]
The screenshake is when you hit someone with a hammer, not because you're wielding it.
New damage numbers are fine.

**Comment by ErisMeleeEnjoyer** [comment]
> Imma leave my two cents. having the malus for using the item be something that actively makes it unpleasant to play the game is not a good idea. Ya'll remember when drugs would make the game echoey and rainbow tinted for like 20 minutes? its not a good idea...

"ALL hammers shake the victim's screen on hit for a very short duration"

"ALL hammers shake the victim's screen on hit"

"shake the victim's screen on hit"

__"victim's"__

Admins? I leave the case in your hands

> having hammers be extremely OP kinda takes away the point of using other melee weaponry

new damage numbers are fine.

**Comment by Rexdyer1** [comment]
new numbers are pretty strong. especially considering that you can print this stuff off of a basic tool disk with two pieces of wood. when ya have such a strong weapon early game with such good stats, it kinda takes away the incentive to try and get better weaponry from moesci and NT.

**Review by hyperioo — APPROVED** [review]
Ok codewise, waiting for sprite opinion.

Also note that you nerfed IH hammer `ARMOR_PEN_DEEP` to `ARMOR_PEN_HALF` (nice sneaky try)

**Comment by ErisMeleeEnjoyer** [comment]
sprite opinion - my sprites are very good and dandy, i like the,m and want merge

**Comment by ErisMeleeEnjoyer** [comment]
also i didn't notice that i sneaky'd IH's sledge, but I guess it's intended now

**Comment by Pink-Chink** [comment]
Merge conflict with Gym. Will need to wait.

**Comment by Pink-Chink** [comment]
CI suite looks fine in the Checks tab, but's giving me grief in the Conversation tab.

**Pull request merged**
