### PR TITLE
bayonet changes

### PR DESCRIPTION
**Pull request by Alliostra**
## About The Pull Request

You can now attach ANY knife to guns instead of only tacknives.
The powered crossbow and the RXD can now hold bayonets
adds a description info to knives that tells people they can be attached to guns.
also fixes bayonets adding 15 to armor divisor (the old value from when armor_divisor was penetration). It now adds 1.6 armor divisor (the equivalent of 15 AP before)

## Why It's Good For The Game
bayonet_reere

Scoped energy-crossbow with a cleaver bayonet cool.
## Changelog
tweak: you can now use any knives as bayonets, this is documented in the description tab as well.
tweak: the powered crossbow and the RXD can now hold bayonets.
fix: fixes bayonets having absurdly high armor penetration
/:cl:

### CODE REVIEW

**Comment by Humonitarian** [comment]
Now make NT knives add extra damage to mutants.

**Comment by SirRichardFrancis** [comment]
> Now make NT knives add extra damage to mutants.

They already do, do they not? By having anti-mutant upgrade build-in.

**Comment by DiaFRAME444** [comment]
He means while they're in the bayonet.

**Comment by Humonitarian** [comment]
> > Now make NT knives add extra damage to mutants.
> 
> Yeah, I was thinking of making guns with bayonets actually attack with the knife they are holding, but that's too complicated to implement for now

You should be able to copy the sanctifier toolmod's effects onto the NT dagger

**Comment by Alliostra** [comment]
> > > Now make NT knives add extra damage to mutants.
> > 
> > 
> > Yeah, I was thinking of making guns with bayonets actually attack with the knife they are holding, but that's too complicated to implement for now
> 
> You should be able to copy the sanctifier toolmod's effects onto the NT dagger

NT dagger is already sanctified

**Comment by Humonitarian** [comment]
> > > > Now make NT knives add extra damage to mutants.
> > > 
> > > 
> > > Yeah, I was thinking of making guns with bayonets actually attack with the knife they are holding, but that's too complicated to implement for now
> > 
> > 
> > You should be able to copy the sanctifier toolmod's effects onto the NT dagger
> 
> NT dagger is already sanctified

Don't **apply** the effects, **add** them. Yknow, treating the dagger as a toolmod, since that's what it is.

**Review by TheShown911 — APPROVED** [review]

**Pull request merged**
