### PR TITLE
New Uniforms and New Signs

### PR DESCRIPTION
**Pull request by ValoTheValo**
## About The Pull Request
31-Aug-22 18-08-42
this PR adds some nt era redsec uniforms for vagabonds to wear, if anyone is going to be running around in 60 year old uniforms its vagabonds, it also updates the alternate inspector hat and coat to look nicer and adds two more signs for mappers to play around with

## Why It's Good For The Game
more customization and variety and some extra mapping stuff for later

## Changelog
:cl:
add: Vagabond and maint exclusive NT Security uniforms. Loadout option for military hats.
del: Removed deprecated loadout options
tweak: Renamed some loadout options to not be Bay era
imageadd: RedSec uniforms. New inspector coat and hat. Alternate Moebius and OneStar signs.
:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
should use TG sec colors instead of.. pink

**Comment by ValoTheValo** [comment]
> should use TG sec colors instead of.. pink

its our red clothing pallette. didn't make the sprites myself.

**Comment by thedarkcrusader** [comment]
Nah these don't look that bad looks decent that bright red from TG hurts to look at

**Comment by ValoTheValo** [comment]
31-Aug-22 18-31-43
better inspector uniform

**Comment by ValoTheValo** [comment]
the hat looks kinda bad but its not worse than the old one

**Comment by thedarkcrusader** [comment]
> 31-Aug-22 18-31-43 better inspector uniform

I am you show the old one side by side with the new one

**Comment by ValoTheValo** [comment]
> > 31-Aug-22 18-31-43 better inspector uniform
> 
> I am you show the old one side by side with the new one

what?

**Comment by thedarkcrusader** [comment]
> > > 31-Aug-22 18-31-43 better inspector uniform
> > 
> > 
> > I am you show the old one side by side with the new one
> 
> what?

Had a fucking stroke show the old and new one side by side.

**Comment by ValoTheValo** [comment]
> > > > 31-Aug-22 18-31-43 better inspector uniform
> > > 
> > > 
> > > I am you show the old one side by side with the new one
> > 
> > 
> > what?
> 
> Had a fucking stroke show the old and new one side by side.

31-Aug-22 19-17-50

**Comment by Humonitarian** [comment]
New hat is based

**Comment by ArmolitskiyCarpoeb** [comment]
I can resprite something if you want

**Comment by TheShown911** [comment]
soulless

**Comment by ValoTheValo** [comment]
> I can resprite something if you want

I honestly kinda like the pinkish red. It grew on me

**Comment by tristain01** [comment]
> > I can resprite something if you want
> 
> I honestly kinda like the pinkish red. It grew on me

I can dig it.

**Review by TheShown911 — APPROVED** [review]
Clean up the changelog.

**Pull request merged**
