### PR TITLE
Slime changes + electrocution changes

### PR DESCRIPTION
**Pull request by MLGTASTICa**
## About The Pull Request
Slime people now use 100 nutrition to regenerate a limb instead of 40
Fixed slime people regeneration not using the organ name
Slime people now have a warning  when their arms are ready to electrocute again
Slime people sprites adjusted to no longer crop out through suits (head and arms)
Electrocutions no longer stun
Electrocution weaken time is now dependant on power , with a minimum of 2 seconds for anything above 15 shock damage and a maximum of 10 seconds
Replaced "slime" with SPECIES_SLIME define where relevant for code standards

## Why It's Good For The Game
Less hardstuns, slime people QoL and adjustments
## Testing
Tested locally , all works as intended, people can finnaly move when electrocuted , wire splicing electrocutions and door ones still take a lot of time.

## Changelog
:cl:
add: Slimepeople now get warned when their glomp recharges
balance:Slimepeople now use 100 nutrition instead of 40 to regenerate limbs
fix: Slimepeople organ regeneration verb now mentions the actual organ name
balance: Removed stun from electrocutions
balance: Weaken from electrocution is now dependant on the shock_damage, any damage above 15 will shock now for 2  seconds minimum and 10 seconds maximum , 
/:cl:

### CODE REVIEW

**Comment by Humonitarian** [comment]
nhp8v4DVda_nice

**Comment by Firefox13** [comment]
изображение
ahem

**Comment by Humonitarian** [comment]
Might be worth to mention,

Slimes experience agony and can get paincritted.
They however cannot experience unconsciousness and will remain aware of their surroundings, able to see and hear everything clearly, despite not being able to interact with the world.

Can't tell which parts are bugs and which parts are intended, or if slimes were even supposed to feel pain in the first place, but yeah

**Comment by MLGTASTICa** [comment]
> Might be worth to mention,
> 
> Slimes experience agony and can get paincritted. They however cannot experience unconsciousness and will remain aware of their surroundings, able to see and hear everything clearly, despite not being able to interact with the world.
> 
> Can't tell which parts are bugs and which parts are intended, or if slimes were even supposed to feel pain in the first place, but yeah

its a bug caused by them seeing without any eyes or a missing hud.

**Review by TheShown911 — APPROVED** [review]

**Review by hyperioo — APPROVED** [review]

**Pull request merged**
