### PR TITLE
Factorio, but with plants (Alchemy Reigns)

### PR DESCRIPTION
**Pull request by Mycah142**
## About The Pull Request
Reintroduces Real Egg Plant, which I found referenced as a mutation of eggplants but the rest was empty. Filled it in, gave it yolk as an additional reagent, and added it's seed packet data and put it into the Curious Seeds of the NT Vendor. Also introduced animal protein as a reagent to blood tomatoes.

## Why It's Good For The Game
A fun thing to do with botany is mix reagents within them, see how far you can push the envelope. I found that one can mix chocolate bars in a plant, so I figured why not meatballs and dough? This essentially lets a skilled person with the right equipment splice up some plants to "automate" the more mundane mixing of basic cooking ingredients.

Plus it's funny as shit when a new player witnesses a plant straight up fart out chocolate bars. This'll be even funnier.

Meatball plant.

## Testing

Klk7fKAH58
uBYzDug41W
dreamseeker_rIZAGihbyq

## Changelog
:cl:
add: Real Egg Plant
add: Animal Protein to Blood Tomato
:cl:

### CODE REVIEW

**Review by Firefox13 — COMMENTED** [review]
tg has similar plant (except it harvests literal eggs) and they have just "eggplant" and "egg plant". I think that's funny can we get the same?

**Comment by Mycah142** [comment]
> tg has similar plant (except it harvests literal eggs) and they have just "eggplant" and "egg plant". I think that's funny can we get the same?

I did try to make it drop actual eggs but I had some trouble, so I went the simpler route.

If it's any consolation, the result does work as an egg in recipes.

**Comment by Firefox13** [comment]
"egg plant" and "eggplant" is a world of difference. I think it's funny, please change

**Comment by Mycah142** [comment]
> "egg plant" and "eggplant" is a world of difference. I think it's funny, please change

Done via mobile editor. Hopefully that's acceptable.

**Review by TheShown911 — APPROVED** [review]

**Pull request merged**
