### PR TITLE
refactor some human abilities

### PR DESCRIPTION
**Pull request by null-Aurelian**
we had about 300 lines of ability code that could have been under human_powers.dm

## About The Pull Request

Moving abilities previously found under human.dm to human_powers.dm

## Why It's Good For The Game

Because it makes the human.dm file more readable and logically separates human powers into their own file where it makes sense we'd find them via casual search. 

## Testing

Tested by comparing effects when running all procs with the ability tag in human dm before and after moving and verifying that the effects were the same.

## Changelog
:cl:
refactor: refactor location of commune(), psychic_whisper(), morph(), phaze_trough(), forcespeak(), remotesay(), remoteobserve(), roach_pheromones(), spider_pheromones() and inner_fuhrer()
/:cl:

### CODE REVIEW

**Review by TheShown911 — APPROVED** [review]
You could sneak a DB nuke in here and I wouldn't notice

**Comment by null-Aurelian** [comment]
My eyes kinda glazed over too when I was trawling through the human.dm file looking for some way to turn a torso into a robotic version.
Then I got mad that all this shit was here and not somewhere that made sense

**Review by hyperioo — COMMENTED** [review]
Seems free of any nuke, Space Gandhi is satisfied.

**Comment by null-Aurelian** [comment]
> Seems free of any nuke, Space Gandhi is satisfied.

wouldn't it be the opposite way around?

**Pull request merged**
