### PR TITLE
Mapped Central Fuel Chamber, plus various atmos related troubleshooting and map fixes

### PR DESCRIPTION
**Pull request by Mycah142**
## About The Pull Request
What started as just making a central fuel tank turned into "What do the numbers MEAN?!", and realized Atmospherics depowering was due to map var edited devices not being done well. 
ShareX_NgFiIeezpk

Here's a step by step as to what I changed: (I tried to do spoilers, but then the images didn't embed properly. I don't know.)

- Removed Supermatter Tip references,  as it's no longer our main engine. Left manuals untouched.

- Added central fuel tank for thusters near atmospherics (in the old Wasting Room where the SM would vent to). Left the smaller individual tanks as "emergencies", connected only to canister ports. Hopefully this redundancy doesn't lead to confusion.
dreamseeker_hw2tvc6K2W

- Removed fuel chamber passive vents, as they continually leaked fuel into the piping. Replaced with lockdown shutters.
dreamseeker_8dLii1UjYi

- Replaced incorrectly var edited gas tank vents with better hard-coded variant, so the only edits needed were for ID Tags.
StrongDMM_iLKtezwwOz
StrongDMM_kJmuvUm1zF

- Added manual valves to cause gas to flow through pipes that wouldn't without them (Plasma tank and Nitrogen tank wouldn't flow round-start without an open manual valve added near Plasma to the thrusters, and Oxygen to the thrusters. Black magic as far as I'm concerned, I spent three hours on this.)
StrongDMM_XROcneNh1x
StrongDMM_nfVcniHezq

- Added coded thruster fuel mixing valve, preset to a 50/50 mix (default to the device), with a description on examine to encourage players to mix it themselves.</summary>
dreamseeker_Oy14jhPLhD

- Added a Hibernation to all vents. If they haven't used power, they don't try to process again between 100-200 ticks. This is measured individually to the vent, and should heavily reduce processing as 99% of vents never encounter a reason to process.
This has lead to many APCs reading negative Total Load, but some areas displaying a negative Total Load has been common since lights no longer process and thus no longer draw power.

- Added Temperature as a process trigger, so every cold room doesn't absolutely NEED someone to drag a heater into it just to stop the fire alarm.

- Fixed mix chambers gas sensors not correctly displaying all gasses in it's composition display. (N2O doesn't have a flag I know about)
old
old
new
new

## Why It's Good For The Game
Atmospherics shouldn't depower within 5 seconds (it's five minutes now ha), and thruster setup should be easier to understand. With a central tank that doesn't need individual thruster set up, it's also faster to do. Select your mix, open the valves, and then open the manual valve outside the window. Previously, when the chamber appeared empty, players thought that fuel was empty, but it was actually entirely in the piping.

Also bugfixes good. The bugfixes involved alot of map editing, so they're part of this PR as they were related to making the Thruster Chambers work as expected.

## Testing
Trust me bro.

Please see the summaries above. I spent alot of time learning how these items work to try and make the best solution.

## Changelog
:cl:
add: Central Thruster Fuel Chamber, and related valves to make it work.
del: Pipe confusion in individual thruster rooms, separating Central Chamber from Emergency Chambers.
del: Supermatter related tips from job text.
tweak: Vent processing to introduce a hibernation, and temperature trigger.
tweak: Fuel chamber venting no longer a passive vent, now shutters.
fix: Map Var Edited gas chamber vents to obey internal pressure, now only should be map edited for ID Tags.
fix: Mixing chamber gas sensors should now display all gas contents in Gas Composition.
/:cl:

### CODE REVIEW

**Review by TheShown911 — APPROVED** [review]
Code looks okay though i have no clue how any of this works.

**Comment by Mycah142** [comment]
Working to fix map now.

**Comment by Mycah142** [comment]
didn't mean to push, god dammit.

**Comment by Mycah142** [comment]
I'll have this one ready for next week, as the amount of mapping needs to be retested. If anything, I could remove the DMM and we can just go with the optimization.

**Comment by Mycah142** [comment]
I have no idea why I had to "update from master" three times, with one of those commits containing zero changed files, and each time the map was perfect on my end, but whatever, you do you github desktop.

Good news, I learned how to force a new head commit today using the terminal.

**Pull request merged**
