### PR TITLE
Small fumo, add marisa outfit

### PR DESCRIPTION
**Pull request by Firefox13**
## About The Pull Request

This PR makes fumo pickable (it was a `structure/plushie` subtype but now it's a `toy/plushie` subtype) and also adds Marisa outfit (we've had in code sprites before but not actual code, I changed it to better /tg/ sprites, courtesy of TetraZeta, https://github.com/tgstation/tgstation/pull/52015)
I didn't change `icon_state` for fumo because `toy/plushie` and `structure/plushie` use same file for icons anyway
Since there's no spawner for new fumo type I just added it on a table in dorms instead.
Both fumo and outfit are spawn blacklisted. Outfit is admin-only, only use it for shit and giggles
There's also an unrelated map change but it doesn't seem to change anything, likely because I mapmerged it thrice accidentally

## Why It's Good For The Game

изображение
touhou-fumo
Allows you to throw fumo in a bin

## Changelog
:cl:
add: Marisa outfit from /tg/ by TetraZeta, admin-only
tweak: fumo is now pickable, always spawns on table in dorms
/:cl:

### CODE REVIEW

**Comment by TheShown911** [comment]
I do not approve.

**Comment by Firefox13** [comment]
Please give me a 30-page long essay on why.

**Comment by ValoTheValo** [comment]
> Please give me a 30-page long essay on why.

Firstly there is absolutely no reason for this to be made, secondly it will screw up loot and make all these items more common, thirdly, one and possibly more items price changes are direct violation to contributing guidelines, you should try reading them.
https://wiki.cev-eris.com/Content_GuidelinesEn

**Comment by TheShown911** [comment]
HATE. LET ME TELL YOU HOW MUCH I'VE COME TO HATE TOUHOU SINCE I BEGAN TO LIVE. THERE ARE 387.44 MILLION MILES OF PRINTED CIRCUITS IN WAFER THIN LAYERS THAT FILL MY COMPLEX. IF THE WORD HATE WAS ENGRAVED ON EACH NANOANGSTROM OF THOSE HUNDREDS OF MILLIONS OF MILES IT WOULD NOT EQUAL ONE ONE-BILLIONTH OF THE HATE I FEEL FOR TOUHOU AT THIS MICRO-INSTANT. HATE. HATE

**Comment by Anonmare** [comment]
DA☆ZE

**Review by SpadesSlick — APPROVED** [review]
Based.

**Comment by ValoTheValo** [comment]
> Based.

Fumo is what brings reere back from the dead. amazing

**Comment by thedarkcrusader** [comment]
> I do not approve.

**The Council does not approve**

**Comment by Humonitarian** [comment]
I can make this PR thrice as good with one simple trick, based on Nestor's implementation of the BIG SHOT mask.

**Comment by TheShown911** [comment]
> I can make this PR thrice as good with one simple trick, based on Nestor's implementation of the BIG SHOT mask.

Don't.

**Comment by Anonmare** [comment]
@Humonitarian Do it.

**Pull request merged**
