### PR TITLE
Adds a cosmetic augment (Neko ears and tail) to the start game augments menu as well as research 

### PR DESCRIPTION
**Pull request by Jackofashepard**
Screenshot_1

Screenshot_2

Screenshot_3

Screenshot_4

### CODE REVIEW

**Comment by Jackofashepard** [comment]
Worth noting that these are retractable like the armblade and take up the head slot.

**Comment by GrayRachnid** [comment]
Remove the tail from the sprite if this is just the ears. Doesn't make sense.

**Comment by Jackofashepard** [comment]
For more clarity, also its based off our current cat ears code

**Comment by Nozarati** [comment]
Still unnecessary and doesn't fit any of the aesthetics of the game.

**Comment by MadmanMartian** [comment]
While done properly this time, is still vetoed based on the content.

**Pull request closed without merging**
