### PR TITLE
Ring Holsters for Axes and Hammers

### PR DESCRIPTION
**Pull request by assortedbeads**
## About The Pull Request
Adds a craftable ring holster for some hammers and the hatchet.
Same recipe as the makeshift scabbard.

Sprites are just shortened versions of the baton and makeshift scabbard respectively.
Uses the sword draw and sheath sounds till I can find a better replacement.

Can store
- Makeshift mace
- Mace
- Power hammer
- Baseball bat
- Bone mace
- Hatchet

## Why It's Good For The Game
Hammers and Axes didn't have the storage option that swords did, this gives them that option.

HammerRingSheath HammerRingSheathMob
HammerSalt
RingSheathBack RingSheathFront RingSheathLeft RingSheathRight

## Changelog
:cl:
add: Adds recipe for a ring sheath
imageadd: Adds icons and sprites for a ring sheath
/:cl:

### CODE REVIEW

**Comment by assortedbeads** [comment]
> Conflicts with #7569. I might just make it so that the baton one accepts there in my PR.

You are removing uniform storage so of course it conflicts

**Comment by ErisMeleeEnjoyer** [comment]
Read the PR again, I am not removing them.

**Comment by ErisMeleeEnjoyer** [comment]
because 1984.

**Comment by maikilangiolo** [comment]
Need to allow the weaker melee weapons too. Cleaver, NT short sword for sure.

**Comment by assortedbeads** [comment]
> because 1984.

Not a proper answer

**Comment by assortedbeads** [comment]
> Need to allow the weaker melee weapons too. Cleaver, NT short sword for sure. 

If you're allowing the short sword then allow the maces too

**Comment by maikilangiolo** [comment]
You're the one that's coding the mace holsters. Change it to allow the one handed maces and hammers, I can't.

**Comment by assortedbeads** [comment]
> You're the one that's coding the mace holsters. Change it to allow the one handed maces and hammers, I can't. 

They literally already do? The code and what I wrote are right there

**Comment by ValoTheValo** [comment]
Based PR. more reasons to use a hammer now.

**Comment by assortedbeads** [comment]
> Based PR. more reasons to use a hammer now. but question. how large of a hammer can you fit? like onestar hammer size?

You should only be able to fit up to a power hammer, but tbh Im still contemplating that. Might remove it in a few hours.

Only the ones listed in the description can fit in, since it's basically hanging off your waist and the one star hammer is like, sledgehammer size I believe?

**Comment by assortedbeads** [comment]
> Based PR. more reasons to use a hammer now. but question. how large of a hammer can you fit? like onestar hammer size?

Updated, nothing bigger than a mace now

**Comment by ErisMeleeEnjoyer** [comment]
well it conflicts with #7577 now. this one doesn't have your nerf you care about.

**Comment by assortedbeads** [comment]
> well it conflicts with #7577 now. this one doesn't have your nerf you care about.

Looks like your scabbard is just a catch all for melee weapons unless Im missing something, did you even make a distinction?

**Comment by ErisMeleeEnjoyer** [comment]
well, yeah, it explicitly says that it needs to be attached. as for sprites, scabbards use(and used) sheath sprites(which is why i removed them in the first pr)

**Comment by assortedbeads** [comment]
> well, yeah, it explicitly says that it needs to be attached. as for sprites, scabbards use(and used) sheath sprites(which is why i removed them in the first pr)

Can hammers/maces even be attached to the uniform in your pr

**Comment by ErisMeleeEnjoyer** [comment]
I am currently stealing your sprite and doing that, so, yes

**Comment by ErisMeleeEnjoyer** [comment]
rightfully stolen and merged to my stuff, now it's mine

**Comment by assortedbeads** [comment]
> rightfully stolen and merged to my stuff, now it's mine

Push the changes then

**Comment by ErisMeleeEnjoyer** [comment]
doen

**Comment by assortedbeads** [comment]
Closing this since the changes are represented in another pr

**Pull request closed without merging**
