### PR TITLE
Autolathe/R&D design unification

### LINKED ISSUE #3444: [R&D/Autolathe PR bugs] Radiocarbon Spectrometer
image
Buttons and text connecting with progress bars

### PR DESCRIPTION
**Pull request by ACCount12**
This PR makes R&D designs and autolathe design datums compatible. It also removes a ton of shitcode and makes adding new R&D designs easier. It also changes autolate UI a bit and fixes some unrelated bugs.

You can now print blank design disks in R&D, load them with R&D designs and use them in autolathes.

Closes #3444.

### CODE REVIEW

**Comment by ACCount12** [comment]
I'm putting it up on the test server. DNM until that happens.

**Comment by ACCount12** [comment]
Test server update failed for some reason. Try again now.

**Comment by ACCount12** [comment]
I've been considering that, but decided against it. Would be hard to implement, especially if you take my further planned update into consideration. And if you want to sell a limited amount of something, just sell items. Disks are more about selling manufacturing capability.

**Comment by SpadesSlick** [comment]
Tested, no problems so far.

**Pull request merged**
