### PR TITLE
More fixes

### LINKED ISSUE #2915: RCD cannot deconstruct low walls.

### LINKED ISSUE #3194: Can't detach signallers
BUG: Can't detach signallers
unknown (6)

### LINKED ISSUE #3201: Preacher can't connect soul to new body, because of sitting in old corpse
Preacher can't use "Reincarnate", while ghost sitting in old body, that forces him to using ahelp, or LOOC to talk with dead guy. Make this litany automatically push ghost from old body, and put into new.

### PR DESCRIPTION
**Pull request by soslow4u**
- Morgue respawn bonus
There always was message about your corpse properly handled with morgue tray. Even when you respawned already. Also, fixes related runtime on morgue  non-mob storing event.
- RCD supports low walls now. (Closes #2915)
It would be built without windows, if you would need windows - ping me.
- Signaler could be detached with bare hands now (Closes #3194)
- [NT] Cloning with reincarnation is possible with ghost sitting in old body (Closes #3201)
- Proper zero-g behaviour around simulated open space tiles and some animation fixes. Also removed some dublicated calls
Animations are quite inconsistent, so expect floating bodies in area with gravity still. You can get your mob floating, but all its vars would state that mob wasn't animated. Joy.
- Fix about console runtime, trying to get your ID when you got only PDA. Maybe realted to #3385, but really not sure about it.
- Fix around drag'n'drop feature that could be aboosed by dead mobs
- Jetpack nerf and proper inertia stuff. Praise be.

### CODE REVIEW

**Comment by soslow4u** [comment]
added drag'n'drop fix thingie

**Comment by SpadesSlick** [comment]
Oooh, that a lot of fixes, you sure can't split them on different PR's?

**Comment by soslow4u** [comment]
tbh they are quite too smol to do it in different prs. Except RCD, but its just unwrapping ifs to switch

**Comment by SpadesSlick** [comment]
No problem, I guess, just do that with further PRs.

**Comment by soslow4u** [comment]
Welp, quite many stuff, but it all is related to zMovement, movement in spess/zero-g and jetpacks. I swear to god this should be done now.
- Jetpack nerf, as it was made to hop around z levels even in areas with gravity. Now you gotta use it only in zero-g. [#2387](https://github.com/discordia-space/CEV-Eris/pull/2387)
- Less duplicated inertia code, movement code and such stuff.
- Almost all mobs that got `allow_spacemove` proc would return -1 or for it. it means slipping and movement around walls and heavy objects in zero-g
- Fixes around zMovement. You was able to shift thru floor from below if it got nothing blocking on its turf.
- Refactoring and even more refactoring.

**Comment by SpadesSlick** [comment]
Wait why would you add even more, stop

**Comment by SpadesSlick** [comment]
You can't just pile up 20 bugfixes for different things in one PR, it will slow down the review, and we can't merge them separately.

**Comment by soslow4u** [comment]
Ye ye, but this one was quite urgent, as I saw some victims of floor phasing.

**Comment by SpadesSlick** [comment]
If your fix is urgent you have EVE MORE reasons to make it separate PR.

**Pull request closed without merging**
