### PR TITLE
Public Church

### PR DESCRIPTION
**Pull request by Mycah142**
## About The Pull Request
Replaced doors leading to the stairwell from the sanctuary with public cruciform doors, with the little janitor closet removed and it's equipment moved below.

Made New Areas to isolate the previously weirdly constructed Ritual Room, now is Ritual, Bioprinter/Work, and Altar rooms.

Public Cruciform Doors connect the Ritual Room (Currently a green room, the space is needed for the Rituals expansion later), which was previously where the Cloner was.

Cloner and Altar were moved east, separated from the Ritual Room with Rwalls and a Clergy Door, with a little abutting storage room where the janitor closet supplies now are, as well as a White Wardrobe for initiates who haven't earned church vestments yet, and spare Ritual Books. The Last Shelter is visible from the Bioprinter Room.

The Bioprinter Room is shortened, with the Sword of Truth moved into it. The weird as shit floor paper bin is removed, because why the fuck has it been there forever I have no idea.

The Storage rooms where the Cahor's and Coffins were stored has been conjoined into a Clergy break room, with a water cooler. Cahors is stored here as well, minus 1 barrel.

The old Cloner room, now the Ritual Room, is filled with greens and a couple card tables currently occupied by tarot decks.

At the bottom floor, a table and windoor were added to the Agrocultural Room wall adjoining the hallway to cater to passers' by.

Rwalls replaced the windows into the Bioreactor room for safety reasons, with the red "main" power wire from the Biogenerator rerouted to the garden immediately to avoid cables under Rwalls.

Misc. fire extinguishers were added, lights moved, APCs moved, wires moved, to accommodate the new areas and their structure to keep them visually appealing.

Coffins were halved and moved to the Body Flinger room, as they were just free wood in a convenient spot near the Bioprinter previously. Grow tower caps you lazy shmucks.

## Why It's Good For The Game
Those of the Faith can exist outside the church, but are usually shunned by the church. This doesn't facilitate the sense of community the church builds upon. With a more public church (to outsiders with cruciforms), this simultaneously creates a better sense of community and inclusion while also making the church slightly less vulnerable to those outside the faith.

Also I got to add more greenery. Which is nice.

## Testing
Firefox wanted screenshots instead of a video.

SDMM:
StrongDMM_X21WU9JVcC
StrongDMM_e0e14lv7Pp
StrongDMM_NlcJWOu4V4
Had to redirect the red power wire, as with the removal of the window into the bioreactor, wires can't be under Rwalls, so it was redirected through the Garden more immediately.
StrongDMM_wuGLITwh7Q

Ingame:
dreamseeker_bYsTpJ5Who
dreamseeker_mIJHweroRw
dreamseeker_VVanjZ897Z
dreamseeker_DIwrzdCCWY
dreamseeker_uFRV5RnI9k
dreamseeker_4jZISKnHA9

## Changelog
:cl:
tweak: Minor reorganization of the Church to allow "public" visitors.
/:cl:

### CODE REVIEW

**Comment by Mycah142** [comment]
Alternative: Swapping the green room with the cloning room, but keeping the size the same, and changing the public door between them to a clergy door.

Would mean the green room is adjacent to the stairwell, and it seems that some folk think average joe faithful having access to the cloner and altar is a bad thing.

**Comment by garrulousTeamotei** [comment]
Not changing the maintenance doors for those semi-public areas?

**Comment by Mycah142** [comment]
> Not changing the maintenance doors for those semi-public areas?

Just as reality, the common folk can enter the church but not enter the backrooms, nor exit from the back under normal circumstances.

For extreme circumstances, apply gun to door.

**Comment by TheLeopold** [comment]
I suggest moving upper stairs to the right and place a door to block passage to the lowest floor.
Like this. 
изображение
There's no reason to let common folk access "the sacred machinery".
And keep the cloner public, wasn't that the whole point?

**Comment by Mycah142** [comment]
At this point the map is out of my hands. I have been accepting input from Fox, who is happier with it this way, and agreed with Daget that leaving the Cloner public will invite grief they won't punish.

**Comment by null-Aurelian** [comment]
Could you make the gift shop up by the theomat general cruciform access? Not like many people use that spot right now

**Comment by Mycah142** [comment]
> Could you make the gift shop up by the theomat general cruciform access? Not like many people use that spot right now

No, when the public door was first made, the shop had it and it was awful. It's the churches stall, if a vagabond wants to work it, they can be granted clergy access as a sanctioned member of the Church, and not just the Faith.

**Comment by hyperioo** [comment]
Hmm, merging #8271 made it conflict, I hoped it wouldn't have seen it was just small tweaks in custodian and acolyte rooms that you did not touch. Easier for your would be to save your dmm somewhere, rebase then reapplied the dmm and redo the changes of #8271 (it's just like changing spawn tokens and fixing a pipe)

**Review by hyperioo — APPROVED** [review]

**Pull request merged**
