### PR TITLE
New fire extinguisher sprites, overlays and extinguisher cabinets (sprites by WatlerJe)

### PR DESCRIPTION
**Pull request by Deon-DF**
## About The Pull Request

Fire Extinguishers:
Change the sprite of our fire extinguishers to the new ones. Found in #assets_storage sprited by WatlerJe

## Why It's Good For The Game

A task requested by Gray.

## Changelog
:cl:
imageadd: new Fire extinguisher/mini fire extinguisher and extinguisher closet sprites by WatlerJe
imageadd: 6 different cosmetic variations of standard (red) fire extinguisher.
imageadd: extinguisher closets show which type of extinguisher is inside when closed.
/:cl:

### CODE REVIEW

**Comment by GrayRachnid** [comment]
add new sprite stats for when the cabinet is full and closed to show that a fire extinguisher is inside.

Make the fire extinguisher sprite have a random selection from all the sprites that watler offers.

**Comment by Deon-DF** [comment]
Corrections accepted:
- 6 different cosmetic overlays for FE (only red, not mini/mech).
- Closed extinguisher closets have different icons based on contained FE.
- Fix for closets, now they update icon when created, not on being opened/closed.

**Comment by Deon-DF** [comment]
A proper fix for checking for extinguisher type when applying overlays. Inclusion instead of exclusion.

This should he ready now unless you want me to implement some easter egg/rare spawn with golden Fire Extinguisher.

**Comment by Deon-DF** [comment]
Done:
- Cosmetic overlays for fire extinguishers are now a list.
- Standard FE has this list, mini/mech FE have this list empty.
- It means that in the future, custom sprite overlays for any FE type can be made and simply added to this list.
- New() moved to Initialize().

**Pull request merged**
