### PR TITLE
Fuck parapen

### PR DESCRIPTION
**Pull request by AgentMA1**
## About The Pull Request
Removes parapen from the uplink and from the ship.

## Why It's Good For The Game
The parapen is an oldified, SS13 generic tator tool. It has a broken stun that makes any combat impossible. If we are focusing on a better and funnier PVP we need to cast this to the shadow realm of oldified baycode. Also, the stun is bugged and infinite, so, more reasons to cast this into the shadow realm. I just had this idea while petting my cat, if want this dumb pen to stay, go ahead,i prefer it leaves but eh,not like i care much.

## Changelog
:cl:
del: Removed Parapen from this ship
/:cl:

### CODE REVIEW

**Comment by FortuneMaster** [comment]
The chem was supposed to be completely changed, but I guess removal will work too for the time being

**Comment by MLGTASTICa** [comment]
fuck parapen but keep in assasin dagger that is parapen but without care for armor?

**Comment by AgentMA1** [comment]
> fuck parapen but keep in assasin dagger that is parapen but without care for armor?

Assasin dagger is getting changes so,no point in touching it

**Comment by Iglpigl** [comment]
> fuck parapen but keep in assasin dagger that is parapen but without care for armor?

Fortune plans to add something similar to carrions too with an organ they can get that's probably why dagger stays.

**Comment by FortuneMaster** [comment]
> > fuck parapen but keep in assasin dagger that is parapen but without care for armor?
> 
> Assasin dagger is getting changes so,no point in touching it

not changes, just a fix of a bug that I was told about

**Comment by maikilangiolo** [comment]
> > fuck parapen but keep in assasin dagger that is parapen but without care for armor?
> 
> Fortune plans to add something similar to carrions too with an organ they can get that's probably why dagger stays.

Can't wait to have ling parasting back in the game, one of the main reasons ling was removed and replaced with carrion.

**Comment by FortuneMaster** [comment]
ok, the para is getting removed completely without any kind of rework or come back

**Comment by AgentMA1** [comment]
> ok, the para is getting removed completely without any kind of rework or come back

Want the assasin dagger to be killed too? Or just parapen

**Comment by FortuneMaster** [comment]
just pen

**Comment by L74814** [comment]
based

**Review by TheShown911 — APPROVED** [review]
Based

**Comment by Firefox13** [comment]
Based

**Pull request merged**
