### PR TITLE
Removes the virus event

### PR DESCRIPTION
**Pull request by Pink-Chink**
## About The Pull Request

Title.

## Why It's Good For The Game

Old bay leftover that causes more trouble than it's worth.

## Testing

- Checked storyteller panel.

## Changelog
:cl:
del: Removed virus event
/:cl:

### CODE REVIEW

**Review by SirRichardFrancis — APPROVED** [review]
Good. Next step - entire virology (feature not used since 2015).

**Comment by Pink-Chink** [comment]
Once Firefox maps it out or gets someone to map it out, we can cut it for good.

**Comment by glaciusinfinity** [comment]
I want virology to be reworked, not removed outright. Admittedly I want to keep it for selfish reasons (I think it has the potential to be really funny).

**Comment by DiaFRAME444** [comment]
Are you going to rework it?

**Comment by Iglpigl** [comment]
> Once Firefox maps it out or gets someone to map it out, we can cut it for good.

Once all current open mapping PRs get merged I can map it out, shouldn't be too hard.

**Comment by Firefox13** [comment]
I'll turn the virology into something else in a different PR

**Comment by Iglpigl** [comment]
Sure thing, changing is better then removing.

**Review by TheShown911 — APPROVED** [review]

**Pull request merged**
