### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ValoTheValo**
## About The Pull Request
update name thing

## Changelog
:cl:
add: Added new things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
fuck wrong thing

**Comment by ValoTheValo** [comment]
certified smoothbrain contributor moment

**Comment by Wouju** [comment]
bro didnt even change the changelog smh

**Comment by SirRichardFrancis** [comment]
It's "Unofficial" btw, not "Unnofical".

**Comment by ValoTheValo** [comment]
> It's "Unofficial" btw, not "Unnofical".

Fucking christ how stupid am i

**Pull request closed without merging**
