### PR TITLE
Katana Fat Shaming

### PR DESCRIPTION
**Pull request by Mycah142**
## About The Pull Request
This changes the size of the Nano Katana from being "Normal" sized, to Huge.

## Why It's Good For The Game
Currently the Nano Katana is incredibly powerful while being unreasonably easy to store for it's capabilities. It starts at 30 damage _unpowered_, where as any other bladed weapon of it's size starts at 21 damage and without the armor penetration. It would fit into any satchel, tool belt, and even an engineering pouch or medium pouch. Which is insane, it's a non-telescopic **SWORD** that somehow fits in the same spot your wallet does.

It still fits on the Uniform, Belt, and Back slots.

This also gives it double-tact, like any other melee weapon of it's damage class. Weep.

## Testing
dreamseeker_XnKyIj3gK7
[dreamseeker_Snv9navoBf.webm](https://github.com/discordia-space/CEV-Eris/assets/11076040/8cfcc570-67e0-45f0-9218-076d7d8a6556)

## Changelog
:cl:
balance: Balanced Nano Katana to fit it's damage class.
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
Insert your CKEY and Character Names in Discussions so the Moebius Metagang knows who to bully and metagame IC.

**Comment by Mycah142** [comment]
If they don't know who I am at this point that's their own fault for being blind.

**Comment by Mycah142** [comment]
>But they ARE just gonna swap over to using claws or armblade implants, since they're always there and are retractable Plus they do similar damage I think

Good, that is at least somewhat unique to their department and at least isn't pulling a fukken big ass sword from their cargo shorts.

**Comment by thevandie** [comment]
Can't argue with that

**Comment by Humonitarian** [comment]
Instead of increasing size, make it deal the same damage as other swords, but with more AP

**Comment by Mycah142** [comment]
> Instead of increasing size, make it deal the same damage as other swords, but with more AP

Honestly should just make it so weapons don't fit into tool belts or pouches. Just because a sword has 10 cutting quality doesn't mean it also fits next to my screwdriver.

**Comment by MemedHams** [comment]
> > Instead of increasing size, make it deal the same damage as other swords, but with more AP
> 
> Honestly should just make it so weapons don't fit into tool belts or pouches. Just because a sword has 10 cutting quality doesn't mean it also fits next to my screwdriver.

the Just Punch People meta grows in power
also belts literally contain full-size shovels and crowbars

**Comment by thevandie** [comment]
>literally contain full-size shovels, wrenches and crowbars

Tbf, those are tools
A sword isn't

**Comment by assortedbeads** [comment]
> Tbf, those are tools
> A sword isnt
It's a tool for killing

**Comment by garrulousTeamotei** [comment]
Nice change. Make sure not to overlook the Claymore and the junksword. NT already did the size balancing pretty well, with only the piss poor damage Short Sword being sized normal.

**Comment by Humonitarian** [comment]
> > Instead of increasing size, make it deal the same damage as other swords, but with more AP
> 
> Honestly should just make it so weapons don't fit into tool belts or pouches. Just because a sword has 10 cutting quality doesn't mean it also fits next to my screwdriver.

That would require a buff to them tbh. Not sure how much we can rely on these band-aid fixes

**Comment by thevandie** [comment]
It would not. Just shove it onto your empty belt slot, or your sheath

**Comment by Mycah142** [comment]
> 
> That would require a buff to them tbh. Not sure how much we can rely on these band-aid fixes

I considered the same, but considering there are uniform accessories that also hold these same melee weapons, available at loadout or midround (with the exception of the scabbard, which the accessory version is only in the loadout. The Sheathe isn't an accessory, and the makeshift scabbard only holds junkblades).

The current ability to hold a large gun on uniform, an SMG on belt, an ammo pouch in a pocket, another gun in a concealed carry, and an engineering pouch with a melee weapon, is far too many available weapons without even talking about backpack storage.

**Comment by Mycah142** [comment]
I think I've come up with a better solution overall.

Engineering Pouch fits into ones pocket. The fact you can fit four fucking shovels in your pocket is nuts, because it accepts any tool that's Normal or smaller.

I think the Engineering Pouch should only accept tools Small or Tiny, and leave the Tool Belt to accept Normal.

This would mean Spades still fit into the engineering pouch, Shovels fit into the Belt, and weapons of Normal size fit into the Belt still.

This would mean examining each tool and changing their item size for both realism and mechanical logic with a happier blend.

**Comment by Mycah142** [comment]
I think I've come up with a better solution overall.

Engineering Pouch fits into ones pocket. The fact you can fit four fucking shovels in your pocket is nuts, because it accepts any tool that's Normal or smaller.

I think the Engineering Pouch should only accept tools Small or Tiny, and leave the Tool Belt to accept Normal.

This would mean Spades still fit into the engineering pouch, Shovels fit into the Belt, and weapons of Normal size fit into the Belt still.

This would mean examining each tool and changing their item size for both realism and mechanical logic with a happier blend.

**Comment by Mycah142** [comment]
I think I've come up with a better solution overall.

Engineering Pouch fits into ones pocket. The fact you can fit four fucking shovels in your pocket is nuts, because it accepts any tool that's Normal or smaller.

I think the Engineering Pouch should only accept tools Small or Tiny, and leave the Tool Belt to accept Normal.

This would mean Spades still fit into the engineering pouch, Shovels fit into the Belt, and weapons of Normal size fit into the Belt still.

This would mean examining each tool and changing their item size for both realism and mechanical logic with a happier blend.

**Comment by Mycah142** [comment]
I think I've come up with a better solution overall.

Engineering Pouch fits into ones pocket. The fact you can fit four fucking shovels in your pocket is nuts, because it accepts any tool that's Normal or smaller.

I think the Engineering Pouch should only accept tools Small or Tiny, and leave the Tool Belt to accept Normal.

This would mean Spades still fit into the engineering pouch, Shovels fit into the Belt, and weapons of Normal size fit into the Belt still.

This would mean examining each tool and changing their item size for both realism and mechanical logic with a happier blend.

**Comment by Mycah142** [comment]
I think I've come up with a better solution overall.

Engineering Pouch fits into ones pocket. The fact you can fit four fucking shovels in your pocket is nuts, because it accepts any tool that's Normal or smaller.

I think the Engineering Pouch should only accept tools Small or Tiny, and leave the Tool Belt to accept Normal.

This would mean Spades still fit into the engineering pouch, Shovels fit into the Belt, and weapons of Normal size fit into the Belt still.

This would mean examining each tool and changing their item size for both realism and mechanical logic with a happier blend.

**Comment by Mycah142** [comment]
I think I've come up with a better solution overall.

Engineering Pouch fits into ones pocket. The fact you can fit four fucking shovels in your pocket is nuts, because it accepts any tool that's Normal or smaller.

I think the Engineering Pouch should only accept tools Small or Tiny, and leave the Tool Belt to accept Normal.

This would mean Spades still fit into the engineering pouch, Shovels fit into the Belt, and weapons of Normal size fit into the Belt still.

This would mean examining each tool and changing their item size for both realism and mechanical logic with a happier blend.

**Comment by DiaFRAME444** [comment]
We heard you the first time.

**Comment by Mycah142** [comment]
Thanks @TheShown911, very cool.

**Review by Firefox13 — COMMENTED** [review]
Most "weapons" (katanas, swords, etc.) can be put into toolbelts because they are considered tools by the game.

If you want to nerf swords sizes then do it to all of them for consistency instead of the one and only super OP.
If going small step at a time, all of them can be made bulky (so you can't stuff them into pouches and belts, they're fucking **SWORDS**) but without double-tact (they are not heavy) (double-tact can be added later if they are still OP).
Pulling out a fucking sword from a satchel is funny though.

**Review by hyperioo — CHANGES_REQUESTED** [review]
☝️  You can change the `w_class = ITEM_SIZE_NORMAL` of the claymore.

**Pull request closed without merging**
