### PR TITLE
Stiffness and obscuration removal

### PR DESCRIPTION
**Pull request by Iglpigl**
## About The Pull Request

Removes(comments out) stiffness and obscuration.

## Why It's Good For The Game

Stiffness creator is fine with it's removal, there are better ways to balance armors.
Screenshot_1

## Testing

Everything works as it should on local(no runtimes, both are fully removed, nothing unrelated should be changed).

## Changelog
:cl:
del: Removed stiffness and obscuration
/:cl:

### CODE REVIEW

**Comment by Humonitarian** [comment]
My concern would be RIGs being too weak, but right now they are heavily overbuffed due to the issues we had with agony. So no need to worry about that one.

As for crusader, light slowdown gonna make them probably the best department armor, albeit pretty fair considering the buffs the Moebius voidsuit gets with this as well.

Eitherways if any armor becomes unbearably unbalanced after this, we can nerf it later.

**Review by Humonitarian — APPROVED** [review]

**Comment by Firefox13** [comment]
изображение
What do you mean by this? Are there any runtimes? Is the stiffness gone absolutely? This is not how you describe testing

**Comment by Firefox13** [comment]
Also why did you use /* and */ instead of // for single line commenting out.

**Comment by ValoTheValo** [comment]
Very based

**Comment by ValoTheValo** [comment]
Also if you want the system disabled you'd also need to comment out obscurity on helmets. It's essentially the same thing but for helmets

**Comment by SaltyOldBull** [comment]
holy mother of based

**Comment by Iglpigl** [comment]
> Also if you want the system disabled you'd also need to comment out obscurity on helmets. It's essentially the same thing but for helmets

Addressed.

**Comment by Iglpigl** [comment]
Also all of your concerns addressed too, Firefox.

**Review by hyperioo — COMMENTED** [review]
I see no real point in leaving that commented in the code. If the stiffness/obscuration game mechanics is scrapped and replaced by an adjustment of the slowdown, then we can just remove everything.

If someone ever wants to put it back, they will be able to retrieve everything just by reverting the PR.

**Comment by Iglpigl** [comment]
> I see no real point in leaving that commented in the code. If the stiffness/obscuration game mechanics is scrapped and replaced by an adjustment of the slowdown, then we can just remove everything.
> 
> If someone ever wants to put it back, they will be able to retrieve everything just by reverting the PR.

Taken care of.

**Pull request closed without merging**
