### PR TITLE
autoinjecor now bypass hardsuits

### PR DESCRIPTION
**Pull request by fernandos13**
## About The Pull Request
autoinjecor now bypass hardsuits

## Why It's Good For The Game
autoinjecor now bypass hardsuits
 to avoid docs loosing someone in a hardsuit to a 30sec cooldown in a AUTOinjector with 5u of inaprovaline. 

## Changelog
:cl:Fernandos33
tweak: autoinjecor now bypass hardsuits
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
This is a known downside of the hardsuit so, in my opinion, removing this downside is a step towards hugbox.

**Comment by GrayRachnid** [comment]
> 
> 
> This is a known downside of the hardsuit so, in my opinion, removing this downside is a step towards hugbox.

It's only meant for auto-injectors and that's limited only to inaprovaline. This is because we have no way of bringing people back to life and sometimes an injection of inaprovaline is the only thing that will keep them from dying. 

I understand your concern and where it is coming from though.

**Comment by genessee596** [comment]
I agree - since this does nothing to allow things like normal syringes or other chemical injectors besides the 5u inaprovaline, this just gives doctors a chance to save someone in a hardsuit if they're smart, while not making it as easy as dumping 30u tricord into them and having them limp off to medbay.

**Comment by Firefox13** [comment]
It is not 30 seconds, remembee that BYOND uses  deci-seconds, 1/10 seconds and 3 seconds isn't much of a delay.
Still, it is a good change(unless we get refillable autoinjectors with zombie powder)

**Comment by Pariah919** [comment]
We've already buffed voidsuits to be incredibly fast in the name of """qol""" so now literally everyone wears them.
Autoinjectors don't need to bypass hardsuits. That's just wacky.

**Comment by SpadesSlick** [comment]
Is it even possible to lost someone to 3 seconds cooldown?

**Comment by Hopekz** [comment]
In addition to the recent arguments, this PR introduces inconsistent behavior that looks unintentional.

We expect syringes to take the 3 seconds for hardsuits because of the mechanic we have in place of finding the injection port.
If we make it instant it strongly implies that the needle itself is going through the "hard" part of the hardsuit since there is now no check for a port.

**Comment by fernandos13** [comment]
i think this summed up the thing "Introducing inconsistency in needle behavior is not worth what this PR is trying to prevent."
so with this words. one that i do agree with. although ive seen many hardsuit wearers die with em. cause of it. it rings back the other point "IT should be one of the drawbacks of it"

so with this two... "points" hammered. i think its enough to close this PR

**Pull request closed without merging**
