### PR TITLE
Monkey resprite

### PR DESCRIPTION
**Pull request by Kurgis**
## About The Pull Request
Gives monkeys a new icon made by Près de l'oiseau.

Here's an idealized photo not representative of current implementation:
image

Known pre-existing issues:
~~1. Eye organs have their own update_icon system which bypasses the eyes var on species.~~
2. The monkey has no tail.

Regarding two, tail handling was stripped as bloat back in 2017, and it's not going to be addressed in this PR for right now.

## Why It's Good For The Game
They look pretty good.

## Changelog
:cl: Près de l'oiseau, Kurgis
imageadd: Monkeys have a new icon made by Près de l'oiseau.
/:cl:

### CODE REVIEW

**Comment by Humonitarian** [comment]
Can't you add the tail as part of the groin? Or would it be concealed under the other bodyparts?

**Comment by Firefox13** [comment]
Those side states look odd. Are you sure clothing fill fit?

**Comment by SirRichardFrancis** [comment]
It 100% would not fit, those monkeys need their own sprite of every clothing.
Guy who originally sprited this monkey made a couple, but that's it.

**Comment by Humonitarian** [comment]
> Those side states look odd. Are you sure clothing fill fit?

They have unique clothes that I do not believe are in this PR yet, but the sprites were alongside the monkey sprites so Kurgis should have them

> It 100% would not fit, those monkeys need their own sprite of every clothing.
Guy who originally sprited this monkey made a couple, but that's it.

Monkeys were already unable to wear any clothes other than a single jumpsuit that was sprited for them - Punpun's
This PR makes it possible to add 2 monkey clothes that have been sprited: a vagabond jacket, and a hawaiian T-shirt
As for sunglasses, hats and backpacks, not quite sure
Backpacks likely won't be an issue the way they are drawn by default, but hat offset will have to be tested, and I'M fairly sure sunglasses might be offset as well by a few pixels (should be fixable via code?)

**Comment by TheShown911** [comment]
Monkeys can wear all human clothing they have the slots for.

**Comment by Humonitarian** [comment]
> Monkeys can wear all human clothing they have the slots for.

Both correct and incorrect.
They have all slots, but cannot fill most slots.
They can spawn with those slots filled by default however, such as PunPun.

**Review by hyperioo — COMMENTED** [review]
I'll put it on test server on Monday so that all those potential sprites issues are checked

**Review by Pink-Chink — APPROVED** [review]
monke

**Pull request merged**
