### PR TITLE
Remove paint

### PR DESCRIPTION
**Pull request by Firefox13**
## About The Pull Request
Removes paint code completely

## Why It's Good For The Game
Mainly used by powergamers to color themselves black so they're harder to spot in low light condition. ~~Do we even need this mechanic? It looks like ass.~~ Removed

## Testing

Well, it's not really there now...

## Changelog
:cl:
del: Paint removed, reduced to ashes, no longer existing.
/:cl:

### CODE REVIEW

**Comment by Firefox13** [comment]
I suppose you're right.

**Comment by Holvr0** [comment]
RIP clown gameplay and painting people pink. It shall be missed.

**Comment by TheShown911** [comment]
Not uh, i like fun.

**Review by hyperioo — APPROVED** [review]
Project head clown

**Pull request merged**
