### PR TITLE
Obelisk

### PR DESCRIPTION
**Pull request by soslow4u**
Adds new machine for Neotheology: **Obelisk**

### CODE REVIEW

**Comment by soslow4u** [comment]
Sprites that needed:
yeh
Maybe some animated sign NT sign to place it over burrows or under strike

**Comment by zamolxius** [comment]
dead space reference? hehehe

**Comment by soslow4u** [comment]
Well, I just used image of first obelisk got in my mind, those sprites are _copyrighted_ placeholders and sure dont fit in lore and whole sprites style, so take it as no

**Comment by Kurgis** [comment]
Could you also remove the old NT marker sprites from the icon folder?

**Comment by soslow4u** [comment]
Updated

**Comment by ACCount12** [comment]
Is this PR ready?

**Comment by soslow4u** [comment]
I feel it like it lacks things like "NT smite" animation on mobs and such eye candies, maybe bit more functionality, but there was request only for machine that buffs neoteos a bit and hurts critters around.

**Pull request merged**
