### PR TITLE
[TESTED] [READY] Expedition and Deepmaint Touchup + Improved Corpse Spawner + Some Vagabond Flavor

### PR DESCRIPTION
**Pull request by ValoTheValo**
## About The Pull Request
this PR does a few things, touches up some old ruin with fixes and balance, gives Serbians a Bojevic crate (I couldn't atomize this change due to editing the serb base with other changes) adds an improved corpse spawner, and some more vagabond job titles 

## Why It's Good For The Game
Bojevic is a serb weapon already, now they dont have to spend TC on it. ruins are now slightly less buggy and with some better mapping

## Testing
tested on live, no issues seen with the skeletons and no additional lag was noticed. mapping seemed to be fine aswell

## Changelog
:cl:
add: new loot skeletons to deepmaint
tweak :more vagabond job titles
balance: onestar turret room now has onestar loot, serbian mercenaries get a bojevic crate
fix: scrap beanbags bad type, onestar window explosions
code: added more functionality to corpse spawner
/:cl:

### CODE REVIEW

**Comment by Pink-Chink** [comment]
GitHub suggestions aren't working. Try this:
```
	corpseuniform = islist(corpseuniform) ? safepick(corpseuniform) : corpseuniform
	corpsesuit = islist(corpsesuit) ? safepick(corpsesuit) : corpsesuit
	corpseshoes = islist(corpseshoes) ? safepick(corpseshoes) : corpseshoes
	corpsegloves = islist(corpsegloves) ? safepick(corpsegloves) : corpsegloves
	corpseradio = islist(corpseradio) ? safepick(corpseradio) : corpseradio
	corpseglasses = islist(corpseglasses) ? safepick(corpseglasses) : corpseglasses
	corpsemask = islist(corpsemask) ? safepick(corpsemask) : corpsemask
	corpsehelmet = islist(corpsehelmet) ? safepick(corpsehelmet) : corpsehelmet
	corpsebelt = islist(corpsebelt) ? safepick(corpsebelt) : corpsebelt
	corpsepocket1 = islist(corpsepocket1) ? safepick(corpsepocket1) : corpsepocket1
	corpsepocket2 = islist(corpsepocket2) ? safepick(corpsepocket2) : corpsepocket2
	corpseback = islist(corpseback) ? safepick(corpseback) : corpseback

	if(corpseuniform)
		M.equip_to_slot_or_del(new corpseuniform(M), slot_w_uniform)
	if(corpsesuit)
		M.equip_to_slot_or_del(new corpsesuit(M), slot_wear_suit)
	if(corpseshoes)
		M.equip_to_slot_or_del(new corpseshoes(M), slot_shoes)
	if(corpsegloves)
		M.equip_to_slot_or_del(new corpsegloves(M), slot_gloves)
	if(corpseradio)
		M.equip_to_slot_or_del(new corpseradio(M), slot_l_ear)
	if(corpseglasses)
		M.equip_to_slot_or_del(new corpseglasses(M), slot_glasses)
	if(corpsemask)
		M.equip_to_slot_or_del(new corpsemask(M), slot_wear_mask)
	if(corpsehelmet)
		M.equip_to_slot_or_del(new corpsehelmet(M), slot_head)
	if(corpsebelt)
		M.equip_to_slot_or_del(new corpsebelt(M), slot_belt)
	if(corpsepocket1)
		M.equip_to_slot_or_del(new corpsepocket1(M), slot_r_store)
	if(corpsepocket2)
		M.equip_to_slot_or_del(new corpsepocket2(M), slot_l_store)
	if(corpseback)
		M.equip_to_slot_or_del(new corpseback(M), slot_back)
```

**Comment by ValoTheValo** [comment]
>GitHub suggestions aren't working. Try replacing lines 79 through 162 with this:

does this allow for a chance to spawn nothing by putting null in the list?

**Comment by Pink-Chink** [comment]
I don't see why it wouldn't work. If null is picked, safepick() will return null. Better to test and see.

**Comment by ValoTheValo** [comment]
this should be ready to merge now

**Review by TheShown911 — APPROVED** [review]

**Pull request merged**
