### PR TITLE
Minor maint map changes

### PR DESCRIPTION
**Pull request by Iglpigl**
## About The Pull Request
2 rooms changed for hopefully makings bombings from those harder, and no more effortless jumping in MBO office.
Screenshot_3

## Why It's Good For The Game

Delegate approved.

## Changelog
:cl:
tweak: tweaked 2 rooms in maint, one has more catwalks while other is now floored.
/:cl:

### CODE REVIEW

**Comment by zombiemimic** [comment]
I think these rooms could use a little more inside of them. Otherwise, they feel empty and useless

**Comment by Kegdo** [comment]
too empty. add romch.

**Comment by Humonitarian** [comment]
Add a few tables, maybe some more junk

**Review by Firefox13 — COMMENTED** [review]
Rooms look *far* too empty

**Comment by Iglpigl** [comment]
> Rooms look _far_ too empty

Adressed.

**Comment by TheShown911** [comment]
Still doesn't look that great.

**Comment by Humonitarian** [comment]
> Still doesn't look that great.

Agreed, no junk piles?

**Comment by Iglpigl** [comment]
> Still doesn't look that great.

Adressed.

**Review by Firefox13 — APPROVED** [review]

**Pull request merged**
