### PR TITLE
Tweaks roach sizes

### PR DESCRIPTION
**Pull request by Humonitarian**
## About The Pull Request

Changes some roach sizes

## Why It's Good For The Game

Some roaches will be harder to hit, others easier

## Changelog
:cl:
tweak: roach sizes changed
/:cl:

### CODE REVIEW

**Comment by maikilangiolo** [comment]
Please fix Jaeger and some spiders teleporting by moving 10 tiles in a second.

**Comment by Humonitarian** [comment]
In another pr

**Comment by assortedbeads** [comment]
Any pictures to show the comparism?

**Comment by maikilangiolo** [comment]
> Any pictures to show the comparism?

In the code, silly man. Not sprite wise

**Comment by assortedbeads** [comment]
> > Any pictures to show the comparism?
> 
> In the code, silly man. Not sprite wise 

How would that make them harder to hit then? From like bullets or

**Comment by Humonitarian** [comment]
> > > Any pictures to show the comparism?
> > 
> > 
> > In the code, silly man. Not sprite wise
> 
> How would that make them harder to hit then? From like bullets or

Mob size influences stray bullet hit chance.

This is why mice are rarely hit, and kaisers eat bullet if you so much as point in their general direction

**Review by hyperioo — APPROVED** [review]
Reading the PR description, I was expecting some matrix magic to randomize the size of the roach sprites. 🧙

**Pull request merged**
