### PR TITLE
vagabond, guild tech and guild merchant resprite

### PR DESCRIPTION
**Pull request by CeUvi**
## About The Pull Request
you know what? fuck you
*resprites vagabond outfit*
bond, vagabond
also guild
technician, guild technician

## Why It's Good For The Game
less old sprets

## Changelog
:cl: CeUvi
imageadd: vagabonds got new outfits
imageadd: guilds got new outfits
/:cl:

### CODE REVIEW

**Comment by Alliostra** [comment]
Firstly there is absolutely no reason for this to be made, secondly it will screw up loot and make all these items more common, thirdly, one and possibly more items price changes are direct violation to contributing guidelines, you should try reading them.
https://wiki.cev-eris.com/Content_GuidelinesEn

**Comment by Wouju** [comment]
I'm fine with the guild but not with touching vagabond outfits

**Comment by Omni44** [comment]
Can we see  how they look in game?

**Comment by Sparrowbird611** [comment]
I'm not gonna lie, I think the new guild coats look uglier than the previous ones. The main issue is that overhanging area, which just looks really ugly IMO. If you removed that, it'd be a lot better.

Vagabonds are already ugly to me so I can't comment on whether the above is an improvement or not.

**Comment by granodd** [comment]
The new orange palette feels more flat and less vibrant than the previous orange on the guild tech and vagabond outfits. Not at all a fan of the new merchant coat, as the previous one is already pretty iconic. Overall I think that the vagabond and guild sprites are fine as they are now, and the only thing I would suggest is perhaps sticking to the previous orange palette and respriting the guild tech coat with it.

**Comment by GrayRachnid** [comment]
> 
> 
> The new orange palette feels more flat and less vibrant than the previous orange on the guild tech and vagabond outfits. Not at all a fan of the new merchant coat, as the previous one is already pretty iconic. Overall I think that the vagabond and guild sprites are fine as they are now, and the only thing I would suggest is perhaps sticking to the previous orange palette and respriting the guild tech coat with it.

Was coming here just to say this, The new orange palette doesn't look as good as the previous one. Also, some ingame screenshots of the outfits next to the environment would be nice.

**Comment by CeUvi** [comment]
image
image

**Comment by zombiemimic** [comment]
Still not a fan of the guild clothes

**Comment by MemedHams** [comment]
vagabond resprite is fine but the guild merchant and techie jackets are a little flushed out. It almost seems like a cell-shaded aesthetic

**Comment by maikilangiolo** [comment]
I like them both. Merchant maybe should have a shorter coat? But otherwise, both are good for me.

**Comment by Rumplenutskin** [comment]
I like where you are going with the tech coat, but the merchant coat we have now is one of the best looking jackets we have on the server. This one is uhh, looks like a life vest.

**Comment by CeUvi** [comment]
g*ild suits updated

**Comment by GrayRachnid** [comment]
Still not a fan of the vagabond palette change, the new colors are way too flat.

firefox_2021-05-18_11-38-56
firefox_2021-05-18_11-39-01

**Comment by CeUvi** [comment]
> Still not a fan of the vagabond palette change, the new colors are way too flat.
> 
> firefox_2021-05-18_11-38-56
> firefox_2021-05-18_11-39-01

nah its fine

**Comment by GrayRachnid** [comment]
Yes, I know it's fine. I'm saying I don't like it.

**Comment by TheShown911** [comment]
Vagabond looks too washed out for me, no opinion on the guild suits.

**Pull request closed without merging**
