### PR TITLE
Adds two new jumpsuit sprites

### PR DESCRIPTION
**Pull request by Alliostra**
## About The Pull Request

Adds two new jumpsuits to the loadout, sprites by Jeff. One **very cyberpunk** jumpsuit, and one bare-chested suit for showing off your cruciform, fancy augments or masculine hair.

## Why It's Good For The Game
Adss more cyberpunk aesthetics

## Changelog
:cl:
add: Added two new uniforms, obtainable through the loadout
/:cl:

### CODE REVIEW

**Comment by Kurgis** [comment]
To resolve conflicts, merge and replace with master, and then re-add your new icons back to the dmi.

**Comment by jaffjafferson** [comment]
very based and redpilled, speedmerge now

**Comment by SpadesSlick** [comment]
It would also be better if you handle those old commits as well.

**Comment by Alliostra** [comment]
how do I remove commits?

**Comment by SpadesSlick** [comment]
You shouldn't, just mind it in further PRs. Also, will you fix the conflicts?

**Comment by Alliostra** [comment]
Won't be available for the next week so im closing this for Now.

**Pull request closed without merging**
