### PR TITLE
FS Guns moved from Billomat to FS Vendor

### PR DESCRIPTION
**Pull request by ValoTheValo**
## About The Pull Request
this pull request returns the Gladstone to the FS vendor and moves the other FS guns from billomat to the FS Vendor. it always annoyed me the Gladstone got a 200$ price hike and that FS Guns weren't sold in the FS vendor. some guns will likely drop in price by roughly 100 or 200 dollars due to how the FS vendor works. will change price back if nessicary

## Why It's Good For The Game
Gladstone now back to its original price and it makes sense to find FS guns in the FS vendor

## Changelog
:cl:
tweak: Frozen Star Guns are now in the Frozen Star Vendor instead of billomat
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
before someone else leaves this comment i guess i will
Firstly there is absolutely no reason for this to be made, secondly it will screw up loot and make all these items more common, thirdly, one and possibly more items price changes are direct violation to contributing guidelines, you should try reading them.
https://wiki.cev-eris.com/Content_GuidelinesEn

**Review by SirRichardFrancis — APPROVED** [review]

**Comment by TheShown911** [comment]
Cringe! At least make things cost the same as before.

**Comment by hyperioo** [comment]
32 commits 
image
Moving some guns to FS vendor, I get it, but try to make it so it does not change the price of everything

**Comment by ValoTheValo** [comment]
> 32 commits image Moving some guns to FS vendor, I get it, but try to make it so it does not change the price of everything

Its only about 100-200 last i checked on how the vendor works. But ill change it back. Also i dont know how to get rid of the commits

**Comment by hyperioo** [comment]
Commits are not a problem, it's just cleaner to not have them. For next PRs you have to reset the state of your master to match eris' master before creating your new branch.

**Comment by Firefox13** [comment]
Billomat is ~~a fucking joke~~ a premium vendor with intentionally overpriced weapons when you don't want to source them like a true vagabond does
if you want some lore explanation on why FS vendor doesn't sell FS guns - it's a self-defense vendor. It even says that in the desc

**Comment by ValoTheValo** [comment]
> Billomat is ~a fucking joke~ a premium vendor with intentionally overpriced weapons when you don't want to source them like a true vagabond does if you want some lore explanation on why FS vendor doesn't sell FS guns - it's a self-defense vendor. It even says that in the desc

The molly and gladstone were moved out of the FS vendor into the billomat despite the molly being a very bad gun and not worth the price point and the gladstone being at a perfectly fine price. Everything else is ridiculously overpriced for its power level and usefullness and the ones that arent only lost like 200$ of price due to not having markup

**Pull request closed without merging**
