### PR TITLE
Nerfs hornet and mandella

### PR DESCRIPTION
**Pull request by Humonitarian**
## About The Pull Request

Hornet is reworked after testing with new walls to be capable of penetrating reinforced walls, allowing it to be used in a similar fashion to the sky diver against AMR users. Its damage is significantly worse, making it not superior to the deckard in every aspect.

Mandella received smaller nerfs to its stats. If more is needed, it will be done at a later date.

## Why It's Good For The Game

Balance good.

## Testing

Tested, guns fired as intended and dealt damage as intended.

## Changelog
:cl:
balance: Hornet can pierce reinforced walls, but deals much less damage than other revolvers
balance: Mandella received minor decrease to damage, and moderate decrease to penetration
/:cl:

### CODE REVIEW

**Comment by Humonitarian** [comment]
With these changes I'd roughly equate the hornet to a deckard in firepower. What it lacks in style damage and stopping power, makes up for in extreme effectiveness against armored targets, and the ability to penetrate walls and shields.

Mandella is... still probably the best .35 handgun you can get, save for the sky diver.

**Comment by thevandie** [comment]
Mandella is a .25 handgun, not a .35
although it probably still is the best low-caliber handgun (as in the handguns that aren't .40)

**Comment by ValoTheValo** [comment]
> Mandella is a .25 handgun, not a .35 although it probably still is the best low-caliber handgun (as in the handguns that aren't .40)

dude .25 is a rifle cartridge

**Comment by DiaFRAME444** [comment]
Correction, Hornet is a .20 handgun. .25 is CLRifle, .20 is SRifle, check https://github.com/discordia-space/CEV-Eris/blob/master/code/modules/projectiles/projectile/bullettypes.dm

**Comment by thevandie** [comment]
Ok maybe it SHOULD be compared with the .40 handguns, idfk man it's 1AM

**Review by Pink-Chink — APPROVED** [review]

**Comment by Humonitarian** [comment]
> Mandella is a .25 handgun, not a .35 although it probably still is the best low-caliber handgun (as in the handguns that aren't .40)

Right, that's what I meant. Handgun category in general.

**Pull request merged**
