### PR TITLE
Adds a cosmetic augment to start menu and mobius research tree

### PR DESCRIPTION
**Pull request by Jackofashepard**
Adds a fine cosmetic item well saught after by FS customers.

### CODE REVIEW

**Comment by jaffjafferson** [comment]
youre a degenerate and youve got to wait for erismed :^))))

**Comment by Nozarati** [comment]
Unneccessary and doesnt fit at all with any of the eris aesthetic. Dunno why you even spent time on this.

**Comment by Pariah919** [comment]
the madlad he actually did it

**Comment by SpadesSlick** [comment]
Hiding the actual content of the PR from name and description, especially such controversial one - is incredibly unprofessional and bad contributing practice in general.

This change (cat ears) should be properly discussed in the community, and even voted by maintainers or general public, because it can potentially impact game in cancerous way.

Because this is a meme PR without proper documentation to it, I'm closing it, and any future attempts to add cat ears AT LEAST must be discussed by maintainers until consensus is met.

**Pull request closed without merging**
