### PR TITLE
Resprites girders, SMES coils (stock parts), RPED and lattices by Infrared_Baron

### PR DESCRIPTION
**Pull request by githubuser4141**
## About The Pull Request

New sprites for the items/objects: RPED, SMES coils (high-cap, high-discharge, basic), girders (reinf girder, mobile girder, basic) and lattices

## Why It's Good For The Game

It just is.

## Testing

image
image
image

## Changelog
:cl: INFRARED_BARON
imageadd: New girder, RPED, lattice and coil sprites
imagedel: Old girder, RPED, lattice and coil sprites
/:cl:

### CODE REVIEW

**Comment by thevandie** [comment]
Is there a unique sprite for halfwall girders yet?

**Comment by githubuser4141** [comment]
> Is there a unique sprite for halfwall girders yet?

Sadly not, if Baron is open for commissions next week I'll ask for one

**Comment by githubuser4141** [comment]
> изображение These don't seem right...

It should be fixed now

**Review by Firefox13 — APPROVED** [review]
RPED should logicaly stick out from the other side on left/right states, but this is just me nitpicking. Good stuff from Baron as usual.

**Pull request merged**
