### PR TITLE
DESTROY THE CHILD

### PR DESCRIPTION
**Pull request by TheShown911**
## About The Pull Request

Removes the "toddler" sprite from the game.
## Why It's Good For The Game

Who the fu- who did th- wha- i should kick your fuckin' ass who did this?

## Changelog
:cl:
imagedel: "toddler" sprite
/:cl:

### CODE REVIEW

**Comment by Medcar** [comment]
image
WHAT HAVE I FOUND

**Comment by Wouju** [comment]
0/10

we should be able to throw a child into the SM pit

**Comment by Honestly101** [comment]
dear god what is that

**Review by mattroks101 — APPROVED** [review]

**Comment by Medcar** [comment]
github abortion

**Comment by drexample** [comment]
DESTROY THE CHILD

**Pull request merged**
