### PR TITLE
Adds Bill Trustworthy's Discount Guns and Enterprising Detritus, AKA …

### PR DESCRIPTION
**Pull request by zombiemimic**
…the trash vendor

## About The Pull Request
This is an addition of the trash vendor. It spawns in the bar, along the railing.

## Why It's Good For The Game
Adds an expensive way to reliably get otherwise unavailable firearms without becoming another maint diver.

## Changelog
:cl:
add: Added Bill Trustworthy's Discount Guns and Enterprising Detritus, a gun and parts vendor.
map: Added the Trash Vendor to the Club
/:cl:

### CODE REVIEW

**Comment by Jackofashepard** [comment]
I can only give to suggestions to this as its otherwise good.

- I would suggest keeping the guns cheaper - barely more expensive than the gladstone as any higher than that reaches the "its honestly better just to trash hunt this"

- List the magazines first so people dont hack this to launch armor and gun parts

**Comment by zombiemimic** [comment]
Alright, down to 1.25 shuttle value

**Comment by Firefox13** [comment]
Aren't some guns are rare for a reason? We have a trade beacon ~~that is never fucking used~~ if you want a wider stock, surplus crates and a junk beacon if you're willing to invest your time. And, where the vendor is placed?

**Comment by zombiemimic** [comment]
> Aren't some guns are rare for a reason? We have a trade beacon ~that is never fucking used~ if you want a wider stock, surplus crates and a junk beacon if you're willing to invest your time. And, where the vendor is placed?

I was just asked by Jack Frost, and since disks were removed, a lot of these guns aren't really able to get in circulation

**Comment by zombiemimic** [comment]
Closing to update the fork

**Pull request closed without merging**
