### PR TITLE
Vintorez to Charon

### PR DESCRIPTION
**Pull request by Humonitarian**
## About The Pull Request

Renames Vintorez to Charon, a Stalker reference.

## Why It's Good For The Game

 Felt oddly fitting considering Charon used a Vintorez, and well, he's Charon.

## Testing

Compiled, worked fine.

## Changelog
:cl:
tweak: Vintorez renamed into a reference
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
Y tho

**Comment by zombiemimic** [comment]
Change for the sake of change, and breaking away from the real-name theme of the other excel weapons.

**Comment by Humonitarian** [comment]
> Change for the sake of change, and breaking away from the real-name theme of the other excel weapons.

Ok

**Comment by Firefox13** [comment]
Scar (CS hero) would be a better choice as he is more knowledgable than Charon (named Monolith NPC (probably leader) in SoC).
That aside, most (if not all) Excelsior weapons are real-life names so I cannot approve this PR in good faith.
Gun in question is very much VSS "Vintorez"
изображение

**Pull request closed without merging**
