### PR TITLE
Adds more upgraded organ designs to the back alley organs disk.

### PR DESCRIPTION
**Pull request by MLGTASTICa**
## About The Pull Request
Adds more organs with buffed stats to it 
Super muscle (muscle 1.5x eff , 0.6 size)
Sensitive nerves (nerve 1.5x eff , 0.6 size)
Extensive blood vessesl (blood 1.5x eff , 0.6 size)
Huge heart (heart 1.5x eff , 2,3 size)
Big liver (liver eff 1.5 , size 1.2)

New sprites for them for the sake of spriter review
image

## Why It's Good For The Game
Not enough upgraded organs to mess around with

## Changelog
:cl:
add: Added upgraded versions of Muscles , nerves , blood vessesl , heart and liver in the back alley organs disk
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
Feel like theese should be more under the territory of cybernetic organs rather than the long lungs disk and shit but good idea anyway

**Comment by Kegdo** [comment]
__C H O N K Y__

**Comment by MLGTASTICa** [comment]
> Feel like theese should be more under the territory of cybernetic organs rather than the long lungs disk and shit but good idea anyway

imagine thinking cybernetics are the future , smh smh smh.

**Comment by SaltyOldBull** [comment]
the naming conventions used could be better

**Comment by drexample** [comment]
Names are rather lackluster

**Comment by hex37** [comment]
I can't wait to put a baboon heart into someone

**Comment by TheShown911** [comment]
I am not sure these should go on a random meme disk, there is more potential for gameplay in them.

**Comment by MLGTASTICa** [comment]
> I am not sure these should go on a random meme disk, there is more potential for gameplay in them.

its preety rare , you'd rather have players be able to always buy them and find them?

**Review by Firefox13 — CHANGES_REQUESTED** [review]
This doesn't actually adds the organs to back alley disk because you didn't made any changes to `autolathe_disks.dm`.
Also organs could use a fancy description too, really.

**Pull request closed without merging**
