### PR TITLE
Allows some organs to be printed in the organ grower and fixes litany typoes.

### PR DESCRIPTION
**Pull request by Vincent983**
Tweaks extensive blood vessels and hypersensitive nerves so they can be printed in organ growers. Also fixes multiple typos and makes the descriptions of several litanies and NT machinery descriptions more clear.

## About The Pull Request

Removes the gold and plastic costs for hypersensitive nerves and extensive blood vessels so they may be printed in an organ grower. Fixes several litany typos, adds multiple "a"'s and "the"'s to the descriptions of some litanies, and updates the cruciform sense litany to match with it's effects.

## Why It's Good For The Game

It allows them to be printed by the faction that actually uses these instead of only being printable by NT, who hates that. It's also nice to have some litanies be made more readable.

## Changelog
:cl:
tweak: Removed the gold and plastic costs from extensive blood vessels and hypersensitive nerves so they may be printed in an organ grower.
spellcheck: Fixes litany typos and updates description of the cruciform sense litany to be in line with it's actual effects.
:cl:/

### CODE REVIEW

**Comment by ValoTheValo** [comment]
very vased

**Comment by Vincent983** [comment]
wait fuck, I meant that for a different PR

**Comment by Vincent983** [comment]
im just going to make a different one

**Comment by Vincent983** [comment]
well, I can't figure out how to PR only a SINGLE commit so I am just going to have both in this single one then.

**Comment by Pink-Chink** [comment]
Next time, create new branches from your master and make the PRs from there.

**Pull request merged**
