### PR TITLE
[TGUI] Asset Cache Update

### PR DESCRIPTION
**Pull request by LetterN**
## About The Pull Request
- newscaster update
- browser.dm update
- made asset cache better
- bump deps

## Changelog
:cl:
code: Updated newscaster a bit
code: Browser.dm updated
code: Asset cache updated; reconnecting shouldnt redownload stuff you already have
code: update dependency versions
code: add rust_g (required for rustg_dmi_strip_metadata)
/:cl:

### CODE REVIEW

**Comment by hex37** [comment]
Aw shit, here we go again

**Comment by Autisem** [comment]
instead of extools maby try auxtools? from what I heard its overall more stable and better

**Comment by LetterN** [comment]
> instead of extools maby try auxtools? from what I heard its overall more stable and better 

didnt mean extools, i meant rust_g

**Comment by LetterN** [comment]
fail is a mapper issue, apc missing

**Pull request merged**
