### PR TITLE
This will be good for the stock market: sawn off rebalance

### PR DESCRIPTION
**Pull request by maikilangiolo**
## About The Pull Request
Keeping in line with what I did in #7550 and sawn off bolt guns, I tried my best to rebalance sawn off shotguns. The comparison was made with the two baseline .35 pistols: paco/mk58, which have the same damage. These pistols can do so and so damage, with more ammo, easier reload and less recoil. By that logic, the "pistol" variants of large guns need some well deserved changes.
core principles:
1. Sawn offs have the same damagge
2. sawn offs have less AP
3. sawn offs have significantly more recoil (though lowered as it was too crazy)
4. sawn offs have slower bullets like the obrezes
What this does, is that the can still be usable vs people with low or no armor, but as armor increases, they lose effectiveness without being better than said Paco/mk58. You wont get a wet paper gun, but neither will you get a new pistol to defeat bulletproof. The slower bullets hinder use as range, as well. This all creates guns that are good hand cannons in cqc, but are hard to aim and use with the recoil and bullet speed.

Included some minors fixes, like the lever guns sawn off having the sawn off var (you could theoretically sawn them off infinitely), and a rework of the flare shotgun. Funnily enough, the AP was not changed so it had 2 AP (4 times higher!). The current stats make it slightly worse than a DB sawn off in damage, though margially better used with one hand, as well as being one size smaller. *may* be tweaked again, but considering how easy it is to make, should be fine.

Like vent pointed out, I forgot to say I lowered buckshot pellet count 8->6, and recoil 8 -> 5. The pellet count is a fix. It wasn't supposed to have 8 pellets. Humon forgot to change it during the first merge of the rework. The recoil is good because buckshot doesn't recoil as hard as slugs.

## Why It's Good For The Game
Well deserved improvements that dont make a giskard do more damage than large caliber sawn offs, while still giving them meaningfull downsides that wont create a better pistol.
Ghetto guns should be fun to use, terrible downgrades arent.

## Changelog
:cl:
balance: rebalanced sawn off shotguns. they trade AP, recoil and bullet speed for being hand cannons
/:cl:

### CODE REVIEW

**Comment by SirRichardFrancis** [comment]
>Well deserved improvements that dont make a giskard do more damage than large caliber sawn offs, while still giving them meaningfull downsides that wont create a better pistol.

   guskard   obrez
image

**Review by TheShown911 — COMMENTED** [review]
I still have no clue what any of these numbers mean

**Comment by maikilangiolo** [comment]
> I still have no clue what any of these numbers mean

It does the same of what the obrez PR does, which you approved (or so the email that I got told me)

**Comment by TheShown911** [comment]
I have no clue what that one does either, but if the armor rework stays in the state it is currently in the whole server will explode from hate and that one seams to have the most major changes as it changes base stats of bullet types.

**Comment by maikilangiolo** [comment]
> if the armor rework stays in the state it is currently in the whole server will explode from hate 
Shown, I've did nothing but take my time and address every issue with the rework when I got pinged or spotted messages in the discord. As you can see from these PRs currently up, we are fixing the issues with it. Truth to be told I didn't think the rework was ready to be merged in live, and it's why you're seeing many patchwork PRs (atomized) to address that. 

I can fix the armor rework, i cannot fix player impressions of the rework that are just that, impression, as I cannot prove them as true. Roma said that the mercenary vest was worthless compared to before, but I checked, and it actually protects from 1-2 more damage than before. Or he said the AMR taking 5 shots to kill is the fault of the rework, when the AMR with the rework did 3 less damage vs medium armor and 3 more vs BP (an difference so small it's irrelevant). Spcr reported decaps with the molly, but the molly was nerfed hard when he reported it (a recent tweak PR buffed it, and no one else reported Molly decaps). Keep in mind, kedgo made a PR that makes decals and head gibs harder than before.

I've local tested the guns, they do the damage they are supposed to do, and I cannot explain how a 2 damage molly decapped a guy in BP. And even more, the only person who defends the armor rework is Budgetcommander (on discord), a player who, in his own time, made a spreadsheet of all guns and posted it publicly so that other players could see the gun damage. Nothing was hidden from the players, and when I ask players to tell me what guns are wrong and what is, if I find that the gun is fine, they ignore me. There are still bugs and kinks in the rework, but they aren't what people claim they are. 

And the biggest reason players despise is that's it's confusing, the UI showed "wrong" numbers. And I've fixed it with a new PR

**Comment by TheShown911** [comment]
I understand you and hope you succeed, that's why I'm approving what to me look like meaningless balance changes.

**Comment by hyperioo** [comment]
I hope you have a spreadsheet on your side to keep track of all of that because I sure as hell can't.

**Pull request merged**
