### PR TITLE
Further augments QoL changes

### PR DESCRIPTION
**Pull request by FrownTown**
## About The Pull Request
<details>
<summary>
Further augments QoL changes
</summary>
<hr>
	By popular demand, removed the scanners from the engineering and surgical augments and got rid of the popup menu. They now deploy instantly when activating the verb, and can be macroed. Additionally, moved the activation of prosthetics from the "Organs" tab to the "Cybernetics" tab, so that excelsior players don't end up with two separate verb tabs for what is basically the same thing.

EDIT: Fixed the surgical omnitool requiring platinum to print from the mechfab. Oops.
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by LethalGhost** [comment]
May be updated tools should be moved out of `multitool` foldier

**Comment by FrownTown** [comment]
> May be updated tools should be moved out of `multitool` folder

This is a good point. I moved them in the data structure but not file structure. Fixed now.

**Comment by SpadesSlick** [comment]
Will it be fixed?

**Comment by FrownTown** [comment]
> Will it be fixed?

Eeyep, fixed now. Made a stupid mistake right before bed.

**Pull request merged**
