### PR TITLE
Disposal mail delivery

### PR DESCRIPTION
**Pull request by TheLeopold**
## About The Pull Request
_(I hope github works as I expect it to work)_
Cleaned and fixed disposal mail delivery. Did slight repiping in the church and engineering. Added Club, Tool storage and Dormitories as mail destination. Each department has 2 destinations: Head office and general area. Exception is medbay - they have third one, Chemistry. And IH, they have only one mailbox which is security lobby, since almost whole 1st section is separated from the rest of the disposal system.

Keeping it as a draft until other map PRs done.
tagger
guild
chapel
preacher
church
lower
atmos1
atmos2

## Why It's Good For The Game
Fix

## Testing
Disposaled myself to every possible destination as a droid.

## Changelog
:cl:
add: Added Club, Tool storage and Dormitories to the list of possible mail recipients. Added trash bin to the Preacher Office.
fix: fixed disposal mail delivery
/:cl:

### CODE REVIEW

**Comment by Mycah142** [comment]
You beat me to it.

**Comment by TheLeopold** [comment]
Updated to not conflict with https://github.com/discordia-space/CEV-Eris/pull/8283 (I hope so)

**Comment by hyperioo** [comment]
> Updated to not conflict with #8283 (I hope so)

Sadly it conflicts :(

**Comment by TheLeopold** [comment]
Did it help?
Damn github

**Comment by TheLeopold** [comment]
Okay lesson learned, gotta re-open it

**Comment by TheLeopold** [comment]
#8321

**Pull request closed without merging**
