### PR TITLE
Materials resprite

### PR DESCRIPTION
**Pull request by Kegdo**
## About The Pull Request

image

## Why It's Good For The Game

bay leftovers bad

## Changelog
:cl:
add: new(good) material sprites(drawn by CeUvi)
del: old(bad) material sprites
/:cl:

### CODE REVIEW

**Review by SirRichardFrancis — COMMENTED** [review]
Consider using materials drawn by INFRARED_BARON, those are of higher quality imo.

**Comment by Kegdo** [comment]
there is no .dmi file with his sprites even, bruh!

**Comment by SirRichardFrancis** [comment]
> his sprites aren't in asset_storage.
> there is no .dmi file with his sprites even, bruh!

Worrying levels of skill issue.

**Comment by CeUvi** [comment]
> Consider instead taking materials drawn by INFRARED_BARON, those are of higher quality imo.

ok, show them
also there are diamonds and uranium made by him, so cope and seethe

**Review by TheShown911 — APPROVED** [review]
Am not too fond off plasma and uranium sprites, but overall good change.

**Comment by drexample** [comment]
THE CUUUUBE

**Pull request merged**
