### PR TITLE
Alternative shotgun change: damage up

### PR DESCRIPTION
**Pull request by maikilangiolo**
## About The Pull Request

- Shotgun ammo got a 20% damage increase
- slug 25 -> 30 damage, buck 21 -> 25 damage
- Slug recoil 8 -> 10
- buckshot recoil 5 -> 7
- .60 ammo got a tweak in accordance with the improved shotgun ammo. this didnt change .60 balance: base ammo is still a weaker slug in damage but has 0.8 step delay vs 1.1 and pierces walls easily. recoil adjusted to reflect the change
- AMR damage 2 -> 1.8. this makes it literally identical to before, no balance changes. it gets no extra recoil penalty with the .60 recoil buff because its single shot anyway. PLEASE NOTE: it could keep the 2x damage mult, it would do....not much more damage: 8 more damage compared what it does now (80 raw vs 72 raw, and 70 @15 armor vs 62 @15 armor)
- all shotguns can take .60 barrels. as stated above, .60 ammo is weaker damage wise but has better AP and bullet speed. this lets you tweak shotguns according to play style: close range, high damage, OR longer range, mediocre damage and wall piercing. Swapping barrels on the go is very slow, so you need to decide beforehand if cqc or long range. NOTE: makeshift shotgun already can take a .60 barrel. This was the intention behind the .60 change in #7547 
- ~~AMR can now take shotgun barrel.~~ in hindsight, no. would mean 105 damage hitscan slugs

alternative to #8194 

## Why It's Good For The Game

The issue: shotguns are CQC weapons but have no advantage in actual CQC due to automatic rifles, revolvers and bolt actions (with bayonets) being a thing.
The solution #8194 offers: remove the step delay malus from shotgun ammo = shotguns are no longer gimped to cqc, no other lethality change. still limited by ammo capacity and recoil
The solution this PR offers: improve the damage = shotguns are excellent damage sticks in cqc. still limited by slow bullets, ammo capacity, as well as slightly higher recoil than what they have now. .60 barrel swap for versatility 

DO NOTE: #8194 is a simpler change with fewer balance implications. it is smaller, but at the same time reduces the shotgun identity. It just makes them a normal gun. This PR is much more extensive in scope, and has to tweak more values as a consequence. I advise test merging because one thing is shooting at dummies in local host, another live playing.

## Testing

done. everything works, barrel swap works, no bugs

Putting some stats here to be more transparent

- .60 stats: 20 damage, 3 AP, 2x wound (40), 10 recoil
- .50 slug: 30 damage, 1 AP, 2x wound (60), 10 recoil
- .50 buck: 25 damage, 1 AP, 0.5 wound (12.5), 6 pellets, 7 recoil
- Double barrel with slug: 60 max damage, 30 damage @15 armor
- double barrel with buckshot: 75 max damage (if all pellets hit), 30 damage @15 armor (if all pellets hit)
- double barrel with .60: 40 max damage, 30 damage @15 armor

## Changelog
:cl:
balance: rebalanced shotgun ammo. more damage, more recoil
balance: .60 changed to keep up with shotgun ammo change
tweak: amr damage bonus changed in line with the .60 damage improvement. no actual balance change as a consequence
balance: shotguns can take .60 barrels
fix: fixed incendiary slugs having bugged damage. they do slightly less damage than normal slugs
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
Why are you rebalancing .60 Ammo? Its in a good spot as it is right now.

**Comment by maikilangiolo** [comment]
> Why are you rebalancing .60 Ammo? Its in a good spot as it is right now.

First of all, AMR is literally unchanged. 18 damage and 2x mult, or 20 damage and 1.8x mult is the same thing.
Second, the slug and buckshot damage upgrades involve .60 getting a minor buff. It is only +2 damage (18 to 20), but really helps it catch up and be a side grade.

**Comment by MLGTASTICa** [comment]
> > Why are you rebalancing .60 Ammo? Its in a good spot as it is right now.
> 
> First of all, AMR is literally unchanged. 18 damage and 2x mult, or 20 damage and 1.8x mult is the same thing. Second, the slug and buckshot damage upgrades involve .60 getting a minor buff. It is only +2 damage (18 to 20), but really helps it catch up and be a side grade.

Fair , the damage is indeed equal .

**Review by TheShown911 — APPROVED** [review]
Code is fine

**Comment by maikilangiolo** [comment]
> Code is fine

Now it's fine

**Comment by Firefox13** [comment]
Closing in favour of merging #8194

**Pull request closed without merging**
