### PR TITLE
Roach tweaks

### PR DESCRIPTION
**Pull request by Humonitarian**
## About The Pull Request

Superior Animals get wounding multipliers, attacktexts are now lists allowing alternate messages.

Most roaches have 1.5 wound mod, but reduced damage Jager roaches possess higher wound mods, panzers possess much lower (with higher base damage) Naniteswarms buffed, now penetrate armor much more effectively

## Why It's Good For The Game

More things to help customize superior animals, indirect reduction to RIG damage from roaches.
Also, more attack text good.

## Changelog
:cl:
balance: roaches now have wounding multipliers
tweak: roaches have multiple attack messages
/:cl:

### CODE REVIEW

**Comment by DiaFRAME444** [comment]
Giving roaches more wounding and less damage?
This a change that hurts Vagabonds (who are supposed to be going through maintenance) and aids people that have amazing armor (Making Acolyte even more of a Vagabond+).

**Comment by assortedbeads** [comment]
> Giving roaches more wounding and less damage?
> This a change that hurts Vagabonds (who are supposed to be going through maintenance) and aids people that have amazing armor (Making Acolyte even more of a Vagabond+).

Maints are supposed to be dangerous without armor, and vagabonds can craft about 3 different kinds of armor with barely any investment on their part.

**Comment by assortedbeads** [comment]
Now make roaches respect shields when they attack

**Comment by ErisMeleeEnjoyer** [comment]
Now make roaches respect

**Review by Pink-Chink — APPROVED** [review]

**Pull request merged**
