### PR TITLE
Wield Delay Removal on non heavy weapons 2, No Merge Conflicts Edition

### PR DESCRIPTION
**Pull request by ValoTheValo**
## About The Pull Request
its the exact same pr as #6742 but without merge conflicts
## Why It's Good For The Game
see PR #6742 TLDR is Most people don't like delay on everything and it makes combat less fun

## Changelog
:cl:
balance: increased VIG requirement and decreased delay on RPG and LMGs
del: removed delay on every weapon that isn't a LMG, GL or RPG
/:cl:

### CODE REVIEW

**Comment by ValoTheValo** [comment]
please tell me if i fucked any of the code up

**Review by Firefox13 — COMMENTED** [review]
Wasn't the zero wield_delay_factor runtime fixed?

**Comment by maikilangiolo** [comment]
I actually like the delay. Git gud and increase your vig

**Comment by MLGTASTICa** [comment]
top kringe PR

**Comment by Humonitarian** [comment]
Imo battlerifles, especially FA ones should have delay to further nerf them, we're in a very FA-meta state at the moment, so this much disadvantage is good.

SMGs (such as the C20-m) and pistols should have none, of course, as they don't have much penetration either.

**Comment by ValoTheValo** [comment]
> Imo battlerifles, especially FA ones should have delay to further nerf them, we're in a very FA-meta state at the moment, so this much disadvantage is good.
> 
> SMGs (such as the C20-m) and pistols should have none, of course, as they don't have much penetration either.

So Kovacs and Vintorez need it?

**Comment by Humonitarian** [comment]
> > Imo battlerifles, especially FA ones should have delay to further nerf them, we're in a very FA-meta state at the moment, so this much disadvantage is good.
> > SMGs (such as the C20-m) and pistols should have none, of course, as they don't have much penetration either.
> 
> So Kovacs and Vintorez need it?

Do they have FA? If no, then probably not, or at least not a lot

**Comment by Humonitarian** [comment]
> > > > Imo battlerifles, especially FA ones should have delay to further nerf them, we're in a very FA-meta state at the moment, so this much disadvantage is good.
> > > > SMGs (such as the C20-m) and pistols should have none, of course, as they don't have much penetration either.
> > > 
> > > 
> > > So Kovacs and Vintorez need it?
> > 
> > 
> > Do they have FA? If no, then probably not, or at least not a lot
> 
> Kovacs doesnt and is the only gun labelled "battle rifle" iirc and vintorez really shouldnt have full auto but it does

Correction then, assault rifles.
I specifically meant things like the AK and the STS

**Comment by tristain01** [comment]
Maybe if you plan to give AKs weild delay, give those with folding stocks less or no delay when folded in exchange for accuracy.

**Review by Firefox13 — APPROVED** [review]
изображение

**Pull request merged**
