### PR TITLE
Removes Monksim Syndrome from virus effects

### PR DESCRIPTION
**Pull request by Anonmare**
## About The Pull Request
Removes Monksim Syndrome from the list of possible symptoms

## Why It's Good For The Game
Considering we made it impossible for one to turn a monkey into a human - this is an irreversible effect for all intents and purposes, that, and it's frankly far too wacky in tone for a grounded codebase. I'd love to go over the whole effects list one by one but that'll need some honest to God discussion.

## Changelog
:cl:
del: It is no logner possible for a virus to turn humans into monkeys
/:cl:

### CODE REVIEW

**Review by Iglpigl — CHANGES_REQUESTED** [review]
Doesn't pass Travis.

**Comment by Anonmare** [comment]
I have no idea why, it shouldn't be failing

**Comment by Iglpigl** [comment]
> I have no idea why, it shouldn't be failing

Well does it compile if it does it should be passing Travis.

**Comment by Alliostra** [comment]
Try making a new commit with some insubstantial changes to make travis rerun it

**Comment by Friendly-South-African-Man** [comment]
Bad PR. The game needs more monkeys, not fewer monkeys.

**Comment by Firefox13** [comment]
I have no idea why Travis errored. I'll close and reopen this PR to restart it.

**Comment by Firefox13** [comment]
well it didn't work.

**Comment by Firefox13** [comment]
gonna make another PR for *make sure* that next time Travis errors it'll be a reasonable one

**Pull request closed without merging**
