### PR TITLE
Vertical event

### PR DESCRIPTION
**Pull request by vode-code**
## About The Pull Request
Featuring info about the map from our favorite skeleton:
>Eris is map is now 35% smaller, but 600% taller: 32 zlevels of pure 55x55 madness.
>every department has been squished above and next to each other, and all maint adjacent to each department has been removed
>the entirety of maint has been scrambled and placed above the last departmental zlevel. It is now mashed together hellscape.
>technomancer update: we heard a lot of complaints about technomancers missing content, and SM being either impossible to set up or boring as balls. That is why I decided to fix every issue. Tecnomancers now have even less content. Atmos is broken, Engines are missing, SM has been replaced by a special singulo (WARNING: DO NOT MOVE OR TOUCH THE SINGULO), pipes are broken (sorry, disposals), and wires are a complete mess. 
>club and medbay are the last level before maint starts, intended to be a safe zone before adventuring into the madness that
>there is a  stairwell shaft that is intended to carry you all the way from the zlevel 1 to medbay, it will be on the bottom right corner of the map

also added the Vagabond Idol and The Captain's Chair.
if anyone except simski/trexdude sits in The Captain's Chair, the round ends.
The Bridge and the Escape Shuttles are at the crows nest of the ship
bleep I thought I fixed the commit spam...
oh yeah, and a ton of space, be prepared for that.

## Why It's Good For The Game
This was a lot of work.

## Changelog
:cl:
add: Added The Tower
add: added the Vagabond Idol, the only way you will survive climbing The Tower
tweak: there is now way too much space.
del: Removed Eris from the rotation
balance: maint is now painfully tall
/:cl:

### CODE REVIEW

**Comment by TheShown911** [comment]
Now this is epic (doesn't compile)

**Comment by vode-code** [comment]
does compile.

**Comment by vode-code** [comment]
Yes, it compiles as soon as I've made sure it compiles.

**Comment by MLGTASTICa** [comment]
Jesus christzer

**Comment by vode-code** [comment]
this may take a few minutes.

**Comment by vode-code** [comment]
all that waiting is 99% space, I have gone through this several times for testing.

**Comment by vode-code** [comment]
and here we go, if the time limit was slacker I mighta reduced the wait.

**Comment by zombiemimic** [comment]
holy mother of based

**Comment by Alliostra** [comment]
basado

**Comment by ValoTheValo** [comment]
Lamprey Station But Eris

**Review by Firefox13 — CHANGES_REQUESTED** [review]
изображение
I'll strangle you

**Comment by garrulousTeamotei** [comment]
Sure, there are unconnected ladders and stairs, APCs in the middle of space, and plenty of far too easy shortcuts that can be made by cutting through floors and space. 
But this makes it all worth it.

press_when_malf

**Pull request merged**
