### PR TITLE
Cloning

### PR DESCRIPTION
**Pull request by Evankhell561**
## About The Pull Request

cloned humans take cloning damage depending on their job.

## Why It's Good For The Game
because design doc

## Changelog
:cl:
tweak: cloned humans take cloning damage depending on their job (priest, acolyte, agrolyte and custodian).
/:cl:

### CODE REVIEW

**Comment by Omni44** [comment]
Okay so, now people with cruciform not only have to hope there is one of three people alive on server to get cloned at all, need to have their cruciforms found, brought to church, not destroyed by Excel/Moebius/sold via Guild, need church to have their machinery and enough biomatter for it, now they will also take cloning damage that is bacisally impossible to cure on your own and is generally horrible to deal with?
And that's just so that _the basic premise_ of entire department and cruciform works at all?
What a ballbuster, man, give me a break. Who wrote this nonsense?

**Comment by Wouju** [comment]
I agree with Omni, this is quite a heavy nerf for NeoTheo, especially since I don't recall NT being able to heal cryo damage on their own, requiring usage of medbay Cryo.

**Comment by Iglpigl** [comment]
> Okay so, now people with cruciform not only have to hope there is one of three people alive on server to get cloned at all, need to have their cruciforms found, brought to church, not destroyed by Excel/Moebius/sold via Guild, need church to have their machinery and enough biomatter for it, now they will also take cloning damage that is bacisally impossible to cure on your own and is generally horrible to deal with?
> And that's just so that _the basic premise_ of entire department and cruciform works at all?
> What a ballbuster, man, give me a break. Who wrote this nonsense?

I agree with both of your opinions, as who wrote it it's FortuneMaster, a delegate who himself said that he hasn't played the game for a month, here is the link in case any of you interested.
https://docs.google.com/document/d/1D1A7Yc9lZy47BWNIJYYMI2NqwOqDrqmBdHVOO3uUuK8/edit?usp=sharing

**Comment by SaltyOldBull** [comment]
Evan, I think you added just the damage and forgot to make it so everyone can clone; the doc asks for any member of neotheo to be able to revive, and the damage comes from the cruciform rank in the reviver's side, not the dead side.
Unless this was your intention, if so

**Comment by Evankhell561** [comment]
> Evan, I think you added just the damage and forgot to make it so everyone can clone; the doc asks for any member of neotheo to be able to revive,

image
think. You may be right but the way this is written it seems like it's just a comment or anecdotal data rather than a request for me to change that. 

 and the damage comes from the cruciform rank in the reviver's side, not the dead side.
> Unless this was your intention, if so

if those who are not priest or acolytes cannot clone then it is logical that the damage received depends on the cruciform of the person to be cloned and not on the one who performs the cloning.

**Comment by basedcringe** [comment]
As much as it against NT that sheet has some problems that you more or less made up and this is already a bad PR

**Comment by FortuneMaster** [comment]
> Okay so, now people with cruciform not only have to hope there is one of three people alive on server to get cloned at all, need to have their cruciforms found, brought to church, not destroyed by Excel/Moebius/sold via Guild, need church to have their machinery and enough biomatter for it, now they will also take cloning damage that is bacisally impossible to cure on your own and is generally horrible to deal with?
> And that's just so that _the basic premise_ of entire department and cruciform works at all?
> What a ballbuster, man, give me a break. Who wrote this nonsense?

me

**Pull request closed without merging**
