### PR TITLE
Artist reassignment to Club,  and some other club stuff

### PR DESCRIPTION
**Pull request by Omni44**
## About The Pull Request

First of all, Guild Artist is no more, now it's Club Artist. They get new locum where shitter used to be, they now work under bar Manager, and can access rest of the bar normally. Guild got replacement for room where artists lived until now.
Second off. Removing most of the junk food that'd spawn in the club too, they should serve real food. I'm also ID locking booze and other vendor behind bar access.
Thirdly, I am putting Bonsai behind proper glass case, in kitchen.

New Artist office:
CEV Eris 2021-11-21 194854
Guild Warehouse:

CEV Eris 2021-11-21 194945

## Why It's Good For The Game

It never made any sense to put artist in guild for me, from any angle. From gameplay perspective it makes role too shallow, it having access to guild's materials, and the stuff they make serving exclusively guild and guild alone. This, I think, does not make the role more fun or promote interaction, and most artist players feel the same I reckon. Putting artist in club feels fitting and makes poor club feel like something close to proper department, or something. From fluff perspective- I don't see any reason business minded Guild would house some weird troupe of bleeding hearts. It does not fit, and I think we can agree on that much after year of it.
 Secondly, I hope to cut down on break-ins into club, by removing most fast food from kitchen and ID locking other two vendors at bar. It's not much, but I hope it helps clubbies a bit.

## Changelog
:cl:

tweak: Turned Guild Artist into Club Artist, and moved their office.
tweak: minor mapping changes to bar

/:cl:

### CODE REVIEW

**Comment by Kegdo** [comment]
> promote interaction

> puts snack vendor back in the game, killing the interaction with the bar, that was already little

bro.
This is a good PR, but PLEASE remove the vendor, send it back to Brazil. It removes the interaction COMPLETELY, and I don't care about your 'there was no interaction anyway' argument. It was not much, it it was STILL an INTERACTION.
Even the fast food removal is good, just please remove the vendor.

**Comment by TheShown911** [comment]
Yet another "there is not enough interaction so we will solve it by removing more interaction", a hood classic.

**Comment by ValoTheValo** [comment]
dont see how moving clown to the bar makes it any better. now that they have to joonk for mats. idk how to feel about snack machine

**Comment by Kegdo** [comment]
> dont see how moving clown to the bar makes it any better. now that they have to joonk for mats. idk how to feel about snack machine

they can buy mats from rnd or guild, so that's fine. Also club content. But everything else... bad...

**Comment by Omni44** [comment]
I still think it's better for people to just come to bar and buy their food from vendor, rather than tear down bar when there are no bar wagies to tend to it around and steal it/not come to club at all. Prospecting bar crew will try to bank on these people, and if vendor customers ignore them, they wouldn't interact with them anyways. 
If maintainers decide not to have ir, sure, I'll remove it. It's two lines change, anyone can do it. I'd rather have it on for week or so and see the results however, since virtually everyone I talked to that remembered times when vendor was there told me it brought people in.

**Comment by Jan-Blasiak** [comment]
Good PR, but I have conflicting feelings about the vendor.

**Comment by Humonitarian** [comment]
If vendor is assigned to club ID, I see no issues with it. If club doesn't want it, they can unwrench and hide it, and while there's no club it keeps the thieves away.

**Comment by Omni44** [comment]
This PR is WIP, reviewers are urged to wait till I roll out rest of the changes.

**Comment by Kegdo** [comment]
couldn't you make a draft then?

**Comment by Omni44** [comment]
I changed my mind, I'll do rest of the changes as separate PR

**Comment by drexample** [comment]
I don't approve moving Artist to the club.
(especially considering plans for that job)

**Comment by Omni44** [comment]
Well, it's wonderful that you guys have plans that neither artist players, contributors, or even maintainers and development delegates that this PR was discussed with know anything about, but if we're to guess your super secret plans and unexpressed thoughts every time we contribute anything that kinda sucks, innit?

**Comment by Rumplenutskin** [comment]
As much as I would miss revenue created by artist, I never understood why they were in the Guild. To me club = entertainment and the arts are entertainment. I like the idea of ID locking the booze since people break in on the regular. I like these changes.

I cant comment on the vendor as having it removed does make me venture to club for food on occasions. I could see if it was ID locked to pack it with cooked food.

**Review by TheShown911 — APPROVED** [review]

**Comment by TheShown911** [comment]
> I don't approve moving Artist to the club. (especially considering plans for that job)

I do.

**Comment by drexample** [comment]
> Well, it's wonderful that you guys have plans that neither artist players, contributors, nor even maintainers and development delegates that this PR was discussed with know anything about, but if we're to guess your super secret plans and unexpressed thoughts every time we contribute anything that kinda sucks, innit?

Yeah, fair.

**Pull request closed without merging**
